### PR TITLE
WebGPURenderer: Add `debug.getRawShaderAsync()`.

### LINKED ISSUE #28984: TSL Editor Example: Does not work because of 404 of three JS files
### Description

When trying the latest [TSL Editor](https://threejs.org/examples/#webgpu_tsl_editor) from the Three.js website (r167) I get 404 error for three JS files and the TSL Editor shows blank page.
```
GET https://threejs.org/src/renderers/webgpu/WebGPURenderer.js net::ERR_ABORTED 404 (Not Found)
webgpu_tsl_editor.html:56 
GET https://threejs.org/src/renderers/webgpu/nodes/WGSLNodeBuilder.js net::ERR_ABORTED 404 (Not Found)
webgpu_tsl_editor.html:57 
GET https://threejs.org/src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js net::ERR_ABORTED 404 (Not Found)
```
Tried Chrome (with WebGPU) and FireFox (without WebGPU), the result is the same.

A direct link to one of the files [https://threejs.org/src/renderers/webgpu/WebGPURenderer.js](https://threejs.org/src/renderers/webgpu/WebGPURenderer.js) confirms the 404 error.

It might be a temporary network issue (that will resolve by itself in a few hours), or missing files, or wrong URLs.

### Reproduction steps

1. Visit [https://threejs.org/examples/#webgpu_tsl_editor](https://threejs.org/examples/#webgpu_tsl_editor)
2. If the page is blank, see the JS console

### Code

N/A

### Live example

[https://threejs.org/examples/#webgpu_tsl_editor](https://threejs.org/examples/#webgpu_tsl_editor)

### Screenshots

Page with the TSL Editor:

image

Direct visit to one of the 404 files:

image

### Version

r167

### Device

Desktop

### Browser

Chrome, Firefox

### OS

Windows

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #28984.

**Description**

This PR fixes `webgpu_tsl_editor` by adding `rendererer.debug.getRawShader()` which allows to get the raw shader (WGSL or GLSL) for a 3D object.

### CODE REVIEW

File: src/renderers/common/Renderer.js [hunk 1]
```diff
@@ -147,7 +147,12 @@ class Renderer {
 
 		this.debug = {
 			checkShaderErrors: true,
-			onShaderError: null
+			onShaderError: null,
+			getRawShader: ( object ) => {
```
Comment (Mugen87) [inline src/renderers/common/Renderer.js:151]: You suggested in https://github.com/mrdoob/three.js/issues/28984#issuecomment-2253318912 scene and camera as additional parameters but I'm not sure what to do with them for recreating the original logic of the example. It seems just the 3D object is sufficient.

File: examples/webgpu_tsl_editor.html [hunk 2]
```diff
@@ -158,11 +154,14 @@
...
 					const showCode = () => {
 
-						result.setValue( nodeBuilder[ options.shader + 'Shader' ] );
+						result.setValue( rawShader[ options.shader + 'Shader' ] );
 						result.revealLine( 1 );
 
 					};
 
+					const webGLRenderer = new THREE.WebGPURenderer( { forceWebGL: true } );
+					webGLRenderer.init();
```
Comment (Mugen87) [inline examples/webgpu_tsl_editor.html:163]: I've implemented it like suggested in https://github.com/mrdoob/three.js/issues/28984#issuecomment-2253318912, but there is one problem. If WebGPU isn't available, you can't force a WGSL output for debugging purposes.

Maybe `getRawShader()` would behave more reliable if you can request the output with a parameter. In this way, the method produces the same result no matter on what system it is executed.

File: src/renderers/common/Renderer.js (hunk 1 above)
Comment (sunag) [reply src/renderers/common/Renderer.js:151]: The problem with sending just the object is that it will create a shader from scratch, ignoring the `RenderContext`, which includes `RenderTarget`, type of camera, scene.environment, etc. The object may have shader variation if it is inside a `RenderBundle` currently `group.static=true`, for this reason we will need to compile the entire scene as well, and then get the real shader code.

Comment (sunag) [reply src/renderers/common/Renderer.js:151]: I'll see what I can do to help here by editing the PR.

File: examples/webgpu_tsl_editor.html (hunk 2 above)
Comment (sunag) [reply examples/webgpu_tsl_editor.html:163]: We could added `getRawShaderAsync()` too.

**Comment by Mugen87** [comment]
@sunag Nice solution! 🙌

**Comment by mrdoob** [comment]
Maybe `getShaderAsync()` instead?
Do we need the `Raw` concept now that we are using nodes?
