### PR TITLE
Geometry: Make .fromBufferGeometry() more generic.

### LINKED ISSUE #17793: Geometry.fromBufferGeometry has an issue when reading InterleavedBuffer
##### Geometry.fromBufferGeometry produces wrong data when working with InterleavedBuffer

Assume we have a bufferGeometry with interleavedBufferAttribute as its attribute type. 

There is an issue in [geometry.js](https://github.com/mrdoob/three.js/blob/f7727f85502cbe34600b65b727c8e6204e9bf505/src/core/Geometry.js#L199) if we call `Geometry.fromBufferGeometry(bufferGeometry)`. 
The current code assumes that the type of attribute is `BufferAttribute`, but it also can be `InterleavedBufferAttribute`, and they cannot be read in the same way.

For `BufferAttribute`, we read attribute like position, normal individually. But for `InterleavedBufferAttribute`, it returns a typed array that bundles all attributes together. So we need to read the data based on its offset and itemsize.

It might be better to support reading attribute individually in `InterleavedBufferAttribute `class, but at least we need a quick fix in the geometry method. 

If you all think this is a bug and nobody is fixing it right now, I can open a PR. I can also create a jsfiddle if you think it's necessary to demonstrate the wrong data output.

##### Three.js version

- [x] Dev
- [x] r109
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
Instead of directly accessing array data, the method now uses `fromBufferAttribute()`/ `getX()`, `getY()` and `getZ()`. This automatically fixes #17793 without introducing a new code path.

### CODE REVIEW

**Comment by Mugen87** [comment]
If there is interest in the PR, I suggest to merge it at the beginning of the `R115` dev cycle. Just to be on the safe side^^.

File: src/core/Geometry.js [hunk 1]
```diff
@@ -196,21 +196,21 @@ Geometry.prototype = Object.assign( Object.create( EventDispatcher.prototype ),
 
 		}
 
-		var positions = attributes.position.array;
-		var normals = attributes.normal !== undefined ? attributes.normal.array : undefined;
-		var colors = attributes.color !== undefined ? attributes.color.array : undefined;
-		var uvs = attributes.uv !== undefined ? attributes.uv.array : undefined;
-		var uvs2 = attributes.uv2 !== undefined ? attributes.uv2.array : undefined;
+		var positions = attributes.position;
```
Comment (WestLangley) [inline src/core/Geometry.js]: I would be in favor of using `position` for the attribute itself:
```js
var position = attributes.position;
```
In the case of the array, we use the plural:
```js
var positions = attributes.position.array;
```
JMHO. :-)

File: src/math/Color.js [hunk 2]
```diff
@@ -580,6 +580,16 @@ Object.assign( Color.prototype, {
 
 	},
 
+	fromBufferAttribute: function ( attribute, index ) {
```
Comment (WestLangley) [inline src/math/Color.js]: The attribute could normalized, and the attribute array a `Uint8Array`, as in https://threejs.org/examples/webgl_buffergeometry_points_interleaved.html. I expect that would be a good test case.

File: src/core/Geometry.js (hunk 1 above)
Comment (Mugen87) [reply src/core/Geometry.js]: Done.

File: src/math/Color.js (hunk 2 above)
Comment (Mugen87) [reply src/math/Color.js]: I've added a check for normalized data. However, `webgl_buffergeometry_points_interleaved` is not a good test case since `Geometry.fromBufferGeometry()` only supports mesh geometries (see #14022).

**Comment by Mugen87** [comment]
@mrdoob Any chances to merge this refactoring? Otherwise it's better to close the PR and mark #17793 as `Won't fix`.

**Comment by mrdoob** [comment]
Thanks for the ping 🙏

**Comment by mrdoob** [comment]
Thanks!
