### PR TITLE
SpotLightHelper: Fix offset when adjusting the scene / parent position

### LINKED ISSUE #27437: Modifying the position of the scene can cause misalignment of the SpotLight and SpotLightHelper positions
### Description

Modifying the position of the scene can cause misalignment of the SpotLight and SpotLightHelper positions

### Reproduction steps

If the scene is not at the origin, it will trigger an error

### Code

```js
// mesh
const plane = new THREE.Mesh(
  new THREE.PlaneGeometry(100, 100),
  new THREE.MeshStandardMaterial({ color: '#ccc' })
);
plane.rotation.x = -Math.PI / 2
plane.receiveShadow = true
scene.add(plane);

const flag = new THREE.Mesh(
  new THREE.BoxGeometry(1, 1, 1),
  new THREE.MeshStandardMaterial({ color: 'red' })
);
flag.position.y = 10;
scene.add(flag);

// light
const spotLight = new THREE.SpotLight('#fff');
spotLight.castShadow = true;
spotLight.angle = Math.PI / 180 * 30
spotLight.intensity = 2
spotLight.distance = 20
spotLight.penumbra = 0.1
spotLight.decay = 0.1
const spotLightHelper = new THREE.SpotLightHelper(spotLight);
scene.add(spotLight, spotLightHelper);
spotLight.position.y = 10

// Trigger
scene.position.y = -2
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/73zhtwdq/)
* [jsfiddle-dev](https://jsfiddle.net/vxnoc5fy/51/)

### Screenshots

image
image

### Version

r159

### Device

Desktop

### Browser

Edge

### OS

Linux

### PR DESCRIPTION
**Pull request by gkjohnson**
Fixed #27437

**Description**

Previously SpotLightHelper was just copying the target light's `matrixWorld` into its local `matrix` field resulting in offsets when the parent was not at 0, 0, 0. Now the target light transform is correctly transformed into the local frame that the helper exists in and it's no longer required to add the helpers to the root of the scene.

This is for another PR but I'm wondering if "update" can just be removed and effectively called in "updateMatrixWorld"?

### CODE REVIEW

**Comment by Mugen87** [comment]
I understand this works but I'm a bit unhappy about the resulting complexity in `updateMatrixWorld()`. If the helper would have to be a child of the light, I assume things could be much easier.

**Comment by gkjohnson** [comment]
> If the helper would have to be a child of the light, I assume things could be much easier.

The requirement to add helpers to the root scene has confused me countless times in the past. Asking users to add a helper to a specific parent so that it works betrays all expectation around the transform hierarchy works. This would be significantly worse of the user experience of the helpers.

> I understand this works but I'm a bit unhappy about the resulting complexity in updateMatrixWorld().

I don't agree that it's so complicated. These are matrix transformations that are used throughout the project. But either way this is a transformation that should be used across all helpers (BoxHelper, CameraHelper, DirectionalLightHelper, etc) should all implement this the same way. If this is added we should add a super class that shares an updateMatrixWorld implementation among all child classes.

**Comment by Mugen87** [comment]
> Can you elaborate on what you feel is complex?

The need to overwrite `updateMatrixWorld()` to begin with. But also the code itself is not something I would label as trivial.

My point is I favor an assumption like "spot light helper must be child of the light" if that makes the overall implementation easier.

**Comment by gkjohnson** [comment]
> The need to overwrite updateMatrixWorld() to begin with.

There are quite a few other classes that also overwrite `updateMatrixWorld` including other Helpers. I would argue it's more user friendly to do this with the Helper-classes, anyway, since it means "update" doesn't need to be called. But either way the code here can be moved to the "update" function if this is an issue.

> But also the code itself is not something I would label as trivial.

The transformation happening is no different than the one required for transforming an object into the camera frame. It's fundamental to rendering graphics.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
I'm okay with merging this new version. As long as we keep the current policy we should make sure to fix https://github.com/mrdoob/three.js/issues/27437 and that's what the PR does.

**Comment by gkjohnson** [comment]
> As long as we keep the current helper policy

What's the expectation for helpers? Some of them update themselves in `updateMatrixWorld` (`Box3Helper`, `SkeletonHelper`, `PlaneHelper`) while others require manually calling an `update` function (`CameraHelper`, `DirectionalLightHelper`, and the rest). Should their APIs be normalized?

**Comment by Mugen87** [comment]
If we want to refactor the world update matrix logic at some point, it would be good if `updateMatrixWorld()` and `updateMatrix()` are not overwritten.

File: src/helpers/SpotLightHelper.js [hunk 1]
```diff
@@ -67,6 +64,24 @@ class SpotLightHelper extends Object3D {
...
+				.multiply( this.light.matrixWorld );
+
+		} else {
+
+			this.matrix
+				.copy( this.light.matrixWorld );
+
+		}
+
+		this.matrix.decompose( this.position, this.quaternion, this.scale );
```
Comment (WestLangley) [inline src/helpers/SpotLightHelper.js:82]: Why are you doing this -- instead of retaining `this.matrixAutoUpdate = false` ?

File: src/helpers/SpotLightHelper.js [hunk 2]
```diff
@@ -67,6 +64,24 @@ class SpotLightHelper extends Object3D {
 		this.light.updateWorldMatrix( true, false );
 		this.light.target.updateWorldMatrix( true, false );
 
+		// update the local matrix based on the parent and light target transforms
+		if ( this.parent ) {
+
+			this.matrix
+				.copy( this.parent.matrixWorld )
```
Comment (WestLangley) [inline src/helpers/SpotLightHelper.js:71]: Is this matrix necessarily current?

File: src/helpers/SpotLightHelper.js (hunk 1 above)
Comment (gkjohnson) [reply src/helpers/SpotLightHelper.js:82]: I suppose I could do that. It would probably be best to se `matrixWorldAutoUpdate` to false but tbh the matrix / matrixWorld update behavior is fairly confusing to me, now. For example the `Object3D.lookAt` function [will call updateWorldMatrix](https://github.com/mrdoob/three.js/blob/a1be53d671b7161ad8479ab47c72de97e34faa68/src/core/Object3D.js#L284) which will automatically update the objects matrixWorld even if `matrixWorldAutoUpdate` is false.

It's not clear to me when they do and don't apply so I fallback to keeping all the values in sync which I think is more clear, anyway.

File: src/helpers/SpotLightHelper.js (hunk 2 above)
Comment (gkjohnson) [reply src/helpers/SpotLightHelper.js:71]: I suppose that's true - I can call `this.parent.updateMatrixWorld` but it has the same caveats as mentioned in https://github.com/mrdoob/three.js/pull/27487#discussion_r1452110938 in that it will undermine the users `parent.matrixWorldAutoUpdate` setting if it's set to false.

File: src/helpers/SpotLightHelper.js (hunk 1 above)
Comment (WestLangley) [reply src/helpers/SpotLightHelper.js:83]: I'd avoid unnecessarily calling `matrix.decompose()` for this helper. JMO, of course.
