### PR TITLE
USDZLoader: throw error instead of warning

### LINKED ISSUE #28684: USDZLoader: loading a binary file does not throw error
### Description

While other loaders throw errors upon encountering a non-recoverable issue, the USDZ loader merely logs a warning and returns an empty group.

USDZLoader should throw an error such that developers may handle it accordingly, instead of receiving a nullish value (empty group).

I've used the following asset for testing: https://developer.apple.com/augmented-reality/quick-look/models/cupandsaucer/cup_saucer_set.usdz

### Reproduction steps

1. Load USDZ file containing one or more 'crate' files using USDZLoader
2. Empty scene is loaded, only warnings in console.

### Code

USDZLoader.load("cup_saucer_set.usdz")

### Live example

N/A

### Screenshots

_No response_

### Version

r165

### Device

Desktop

### Browser

Firefox

### OS

Linux

### PR DESCRIPTION
**Pull request by zaesur**
Fixed  #28684

**Description**

USDZLoader should throw an error instead of the warning, to allow the consumer to act upon the error. This PR changes the console warnings to throw errors, and removes the block that returns an empty group when findUSD returns undefined.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

File: examples/jsm/loaders/USDZLoader.js [hunk 1]
```diff
@@ -182,8 +182,7 @@ class USDZLoader extends Loader {
 
 					if ( isCrateFile( zip[ filename ] ) ) {
 
-						console.warn( 'THREE.USDZLoader: Crate files (.usdc or binary .usd) are not supported.' );
-						continue;
+						throw Error( 'THREE.USDZLoader: Crate files (.usdc or binary .usd) are not supported.' );
```
Comment (Mugen87) [inline examples/jsm/loaders/USDZLoader.js:185]: Yeah, I think throwing an error is indeed more helpful than just logging a warning. In this way, the app can better handle the situation.
