### PR TITLE
GLTFLoader: Fix cubicspline interpolation for quaternions.

### LINKED ISSUE #22339: GLTFLoader: Quaternions not normalized after cubic interpolation
**Describe the bug**

GLTFLoader should normalize quaternions after applying cubic interpolation when doing a cubic rotation animation, in accordance with

> [When the sampler targets a node's rotation property, the resulting p(t) quaternion must be normalized before applying the result to the node's rotation.](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#appendix-c-spline-interpolation)

Because the quaternions aren't normalized, a pure rotation animation stretches and squishes while rotating.

If they're normalized, everything looks correct to me (tested by sticking normalization code [here](https://github.com/mrdoob/three.js/blob/918c364b117cde98bf70f91afaae1fbe64058c13/examples/jsm/loaders/GLTFLoader.js#L1775)). 

**To Reproduce**

Can repro in https://gltf-viewer.donmccurdy.com/. See test file at https://github.com/donmccurdy/three-gltf-viewer/issues/261.

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Firefox
 - Three.js version: r131

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #22339.

**Description**

From the glTF spec:

> When the sampler targets a node's rotation property, the resulting p(t) quaternion must be normalized before applying the result to the node's rotation.

### CODE REVIEW

File: examples/jsm/loaders/GLTFLoader.js [hunk 1]
```diff
@@ -1705,10 +1706,12 @@ class GLTFMeshQuantizationExtension {
 // Specification: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#appendix-c-spline-interpolation
 class GLTFCubicSplineInterpolant extends Interpolant {
 
-	constructor( parameterPositions, sampleValues, sampleSize, resultBuffer ) {
+	constructor( parameterPositions, sampleValues, sampleSize, resultBuffer, targetQuaternion ) {
```
Comment (WestLangley) [inline examples/jsm/loaders/GLTFLoader.js:1709]: I think a better parameter name would be `normalize` -- or `normalizeOutput`.

Comment (Mugen87) [reply examples/jsm/loaders/GLTFLoader.js:1709]: Yeah, thought about this, too. But having a parameter that has `quaternion` in its name sounds more descriptive to me. And thus easier to understand.

Comment (WestLangley) [reply examples/jsm/loaders/GLTFLoader.js:1709]: It is a bit confusing IMO. It is not a  "target" quaternion. It is a boolean.

Furthermore, using "quaternion" is too restrictive. You can interpolate positions on a sphere, for example.

Using the boolean parameter `normalize` follows the pattern used elsewhere in the library.

Comment (Mugen87) [reply examples/jsm/loaders/GLTFLoader.js:1709]: The idea that the instance of `GLTFCubicSplineInterpolant` targets a rotation property and thus a quaternion.

Besides, the parameter only affects quaternions and thus a generic name is misleading.

Comment (Mugen87) [reply examples/jsm/loaders/GLTFLoader.js]: Changed the name to `normalizeQuaternion`.

Comment (Mugen87) [reply examples/jsm/loaders/GLTFLoader.js]: > If the method is only used to interpolate quaternions,

No it isn't.

> If the method can be used to interpolate something other than a quaternion, then normalizeQuaternion makes no sense. A better name for the parameter would be normalize.

The normalization is only necessary for quaternions.

File: examples/jsm/loaders/GLTFLoader.js [hunk 2]
```diff
@@ -3615,7 +3626,9 @@ class GLTFParser {
 							// representing inTangent, splineVertex, and outTangent. As a result, track.getValueSize()
 							// must be divided by three to get the interpolant's sampleSize argument.
 
-							return new GLTFCubicSplineInterpolant( this.times, this.values, this.getValueSize() / 3, result );
+							const normalizeQuaternion = PATH_PROPERTIES[ target.path ] === PATH_PROPERTIES.rotation;
```
Comment (donmccurdy) [inline examples/jsm/loaders/GLTFLoader.js:3629]: It would be nice if the interpolant didn't depend on local scope of the loop. It's the kind of thing that can behave weirdly with 'var', ought to work with 'const', but still feels better just to avoid. Instead I think we could do:

```js
const normalizeQuaternion = this instanceof QuaternionKeyframeTrack;
```

File: examples/jsm/loaders/GLTFLoader.js (hunk 1 above)
Comment (donmccurdy) [reply examples/jsm/loaders/GLTFLoader.js]: I can imagine hypothetical situations where a user might want to interpolate normalized vectors, but glTF does not include any such cases. Since this is an internal API I don't think I have any preference on the naming, and implementing unused normalization of Vector2, Vector3, is certainly overkill. One other idea (again, previous solutions are also fine) would be to use a simple subclass instead of a constructor parameter:

```js
class GLTFCubicSplineQuaternionInterpolant extends GLTFCubicSplineInterpolant {
  /* overrides interpolate_ ... */
}
```

Comment (WestLangley) [reply examples/jsm/loaders/GLTFLoader.js]: >use a simple subclass instead of a constructor parameter

That sounds like the best idea to me.

**Comment by Mugen87** [comment]
@donmccurdy I've implemented your feedback! Code looks now way simpler than before.
