### PR TITLE
WebXRManager: Add Raw Camera Access module.

### LINKED ISSUE #26452: Loading VideoTexture in WebXR gives camera feed instead of actual video
### Description

I have a THREE.PlaneGeometry that has a videotexture on it, and I position it using the hit detection from WebXR just by touching the screen. No problems. But if I enable camera-access from WebXR, the texture will become the live camera feed. I want to be able to have the camera image, while also having the normal videotexture and 3D scene.

### Reproduction steps

1. Open the 1st JSFiddle. You should see an app that uses WebXR to position a video with hit detection when you touch the screen. No problems at all.
2. Open the 2nd JSFiddle. The only difference is that I removed the comment from the camera-access in the required features of WebXR, and now the videotexture becomes the live camera feed. 

### Code

const videoTexture = new THREE.VideoTexture(video);
...
navigator.xr
      .requestSession("immersive-ar", {
        requiredFeatures: ["camera-access", "hit-test", "local"],
        optionalFeatures: ["dom-overlay"],
        domOverlay: { root: document.getElementById("overlay") },
      })
.then(onSessionStarted, onRequestSessionError);

### Live example

* https://jsfiddle.net/schaldac/br2yh70p/
* https://jsfiddle.net/schaldac/u4k1h8g7/

### Screenshots

Screenshot_20230628-092102_Chrome (1)
Screenshot_20230626-085834

### Version

0.147.0

### Device

Mobile

### Browser

Chrome

### OS

Android

### LINKED ISSUE #26891: Provide Access to WebXR camera feed when `camera-access` feature is enabled.
### Description

I would like to be able to get a `Texture` class that references the camera feed from an XR session.

#### User API

Proposal would be to be able to request the camera texture from the WebXRManager class, however this glosses over a lot of implementation detail and may not map to the WebXR access patterns very well.

```javascript
const texture = renderer.xr.getCameraTexture();
```

---

#### Proposed Internal changes

I am currently having a stab implementing this, I have little experience with the internals of three.js so everything is open to change.

Would require the creation of a new THREE.js Texture class that receives the underlying WebGLTexture instead of initialising it.  Lets call it `ExternalTexture`.  In an `ExternalTexture` THREE.js is not responsible for creating / deleting the GPU data, only binding it and tracking its state.  As this could introduce a lot of footguns it may be best to keep this class for internal use for now.

```javascript
const glTexture = gl.createTexture();
const texture = new ExternalTexture(glTexture);
```

Additionally, the texture provided by the WebXR api has some limitations.  It is what the WebXR specs call an [opaque texture](https://immersive-web.github.io/layers/#opaque-texture).  In summary it is:
- Only a valid texture from within the `requestAnimationFrame()` callback of the `XRSession`
- Calling `deleteTexture` on this texture will result in an `INVALID_OPERATION` error.
- Must be unbound and detached from all WebGLShader objects at the end of the `requestAnimationFrame()`
- Changes to dimensions or format is not allowed and any gl call that *could* change these parameters will fail with an `INVALID_OPERATION` error.

This will probably require a second class that extends from `ExternalTexture`, lets call it `ExternalOpaqueTexture`.  To navigate the requirement that the texture is only valid from within an XRSession's `requestAnimationFrame` callback, from what I see there are two options.

##### Option 1: Manually passing in the new opaque texture each frame.
```javascript
const threeOpaqueTexture = new ExternalOpaqueTexture(null);
// Later on, user manually updates it.
const animate = () => {
  const glOpaqueTexture = ...;
  threeOpaqueTexture.image.source = glOpaqueTexture;
  threeOpaqueTexture.needsUpdate = true;
}
```

##### Option 2: Passing in a getter for the opaque texture in the constructor.
```javascript
const getGLOpaqueTexture = () => {
  // ... interact with the XR session to get the camera feed texture
  return glOpaqueTexture;
}
const threeOpaqueTexture = new ExternalOpaqueTexture(getGLOpaqueTexture);
// Three.js internals will automatically handle re-fetching it when needed.
```

#### User API Usage
There are two ways the api might have to be used based on the limitations of an opaque texture (see above).  These access patterns map to option1 and option 2 of how the underlying ExternalOpaqueTextureClass might work.

1. User must call `getCameraTexture` within `requestAnimationFrame()` of the XR session or it will error.  This object is valid only for the `requestAnimationFrame` that it was called within and will error/warn if used otherwise.
3. User can call it at any time and receive a ExternalOpaqueTexture that will be managed by three.js, Three.js internals will call the function to get the texture inside of `textures.setTexture2D`.  If this is called from outside of an XR sessions `requestAnimationFrame` it will be black.

_Edited for formatting and a bit of extra information_
### Alternatives

I have attempted to get the camera access texture using raw webgl binds and use three.resetState to clean the three state but it doesn't work.

### Additional context

[Draft proposal: WebXR Raw Camera Access Module](https://immersive-web.github.io/raw-camera-access/)
[Raw WebGL Example
](https://storage.googleapis.com/chromium-webxr-test/r1095250/proposals/camera-access-barebones.html)[Raw WebGL Example, source code](https://source.chromium.org/chromium/chromium/src/+/main:third_party/webxr_test_pages/webxr-samples/proposals/camera-access-barebones.html)
#26452

Our sales person sold a project that depends on this feature so I am going to try implement it to this spec (on r151 however).  I would appreciate any advice, I know almost nothing about how three.js tracks the state internally so any help or advice would be much appreciated.  If i can get it working for our project I can PR on the latest threejs version in my free time.

### PR DESCRIPTION
**Pull request by mikeskydev**
Closes #26452, Closes #26891

**Description**

This PR implements support for the [WebXR Raw Camera Access](https://immersive-web.github.io/raw-camera-access) module, and provides an example where the camera texture is placed on a rotating cube.

I have addressed the issue in #26452 by unbinding texture state if camera access is enabled, as it appears the module will automatically bind the raw camera textures at the beginning of the frame, which was affecting three.js's internal state tracking.

As this was tested on Chrome for android, this may be an implementation bug in Blink that has gone unnoticed, as their test case always rebinds textures.

shared image

### CODE REVIEW

**Comment by mikeskydev** [comment]
Any chance this makes r179? My actual use case is further downstream... :)

File: src/renderers/webxr/WebXRManager.js [hunk 1]
```diff
@@ -984,6 +999,42 @@ class WebXRManager extends EventDispatcher {
...
+								if ( ! cameraTex ) {
+
+									cameraTex = new Texture();
+									cameraAccessTextures[ camera ] = cameraTex;
+
+								}
+
+								const glTexture = glBinding.getCameraImage( camera );
+								const texProps = renderer.properties.get( cameraTex );
+								texProps.__webglTexture = glTexture;
```
Comment (Mugen87) [inline src/renderers/webxr/WebXRManager.js]: I'm afraid we can't merge the PR because of these two lines. We need a `GLTexture` class similar to `GLBufferAttribute` so you can do this:
```js
const glTexture = glBinding.getCameraImage( camera );
cameraTex = new GLTexture( glTexture ) ;
```
See https://github.com/mrdoob/three.js/issues/26452#issuecomment-1658152049 for more details. 

We require a special handling for `GLTexture` since if you would call `dispose()` on `cameraTex` on app level, you create an invalid operation. There might be more edge cases that we have to handle because `getCameraImage()` returns as so called _opaque texture_. E.g. what would happen if the user sets `needsUpdate` to `true` for `cameraTex`?

Not having `GLTexture` was the actual blocker why camera access has not been implemented yet. `WebXRDepthSensing` should also be updated to use the new `GLTexture` class.

> I have chosen not to implement any form of Opaque/Raw/External Texture specific class at this time as previously discussed in https://github.com/mrdoob/three.js/issues/26891, as such a texture is technically also used by WebXR Layers and Depth Sensing modules, but are currently not present in either of their implementations.

I'm afraid when merging `WebXRDepthSensing` we have overlooked the `__webglTexture` hack. It's now a good opportunity to find a better solution for this use case. 

With `WebGPURenderer` in mind, we probably should name the class `RawTexture` instead of `GLTexture`. The class also needs an `isOpaque` flag that is set to `true` when using the texture from `getCameraImage()`.

Comment (Mugen87) [reply src/renderers/webxr/WebXRManager.js]: @mikeskydev I can try to figure out an implementation for `RawTexture` in the next days. When merged, you can just rebase the PR and migrate to `RawTexture`.

Comment (mikeskydev) [reply src/renderers/webxr/WebXRManager.js]: It's okay, I want this in so I'll work on `RawTexture` this afternoon.

Comment (Mugen87) [reply src/renderers/webxr/WebXRManager.js:1028]: >  I would have loved to have this review last week so I could have made the change in time for this month's release.

Well, we have always a lot on our plate and other tasks have a higher priority than XR related stuff.

File: src/renderers/webgl/WebGLTextures.js [hunk 2]
```diff
@@ -515,7 +522,7 @@ function WebGLTextures( _gl, extensions, state, properties, capabilities, utils,
 
 		if ( texture.isVideoTexture ) updateVideoTexture( texture );
 
-		if ( texture.isRenderTargetTexture === false && texture.version > 0 && textureProperties.__version !== texture.version ) {
+		if ( texture.isRenderTargetTexture === false && texture.isRawTexture === false && texture.version > 0 && textureProperties.__version !== texture.version ) {
```
Comment (Mugen87) [inline src/renderers/webgl/WebGLTextures.js]: Try it with:
```js
texture.isRawTexture !== true
```

File: src/renderers/webgl/WebGLTextures.js [hunk 3]
```diff
@@ -515,7 +522,7 @@ function WebGLTextures( _gl, extensions, state, properties, capabilities, utils,
 
 		if ( texture.isVideoTexture ) updateVideoTexture( texture );
 
-		if ( texture.isRenderTargetTexture === false && texture.version > 0 && textureProperties.__version !== texture.version ) {
+		if ( texture.isRenderTargetTexture === false && texture.isRawTexture !== true && texture.version > 0 && textureProperties.__version !== texture.version ) {
```
Comment (Mugen87) [inline src/renderers/webgl/WebGLTextures.js:518]: After a closer look, we can simplify the code in `WebGLTextures`. Because of the enhancement of `setTexture2D()`, you can delete the modifications in `deleteTexture()`.

`deleteTexture()` is only relevant when `initTexture()` is executed which is not the case for raw textures (because of the new check in this line). So no dispose handler is registered and `deallocateTexture()` is never executed. That is the expected behavior for raw textures. `RawTexture` is also irrelevant for render targets so it seems were are safe here.

Comment (mikeskydev) [reply src/renderers/webgl/WebGLTextures.js:518]: Thanks, I did figure it never hit this codepath, but wanted to be thorough.

**Comment by Mugen87** [comment]
I've removed the `opaque` property from `RawTexture` because the renderer does not evaluate the flag anymore. Also committed some JSDoc improvements.

Do you mind temporarily updating the builds so I can test the PR with a Quest 2 over `https://rawcdn.githack.com/`?

**Comment by mikeskydev** [comment]
Thanks! I have a built version for my own purposes on https://github.com/mikeskydev/three.js/tree/cam-access-build , but be aware `camera-access` isn't available on Quest yet. I've been working for mobile, and it should be supported on a default Android Chrome with no extra flags

**Comment by Mugen87** [comment]
Thanks for the heads-up. I can still test if the depth sensing demos work so we have no regression on that side.

https://rawcdn.githack.com/mikeskydev/three.js/98bc573b5d9ea8280116d100497ecadf08260139/examples/index.html

**Comment by Mugen87** [comment]
There seems to be no change in behavior 👍 . 

However, it seems like depth sensing is currently broken in production. When I understand [webxr_xr_dragging_custom_depth](https://threejs.org/examples/webxr_xr_dragging_custom_depth) correctly, the meshes should be occluded by objects in the real world (see https://x.com/rcabanier/status/1748050448270135425). However, I don't get objects occluded at least on my Quest 2. They are always rendered in front of everything.

There are no WebGL/WebXR warnings in the browser console when using remote debugging.

/ping @cabanier I'm afraid a regression has sneaked in. Could you please have a look?

**Comment by mikeskydev** [comment]
I tried the depth example on my phone (which doesn't support depth) and it seems to silently fail as it's an optional feature, so it may also be depth sensing was turned off for quest browser at some point?

**Comment by Mugen87** [comment]
Oh wait, it seems depth sensing only works with a Quest 3 since the Quest 2 does not have the required depth sensor.

@cabanier Sorry for the ping 😇  .

**Review by Mugen87 — APPROVED** [review]

**Comment by cabanier** [comment]
> Oh wait, it seems depth sensing only works with a Quest 3 since the Quest 2 does not have the required depth sensor.

Depth sensing is no longer working with these changes. I'll investigate why.

**Comment by cabanier** [comment]
> > Oh wait, it seems depth sensing only works with a Quest 3 since the Quest 2 does not have the required depth sensor.
> 
> Depth sensing is no longer working with these changes. I'll investigate why.

If I revert 6692d4d036 (Flip bool), depth sensing works again

**Comment by Mugen87** [comment]
The texture retrieved via `getDepthInformation()` just needs to be bound for usage, right? There is no need for an explicit texture data upload.

We've introduced `RawTexture` to have a dedicated code path for this use case and avoid code sections like:
```js
const texProps = renderer.properties.get( texture );
texProps.__webglTexture = depthData.texture;
```
If the depth sensing texture is wrapped into a `RawTexture` instance, the outcome _should_ be the same. Especially since nowhere in `WebXRDepthSensing` `texture.needsUpdate` is set to `true`. I wonder what me miss 🤔 .

**Comment by mikeskydev** [comment]
Technically opaque textures should be bound every frame as they go invalid, In camera access it doesn't work unless I rebind in the loop.

Any chance that depth was also working by a fluke and is also affected by the unbind?

**Comment by cabanier** [comment]
> Technically opaque textures should be bound every frame as they go invalid, In camera access it doesn't work unless I rebind in the loop.
> 
> Any chance that depth was also working by a fluke and is also affected by the unbind?

Yes, you need to rebind the textures every frame. This is because we play tricks under the hood and replace the underlying system texture.

File: src/renderers/webxr/WebXRDepthSensing.js [hunk 4]
```diff
@@ -74,18 +74,14 @@ class WebXRDepthSensing {
...
-	init( renderer, depthData, renderState ) {
+	init( depthData, renderState ) {
 
 		if ( this.texture === null ) {
 
-			const texture = new Texture();
-
-			const texProps = renderer.properties.get( texture );
-			texProps.__webglTexture = depthData.texture;
+			const texture = new RawTexture( depthData.depthTexture );
```
Comment (Mugen87) [inline src/renderers/webxr/WebXRDepthSensing.js]: There is a typo. It should be:
```js
const texture = new RawTexture( depthData.texture );
```

Comment (mikeskydev) [reply src/renderers/webxr/WebXRDepthSensing.js]: Oh how I miss types. Thanks for finding!

Comment (Mugen87) [reply src/renderers/webxr/WebXRDepthSensing.js]: @cabanier The latest commit 89c906ba2cd7ce3b5d3305dd1f664902290cff69 should fixed the broken depth sensing 🚀 .

Comment (cabanier) [reply src/renderers/webxr/WebXRDepthSensing.js]: > @cabanier The latest commit [89c906b](https://github.com/mrdoob/three.js/commit/89c906ba2cd7ce3b5d3305dd1f664902290cff69) should fixed the broken depth sensing 🚀 .

yes, it's working again!

**Comment by Mugen87** [comment]
@mikeskydev Thanks for working on camera access and implementing the `RawTexture` solution. It's great to see that also the depth sensing code path benefits from the new texture type.

**Comment by mikeskydev** [comment]
Agreed, thanks for pushing for the cleaner solution, helping get the PR over the line and for your time, it's really appreciated!

File: src/textures/RawTexture.js [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+ * Represents a texture created externally from the renderer context.
+ *
+ * This may be a texture from a protected media stream, device camera feed,
+ * or other data feeds like a depth sensor.
+ *
+ * Note that this class is only supported in {@link WebGLRenderer} right now.
+ *
+ * @augments Texture
+ */
+class RawTexture extends Texture {
```
Comment (mrdoob) [inline src/textures/RawTexture.js:13]: Maybe `ExternalTexture` could be a better name?
Are there other uses for it? If not, may be `WebXRCameraTexture`?

Comment (mikeskydev) [reply src/textures/RawTexture.js:13]: We also use it for webxr depth textures, but there was some debate about naming in the linked issues and RawTexture was settled on. I could see it being useful for anything that uses raw texture handles, possibly protected content?
