### PR TITLE
OrbitControls: fix Orthographic 'change' event

### LINKED ISSUE #27280: OrbitControls update event always fired if using an Orthographic Camera
### Description

Hi Three Team -

Just ran across this and am not sure if it's an issue or not.  I have an app that uses both ortho and perspective cameras along with OrbitControls.  I have the OrbitControls update() in my render loop because I am using dampening.  I also have an event listener or the change event of OrbitControls.  

When I'm in perspective camera, I see the change event being fired only when I'm actually orbiting around the scene.  In orthographic mode I see it firing every time the render loop calls update().  

Maybe this is by design and part of how ortho cameras need to work.  Just though I'd let you know.

### Reproduction steps

1. Create a scene and add orthographic and perspective cameras.   Add the orbit controls.
2. Add an event handler on the change event for OrbitControls.
3. Swap between the two cameras and watch it fire constantly when in orthographic mode, and only when the orbit controls are firing when in perspective.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

_No response_

### Version

0.158

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by sciecode**
Fixes #27280

Prevents `OrthographicCamera` from triggering `change` event every frame.

### CODE REVIEW

**Comment by sciecode** [comment]
Detected an issue, don't merge yet.

File: examples/jsm/controls/OrbitControls.js [hunk 1]
```diff
@@ -373,10 +373,15 @@ class OrbitControls extends EventDispatcher {
 					}
 
 				} else if ( scope.object.isOrthographicCamera ) {
+					
+					zoomChanged = scale != 1;
```
Comment (Mugen87) [inline examples/jsm/controls/OrbitControls.js:377]: Nit: `( scale !== 1 )`.

**Comment by Mugen87** [comment]
The PR indeed fixes the issue. Here is the code I have tested with: https://jsfiddle.net/13Ltqzye/

File: examples/jsm/controls/OrbitControls.js (hunk 1 above)
Comment (sciecode) [reply examples/jsm/controls/OrbitControls.js]: 👍🏽

**Review by Mugen87 — APPROVED** [review]

**Comment by jedleslie** [comment]
You all rule.  Thanks for all you do!
