### PR TITLE
WebGLRenderer: Add support for multiple programs per material.

### LINKED ISSUE #15047: WebGLRenderer: Add support for multiple shader programs with a single material.
It would be necessary to have multiple multiple webglprogram on a single material to solve #11400.

This would require several steps to be taken to get this done:
 - [x] Figuring out what parameters are necessary to generate a webglprogram and use a single parameter source to create it. (#18279)
 - [ ] Build single parameter source from 4 parameter sources: material, object, renderer, scene.
     - [ ] Material parameter: gets regenerated when needsUpdate is true
     - [ ] Renderer parameter: gets regenerated every render    
     - [ ] Scene parameter: gets regenerated every render
     - [ ] object parameter: gets regenerated every ??
 - [ ] Create keys based of the 4 parameter sources to figure out if something changed.
 - [ ] Use single parameter source as key to figure out if program needs to be created.
 - [ ] Use single parameter source as key to figure out which program to use.

We would also need to track which program gets used by which material to make sure that the programs get deleted when the material gets disposed of.

### LINKED ISSUE #17701: InstancedMesh's setMatrixAt fails when another mesh in the scene has the same material
##### Description of the problem

I'm having a problem where the InstancedMesh method `setMatrixAt` seems to fail (the matrix positions doesn't change visually) whenever I add another object with the same material object (not a clone) in the scene. No log/warning/errors are emitted.

The following briefly illustrates:

```js
    var geometry = new THREE.BoxBufferGeometry();
    var material = new THREE.MeshStandardMaterial( { roughness: 0, envMap: texture });
    var mesh1 = new THREE.Mesh( geometry, material );
    mesh1.position.set(0, 1, 0);
    scene.add( mesh1 ); // removing this line makes the instanced mesh work as intended
    mesh = new THREE.InstancedMesh( geometry, material, 9 ); // same material usage
    scene.add( mesh ); // This works and I can see both meshes in the scene.
    
    var dummy = new THREE.Object3D();
    dummy.position.set( 1, 5, 1 );
    dummy.updateMatrix();
    mesh.setMatrixAt( 0, dummy.matrix ); // Nope, doesn't work, it just stays where it's at.
    mesh.setMatrixAt( 1, dummy.matrix ); // Rotation seems to be applied, but position doesn't.
    // It looks like every instance is at the same place, but I don't know.
```

Note that if I use material.clone() at the instanced mesh declaration, the problem also goes away / is fixed, but now I have two materials, and I intend to have one for performance reasons.

A live example is available here:

* [jsfiddle](https://jsfiddle.net/ghmrdk4z/4/) (The problem is that you should see multiple boxes, but only 1 or 2 are visible, remove line 41 to fix)

##### Three.js version

- [x] Dev
- [x] r109
- [ ] r108

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [X] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

(Not applicable, as far as I know)

### LINKED ISSUE #19056: Shader recompilation when using sRGB encoding and RTT
##### Description of the problem

Hi there,

I'm working on an application that renders the same scene twice in a single frame, once without post processing and once using EffectsComposer. The use case is basically an editor with a thumbnail preview of the scene with postfx.

This seems to trigger a shader recompilation, as has been discovered in a few other issues*. The advice so far has been to only use EffectsComposer and apply gamma correction as a pass in the effects chain, but this is pretty problematic for our use case as we use line rendering quite a bit for e.g. reference grids so losing hardware AA when using RTT results in unacceptable image quality.

A potential work around is setting the encoding of all render targets in the EffectComposer chain to use sRGB encoding, but I'm not certain what problems this might produce and feels brittle since there is no way to _force_ every pass to use the correct encoding as far as I know. But results should still be correct, since my understanding of using sRGB encoding for a texture is that hardware then performs the appropriate conversions on reads/writes, so shaders can still run code as if the data was linear.

It seems that the necessary conditions to reproduce are:
- sRGB encoding for `renderer.outputEncoding`
- using two different cameras
- RTT (EffectsComposer in this case)

Stepping through the code it seems specifically to do with the [`renderContext.state.lights` version](https://github.com/mrdoob/three.js/issues/14121) being different for each camera, which then triggers a check of the various properties against those when the program was created, which in will fail due to the different renderTargets and their encoding.

https://jsfiddle.net/BruOps/qy6o74pn/9/

* Related:
https://github.com/mrdoob/three.js/issues/18893
https://github.com/mrdoob/three.js/issues/18699
https://github.com/mrdoob/three.js/issues/18355
~https://github.com/mrdoob/three.js/issues/14121~

##### Three.js version

- [x] Dev
- [x] r115

Introduced in r112

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

##### Hardware Requirements (graphics card, VR Device, ...)

None

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #15047.
Fixed #19056.
Fixed #17701.

A material can now reference to multiple shader programs. This avoids expensive shader recompilation effects and solves some conceptual issues like #17701. Since this PR is a deep change in how `WebGLRenderer` manages shader programs, I recommend to merge it at the beginning of a dev cycle.

The performance of existing apps should not be affected by this change since the general code flow in the renderer is the same. That said, it's still room for performance improvements since I've noticed during the development that certain tasks like the build of uniforms lists _could_ be optimized.

BTW: I've renamed `initMaterial()` to `getProgram()` since the method now returns an instance of `WebGLProgram` to the caller.

### CODE REVIEW

File: src/renderers/WebGLRenderer.js [hunk 1]
```diff
@@ -905,19 +907,13 @@ function WebGLRenderer( parameters ) {
 
 						const material2 = material[ i ];
 
-						if ( compiled.has( material2 ) === false ) {
```
Comment (Mugen87) [inline src/renderers/WebGLRenderer.js:908]: I'm afraid this check does not work anymore since materials can now be compiled multiple times.

**Comment by cedemax** [comment]
Would this fix the closed issue [#19566](https://github.com/mrdoob/three.js/issues/19566)? If so, is there any example or tips on how to modify the use of overridematerial (in SSAOPass for example) to use this new feature? Thanks!

**Comment by Mugen87** [comment]
> Would this fix the closed issue #19566?

Yes, I think so.

**Comment by mrdoob** [comment]
Lets try merging this one this cycle! Do you mind resolving the conflicts?

**Comment by Mugen87** [comment]
Conflicts resolved!

**Comment by mrdoob** [comment]
@Oletus Do you have time to take a look at this PR?

File: src/renderers/WebGLRenderer.js [hunk 2]
```diff
@@ -1430,11 +1421,24 @@ function WebGLRenderer( parameters ) {
 
 		}
 
-		const progUniforms = materialProperties.program.getUniforms();
+		const progUniforms = program.getUniforms();
 		const uniformsList = WebGLUniforms.seqWithValue( progUniforms.seq, uniforms );
```
Comment (Oletus) [inline src/renderers/WebGLRenderer.js:1425]: Maybe some more of the uniform-related data could be made a property of the program so it wouldn't need to be regenerated here on program change? But it's fine to leave this as a follow-up change.

File: src/renderers/WebGLRenderer.js (hunk 1 above)
Comment (Oletus) [reply src/renderers/WebGLRenderer.js:917]: The change seems otherwise acceptable, but this code doesn't seem to update materialProperties.currentProgram, which prevents early outs in getProgram().

File: src/renderers/WebGLRenderer.js [hunk 3]
```diff
@@ -1337,67 +1333,62 @@ function WebGLRenderer( parameters ) {
...
 
-			programChange = false;
+		if ( program !== undefined ) {
 
-		} else if ( parameters.shaderID !== undefined ) {
+			// early out if program and light state is identical
 
-			// same glsl and uniform list
-			return;
+			if ( materialProperties.currentProgram === program && materialProperties.lightsStateVersion === lightsStateVersion ) {
```
Comment (Oletus) [inline src/renderers/WebGLRenderer.js:1361]: It seems a bit messy that currentProgram is checked here even though it's managed outside this function. Would it be fine to just set currentProgram at the end of this function instead? That would make the early out work also in WebGLRenderer.compile().

**Review by Oletus — CHANGES_REQUESTED** [review]
This is definitely a welcome change! Few things I'd like to see changed inline but nothing major.

Also, what I'm a bit worried about is loading multiple versions of the same shader program unintentionally, though it's obviously better than wrecking runtime performance by constantly recompiling programs. For example, it's easy to end up using multiple framebuffer formats in a situation where just using sRGB for everything would be fine. Each format multiplies the number of shaders that need to be loaded, increasing load times. Would there be any suitable mechanism for communicating to the three.js app developer that their render pipeline may be using more variants of shaders than they expect?

File: src/renderers/WebGLRenderer.js [hunk 4]
```diff
@@ -1468,49 +1472,67 @@ function WebGLRenderer( parameters ) {
...
+			needsProgramChange = true;
 			materialProperties.__version = material.version;
 
 		}
 
+		//
+
+		let program = materialProperties.currentProgram;
+
+		if ( needsProgramChange === true ) {
```
[the remark this answers is not in the document]
Comment (Mugen87) [reply src/renderers/WebGLRenderer.js:1524]: For clarification reason, we have lately started to make such comparison more explicit. Similar to 
```js
if ( object.isMesh === true )
```
instead of 
```
if ( object.isMesh )
```

File: src/renderers/WebGLRenderer.js (hunk 2 above)
Comment (Mugen87) [reply src/renderers/WebGLRenderer.js:1425]: > But it's fine to leave this as a follow-up change.

I would prefer that. The PR is already complex and this change be changed later.

File: src/renderers/WebGLRenderer.js (hunk 3 above)
Comment (Mugen87) [reply src/renderers/WebGLRenderer.js:1361]: I think that should work!

File: src/renderers/WebGLRenderer.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (Oletus) [reply src/renderers/WebGLRenderer.js:1525]: Ok, I wasn't aware of this. A bit unusual choice, though it can make sense in the context of JavaScript 🙂

**Review by Oletus — APPROVED** [review]
Looks good!

**Comment by mrdoob** [comment]
> Would there be any suitable mechanism for communicating to the three.js app developer that their render pipeline may be using more variants of shaders than they expect?

We could try to add this to https://github.com/threejs/three-devtools?

**Comment by mrdoob** [comment]
Maaaaaany thanks!
