### PR TITLE
ColladaLoader: Fix #12855

### LINKED ISSUE #12855: ColladaLoader fails to parse dae file
Hello,

[ColladaLoader.js](https://github.com/mrdoob/three.js/blob/dev/examples/js/loaders/ColladaLoader.js) fails to parse these [dae files](https://github.com/fetchrobotics/fetch_ros/tree/indigo-devel/fetch_description/meshes). I got these stack trace.

[shoulder_pan_link.dae](https://raw.githubusercontent.com/fetchrobotics/fetch_ros/indigo-devel/fetch_description/meshes/shoulder_pan_link.dae)

```
http://localhost:8888/fetch_description/meshes/shoulder_pan_link.dae
ColladaLoader.js:3350 THREE.ColladaLoader: DOMParser: 6.8740234375ms
ColladaLoader.js:3357 THREE.ColladaLoader: File version 1.4.1
ColladaLoader.js:3403 THREE.ColladaLoader: Parse: 64.591064453125ms
ColladaLoader.js:202 Uncaught TypeError: Cannot read property 'build' of undefined
    at getBuild (ColladaLoader.js:202)
    at getCamera (ColladaLoader.js:1622)
    at buildNode (ColladaLoader.js:3032)
    at getBuild (ColladaLoader.js:204)
    at getNode (ColladaLoader.js:3227)
    at buildVisualScene (ColladaLoader.js:3273)
    at buildLibrary (ColladaLoader.js:192)
    at THREE.ColladaLoader.parse (ColladaLoader.js:3416)
    at Object.onLoad (ColladaLoader.js:28)
    at XMLHttpRequest.<anonymous> (three.js:30483)
```

##### Three.js version

- [x] Dev
- [x] r88
- [ ] ...

##### Browser

- [x] All of them
- [] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
At least lights and camera are processed now with more tolerance 😉 .

That's sufficient for the `dae` files mentioned in #12855

### CODE REVIEW

**Comment by jihoonl** [comment]
I quickly ran a test and got this error.
```
Uncaught TypeError: Cannot read property 'extractUrlBase' of undefined
    at THREE.ColladaLoader.load (ColladaLoader.dev.js:22)
    at new ROS3D.MeshResource (ros3d.js:2650)
    at new ROS3D.Urdf (ros3d.js:3896)
    at ros3d.js:4012
    at roslib.js:1458
    at Ros.<anonymous> (roslib.js:2173)
    at Ros.listener (roslib.js:265)
    at Ros.EventEmitter.emit (roslib.js:329)
    at handleMessage (roslib.js:2308)
    at handlePng (roslib.js:2324)
```

**Comment by Mugen87** [comment]
You need to use the latest `three.js` build from `dev`. A new file `LoaderUtils` was introduced with this #12654.

**Comment by Mugen87** [comment]
Oh sry. Looks like the build files are not updated yet. If you want to test this change, you have to build `three.js` yourself. But that's not complicated. Just run `npm install` in the project root directory and then `npm run build` (node.js must be installed).

**Comment by jihoonl** [comment]
Ok. on it. thanks for quick info.

**Comment by jihoonl** [comment]
Thanks for the quick fix. I confirmed that no error occurs while loading.  #12856 also appears while loading this model though.

noerror

**Comment by Mugen87** [comment]
Happy to hear this good news 😊 🎉

**Comment by jihoonl** [comment]
Could you hold this PR? I just found out that it is not visualizing other dae files. I would like to test it more with [these dae files](https://github.com/T045t/turtlebot/blob/kinetic/turtlebot_description/meshes/stacks/hexagons/plate_top.dae).

**Comment by Mugen87** [comment]
I think it won't hurt to merge this one. We can make a new PR if necessary...

**Comment by jihoonl** [comment]
Ok. I have confirmed that it works most of our use cases. [The linked dae file](https://github.com/T045T/kobuki/blob/devel/kobuki_description/meshes/main_body.dae) and [these](https://github.com/T045t/turtlebot/tree/kinetic/turtlebot_description/meshes/stacks/hexagons) aren't visualising.

These dae files contain [instance_light](https://github.com/T045t/turtlebot/blob/kinetic/turtlebot_description/meshes/stacks/hexagons/plate_top.dae#L145) without instance_camera.

**Comment by Mugen87** [comment]
`dev` is currently a bit broken 😅 . But there is already a PR to fix this see #12868

**Comment by Mugen87** [comment]
`main_body.dae` should work after the mentioned PR is merged.

**Comment by mrdoob** [comment]
Thanks!

File: examples/js/loaders/ColladaLoader.js [hunk 1]
```diff
@@ -1624,7 +1624,15 @@ THREE.ColladaLoader.prototype = {
 
 		function getCamera( id ) {
 
-			return getBuild( library.cameras[ id ], buildCamera );
+			var data = library.cameras[ id ];
+
+			if ( data !== undefined ) {
```
Comment (mrdoob) [inline examples/js/loaders/ColladaLoader.js]: Actually, considering that the check is simple, what do you think about logging a warning in the console for these situations? Something like...

```js
var data = library.cameras[ id ];

if ( data !== undefined ) {

    return getBuild( data, buildCamera );

}

console.warn( 'THREE.ColladaLoader: Couldn't find camera ', id );
return null;
```

We can later also warn the user that the file doesn't follow the collada spec. By now it serves to document the fact that we're being tolerant, and also to highlight "broken" files. It will also be handy in the future if someone is having issues with a collada file and we see that in the logs, we can already suspect that they user a bad exporter.

Comment (Mugen87) [reply examples/js/loaders/ColladaLoader.js]: Great idea 👍 . I'll make a PR 😊
