### PR TITLE
EXRLoader: Fix for Firefox by only returning RGBA textures

### LINKED ISSUE #16778: RGB floating point textures broken on latest Firefox
The EXRLoader recently broke on Firefox, tested on MacOS and Windows.

See https://threejs.org/examples/webgl_materials_envmaps_exr.html

It works on Chrome (setting aside visual artefacts as reported on https://github.com/mrdoob/three.js/issues/16409)

### PR DESCRIPTION
**Pull request by JordyvanDortmont**
Fixes #16778.

I quite literally implemented what @Mugen87 suggested https://github.com/mrdoob/three.js/issues/16778#issuecomment-537948960.

This works for Firefox and many other browsers and platforms. I didn't test the `PIZ_COMPRESSION` case, but I adjusted the argument to the original number of channels. I think PR #17883 that's just in also works with this change.

### CODE REVIEW

**Comment by sciecode** [comment]
Works for all compression types currently supported and has no conflicts with PR #17883.

**Comment by sciecode** [comment]
[ PR example ](https://rawcdn.githack.com/dialoguetrainer/three.js/fdcc551b9de4a628ca25b1fca7d6393917952c71/examples/webgl_materials_envmaps_exr.html)
[ DEV example](https://threejs.org/examples/?q=exr#webgl_materials_envmaps_exr)

**Review by Mugen87 — APPROVED** [review]
It's great to see the example finally running in Firefox!

**Comment by mrdoob** [comment]
@WestLangley does this look good to you?

**Comment by WestLangley** [comment]
>@WestLangley does this look good to you?

I don't think so. Is alpha being set to 1 when the data is RGB?

**Comment by Mugen87** [comment]
One way to ensure `1` is set for alpha is to initialize `byteArray` with this value. When parsing `RGB` data, the alpha value won't be overwritten. Initializing can be done like so:
```js
var size = width * height * numChannels;

var byteArray1 = new Float32Array( size );
var byteArray2 = new Uint16Array( size );

byteArray1.fill(1, 0, size); 
byteArray2.fill(0x3C00, 0, size); // Uint16Array holds half float data, 0x3C00 is 1
```
Adding this code here should work:

https://github.com/mrdoob/three.js/blob/8e60034bfa521e0d184adb6b81c9132dac042f61/examples/js/loaders/EXRLoader.js#L1157-L1165

**Comment by JordyvanDortmont** [comment]
Thanks @Mugen87 and @WestLangley. Fixed it.

**Comment by WestLangley** [comment]
@JordyvanDortmont It appears my comments were marked as resolved without first making the requested changes, so I will repeat:

For a temporary, browser-specific work-around, _comment out_ the existing code (do not remove it), and add the work-around code with an explanatory comment. That way, the existing code can be restored at a future date when the work-around is no longer needed.

File: examples/js/loaders/EXRLoader.js [hunk 1]
```diff
@@ -1220,7 +1238,7 @@ THREE.EXRLoader.prototype = Object.assign( Object.create( THREE.DataTextureLoade
 			width: width,
 			height: height,
 			data: byteArray,
-			format: EXRHeader.channels.length == 4 ? THREE.RGBAFormat : THREE.RGBFormat,
+			format: numChannels == 4 ? THREE.RGBAFormat : THREE.RGBFormat,
```
Comment (Mugen87) [inline examples/js/loaders/EXRLoader.js]: Is this a regression? I  think we always want to return `THREE.RGBAFormat`?

**Comment by Mugen87** [comment]
We have a version control system, so it should be easy enough to restore the code via git. I think adding a comment with a reference to this PR (`#17887`) should be sufficient.

**Review by WestLangley — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!
