### PR TITLE
WebGLRenderer: Only use sRGB shader encode for default framebuffer.

### LINKED ISSUE #23251: outputEncoding not handled correctly when using sRGB render target in WebGL2
**Describe the bug**

In #23129, the `outputEncoding` is calculated differently from before. I believe the previous way is correct.

**To Reproduce**

See following code and fiddle.

***Code***

```js

const renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );
renderer.outputEncoding = THREE.sRGBEncoding;
renderer.setPixelRatio( window.devicePixelRatio );
document.body.appendChild( renderer.domElement );

const geometry = new THREE.PlaneGeometry( 2, 2 );
const material = new THREE.MeshBasicMaterial();
const mesh = new THREE.Mesh( geometry, material );

const renderTarget = new THREE.WebGLRenderTarget( window.innerWidth, window.innerHeight, { encoding: THREE.sRGBEncoding } );

const camera = new THREE.OrthographicCamera();
camera.position.set( 0, 0, 1 );

new THREE.TextureLoader().load( 'https://threejs.org/examples/textures/crate.gif', (texture) => {

  texture.encoding = THREE.sRGBEncoding;

  material.map = texture;
  renderer.setRenderTarget( renderTarget );
  renderer.render( mesh, camera );

  material.map = renderTarget.texture;
  renderer.setRenderTarget( null );
  renderer.render( mesh, camera );

} );

```

***Live example***

* [jsfiddle-latest-release](https://jsfiddle.net/st06pgbc/)
* [jsfiddle-dev](https://jsfiddle.net/0wjhn1pu/1/)

**Expected behavior**

`dev` should behave the same as `r136`.

**Screenshots**

`r136`
image

`dev`
image

**Platform:**

 - Device: Desktop
 - OS: Linux
 - Browser: Chrome
 - Three.js version: dev

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #23251.

**Description**

The inline shader sRGB encode only needs to be done for the default framebuffer.

### CODE REVIEW

File: src/renderers/WebGLRenderer.js [hunk 1]
```diff
@@ -1415,7 +1415,7 @@ function WebGLRenderer( parameters = {} ) {
 
 		const fog = scene.fog;
 		const environment = material.isMeshStandardMaterial ? scene.environment : null;
-		const encoding = ( _currentRenderTarget === null ) ? _this.outputEncoding : _currentRenderTarget.texture.encoding;
+		const encoding = ( _currentRenderTarget === null ) ? _this.outputEncoding : LinearEncoding;
```
Comment (chubei-oppen) [inline src/renderers/WebGLRenderer.js:1418]: I think we still need to consider the WebGL1 case. We still need to do inline encoding if context is WebGL1.

Comment (chubei-oppen) [reply src/renderers/WebGLRenderer.js:1418]: Sorry, didn't realize `ext_sRGB` is required now.

**Comment by Mugen87** [comment]
Updated builds for further testing: e2dac113d6e0563b71dabcb4b1f549d6d688e376

**Comment by mrdoob** [comment]
Thanks!
