### PR TITLE
CSM: Avoid circular dependency in camera computations.

### LINKED ISSUE #25246: CSM not rendered properly in the first frame
### Description

When you run the _webgl_shadowmap_csm_ example, the first frame is missing some shadows (one or more near cascades).

I guess some update of a camera or a light is missing in `CSM.update`.

### Reproduction steps

1. to make the issue obvious. open _webgl_shadowmap_csm.html_ source and replace `requestAnimationFrame( animate )` with `setTimeout(() => requestAnimationFrame( animate ), 2000)` or remove it completely, so that you can see the first frame
2. run _webgl_shadowmap_csm.html_
3. notice near shadows are missing

### Code

Use the example code `webgl_shadowmap_csm.html`

### Live example

Use https://threejs.org/examples/webgl_shadowmap_csm, but to better see the issue modify the source as described

### Screenshots

This is how the first frame looks like:

image

And this is the correct result, shown on sucessive frames:

image

### Version

r148

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by OndrejSpanel**
Fixed #25246.

**Description**

CSM computations in `CSM.update` used `light.shadow.camera` `position` and `orientation`, but those were set during the rendering based on `light.position` (see `LightShadow.updateMatrices`), which itself was set later in the `CSM.update`. This led to a kind of chicken and egg problem, as a result the shadows in the first frame rendered ever or after significant camera orientation change had some shadows missing because of improper bounding boxes computed for the shadow frustums.

The PR avoids the circular dependency, using `lightDirection` to compute the transformation matrix directly.

### CODE REVIEW

**Comment by OndrejSpanel** [comment]
@Mugen87 @WestLangley Can someone please check the PR? The fix is short and simple, but finding the exact cause was quite time consuming and I would hate to lose that work.

File: examples/jsm/csm/CSM.js [hunk 1]
```diff
@@ -200,14 +204,20 @@ export class CSM {
...
+		_lightOrientationMatrix.lookAt( camera.position, _lightTarget, _up );
+		_lightOrientationMatrixInverse.copy(_lightOrientationMatrix).invert();
+
 		for ( let i = 0; i < frustums.length; i ++ ) {
 
 			const light = this.lights[ i ];
 			const shadowCam = light.shadow.camera;
 			const texelWidth = ( shadowCam.right - shadowCam.left ) / this.shadowMapSize;
 			const texelHeight = ( shadowCam.top - shadowCam.bottom ) / this.shadowMapSize;
-			light.shadow.camera.updateMatrixWorld( true );
```
Comment (Mugen87) [inline examples/jsm/csm/CSM.js:209]: Wouldn't it be possible to use the following code block instead:
```js
light.updateWorldMatrix( true, false );
light.target.updateWorldMatrix( true, false );

light.shadow.updateMatrices( light );
```
Shouldn't this code also ensure the shadow camera has a correct world matrix for further computation?

Comment (OndrejSpanel) [reply examples/jsm/csm/CSM.js:209]: That is the chicken-egg problem. Light position is not set yet, it will be set later in this function based on the frustum bounding box.

File: examples/jsm/csm/CSM.js [hunk 2]
```diff
@@ -200,14 +204,20 @@ export class CSM {
 
 		const camera = this.camera;
 		const frustums = this.frustums;
+
+		// for each frustum we need to find its min-max box aligned with the light orientation
+		// the position in _lightOrientationMatrix does not matter, as we transform there and back
+		_lightTarget.copy( this.lightDirection ).add( camera.position );
+		_lightOrientationMatrix.lookAt( camera.position, _lightTarget, _up );
```
Comment (Mugen87) [inline examples/jsm/csm/CSM.js:211]: Instead of defining a custom `up` vector, could you use `light.up` instead?

Comment (OndrejSpanel) [reply examples/jsm/csm/CSM.js:211]: Good idea. The trouble is `light` is not available at the point where `_lightOrientationMatrix` is computed, which is outside the loop. I can use `camera.up`, though - adding a commit doing it that way.

Comment (Mugen87) [reply examples/jsm/csm/CSM.js]: Although using `camera.up` isn't right. It has to be the `up` vector of the light. Probably better to move the computation inside the loop where you can access `light`.

Comment (OndrejSpanel) [reply examples/jsm/csm/CSM.js]: This may sound like a reasonable thing as first sight, but at second side that would achieve nothing more than my original code. The `light` inside of the loop is a synthetic light created by CSM plugin (see `createLights`). It has no relation to the real directional light in the scene, one could use `Object3D.DefaultUp` instead. The light direction is passed in `data.lightDirection` and I have no access to the `DirectionalLight` object. I could pass the `up` next to the direction, or perhaps the whole interface could be changed to pass the whole light object.

Comment (OndrejSpanel) [reply examples/jsm/csm/CSM.js]: Note: previous implementation effectively used `Object3D.DefaultUp`, as the light direction is set using `shadowCamera.lookAt( _lookTarget );` in `LightShadow.matrices`. `DirectionalLightShadow` uses `new OrthographicCamera` to construct its camera, never manipulating its `up` in any way.

Comment (Mugen87) [reply examples/jsm/csm/CSM.js]: Okay, if the `up` vector of the generated lights can't be manipulated anyway it's okay to use a default vector.

**Comment by OndrejSpanel** [comment]
There is some screenshot difference reported after the last commit:

ERROR! Diff wrong in 0.938 of pixels in file: webgl_shadowmap_csm

Does this mean means most pixels are wrong, or that one pixel is wrong?

When running locally I do not see any noticeable difference.

**Comment by Mugen87** [comment]
https://threejs.org/examples/webgl_shadowmap_csm
https://raw.githack.com/OndrejSpanel/three.js/fix_csm_computations/examples/webgl_shadowmap_csm.html

The boxes have a random height but it seems the shadow quality itself have changed when comparing dev and prod.

**Comment by OndrejSpanel** [comment]
On my computer I do not see any difference in the shadow quality, only in the random box size (which is not new, therefore I do not think it should be a problem). If you see a difference, can you please post some screenshots?

**Comment by Mugen87** [comment]
Granted, the difference is not easy to spot. But check the shadows between the second and third box.

Prod:

image

Dev:

image

**Comment by OndrejSpanel** [comment]
I have run make-screenshot locally. One difference I see compared to the previous version is previous version contained some artifact line, which is not present in my version:

image

I commit the screenshot from the new version, though I am not convinced it will pass, as this cannot account for 93% of pixels.

**Comment by Mugen87** [comment]
Not sure why the E2E test fails under these conditions. I'll try a re-run.

**Comment by OndrejSpanel** [comment]
It has already failed three times in a row, therefore I guess it seems something significant. I have no idea what could it be, though. 😟

**Comment by OndrejSpanel** [comment]
I have reverted the DefaultUp commit - let us see if it has any influence on the test on the runner (I see no difference on my computer). Based on the result, I will try a few more commits to pinpoint the issue.

**Comment by OndrejSpanel** [comment]
I think it is obvious now something is wrong with `Object3D.DefaultUp` during the e2e test. The most compelling evidence is fea82c0315899cb03be2a6eb4673a81fdbfc9ca9. I guess the variable is either not initialized, or has a different value.

I do not see any issue when running `npm run make-screenshot webgl_shadowmap_csm` on my computer even when it is using the `DefaultUp`,

I have to say I am confused and unsure how to proceed.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
TBH, as long as https://github.com/mrdoob/three.js/issues/25246 is fixed, I'm okay with the PR in its current state^^. When merged, I have a look at it on my local computer.

**Comment by OndrejSpanel** [comment]
I see you approved it - should I use the version with `camera.up`, or rather define my own `_up`? Each of them has limitations: `camera.up` is changed when rendering cubemaps, my own `_up` does not follow any changes in `Object3D.DefaultUp`.

I have no idea how would I debug the e2e runner issues - even console.log does not seem to work in `npm run make-screenshot`, therefore all I can see is the task has failed or succeeded, which does not tell much.

**Comment by OndrejSpanel** [comment]
> When merged, I have a look at the E2E issue on my local computer.

I hope you will see something, as I did not see any issues not only with the example, but with E2E task as well - the screenshot was produced fine even with `DefaultUp`.

**Comment by Mugen87** [comment]
> should I use the version with camera.up, or rather define my own _up?

In this case use your own `_up` vector.

**Comment by OndrejSpanel** [comment]
I think my PR was based on r.144 previously. I have rebased it to current dev and added `DEFAULT_UP`. Now stay tuned for the test result.

**Comment by OndrejSpanel** [comment]
I am dropping the DEFAULT_UP commit again. For anyone interested it is stored in https://github.com/OndrejSpanel/three.js/tree/failing_e2e_csm_defaultup

**Comment by Mugen87** [comment]
@gkjohnson What do you think about this PR?

**Comment by OndrejSpanel** [comment]
What can be done about the PR now?

**Comment by Mugen87** [comment]
@mrdoob When CSM was added to the repo with #18481, the sources from the original repository were copied over.

I think it would be better to refactor the code and organize it similar to the _external_ examples (bvh, pathtracer, ifc etc.). Meaning include a build from the CSM project build from a CDN. The code is then maintained in https://github.com/StrandedKitty/three-csm and not here.

File: examples/jsm/csm/CSM.js [hunk 3]
```diff
@@ -200,14 +204,20 @@ export class CSM {
...
+		_lightOrientationMatrixInverse.copy(_lightOrientationMatrix).invert();
```
Comment (StrandedKitty) [inline examples/jsm/csm/CSM.js:212]: I'm pretty sure you can just simplify it to
```
_lightOrientationMatrix.lookAt( new Vector3(), this.lightDirection, _up );
_lightOrientationMatrixInverse.copy( _lightOrientationMatrix ).invert();
```
(no need for `_lightTarget`)

**Comment by StrandedKitty** [comment]
@OndrejSpanel This is great that you've figured it out! Pretty clever solution. I was aware of this bug for quite some time but it seemed too minor to spend time looking into. Actually I think I have the same issue in my another CSM implementation built on top of a custom engine...

**Comment by mrdoob** [comment]
@Mugen87 I guess it's up to @StrandedKitty...

@StrandedKitty What would you like us to do?

**Comment by StrandedKitty** [comment]
> @StrandedKitty What would you like us to do?

I agree that it's better to maintain the CSM code in one place (in the original repository) and use it in the example through import. I think when I originally made a PR to add CSM example here none of the existing examples used imports so we didn't even consider this option at that point.

**Comment by OndrejSpanel** [comment]
If the original repo should be "the single source of truth", I would like to remind of another PR of mine, which went into this repo: #23631. You might find others fixes in https://github.com/mrdoob/three.js/commits/master/examples/webgl_shadowmap_csm.html

**Comment by LeviPesin** [comment]
https://github.com/mrdoob/three.js/pull/25119 also slightly modified CSM's code.

**Comment by StrandedKitty** [comment]
@OndrejSpanel @LeviPesin Thanks, of course I will have to move all the recent changes that are only present here to my repository. And after this I will make a new PR to modify the example. But for now we should merge this PR.

**Comment by Mugen87** [comment]
@StrandedKitty As an orientation, check out how [webgl_raycaster_bvh](https://github.com/mrdoob/three.js/blob/master/examples/webgl_raycaster_bvh.html) is organized. Ideally, the CSM example is structured similar 👍 .
