### PR TITLE
ShadowMaskModel: Fix signatures.

### LINKED ISSUE #30762: WebGPU - ShadowNodeMaterial not working
### Description

In a basic scene using ShadowMaterial make error `Bug Uncaught TypeError: Cannot read properties of undefined (reading 'rgb') at ShadowMaskModel.finish` 

Also in my test I success to make the shadows work only with standard/physical material, `MeshBasicMaterial` or `MeshBasicNodeMaterial` dont work either..

### Reproduction steps

1. make a basic lighting shadow setup
2. use ShadowNodeMaterial

### Code

```js
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

let mesh, renderer, scene, camera, controls;

init();

function init() {

    // renderer
    renderer = new THREE.WebGPURenderer();
    renderer.setSize( window.innerWidth, window.innerHeight );
    renderer.setPixelRatio( window.devicePixelRatio );
    renderer.setAnimationLoop( animate );
    
    // shadowMap enabled 
    renderer.shadowMap.enabled = true
    
    document.body.appendChild( renderer.domElement );

    scene = new THREE.Scene();
    scene.background = new THREE.Color( 0x000000 );
    camera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight, 1, 10000 );
    camera.position.set( 20, 20, 20 );
    controls = new OrbitControls( camera, renderer.domElement );

		scene.add( new THREE.AmbientLight( 0x222222 ) );

		// light
    const light = new THREE.DirectionalLight( 0xffffff, 1 );
    light.position.set( 0,50, 0 );
    // light shadow settings
    light.castShadow = true
		light.shadow.camera.near = 0.1
		light.shadow.camera.far = 100
		light.shadow.camera.right = 10
		light.shadow.camera.left = - 10
		light.shadow.camera.top	= 10
		light.shadow.camera.bottom = - 10
		light.shadow.mapSize.width = 2048
		light.shadow.mapSize.height = 2048
		light.shadow.radius = 5

    scene.add( light );
    scene.add( new THREE.AxesHelper( 20 ) );
    
    // FLOOR
    
    // TEST 1 : Bug Uncaught TypeError: Cannot read properties of undefined (reading 'rgb') at ShadowMaskModel.finish
    // const shadowMaterial = new THREE.ShadowMaterial( { transparent: true } )
  	
    // TEST 2 : No shadow showing
    const shadowMaterial = new THREE.MeshBasicNodeMaterial( {  } )
    
  	// TEST 3 : Shadow showing
    //const shadowMaterial = new THREE.MeshStandardMaterial( {  } )
    
    const floor = new THREE.Mesh( new THREE.PlaneGeometry( 20, 20 ), shadowMaterial )
		floor.receiveShadow = true
		floor.rotation.x = - Math.PI / 2
		floor.position.y = -5
		floor.position.x = 1
		scene.add( floor )

    // SPHERE
    const geometry = new THREE.SphereGeometry( 5, 12, 8 );
    const material = new THREE.MeshPhongMaterial( {} );
    mesh = new THREE.Mesh( geometry, material );
    mesh.castShadow = true
    scene.add( mesh );
    
}

function animate() {
    renderer.render( scene, camera );
}
```

### Live example

https://jsfiddle.net/54r71tdb/19/

### Screenshots

_No response_

### Version

r175dev

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #30762.

**Description**

The `direct()` and `finish()` methods of `ShadowMaskModel` have outdated signatures. It seems when refactoring shadow and lighting related code the interface of this class was overlooked.

The PR restores `ShadowMaterial` with `WebGPURenderer`. However, `ShadowNodeMaterial` does not show the shadow mask for some reason. The following fiddles is using `ShadowMaterial`  and fixed with the PR but when using `ShadowNodeMaterial`, the plane gets black. https://jsfiddle.net/tbmgkf4s/

@sunag Before I dive into this more deeply, do you have an idea what's going wrong?

### CODE REVIEW

**Comment by sunag** [comment]
> @sunag Before I dive into this more deeply, do you have an idea what's going wrong?

It's probably related to this https://github.com/mrdoob/three.js/pull/30530

The signature of the light model functions has been changed.

File: src/nodes/functions/ShadowMaskModel.js [hunk 1]
```diff
@@ -30,18 +30,18 @@ class ShadowMaskModel extends LightingModel {
 	 *
 	 * @param {Object} input - The input data.
 	 */
-	direct( { shadowMask } ) {
+	direct( { lightNode } ) {
 
-		this.shadowNode.mulAssign( shadowMask );
+		this.shadowNode.assign( lightNode.shadowNode );
```
Comment (sunag) [inline src/nodes/functions/ShadowMaskModel.js:35]: It's necessary be `mulAssign()` to support multiples shadows.

**Comment by Mugen87** [comment]
I've found the issue. `ShadowNodeMaterial` did not set `transparent` to `true`. I've missed that `setDefaultValues()` only sets values for undefined properties.
