### PR TITLE
GLTFExporter: Fix regression in normalized attributes

### LINKED ISSUE #25019: GLTF exporter doesn't correctly handle normalized attributes
**Describe the bug**

The GLTF exporter currently exports normalized attributes as their 0-1 float value instead of their 0-255 integer values. This affects the attribute buffers themselves as well as the gltf sampler min and max fields.

This probably broke because of c6a80f9bb8411575a50990e35b9a169c8d409b41

**To Reproduce**

1. Use the gltf exporter to download a model (for example the [fiddle](https://jsfiddle.net/7abpk50j/56/))
2. Load the model file into a validator like https://gltf-viewer.donmccurdy.com/
3. Click errors on the bottom left to view the errors

***Code***

```js
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter';

function exportModel(node){
    let exporter = new GLTFExporter();
    exporter.parse(node, gltf => resolve(gltf), reject, {
  	binary: true
    });
}
```

***Live example***
https://jsfiddle.net/7abpk50j/56/
click download and then load the file into https://gltf-viewer.donmccurdy.com/

**Expected behavior**

The model including the vertex colors load correctly.

**Screenshots**
image
**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r146

### PR DESCRIPTION
**Pull request by donmccurdy**
Related:

- https://github.com/mrdoob/three.js/pull/22874 (caused regression)
- Fixes https://github.com/mrdoob/three.js/issues/25019

Some vertex attributes require KHR_mesh_quantization
for normalized values, and this is not supported yet. See:

- https://github.com/mrdoob/three.js/issues/20474

### CODE REVIEW

File: examples/jsm/exporters/GLTFExporter.js [hunk 1]
```diff
@@ -1606,12 +1618,14 @@ class GLTFWriter {
...
-								attribute.getZ( j ) - baseAttribute.getZ( j )
-							);
+							for ( let a = 0; a < attribute.itemSize; a ++ ) {
+
+								if ( a === 0 ) relativeAttribute.setX( j, attribute.getX( j ) - baseAttribute.getX( j ) );
+								if ( a === 1 ) relativeAttribute.setY( j, attribute.getY( j ) - baseAttribute.getY( j ) );
+								if ( a === 2 ) relativeAttribute.setZ( j, attribute.getZ( j ) - baseAttribute.getZ( j ) );
+								if ( a === 3 ) relativeAttribute.setW( j, attribute.getW( j ) - baseAttribute.getW( j ) );
+
+							}
```
Comment (donmccurdy) [inline examples/jsm/exporters/GLTFExporter.js:1628]: (this part is not normalization-related, just wanted to add support for vec4 types while I was here)

**Review by Mugen87 — APPROVED** [review]
