### PR TITLE
Editor: Ensure camera controls is enabled after object removal

### LINKED ISSUE #14810: Editor: Deleting node while dragging breaks viewport
1. Load any scene in the editor, e.g. the examples will do fine.
2. Use the left mouse button to select an object.
3. Left-click and hold one of the square transform gizmos that let you move the object on two axes.
4. While holding LMB, press Backspace to delete the selected node.
5. Observe that you can no longer move the viewport camera with the left and right mouse buttons.

You can restore the camera functionality by selecting another object and then unselecting it. Clearly something about the "is an object currently selected" state got broken in step 4.

Tested in Chrome stable 68.0.3440.106 and Firefox nightly 63.0a1 on Ubuntu.

##### Three.js version

- [ ] Dev
- [x] r96
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] macOS
- [x] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Temdog007**
Fixes #14810

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Temdog007/three.js/editor/DraggingIssue/editor/index.html

File: editor/js/Viewport.js [hunk 1]
```diff
@@ -413,6 +413,7 @@ var Viewport = function ( editor ) {
 
 	signals.objectRemoved.add( function ( object ) {
 
+		controls.enabled = true;
```
Comment (Mugen87) [inline editor/js/Viewport.js]: Maybe adding the issue would clarify why this line is now present. Something like
```
controls.enabled = true; // #14810
```

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!
