### PR TITLE
Line2 world units raycaster

### LINKED ISSUE #22611: Line2's raycaster threshold not compatable with LineMaterial's 'worldUnits'
**Describe the bug**

When using LineMaterial with worldUnits (worldUnits: true), and raycaster.params.Line2.threshold,
zooming in and out changes the threshold in which the line can be clicked. This is a result of the threshold being related to pixels and the linewidth being constant in the scene.

**Expected behavior**

Zooming in and out doesn't change the threshold in which the line can be clicked.

 - Three.js version: .132

### PR DESCRIPTION
**Pull request by bergden**
Fixed #22611.

**Description**

- Adding raytracing (and thresholds) to the lines_fat example
- Respecting worldUnits in ray tracing for LineSegments2

This contribution is funded by [Resonai](https://resonai.com).

### CODE REVIEW

**Review by gkjohnson — CHANGES_REQUESTED** [review]
Awesome! Thanks for the addition.

The required raycasting logic between world-unit lines and screen-space thickness lines should be sufficiently different that I think the logic would be easier to follow if there were two separate loops for each case. There's also a lot of unnecessary computation happening with world unit lines, as well:

```js
if ( worldUnits ) {

    // for loop finding world unit intersections

} else {

    // for loop finding screen space intersections

}
```

And a couple other thoughts:

- I think we should make the intersection spheres in the example a lot smaller so it's more clear where the intersection points are being reported.
- It might be best to treat the world-unit line intersections as capsules similar to the way they're being rendered? As it is it looks like the "hit" point is the point of closest approach, instead, meaning the hit point is not necessarily on the surface. This is happening with screenspace lines, too, though it might be more noticeable with world unit lines. Not sure if that has to happen in this PR, though.

Live link to the updated example:

https://raw.githack.com/bergden-resonai/three.js/line2-world-units-raycaster/examples/webgl_lines_fat.html

cc @WestLangley not sure if you have other thoughts

**Comment by WestLangley** [comment]
I would create a separate test case for raycasting with fat lines.

**Comment by WestLangley** [comment]
I would create a separate example for raycasting with fat lines.

File: examples/jsm/lines/LineSegments2.js [hunk 1]
```diff
@@ -125,7 +125,17 @@ class LineSegments2 extends Mesh {
 		const distanceToSphere = Math.max( camera.near, _sphere.distanceToPoint( ray.origin ) );
 
 		// increase the sphere bounds by the worst case line screen space width
-		const sphereMargin = getWorldSpaceHalfWidth( camera, distanceToSphere, lineWidth, resolution );
+		let sphereMargin;
+		if ( this.material.worldUnits ) {
```
[the remark this answers is not in the document]
Comment (ariel-resonai) [reply examples/jsm/lines/LineSegments2.js]: changed

File: examples/jsm/lines/LineSegments2.js [hunk 2]
```diff
@@ -248,21 +263,50 @@ class LineSegments2 extends Mesh {
 			const zPos = MathUtils.lerp( _start4.z, _end4.z, param );
 			const isInClipSpace = zPos >= - 1 && zPos <= 1;
 
-			const isInside = _ssOrigin3.distanceTo( _closestPoint ) < lineWidth * 0.5;
+			if ( ! isInClipSpace ) {
+
+				return;
+
+			}
```
[the remark this answers is not in the document]
Comment (ariel-resonai) [reply examples/jsm/lines/LineSegments2.js]: changed

File: examples/jsm/lines/LineSegments2.js [hunk 3]
```diff
@@ -248,21 +263,50 @@ class LineSegments2 extends Mesh {
...
 
-			if ( isInClipSpace && isInside ) {
+			let isInside;
+			let point, pointOnLine;
+			function getPointAndPointOnLine() {
```
[the remark this answers is not in the document]
Comment (ariel-resonai) [reply examples/jsm/lines/LineSegments2.js]: done

File: build/three.cjs [hunk 4]
```diff
@@ -19551,11 +19551,11 @@ function WebGLRenderer(parameters = {}) {
 		background.setClearAlpha.apply(background, arguments);
```
Comment (bergden-resonai) [inline build/three.cjs:19551]: Please revert build/ files

File: examples/jsm/lines/LineSegments2.js [hunk 5]
```diff
@@ -147,135 +232,212 @@ class LineSegments2 extends Mesh {
...
-			if ( _start4.z > near ) {
+				if ( ! isInClipSpace( projectionMatrix, resolution ) ) {
 
-				const deltaDist = _start4.z - _end4.z;
-				const t = ( _start4.z - near ) / deltaDist;
-				_start4.lerp( _end4, t );
+					continue;
 
-			} else if ( _end4.z > near ) {
+				}
```
Comment (gkjohnson) [inline examples/jsm/lines/LineSegments2.js:284]: For the world units lines there's no reason to ensure the lines are in clip space anymore. The only reason the camera is required otherwise is because it's necessary they are in screen space. I think the simplest approach would be to iterate over the lines without any screenspace or camera logic and checking ray / line segment distances for intersections. Then there's no requirement that the lines be visible in order to be interacted with. Let me know if that sounds good to you!

**Review by gkjohnson — COMMENTED** [review]
The example looks great, thanks!

https://raw.githack.com/bergden-resonai/three.js/line2-world-units-raycaster/examples/webgl_lines_fat_raycasting.html

I've added a couple comments on the complexity of the loops and how to address. Can you explain the "isLoopingInside" variable? It doesn't seem like it should be necessary.

File: examples/jsm/lines/LineSegments2.js (hunk 5 above)
Comment (bergden-resonai) [reply examples/jsm/lines/LineSegments2.js:284]: I'm not sure I understand - let's say we have a very long line that's going from behind the camera near to inside the camera frustum
We don't want the parts of the lines before the camera near to be considered, but if we only keep the intersections and try to calculate it at the end we will be missing some information - no?

I agree about the clipSpace, remove the `if` block for that
Let me know if you meant to remove the trimSegment and isBehindCameraNear as well

Comment (bergden-resonai) [reply examples/jsm/lines/LineSegments2.js:284]: Also, out of curiosity - why don't we need to consider far?
The raytracer removes points that are behind the far plane - but sometimes a closer part of the line might fall within the threshold so we would miss intersections there, am I missing something?

**Comment by bergden-resonai** [comment]
Made a lot of changes, hopefully without new bugs:
1. Split raycasting for world units and non world units (how do we want to call this?)
2. Removed dashed/gl.line from the example, added visualizations for the thresholds to help debug and explain it, made it easy to switch from segments to lines, the colors of the points change to increase contrast with the intersected segment
3. Minor code readability improvements
4. Remove isLoopingInside which to best of my knowledge (I need to sync with @ariel-resonai on that) tried to solve the case where if segment1 and segment2 were overlapping in screen space after factoring the threshold, but the cursor was obviously over segment1 the intersection returned would prefer segment2 since it's closer (where Ariel wanted to minimize the distance between the point and pointOnLine)

With inLoopingInside:
https://user-images.githubusercontent.com/37291459/154805071-8f47bc40-f0ca-4803-b891-d0059387ad67.mov

Without:
https://user-images.githubusercontent.com/37291459/154805089-50b27b6e-c3a9-40cc-8da2-2e8258894e89.mov

Open questions:
A. I'm not sure why there's a discrepancy between the threshold visualization and the intersections found in non-worldUnits mode
image
B. [This](https://github.com/mrdoob/three.js/pull/23358#discussion_r810461235)

File: examples/jsm/lines/LineSegments2.js (hunk 5 above)
Comment (gkjohnson) [reply examples/jsm/lines/LineSegments2.js]: There's no reason that world lines have to be handled in screen space. The only reason the screen space lines used the camera is because it's required based on how they're displayed. Picking effectively happens in 2D and given the way they're rendering proper picking is effectively undefined outside of the camera clip space. It's definitely a special case for the screen space line variant.

This isn't the case with the world unit lines, though. They're basically rendered as capsules. Meshes, for example, don't have special handling when they're behind the camera and don't consider the camera at all. This enables rays that are not derived from a camera and mouse coordinate to be used for raycasting (ie vr controller rays outside of view or rays for game mechanics outside of view)

The built in [GL line raycasting](https://github.com/mrdoob/three.js/blob/1c553914ace73127cc67660597806b2c7c013548/src/objects/Line.js#L160-L189) doesn't use a camera and includes support for a threshold which effectively means they're treated as capsules. I think that's more along the lines of what I imagine for world unit raycasting.

**Comment by gkjohnson** [comment]
> Split raycasting for world units and non world units (how do we want to call this?)

I think world units and screen space is good.

> Remove isLoopingInside which to best of my knowledge (I need to sync with @ariel-resonai on that) tried to solve the case where if segment1 and segment2 were overlapping in screen space after factoring the threshold, but the cursor was obviously over segment1 the intersection returned would prefer segment2 since it's closer (where Ariel wanted to minimize the distance between the point and pointOnLine)

I think if we want to improve screen space line behavior it should be done in a separate PR and this should focus on just adding world space line raycasting. The number of changes has made it harder to follow exactly what's been changed so far. The screen space line logic was a fairly complicated piece of logic to add so I'm less keen on making any changers to it here.

That aside there are ambiguities / redundancies at points where segments overlap which causes the popping but I think that's just the nature of this kind of raycasting. I believe it happens with the GL line variant, as well.

> A. I'm not sure why there's a discrepancy between the threshold visualization and the intersections found in non-worldUnits mode

Can we confirm that this happens with the original code on master? I just want to make sure it's not a newly introduced issue. If it's on master I think you need to worry about it here and it can be addressed in a different PR.

File: examples/jsm/lines/LineSegments2.js (hunk 5 above)
Comment (gkjohnson) [reply examples/jsm/lines/LineSegments2.js]: That would mean the "computeStartEnd", "trimSegment", and "isInClipSpace" functions do not need to be shared and don't need to be pulled out into separate functions. I just want to keep the changes to the original logic minimal.

Comment (bergden-resonai) [reply examples/jsm/lines/LineSegments2.js]: Oh I forgot to update - I changed the main camera's near to `10` to test behavior and luckily committed it by accident so it can still be tested:


https://user-images.githubusercontent.com/37291459/154812175-afe783da-5fa0-49ec-813a-5c5e8ca22ac8.mov


The lines are rendered truncated by the near plane and the intersection still happens (denoted by the cursor and the little canvas on the bottom left which still has near set to `1` - which I'm pretty sure is a bug in my last commits
I just want to confirm - this is the desired behavior? if so I'll remove the calls to trimSegment/isBehindCamera instead of debugging

**Comment by bergden-resonai** [comment]
> > Split raycasting for world units and non world units (how do we want to call this?)
> 
> I think world units and screen space is good.
> 
> > Remove isLoopingInside which to best of my knowledge (I need to sync with @ariel-resonai on that) tried to solve the case where if segment1 and segment2 were overlapping in screen space after factoring the threshold, but the cursor was obviously over segment1 the intersection returned would prefer segment2 since it's closer (where Ariel wanted to minimize the distance between the point and pointOnLine)
> 
> I think if we want to improve screen space line behavior it should be done in a separate PR and this should focus on just adding world space line raycasting. The number of changes has made it harder to follow exactly what's been changed so far. The screen space line logic was a fairly complicated piece of logic to add so I'm less keen on making any changers to it here.
> 
> That aside there are ambiguities / redundancies at points where segments overlap which causes the popping but I think that's just the nature of this kind of raycasting. I believe it happens with the GL line variant, as well.
> 
> > A. I'm not sure why there's a discrepancy between the threshold visualization and the intersections found in non-worldUnits mode
> 
> Can we confirm that this happens with the original code on master? I just want to make sure it's not a newly introduced issue. If it's on master I think you need to worry about it here and it can be addressed in a different PR.

I took the current example and used it with the dev version of LineSegments2.js and saw the same behavior - I'll open an issue after this PR
Ack on rest of comments here

File: examples/jsm/lines/LineSegments2.js (hunk 5 above)
Comment (gkjohnson) [reply examples/jsm/lines/LineSegments2.js]: I believe this is a function of the math involved. The lines are rendered as capsules and have thickness -- you're not seeing back faces of the capsule but technically the near plane (and therefore the ray start) is within the capsule and registers as a "hit" within the given threshold.

**Comment by bergden-resonai** [comment]
Hopefully this time everything's sorted out

I couldn't make the diff work for the current way the code is organized, but I reverted the raycasting function to mrdoob/dev version. I kept the split in the functions because I the if/else was getting too long (thus the alleged big diff you see in the PR). There are minor changes in variable/global variable names, and the functionality regarding sphere/box is common so I kept it outside the type-specific functions

https://user-images.githubusercontent.com/37291459/154813566-5641f26b-a776-4f4a-aa5b-f06728376f05.mov

File: examples/jsm/lines/LineSegments2.js [hunk 6]
```diff
@@ -147,135 +232,212 @@ class LineSegments2 extends Mesh {
...
-				const pointOnLine = new Vector3();
-				const point = new Vector3();
+				}
 
-				ray.distanceSqToSegment( _line.start, _line.end, point, pointOnLine );
+				const distTmp = _ssOrigin3.distanceTo( _closestPoint );
+				const isInside = distTmp < lineWidth * 0.5;
 
-				intersects.push( {
+				if ( ! isInside && isLoopingInside ) {
```
[the remark this answers is not in the document]
Comment (bergden-resonai) [reply examples/jsm/lines/LineSegments2.js]: Reverted to dev's version - https://github.com/mrdoob/three.js/pull/23358#issuecomment-1046076279

**Comment by WestLangley** [comment]
The inset in the [original example](https://github.com/mrdoob/three.js/pull/11349#issue-229180510) was added to study the impact of canvas size and the user-set resolution parameter.

I would not include the inset viewport in the raycasting example -- unless there is a compelling reason to do so.

**Comment by bergden-resonai** [comment]
> The inset in the [original example](https://github.com/mrdoob/three.js/pull/11349#issue-229180510) was added to study the impact of canvas size and the user-set resolution parameter.
> 
> I would not include the inset viewport in the raycasting example -- unless there is a compelling reason to do so.

This example also showcases how the resolution affects the rendered lines relative size
And also this really helped me catch a few bugs when the cameras didn't match in their position/near/far (I reverted these changes since it's easy but reviving the smaller canvas is harder if I remove it)
I don't know if this is compelling enough :)

**Comment by WestLangley** [comment]
>I don't know if this is compelling enough :)

@bergden-resonai Thank you for your contribution. I'll defer to whatever @gkjohnson recommends. :-)

**Review by gkjohnson — APPROVED** [review]
Looks great! Thanks again.

> I'll defer to whatever @gkjohnson recommends. :-)

I don't have any strong feelings on this. It can always be adjusted later.

I don't

**Comment by mrdoob** [comment]
Thanks!
