### PR TITLE
WebGPURenderer: fix rendering to depth textures with multiple color attachments (MRT - WGSL)

### LINKED ISSUE #28519: It seems like there is an issue with outputNode in connection with depthNode
### Description

I use the vertexNode, depthNode, colorNode. I use the depthNode because I work with the logarithmicDepthBuffer and therefore have to create the depth value myself because of coordinate transformations in the vertex shader. In the codePen example, I left out coordinate transformations in the shader for the sake of simplicity. 
So I create vDepth in the vertex shader and then use a depth shader to operate the depthNode. 
Then finally I use the colorNode with a very simple color shader. This all works wonderfully. And this also works with my much more complex software in which the logarithmic influence really comes into play with coordinate transformation everything exactly as it should. That's really nice. 
Now I would like to replace the colorNode with the outputNode because I need more than one fragmentShader. But this no longer works with the outputNode. Without logarithmicDepthBuffer and commented out depthNode, the codePen also works with the outputNode. As soon as you include the depthNode, this also no longer works.
This seems to be something between the depthNode and the outputNode.

In the codePen example you can choose between colorNode 0 and outputNode 1 in line 94.

I've been thinking for the last few days if I'm missing something, but I can't think of anything. Since there is still the possibility that I have to take something extra into account that I don't see, I can't say with certainty that there really is a bug here.
Because there is no one in the forum who has yet dealt with these deep functionalities in WebGPU and can evaluate whether it is an issue or something is missing, I am including it here with a note of possible user errors on my part, as I cannot rule it out.

### Reproduction steps

1. create vertexShader, depthShader, fragmentShader like I did in the codePen or simply use my codePen directly instead. That's much more comfortable
2. assign the shaders to the vertexNode, depthNode, colorNode
3. replace the colorNode with the outputNode and you will get a withe screen. If you comment out the depthNode then it works with the outputNode

When testing with the logarithmicDepthBuffer you have a white screen even without the depthNode, but this is probably due to the fact that the depthNode is absolutely necessary with the logarithmicDepthBuffer. In any case, with the colorNode, the depthNode and the logarithmicDepthBuffer work perfectly.

Therefore I suspect an issue between the combination depthNode and outputNode

### Code

```js
import * as THREE from "https://esm.sh/three";
import {MeshBasicNodeMaterial, wgslFn, vec4, texture, attribute, outputStruct, varyingProperty, cameraProjectionMatrix, modelWorldMatrix, cameraViewMatrix } from "https://esm.sh/three/nodes";
import {OrbitControls} from "https://esm.sh/three/addons/controls/OrbitControls.js";
import Stats from "https://esm.sh/three/addons/libs/stats.module.js";
import WebGPURenderer from "https://esm.sh/three/addons/renderers/webgpu/WebGPURenderer.js";


const renderer = new WebGPURenderer({
  antialias: true,
  logarithmicDepthBuffer: true,
  forceWebGL: false, 
});
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.setPixelRatio( window.devicePixelRatio );
renderer.setSize( window.innerWidth,window.innerHeight );
renderer.setClearColor( 0x000000 );
document.body.appendChild( renderer.domElement );


const camera = new THREE.PerspectiveCamera( 50.0, window.innerWidth/window.innerHeight, 1e-6, 1e10 );
const scene = new THREE.Scene();
scene.background = new THREE.Color( 0x00001f );

camera.position.set( 4, 4, 4 );

const controls = new OrbitControls( camera, renderer.domElement );
//-------------------------------------------------------------------

window.addEventListener( "resize", onWindowResize, false );


init();
await render();


function init() {

  const vDepth = varyingProperty( "float", "vDepth" );
  
  const vertexShaderParams = {
    projectionMatrix: cameraProjectionMatrix,
    modelWorldMatrix: modelWorldMatrix,
    cameraViewMatrix: cameraViewMatrix,
    position: attribute( "position" ) 
  }
  
  const depthShaderParams = {
    vDepth: vDepth,
    logDepthBufFC: 2 / ( Math.log( camera.far + 1 ) / Math.LN2 )
  }
  
  const vertexShader = wgslFn(`
    fn main_vertex(
      projectionMatrix: mat4x4<f32>,
      modelWorldMatrix: mat4x4<f32>,
      cameraViewMatrix: mat4x4<f32>,    
      position: vec3<f32>
    ) -> vec4<f32> {
    
      var outPosition = projectionMatrix * modelWorldMatrix * cameraViewMatrix * vec4<f32>(position, 1.0);
    
      varyings.vDepth = outPosition.w;
    
      return outPosition;
    }
  `, [vDepth] );
  
  const depthShader = wgslFn(`
    fn main_depth(
      vDepth: f32,
      logDepthBufFC: f32
    ) -> vec4<f32> {
      
      var fragDepth = log2(vDepth) * logDepthBufFC * 0.5;
      return vec4<f32>(fragDepth, fragDepth, fragDepth, 1.0);
    }
  `);  
  
  const fragmentShader1 = wgslFn(`
    fn main_fragment_1(
    ) -> vec4<f32> {
      return vec4<f32>(1, 0, 0, 1);
    }
  `);

  const fragmentShader2 = wgslFn(`
    fn main_fragment_2(
    ) -> vec4<f32> {
      return vec4<f32>(0, 1, 0, 1);
    }
  `);

  //switch between colorNode and outputNode
  const useOutputNode = 0;
  
  const material = new MeshBasicNodeMaterial();
  material.vertexNode = vertexShader( vertexShaderParams );
  material.depthNode = depthShader( depthShaderParams );
  if( useOutputNode ) {
    material.outputNode = outputStruct(
      fragmentShader1(),
      fragmentShader2()
    );
  }
  else {
    material.colorNode = fragmentShader1();
  }
  
  const geometry = new THREE.BoxGeometry( 1, 1, 1 );
  const box = new THREE.Mesh( geometry, material );
  scene.add( box );
  
}

async function render() {
  requestAnimationFrame( render );
  await renderer.renderAsync( scene, camera ); 
}

function onWindowResize() {
  camera.aspect = window.innerWidth / window.innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize( window.innerWidth, window.innerHeight );
}
```

### Live example

https://codepen.io/Spiri0/pen/ExJdzpL

### Screenshots

_No response_

### Version

r164

### Device

Desktop, Mobile

### Browser

Chrome, Firefox

### OS

Windows, Linux, Android

### PR DESCRIPTION
**Pull request by aardgoose**
Related issue: Closes #28519 

Rendering using outputStruct() to multiple render targets doesn't handle depth with WGSL because @builtin('frag_depth') not included in the output struct definition. (GLSL unaffected).

Include builtins as required and simplify, avoiding the var in main fragment shader function and aligning with standard code with the output named 'output'.

### CODE REVIEW

File: examples/jsm/renderers/webgl/nodes/GLSLNodeBuilder.js [hunk 1]
```diff
@@ -51,12 +51,16 @@ class GLSLNodeBuilder extends NodeBuilder {
 
 	getPropertyName( node, shaderStage ) {
 
-		if ( node.isOutputStructVar ) return '';
-
 		return super.getPropertyName( node, shaderStage );
 
 	}
 
+	getOutputName() {
```
Comment (sunag) [inline examples/jsm/renderers/webgl/nodes/GLSLNodeBuilder.js:58]: What do you think `getOutputStructName()`?

**Comment by Spiri0** [comment]
I just tested the changes locally in my app. That works, with this changes the depthNode works in conjunction with the outputNode like with the colorNode. 
Then my ticket #28519 can also be closed as solved.

File: examples/jsm/renderers/webgl/nodes/GLSLNodeBuilder.js (hunk 1 above)
Comment (aardgoose) [reply examples/jsm/renderers/webgl/nodes/GLSLNodeBuilder.js:58]: sounds good, I'll change it
