### PR TITLE
Texture: Add setValues.

### LINKED ISSUE #28100: WebGLArrayRenderTarget: Constructor texture options are not respected
### Description

When passing texture options into the `WebGLArrayRenderTarget` constructor they are not retained on the `target.texture` objects as expected.

### Reproduction steps

1. Create a new WebGLArrayRenderTarget with custom texture options
2. See that options are not retained

### Code

```js
target = new THREE.WebGLArrayRenderTarget( 1, 1, 1, { wrapS: THREE.RepeatWrapping } );
target.texture.wrapS === THREE.RepeatWrapping;
```

### Live example

Run above code in [three.js docs console](https://threejs.org/docs/)

### Screenshots

_No response_

### Version

163

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Fixed #28100

**Description**

Implements `setValues` in `Texture`. Since every render target class would need to filter options into texture parameters, I implement an internal `_setTextureOptions` method. It is recommended to use public API to enjoy validation.

### CODE REVIEW

File: src/core/RenderTarget.js [hunk 1]
```diff
@@ -149,6 +145,8 @@ class RenderTarget extends EventDispatcher {
 
 		}
 
+		this._setTextureOptions( options );
```
Comment (Mugen87) [inline src/core/RenderTarget.js:148]: I think we also must update `RenderTarget3D` since its texture reference is overwritten with a new instance of `Data3DTexture`.

File: src/core/RenderTarget.js [hunk 2]
```diff
@@ -204,6 +202,37 @@ class RenderTarget extends EventDispatcher {
...
+		const values = {
+			minFilter: LinearFilter,
+			generateMipmaps: false,
+			flipY: false,
+			internalFormat: null
+		};
+
+		if ( options.mapping !== undefined ) values.mapping = options.mapping;
+		if ( options.wrapS !== undefined ) values.wrapS = options.wrapS;
+		if ( options.wrapT !== undefined ) values.wrapT = options.wrapT;
```
Comment (Mugen87) [inline src/core/RenderTarget.js:216]: For all render target types relying on 3D or array textures, we must honor the `wrapR`.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
@gkjohnson Does the PR look good to you as well?

**Review by gkjohnson — APPROVED** [review]
