### PR TITLE
Renderer: Use output color space conversion only when rendering to screen.

### LINKED ISSUE #28826: WebGPURenderer: `CubeRenderTarget.fromEquirectangularTexture()` does not work with sRGB input.
### Description

`WebGPURenderer` should be able to automatically convert equirectangular texture to the cube map format. I've tried to implement auto-conversion for `envMap` in `BasicEnvironmentNode` but then encountered an issue.

`CubeRenderTarget.fromEquirectangularTexture()` (which internally uses `CubeCamera.update()`) only works if the input is `linear-srgb`. If it is `srgb` which is more or less always true for non HDR textures, the rendering fails with the following WebGPU warnings:
```
Texture view array layer range (baseArrayLayer: 1, arrayLayerCount: 1) exceeds the texture's array layer count (1).
 - While validating [TextureViewDescriptor] against [Texture (unlabeled 2734x1288 px, TextureFormat::RGBA16Float)].
 - While calling [Texture (unlabeled 2734x1288 px, TextureFormat::RGBA16Float)].CreateView([TextureViewDescriptor]).

_display/:1 [Invalid TextureView] is invalid.
 - While validating colorAttachments[0].
 - While encoding [CommandEncoder "renderContext_2"].BeginRenderPass([null]).

_display/:1 [Invalid CommandBuffer from CommandEncoder "renderContext_2"] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer from CommandEncoder "renderContext_2"]])
```
The renderer logs this for the `baseArrayLayer` 1-5 which means for the cube sides 1-5. The first one seems to render as expected.

### Reproduction steps

1. Go to https://jsfiddle.net/hvoju7bw/1/.
2. Check browser console.

### Code

```js
const renderer = new THREE.WebGPURenderer();
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(window.innerWidth, window.innerHeight);
document.body.appendChild(renderer.domElement);

await renderer.init();

const loader = new THREE.TextureLoader();

const texture = await loader.loadAsync('https://threejs.org/examples/textures/2294472375_24a3b8ef46_o.jpg');
texture.mapping = THREE.EquirectangularReflectionMapping;
texture.colorSpace = THREE.SRGBColorSpace;

const renderTarget = new CubeRenderTarget(texture.image.height);
renderTarget.fromEquirectangularTexture(renderer, texture);
```

### Live example

https://jsfiddle.net/hLcnrsfb/

### Screenshots

_No response_

### Version

r167dev

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #28826.

**Description**

This PR ensures output tone mapping and color space conversion follow the same policy. They are only used when rendering to screen.

### CODE REVIEW

**Comment by WestLangley** [comment]
Can you please summarize the policy for both `WebGLRenderer` and `WebGPURenderer`?

Which renderer properties only apply when rendering to the screen?

**Comment by donmccurdy** [comment]
At some point, I would be interested in making this configurable. Users may need to do these transforms when drawing to a render target, without the cost of an additional pass. Would something like `renderTarget.needsOutputTransform = true` make sense?

File: src/renderers/common/Renderer.js [hunk 1]
```diff
@@ -457,7 +457,7 @@ class Renderer {
 		const { currentColorSpace } = this;
```
Comment (sunag) [inline src/renderers/common/Renderer.js:457]: `currentColorSpace` already does that, I was thinking of renaming it to `targetColorSpace`.

**Comment by Mugen87** [comment]
When a render target is marked as `RGBA8UnormSRGB` (WebGPU) or `SRGB8_ALPHA8` (WebGL 2), the framebuffer hold sRGB values. There is no need for a manual color space conversion. `WebGLRendeder` does honor that, `WebGPURenderer` don't.

If you want to force a color space when rendering into a render target, it's best to introduce a new property and don't use `renderTarget.texture.colorSpace` for that.

**Comment by Mugen87** [comment]
When a render target is marked as `RGBA8UnormSRGB` (WebGPU) or `SRGB8_ALPHA8` (WebGL 2), the framebuffer hold sRGB values. There is no need for a manual color space conversion. `WebGLRendeder` does honor that, `WebGPURenderer` don't.

If you want to force a color space conversion when rendering into a render target, it's best to introduce a new property and don't use `renderTarget.texture.colorSpace` for that. Like with normal textures, `colorSpace` should just indicate what the color space of the texels is. It is not a save indicator for triggering a conversion since that depends on the render targets format/type.

**Comment by donmccurdy** [comment]
Yes, I think the current behavior for color space conversion is probably enough, no need for a property to force that. But in either case, we need tone mapping to happen before the color space conversion, and that's hard-coded off for render targets.

**Comment by Mugen87** [comment]
I'm afraid this could have side effects. Think of an app that configures tone mapping on renderer level and now loads an sRGB equirectangular texture. The renderer should automatically convert it to the cube map format. If the cube map render target is marked as RGBA8 + sRGB, there should be no tone mapping in place since the source is RGBA8 + sRGB. 

I don' think it's possible to figure out an automatism that selectively applies tone mapping whenever rendering to `SRGB8_ALPHA8` or `RGBA8UnormSRGB` .

**Comment by donmccurdy** [comment]
True, and I agree that we can't and shouldn't try to automatically handle every case. I guess I was thinking of that suggestion as making it "less automatic" than it is now, automatically disabling tone mapping only for float render targets, rather than for all render targets.

The caller in the cube map scenario would need to do this...

https://github.com/mrdoob/three.js/blob/ffef51075d125234079aaa494f9da1066f3d3e77/src/nodes/lighting/AnalyticLightNode.js#L224-L232

... which I'm inclined to say should be best practice anyway, rather than assuming that render targets ignore the tone mapping setting.

But without that, I suppose an explicit option would be required.

**Comment by Mugen87** [comment]
Um, I'm okay with revisiting this topic and maybe define a new policy when tone mapping and color space conversion is applied for render targets. But this is something I would discuss in a separate issue. Would that be okay for everyone?

This PR is just intended to make `WebGPURenderer` honor the _existing_ policy. And that means no color space conversion happens in the renderer with an active render target. The output color space conversion is done by the renderer when rendering to screen or by `OutputPass`/`renderOutput()` when doing FX.

**Comment by donmccurdy** [comment]
Yes, sorry for side-tracking – that's fine with me, I'll follow up elsewhere, and thank you!

**Comment by WestLangley** [comment]
>This PR is just intended to make WebGPURenderer honor the existing policy.

@Mugen87 I do not think there is an existing policy that is being adhered to consistently by either the code or the docs. But I would like to check.

If you would answer my question above, I would be grateful, and I will continue the discussion in another thread if needed.

**Comment by Mugen87** [comment]
> If you would answer my question above, I would be grateful, and I will continue the discussion in another thread if needed.

I thought I did in https://github.com/mrdoob/three.js/pull/28909#issuecomment-2237259221.

**Comment by WestLangley** [comment]
OK, I'll state what I think your policy is...

WebGLRenderer

1. `renderer.outputColorSpace` is honored only when rendering to the default drawing buffer.

2. According to the docs, when rendering to a render target, `renderTarget.texture.colorSpace` is honored instead. I am not sure if that is what you intend -- or even if it is true.

3. `renderer.toneMapping` is honored only when rendering to the default drawing buffer.

4. `renderer.toneMapping` is ignored when rendering to a render target -- although the docs do not explicitly make that clear.


WebGPURenderer

I assume you want the behavior to be the same as it is for WebGLRender.

//

Classes such as `Reflector` render to a render target and do not adhere to these policies. Correct?

**Comment by Mugen87** [comment]
> According to the docs, when rendering to a render target, renderTarget.texture.colorSpace is honored instead. I am not sure if that is what you intend -- or even if it is true.

This statement in the docs is wrong. When a render target is set, the output color space is _always_ `LinearSRGBColorSpace` (except for XR ). Respective line in `WebGLPrograms`.

https://github.com/mrdoob/three.js/blob/460efde132f8d8f1917376a629ac8f857990e2bb/src/renderers/webgl/WebGLPrograms.js#L201

**Comment by donmccurdy** [comment]
> When a render target is set, the output color space is _always_ `LinearSRGBColorSpace`

Minor: I think we'd like this to be `ColorManagement.workingColorSpace`, rather than hard-coded to `LinearSRGBColorSpace`, but of course they're the same in 99.9% of cases today.

> Classes such as Reflector render to a render target and do not adhere to these policies. Correct?

I think it's OK for particular classes to make different decisions than the renderer defaults ... but whether classes like Reflector are making the decisions we'd prefer, currently, I'm not sure.

**Comment by Mugen87** [comment]
> Classes such as Reflector render to a render target and do not adhere to these policies. Correct?

The internal render target of reflector is linear-srgb (so no color space conversion happens). However, the material that renders the reflective texture to screen inline color space conversion via the `colorspace_fragment` chunk like all other built-in materials.

In `WebGPURenderer` there is no inline color space conversion anymore since this happens as a separate pass.
