### PR TITLE
WebGLRenderer: Track camera per render state.

### LINKED ISSUE #28111: Incorrect clipping with global clipping planes and nested render calls (e.g. Reflector)
### Description

Global [clipping planes](https://threejs.org/docs/index.html#api/en/renderers/WebGLRenderer.clippingPlanes) can be defined on the renderer. While these are specified in World Space, they are converted to camera space in the renderer. Nested render calls can cause these to be recomputed for a different camera, and their original state is never restored. This results in the remainder of the render call using incorrect clipping planes.

### Reproduction steps

1. Setup global clipping planes on the renderer
2. Add an object to the scene the results in a nested render call (e.g. Reflector)
3. Render the scene and observe the clipping behaving inconsistently 

### Code

```js
// clipping plane
renderer.clippingPlanes = [ new THREE.Plane( new THREE.Vector3( 1, 0, 0 ), 0 ) ];

// add reflector
const reflector = new Reflector( ... );
scene.add( reflector );
```

### Live example

* https://jsfiddle.net/L0v4pntz/

Moving the camera around shows that the clipping isn't consistent between the sphere and its reflection. This happens because the main sphere is rendered _after_ the Reflector (and thus after the nested render call that messes up the global clipping plane uniforms).

Once the Reflector is out of view it won't be rendered, and the sphere is consistently clipped along the defined clipping plane.

### Screenshots

image
Note how the sphere and its reflection have different parts clipped.

### Version

r164

### Device

Desktop

### Browser

Chrome, Firefox

### OS

Linux

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #28111.

**Description**

This PR makes sure the camera is tracked in the render state so it's possible to perform camera related restore operation after a nested render call.

Clipping uniforms are now correctly restores and also the viewport configuration can be restored in the renderer now. This was previously done in the component which triggers the nested render call.

### CODE REVIEW

File: src/renderers/WebGLRenderer.js [hunk 1]
```diff
@@ -1242,6 +1242,20 @@ class WebGLRenderer {
 
 				currentRenderState = renderStateStack[ renderStateStack.length - 1 ];
 
+				// restore clipping uniforms and viewport
+
+				const renderStateCamera = currentRenderState.state.camera;
+
+				if ( _clippingEnabled === true ) clipping.setGlobalState( _this.clippingPlanes, renderStateCamera );
+
+				const viewport = renderStateCamera.viewport;
```
Comment (mrxz) [inline src/renderers/WebGLRenderer.js:1251]: The `.viewport` is present on the (sub)cameras of the XR camera, whereas the render state stores the XR camera itself. So I don't think this now actually restores the viewport properly.

I was thinking that it might make the whole viewport handling easier if the XR viewports are associated with the WebXR render target. That way switching back and forth between render targets should automatically restore the right viewport. So instead of passing a `viewport` into `renderScene` the viewport property of the WebXR render target would be updated for each eye.

Comment (Mugen87) [reply src/renderers/WebGLRenderer.js]: Good point! I leave the viewport related changes out for now.

Let's try your approach with a different PR.
