### PR TITLE
TSL: Check for `undefined` in `uniform()`.

### LINKED ISSUE #32182: Bug: TSL `uniform(float(x))` crashes lil-gui control when x is exact 0
### Description

(please see code section)

### Reproduction steps

-

### Code

```js
import { uniform, float } from 'three/tsl'
import { GUI } from 'three/addons/libs/lil-gui.module.min.js'

const u1 = uniform(0)
const u2 = uniform(float(0))
const u3 = uniform(float(0.0001))

const gui = new GUI()
gui.add(u1, 'value').name('u1') // ok
gui.add(u2, 'value').name('u2') // <-- crash
gui.add(u3, 'value').name('u3') // ok
```

### Live example

demo: https://jsfiddle.net/qk0p6ugj/

### Screenshots

_No response_

### Version

r181

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #32182.

**Description**

`uniform()` currently uses this check `( value.node && value.node.value )`. This check does not properly handle the case when `value.node.value` is `0` (a valid value). The PR changes the check by testing for `undefined`.

@sunag Do we also have to honor `null`?

### CODE REVIEW

File: src/nodes/core/UniformNode.js [hunk 1]
```diff
@@ -236,7 +236,7 @@ export const uniform = ( value, type ) => {
 	}
 
 	// @TODO: get ConstNode from .traverse() in the future
```
Comment (sunag) [inline src/nodes/core/UniformNode.js]: I added the TODO to the traverse when we didn't yet have the `node.traverse()` function; I think we could use it now. 

Instead of detecting the value, we would be detecting if an `isConstNode` Node exists in the stream tree.

Comment (Mugen87) [reply src/nodes/core/UniformNode.js]: I'll give it a try!
