### PR TITLE
GLTFExporter: Fix handling of shared buffer attributes with morph data.

### LINKED ISSUE #24074: GLTFExporter uses wrong cache value `baseAttribute` instead of `relativeAttribute`
**Describe the bug**

We have a model that is multiple cubes with the same POSITION attributes. One of the cubes has a morph target. When we export this model the mesh with the morph target came out correct, but the other meshes had their position data messed up.

I did some digging and realized that the POSITION attribute for the cubes w/o morph targets were using the attribute for the morph target. We're not creating/editing attributes at all, and the scene looked fine before export, so I started digging into the GLTFExporter code. I tracked the issue down to this code:

```
// Clones attribute not to override
const relativeAttribute = attribute.clone();

if ( ! geometry.morphTargetsRelative ) {

for ( let j = 0, jl = attribute.count; j < jl; j ++ ) {

	relativeAttribute.setXYZ(
		j,
		attribute.getX( j ) - baseAttribute.getX( j ),
		attribute.getY( j ) - baseAttribute.getY( j ),
		attribute.getZ( j ) - baseAttribute.getZ( j )
	);

}

}

target[ gltfAttributeName ] = this.processAccessor( relativeAttribute, geometry );
cache.attributes.set( this.getUID( baseAttribute ), target[ gltfAttributeName ] );
```

The last line is the culprit, but I included more for context. Basically the `baseAttribute` is used to update `cache.attributes` instead of `relativeAttribute` which caused subsequent meshes to processed incorrectly as the would use the morph attribute instead of the position one. 

**To Reproduce**

1. Load the following model using the GLTFLoader 
[model(13).zip](https://github.com/mrdoob/three.js/files/8703833/model.13.zip)

2. Export the model using GLTFExporter.parse using the following options:
```js
{
  binary: true,
}
```
3. If you inspect the exported model you should see that one of the cubes (the one with the morph target) is correct, while the others are using the accessor id for the morph target data.

**Expected behavior**

The exporter should cache the morph target attribute using `relativeAttribute` instead of `baseAttribute`.

**Platform:**

 - Device: [Desktop, Mobile]
 - OS: [Windows, MacOS, Linux, Android, iOS]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev, r140]

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #24074.

**Description**

Ensures `GLTFExporter` can correctly process geometries which share buffer attributes (like `position`) but with different morph target setups.

### CODE REVIEW

File: examples/jsm/exporters/GLTFExporter.js [hunk 1]
```diff
@@ -1514,9 +1527,9 @@ class GLTFWriter {
 
 			if ( ! validVertexAttributes.test( attributeName ) ) attributeName = '_' + attributeName;
 
-			if ( cache.attributes.has( this.getUID( attribute ) ) ) {
+			if ( cache.attributes.has( this.getUID( attribute, morphAttributes[ attributeName ] ) ) ) {
```
Comment (donmccurdy) [inline examples/jsm/exporters/GLTFExporter.js:1530]: Could we just say `this.getUID( attribute, false )` here? If there were a morph target version, we wouldn't want its ID here, correct? Also applies to the next two 'getUID' calls.

File: examples/jsm/exporters/GLTFExporter.js [hunk 2]
```diff
@@ -1600,9 +1613,9 @@ class GLTFWriter {
 
 					const baseAttribute = geometry.attributes[ attributeName ];
 
-					if ( cache.attributes.has( this.getUID( attribute ) ) ) {
+					if ( cache.attributes.has( this.getUID( attribute, morphAttributes[ attributeName ] ) ) ) {
```
Comment (donmccurdy) [inline examples/jsm/exporters/GLTFExporter.js:1616]: Could we just say `getUID( attribute, true )` here, and below?

File: examples/jsm/exporters/GLTFExporter.js [hunk 3]
```diff
@@ -602,16 +602,27 @@ class GLTFWriter {
...
+			uids.set( false, this.uid ++ );
+
+			this.uids.set( attribute, uids );
+
+		}
+
+		const uids = this.uids.get( attribute );
+		const hasMorphTargets = Array.isArray( morphTargets ) && morphTargets.length > 0;
+
+		return uids.get( hasMorphTargets );
```
Comment (donmccurdy) [inline examples/jsm/exporters/GLTFExporter.js:625]: I'm having a difficult time understanding this method – a few questions:

- Why `uids.set( true, this.uid ++ );` and `uids.set( false, this.uid ++ );`, What do those lines do?
- Since we don't seem to use the morph target object for anything more than a boolean check, could we replace it with a boolean? Possibly `isRelativeCopy` or something like that. 

Note that if the attribute were used both for the base geometry and a morph target, and the morph target were _relative_, we wouldn't need to copy it or do any of this. That's very unlikely (how could the same attribute be used for both relative and absolute data?) and so I'm not really worried about duplicate data in that case, but just to say that it's not the fact that the attribute "hasMorphTargets" that we actually care about here, it's the fact that we cloned the original and rewrote it as relative deltas.

Now that three.js supports relative morph targets, we could even put this in an external utility function.

**Review by donmccurdy — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!
