### PR TITLE
ExtrudeGeometry: Fix regression introduced by #30750.

### LINKED ISSUE #30819: ExtrudeGeometry: Extruded faces are missing
### Description

The extruded front and back faces are missing when `bevelEnabled` is `false`.

git bisect points to #30750.

/ping @mlasala45 Can you please have a look?

### Reproduction steps

1. https://threejs.org/examples/webgl_geometry_text.html // click change bevel button

2. https://threejs.org/examples/webgl_geometry_extrude_shapes.html // inspect the missing end-caps

3. https://threejs.org/examples/webgl_geometry_shapes.html // hack the code and set `bevelEnabled: false`

### Code

n/a

### Live example

https://threejs.org/examples/webgl_geometry_text.html // click change bevel button

https://threejs.org/examples/webgl_geometry_extrude_shapes.html // inspect the missing end-caps

https://threejs.org/examples/webgl_geometry_shapes.html // hack the code and set `bevelEnabled: false`

### Screenshots

_No response_

### Version

r175

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by mlasala45**
Fixed #30819

**Description**

Changes introduced by #30750 resulted in the inputs to ShapeUtils.triangulateGeometry not being initialized when bevelSegments == 0 (which happens when bevelEnabled == false), causing triangulation to fail. This PR adds code to manually populate those lists if they are empty before triangulation, fixing the issue. See related issue for examples.

### CODE REVIEW

**Comment by mlasala45** [comment]
Maybe it would be worth having a test screenshot for bevelEnabled == false?

File: src/geometries/ExtrudeGeometry.js [hunk 1]
```diff
@@ -439,6 +439,27 @@ class ExtrudeGeometry extends BufferGeometry {
 
 			}
 
+			//When bevelSegments == 0, the modified vert arrays will not have been populated. We do this here.
+			{
```
Comment (Mugen87) [inline src/geometries/ExtrudeGeometry.js:443]: Can we avoid using these extra brackets?

**Comment by WestLangley** [comment]
These new changes appear to be causing additional regressions. Also check the console errors.

Screenshot 2025-03-29 at 7 25 29 PM

https://threejs.org/examples/webgl_geometry_text.html // tested after merging this PR

I would be inclined to revert #30750 at this point and allow time for proper testing.

**Comment by mlasala45** [comment]
@WestLangley not seeing console errors, but I see the geometry bug (oddly, it's different on my end). I'll investigate.

**Comment by mlasala45** [comment]
Fixed. The change was using the wrong variable to populate contractedContourVertices, which would cause an error for shapes with holes when bevelEnabled == false. My bad, I should have tested the PR more thoroughly.

**Comment by WestLangley** [comment]
>@WestLangley not seeing console errors, ...

The console errors occurred when the font was changed.

Unrelated to this PR, but FYI, file `8.svg` from the `webgl_loader_svg.html` example does not extrude properly. It is just a rectangle with a single hole.

**Comment by mlasala45** [comment]
> Unrelated to this PR, but FYI, file 8.svg from the webgl_loader_svg.html example does not extrude properly. It is just a rectangle with a single hole.
It appears that the outside boundary is being classified as a hole, while the inside boundary is being classified as a contour. This is happening before it's passed to ExtrudeGeometry, so it's probably a defect with the SVG file itself, the SVGLoader, or path.toShapes(). The issue seems to predate #30750 though.

**Comment by WestLangley** [comment]
@gkjohnson I have done the best I can to identify the failure points. Someone other than myself will have to approve the code changes. 🙏

File: src/geometries/ExtrudeGeometry.js [hunk 2]
```diff
@@ -439,6 +439,24 @@ class ExtrudeGeometry extends BufferGeometry {
 
 			}
 
+			//When bevelSegments == 0, the modified vert arrays will not have been populated. We do this here.
```
Comment (gkjohnson) [inline src/geometries/ExtrudeGeometry.js:442]: Lets use spaces after comments so we're consistent with the rest of the files.

File: src/geometries/ExtrudeGeometry.js [hunk 3]
```diff
@@ -439,6 +439,24 @@ class ExtrudeGeometry extends BufferGeometry {
...
+
+			if ( expandedHoleVertices.length == 0 ) {
+
+				for ( let h = 0, hl = numHoles; h < hl; h ++ ) {
+
+					expandedHoleVertices.push( holes[ h ] ); //triangulateShape expects a Vec2[][], ie. an array of holes, with each hole being a Vec2[]
+
+				}
+
+			}
```
Comment (gkjohnson) [inline src/geometries/ExtrudeGeometry.js:458]: Is there ever a case where contract contour will have length 0 but expandedHoleVertices will not? I think for clarity we should handle these in the same condition.

File: src/geometries/ExtrudeGeometry.js [hunk 4]
```diff
@@ -439,6 +439,24 @@ class ExtrudeGeometry extends BufferGeometry {
 
 			}
 
+			//When bevelSegments == 0, the modified vert arrays will not have been populated. We do this here.
+
+			if ( contractedContourVertices.length == 0 ) {
+
+				contractedContourVertices.push( ...contour );
```
Comment (gkjohnson) [inline src/geometries/ExtrudeGeometry.js:446]: I've seen the spread operator cause stackoverflow errors when used with "push" - lets avoid using it here. Is there a reason to push the vertices onto the array rather than replacing the variable?

**Comment by gkjohnson** [comment]
> I have done the best I can to identify the failure points. Someone other than myself will have to approve the code changes. 🙏

Sorry I missed that there were already other reviews on this PR somehow. I'm not an expert in this file but as this PR is addressing it looks like the tringulated arrays were not being populated if there were no bevel points. Using the "contour" and "holes" arrays should revert the behavior back to what it was before #30750 when bevels were disabled. This change also seems to work.

```js
let faces;
if ( contractedContourVertices.length === 0 ) {

	faces = ShapeUtils.triangulateShape( contour, holes );

} else {

	faces = ShapeUtils.triangulateShape( contractedContourVertices, expandedHoleVertices );

}
```

**Comment by mlasala45** [comment]
>Using the "contour" and "holes" arrays should revert the behavior back to what it was before https://github.com/mrdoob/three.js/pull/30750 when bevels were disabled.

@gkjohnson Good call. I've restructured this fix to check bevelSegments early, and avoid calculating contractedContourVertices and expandedHoleVertices  when not necessary. The diffs show up poorly due to indentation changes, but the structure is now:
```js
let faces;
if ( bevelSegments == 0 ) {

	faces = ShapeUtils.triangulateShape( contour, holes );

} else {
	// Calculate contractedContourVertices and expandedHoleVertices
	// ...

	faces = ShapeUtils.triangulateShape( contractedContourVertices, expandedHoleVertices );
}
```

**Review by gkjohnson — COMMENTED** [review]
I think this looks good and ready to merge.
