### PR TITLE
WebGLTextures: Only use anistropic filtering with certain `minFilter`/`magFilter` combinations.

### LINKED ISSUE #25067: GPU implementation differences with texture anisotropy and NEAREST filtering
**Describe the bug**

Turns out #25015 has uncovered (not introduced!) a bug in ANGLE affecting three.js: when texture ansiotropy is != 1, the actual filtering mode is ignored in _some_ implementations (but not others) and results in linear filtering being used. This is problematic for cases where NEAREST filtering was actually the intended result (e.g. pixel art). There doesn't seem to be a cross-platform way to get anisotropic NEAREST filtering.

More references:
- https://bugs.chromium.org/p/angleproject/issues/detail?id=4994
- https://github.com/KhronosGroup/WebGL/pull/3159
- https://github.com/KhronosGroup/Vulkan-Docs/issues/1361#issuecomment-692232030

Some comments from those:
> The only thing we can recommend is avoiding them: use aniso only when it will give a desired quality boost vs plain LINEAR.
>  if you ask for anisotropic filtering but with NEAREST or maxAnisotropy = 1.0, you get what you get

So we'll probably want to avoid that anisotropy is ever used if the filtering is NEAREST.
I'm happy to make a PR: I would probably check here
- https://github.com/mrdoob/three.js/blob/d7b1ca7446ee21f1e1e3e5f15536e53c97a371dd/src/renderers/webgl/WebGLTextures.js#L573
if NEAREST is used and skip setting anisotropy in that case.

**To Reproduce**

- Set Texture.DEFAULT_ANISOTROPY to 4 (or set any loaded texture's ansio to 4)
- Load this texture:
pixelArt
- or this glb: 
[PixelArt.zip](https://github.com/mrdoob/three.js/files/10146851/PixelArt.zip)

**Expected behavior**

Point filtering stays point filtering, even with anisotropy enabled, users shouldn't have to know about hardware implementation bugs.

**Platform:**

 - Device: [Desktop]
 - OS: [Windows]
 - Browser: [Chrome, Firefox, Safari, Edge]
 - Three.js version: [dev]

### PR DESCRIPTION
**Pull request by hybridherbst**
Fixed #25067

**Description**

Fixes the above mentioned issue by not setting anisotropy if the texture has NEAREST magFilter.

I'm not sure: would this need to be applied on the new WebGPURenderer and so on as well?

*This contribution is funded by [Needle](https://needle.tools)*

### CODE REVIEW

File: src/renderers/webgl/WebGLTextures.js [hunk 1]
```diff
@@ -570,7 +570,7 @@ function WebGLTextures( _gl, extensions, state, properties, capabilities, utils,
 
 		}
 
-		if ( extensions.has( 'EXT_texture_filter_anisotropic' ) === true ) {
+		if ( texture.magFilter !== NearestFilter && extensions.has( 'EXT_texture_filter_anisotropic' ) === true ) {
```
Comment (Mugen87) [inline src/renderers/webgl/WebGLTextures.js:573]: Shouldn't you check for `minFilter` instead?

**Comment by Mugen87** [comment]
Although it's technically possible, I've always though you should always use anistropic filtering with mipmapping for performance reasons (see https://paroj.github.io/gltut/Texturing/Tut15%20Anisotropy.html). So we could also check for `( texture.minFilter !== NearestFilter && texture.minFilter !== LinearFilter )`.

**Comment by hybridherbst** [comment]
Makes sense. I hope I get to change this next week.

**Comment by elalish** [comment]
Good catch! I think I'll wait on https://github.com/google/model-viewer/pull/4005 until this fix is in. If it can sneak into r148, that would be much appreciated!

**Comment by hybridherbst** [comment]
I believe I got all cases right now; I compared behaviour with aniso=1 and =4 for a number of combinations of minFilter and magFilter (including some weird ones).
- `magFilter === Nearest` must be excluded
- only `minFilter === NearestMipmapLinearFilter` and `minFilter === LinearMipmapLinearFilter` are the remaining options where anisotropy makes sense

Test file:
[TextureFiltering-Pixelgraphics.zip](https://github.com/mrdoob/three.js/files/10222869/TextureFiltering-Pixelgraphics.zip)

File: src/renderers/webgl/WebGLTextures.js (hunk 1 above)
Comment (hybridherbst) [reply src/renderers/webgl/WebGLTextures.js]: Turns out both need to be checked, see response in thread below

**Review by Mugen87 — APPROVED** [review]
