### PR TITLE
GLTF: export same mimetype as import

### LINKED ISSUE #23587: GLTFExporter grows files 5x from import
**Describe the bug**

JPEG textures in an input GLB get exported as PNG, causing such models to grow enormously in size. 

**To Reproduce**

1. Go to https://threejs.org/editor/
2. Import [DamagedHelment.glb](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/DamagedHelmet/glTF-Binary)
3. Export as GLB
4. Note the original was 3.8 Mb, while the new is 17.9 Mb

**Expected behavior**

The exported model should be pretty close to the same size as the original. I understand it won't be identical, which is fine, but this is pretty unusable. 

**Cause**

#23385 is sort of the culprit, but really it was #23228 where the RGBFormat was removed and this was the only way we had to tell if a texture had been a JPG or a PNG. @Mugen87 @donmccurdy This is blocking model-viewer's update to r137/r138 because it affects our editor the same as yours. Can anyone think of a quick work-around?

### PR DESCRIPTION
**Pull request by elalish**
Fixes: #23587

**Description**

This allows GLTFExporter to create textures of the same mimeType as the input, so keep file size from growing. @donmccurdy @Mugen87

### CODE REVIEW

**Comment by elalish** [comment]
With this change, the export of DamagedHelmet.glb drops from 17.9 Mb to 3.1 Mb, very near the input of 2.9 Mb. I understand this method isn't perfect, but I also don't want to throw the baby out with the bath water. This has the additional advantage that one can now specify any output format for each texture simply by setting `userData.mimeType`. If this is useful more generally (added to other import/export formats here) we could even make it a member of `Texture`.

**Review by Mugen87 — APPROVED** [review]
As a start this solution is okay!

File: examples/jsm/exporters/GLTFExporter.js [hunk 1]
```diff
@@ -1184,7 +1189,7 @@ class GLTFWriter {
 
 		const textureDef = {
 			sampler: this.processSampler( map ),
-			source: this.processImage( map.image, map.format, map.flipY )
+			source: this.processImage( map.image, map.format, map.flipY, map.userData.mimeType )
```
Comment (donmccurdy) [inline examples/jsm/exporters/GLTFExporter.js:1192]: Note this will result in invalid files if the input was WebP; we'd need to append `EXT_texture_webp`.

**Comment by Mugen87** [comment]
Basically yes. However, looking at the code I think using `Texture.userData` is fine for now.

File: examples/jsm/exporters/GLTFExporter.js (hunk 1 above)
Comment (elalish) [reply examples/jsm/exporters/GLTFExporter.js:1192]: Indeed; fodder for a next PR?

Comment (donmccurdy) [reply examples/jsm/exporters/GLTFExporter.js:1192]: If you're planning to make that PR in the next week or two, sure! Otherwise I'd just limit the output to PNG or JPEG here for now.

Comment (elalish) [reply examples/jsm/exporters/GLTFExporter.js:1192]: sure, I can limit it for now.

Comment (donmccurdy) [reply examples/jsm/exporters/GLTFExporter.js:1192]: Thanks! Just hoping to avoid having an interim span of time where we output invalid files. :)

Comment (elalish) [reply examples/jsm/exporters/GLTFExporter.js]: Done.

File: examples/jsm/exporters/GLTFExporter.js [hunk 2]
```diff
@@ -756,7 +756,11 @@ class GLTFWriter {
 
 			context.putImageData( composite, 0, 0 );
 
-			return new Texture( canvas );
+			const texture = new Texture( canvas );
+
+			texture.userData.mimeType = material.roughnessMap.userData.mimeType ?? material.metalnessMap.userData.mimeType ?? material.aoMap.userData.mimeType;
```
Comment (donmccurdy) [inline examples/jsm/exporters/GLTFExporter.js:761]: Based on https://github.com/mrdoob/three.js/pull/23488 I think we're trying to stick to ≤ES2018 at this point, so no nullish coalescing yet.

Comment (elalish) [reply examples/jsm/exporters/GLTFExporter.js:761]: Ugh, okay, how's this?

File: examples/jsm/loaders/GLTFLoader.js [hunk 3]
```diff
@@ -2966,6 +2966,15 @@ class GLTFParser {
 
 			}
 
+			texture.userData.mimeType = sourceDef.mimeType;
+
+			if ( ! sourceDef.mimeType ) {
+
+				const ext = sourceDef.uri.split( '.' ).pop().toLowerCase();
+				texture.userData.mimeType = ( ext.includes( 'jp' ) ) ? 'image/jpeg' : ext === 'webp' ? 'image/webp' : 'image/png';
```
Comment (mrdoob) [inline examples/jsm/loaders/GLTFLoader.js:2974]: I agree with @donmccurdy: https://github.com/mrdoob/three.js/issues/23587#issuecomment-1052684982

Better to use jpeg in this case.

Comment (elalish) [reply examples/jsm/loaders/GLTFLoader.js:2974]: Okay, I took care of that on export like he asked. I figured this was fine to leave in for now since someone could at least query to see if the input happened to be webp, even though it'll export as png.

Comment (donmccurdy) [reply examples/jsm/loaders/GLTFLoader.js:2974]: Yeah I think is OK now – we'll set `userData.mimeType = 'image/webp'` sometimes, but GLTFExporter will export those as PNG instead. JPEG would also be fine with me in that case.

**Review by donmccurdy — APPROVED** [review]

File: examples/jsm/exporters/GLTFExporter.js (hunk 2 above)
Comment (donmccurdy) [reply examples/jsm/exporters/GLTFExporter.js]: Thanks! `||` would also be fine.

Comment (elalish) [reply examples/jsm/exporters/GLTFExporter.js]: Argh, now you tell me...

Comment (elalish) [reply examples/jsm/exporters/GLTFExporter.js]: Cleaned up.

File: examples/jsm/loaders/GLTFLoader.js (hunk 3 above)
Comment (mrdoob) [reply examples/jsm/loaders/GLTFLoader.js:2974]: Ah I see. That nested ternary operator was hard to read.

**Comment by mrdoob** [comment]
Hmm, I still wonder though....

Isn't there a way to store the original image raw data in `userData` and just write that raw data in the output instead?

Recompressing jpgs/webms doesn't make me feel good 😅

**Comment by elalish** [comment]
For sure, this is a stop-gap solution. But honestly, recompressing a JPEG as a JPEG at the same resolution is pretty much lossless anyway (the high frequencies were already removed). And WebP to PNG is fine except for inflating the size (and it's a small use case at the moment). That's fixable by doing what @donmccurdy was suggesting.

File: examples/jsm/exporters/GLTFExporter.js [hunk 4]
```diff
@@ -1182,9 +1187,11 @@ class GLTFWriter {
 
 		if ( ! json.textures ) json.textures = [];
 
+		const mimeType = map.userData.mimeType === 'image/webp' ? 'image/png' : map.userData.mimeType;
+
```
Comment (mrdoob) [inline examples/jsm/exporters/GLTFExporter.js:1191]: This is dumber but it's easier to understand what is trying to do:

```js
let mimeType = map.userData.mimeType;

if ( mimeType === 'image/webp' ) mimeType = 'image/png';
```

Comment (elalish) [reply examples/jsm/exporters/GLTFExporter.js:1191]: done.

File: examples/jsm/loaders/GLTFLoader.js [hunk 5]
```diff
@@ -2966,6 +2966,15 @@ class GLTFParser {
...
+
+			}
+
```
Comment (mrdoob) [inline examples/jsm/loaders/GLTFLoader.js:2977]: I think this deserves to be its own function:

```js
function getImageURIMimeType( uri ) {

	if ( uri.search( /\.jpe?g($|\?)/i ) > 0 || uri.search( /^data\:image\/jpeg/ ) === 0 ) return 'image/jpeg';
	if ( uri.search( /\.webp($|\?)/i ) > 0 || uri.search( /^data\:image\/webp/ ) === 0 ) return 'image/webp';

	return 'image/png';

}
```

And then is just this:

```js
texture.userData.mimeType = sourceDef.mimeType || getImageURIMimeType( sourceDef.uri );
```

Comment (elalish) [reply examples/jsm/loaders/GLTFLoader.js]: done.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
Cherry-picked into `master` and included in `0.138.2`.

**Comment by bildekrokodil** [comment]
Hi,

Since this change I have problem when my textures come from a canvas element.
map.userData is undefined so it crashes to get the mimeType of it.

Kind regards

**Comment by donmccurdy** [comment]
@bildekrokodil could you share the specific error and stack trace that is thrown when this error happens? All texture types should have `.userData`. But I think this error might fail if one of the three texture types is missing...

```js
texture.userData.mimeType = material.roughnessMap.userData.mimeType || material.metalnessMap.userData.mimeType || material.aoMap.userData.mimeType;
```

**Comment by elalish** [comment]
Oh, interesting; I thought `userData` always existed on Textures. Does it only exist on certain types of textures?

**Comment by donmccurdy** [comment]
All texture types do extend from Texture and so have `.userData`, I think the source of the error was probably when a property like `material.roughnessMap` was missing. https://github.com/mrdoob/three.js/pull/23616 would have solved that I think.

**Comment by mrdoob** [comment]
> All texture types do extend from Texture and so have `.userData`, I think the source of the error was probably when a property like `material.roughnessMap` was missing. https://github.com/mrdoob/three.js/pull/23616 already solved that probably.

Yeah, I sneaked in a robustness fix in that PR. I should have mentioned it but I was brain dead 😅

**Comment by bildekrokodil** [comment]
Hi,

This is the error I got:
TypeError: Cannot read properties of undefined (reading 'mimeType')
    at GLTFWriter.processTexture (GLTFExporter.js:1058:32)
    at GLTFWriter.processMaterial (GLTFExporter.js:1146:18)
    at GLTFWriter.processMesh (GLTFExporter.js:1516:27)
    at GLTFWriter.processNode (GLTFExporter.js:1780:28)
    at GLTFWriter.processNode (GLTFExporter.js:1801:30)
    at GLTFWriter.processNode (GLTFExporter.js:1801:30)
    at GLTFWriter.processScene (GLTFExporter.js:1852:29)
    at GLTFWriter.processInput (GLTFExporter.js:1907:11)
    at GLTFWriter.write (GLTFExporter.js:385:9)
    at Proxy.parse (GLTFExporter.js:92:11)

I use the JS version in combination with A-Frame. I export an A-Frame model with canvas textures on it. It works until this commit. At this moment I use the previous version of the GLTFExporter to make it work.

Kind regards

**Comment by mrdoob** [comment]
@bildekrokodil Any change you can do a jsfiddle reproducing the issue?

**Comment by bildekrokodil** [comment]
@mrdoob 
I created a jsfiddle for you. (Sorry it took me some time)

https://jsfiddle.net/bigcroco/xq6hacw5/1/

In the code I have the default a-frame scene. But added a canvas as a resource and another box that uses this canvas as a texture. 

When you run it it will give you that error.
If you remove the box with the canvas element as a texture. it works fine and a glft model will be downloaded.

Kind regards

**Comment by mrdoob** [comment]
@bildekrokodil Please, report the issue in the a-frame repo instead: https://github.com/aframevr/aframe

**Comment by donmccurdy** [comment]
Important to note that the demo above uses an A-Frame version pinned to three.js r125. Pulling a newer version of THREE.GLTFExporter in with an older version of three.js is not really supported by three.js or by A-Frame. It might be best to use a copy of GLTFExporter from r125 until A-Frame updates to a newer version of three.js.
