### PR TITLE
WebGLRenderer: Fix texture unit allocation of morph textures.

### LINKED ISSUE #22619: Rendering issues with shadow-casting, morphed meshes.
His shadow is working so hard but he just sits [there](https://threejs.org/examples/webgl_animation_multiple.html) motionless:

https://user-images.githubusercontent.com/242577/135541123-36ee92d3-a2d6-4c76-a661-dde9438d6b35.mp4

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #22619

**Description**

This PR ensures that similar to bone textures, morph textures allocated the same texture unit.

### CODE REVIEW

File: src/renderers/WebGLRenderer.js [hunk 1]
```diff
@@ -1514,11 +1508,11 @@ function WebGLRenderer( parameters = {} ) {
 		const environment = material.isMeshStandardMaterial ? scene.environment : null;
 		const encoding = ( _currentRenderTarget === null ) ? _this.outputEncoding : _currentRenderTarget.texture.encoding;
 		const envMap = ( material.isMeshStandardMaterial ? cubeuvmaps : cubemaps ).get( material.envMap || environment );
-		const vertexAlphas = material.vertexColors === true && !! object.geometry && !! object.geometry.attributes.color && object.geometry.attributes.color.itemSize === 4;
```
Comment (Mugen87) [inline src/renderers/WebGLRenderer.js:1517]: I don't think the `!! object.geometry` make sense. Render items always have a geometry, no?

Comment (Mugen87) [reply src/renderers/WebGLRenderer.js:1517]: Ah wait, we need this for `ImmediateRenderObject`.

Comment (Mugen87) [reply src/renderers/WebGLRenderer.js:1517]: I wonder if we could remove `ImmediateRenderObject` and implemented the marching cube example more straightforward based in `BufferGeometry`. This would noticeably simplify the renderer. And in that way,`WebGPURenderer` does not have to support `ImmediateRenderObject`.

**Comment by Mugen87** [comment]
I guess we need `r133.1` with this fix.

File: src/renderers/WebGLRenderer.js (hunk 1 above)
Comment (mrdoob) [reply src/renderers/WebGLRenderer.js:1517]: That sounds good to me 👍
