### PR TITLE
TSL: Add active stack and improve "node block" support

### LINKED ISSUE #30954: TSL - Loop with boolean values doesn't work??
### Description

The case of using a Loop node with a boolean node doesn't seem to be working...

### Reproduction steps

---

### Code

```js
// This should remove all green...
 const out = vec3(0,1,0 ).toVar();
    const o = Fn(()=>{ 

        const value = float( 0 ).toVar();

        Loop( value.lessThan( 10 ), () => {
            value.addAssign( 1 );  
            out.y.subAssign( 0.1 );
        });    

        return out ; 
    });  
```

### Live example

https://jsfiddle.net/xzonyf37/

### Screenshots

_No response_

### Version

r174

### Device

Desktop

### Browser

Chrome

### OS

Linux

### PR DESCRIPTION
**Pull request by sunag**
Fixes https://github.com/mrdoob/three.js/issues/30954, https://github.com/mrdoob/three.js/issues/32009, 
Related issue: https://github.com/mrdoob/three.js/pull/31929

**Description**

Variables declared outside the stack are being added to the main stack. This fixes the bug in question, and opens some windows for optimization as well.

### CODE REVIEW

**Comment by Mugen87** [comment]
This change introduces a regression in context of logarithmic depth buffer. Reverting the commit fixes the issue (it's necessary to resolve a merge conflict in `VarNode` though. 

A reproduction test case is available in https://github.com/mrdoob/three.js/issues/32686#issuecomment-3722080553.

File: src/nodes/core/VarNode.js [hunk 1]
```diff
@@ -313,12 +331,6 @@ export const Const = ( node, name = null ) => createVar( node, name, true ).toSt
  */
 export const VarIntent = ( node ) => {
 
-	if ( getCurrentStack() === null ) {
-
-		return node;
-
-	}
-
```
Comment (Methuselah96) [inline src/nodes/core/VarNode.js:321]: @sunag I'm not sure whether this is an issue with this change or an issue in the examples, but this changes the value constructor functions (e.g., `color()`, `vec3()`, etc.) to return a `VarNode` instead of a `ConstNode` and there are some places in the examples where it was expected that they would return a `ConstNode`. For example, in `webgpu_custom_fog` we are [expecting the `.value` properties to exist](https://github.com/mrdoob/three.js/blob/dev/examples/webgpu_custom_fog.html#L115) for nodes constructed using the `color()` function, but they do not exist on `VarNode` and therefore trying to access `.value` returns `undefined` instead of the expected color value.

Comment (sunag) [reply src/nodes/core/VarNode.js:321]: Make sense, thank you for the verification, TSL constants it is not safe to obtain values through `.value`, better to use it separately
