### PR TITLE
GLTFLoader: Fixed variants normal map scale

### LINKED ISSUE #21136: Normal is not correct when switching Variant in webgl_loader_gltf_variants
**Describe the bug**

I tried the sample [KHR_materials_variants](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_variants/README.md) extension of `glTF`.
However, when I switch the Variant from `midnight` to `beach`, Normal does not seem to be correct.

**To Reproduce**

1. Go to https://threejs.org/examples/?q=variant#webgl_loader_gltf_variants
2. Switch the Variant from `midnight` to `beach`
3. Look at the logo on the side of the shoe.

**Expected behavior**

Since this model refers to the same `normal.jpg`, the expected behavior is that the unevenness will not change.

**Screenshots**

|Variant|image|
|:-----:|:------:|
|midnight|image|
|beach|image|

**Platform:**

 - Device: MacBook Air
 - OS: Windows 10 (BootCamp)
 - Browser: Chrome 87.0.4280.141
 - Three.js version: r124

### PR DESCRIPTION
**Pull request by elalish**
Fixes #21136 

This makes `assignFinalMaterial()` public (well, it sort of was already, just not in the types file). I couldn't think of a better name, and `getDependency()` is already kind of confusing to me, so I feel like the bar isn't too high. 😂

I verified this works on both the three.js example and in model-viewer. If anyone has a model with vertex tangents and variants, that would be good to test, but I'm pretty confident this will work. Basically the sign-flip is now the default behavior and flipping it back is inside of a cache check, so it does't happen more than once.

### CODE REVIEW

**Comment by elalish** [comment]
@donmccurdy @mrdoob Getting a bit close for the release, but it'd be nice to make r125.

**Comment by elalish** [comment]
FYI @takahirox

File: examples/js/loaders/GLTFLoader.js [hunk 1]
```diff
@@ -2621,11 +2621,20 @@ THREE.GLTFLoader = ( function () {
...
 				if ( useMorphTargets ) cachedMaterial.morphTargets = true;
 				if ( useMorphNormals ) cachedMaterial.morphNormals = true;
+				
+				if ( useVertexTangents ) {
+
+					cachedMaterial.vertexTangents = true;
+
+					// https://github.com/mrdoob/three.js/issues/11438#issuecomment-507003995
+					if ( material.normalScale ) material.normalScale.y *= -1;
+					if ( material.clearcoatNormalScale ) material.clearcoatNormalScale.y *= -1;
```
Comment (donmccurdy) [inline examples/js/loaders/GLTFLoader.js:2635]: These two lines are needed only if vertex tangents are _not_ present — that's the issue in https://github.com/mrdoob/three.js/issues/21136 as well.

Comment (elalish) [reply examples/js/loaders/GLTFLoader.js:2635]: No, because I reversed them by default above, so now they need to be re-reversed if vertexTangents are used, which can work because vertexTangents create a new cacheKey.

File: examples/js/loaders/GLTFLoader.js [hunk 2]
```diff
@@ -2778,11 +2774,11 @@ THREE.GLTFLoader = ( function () {
 
 			pending.push( parser.assignTexture( materialParams, 'normalMap', materialDef.normalTexture ) );
 
-			materialParams.normalScale = new THREE.Vector2( 1, 1 );
+			materialParams.normalScale = new THREE.Vector2( 1, -1 );
 
 			if ( materialDef.normalTexture.scale !== undefined ) {
 
-				materialParams.normalScale.set( materialDef.normalTexture.scale, materialDef.normalTexture.scale );
+				materialParams.normalScale.set( materialDef.normalTexture.scale, -materialDef.normalTexture.scale );
```
Comment (elalish) [inline examples/js/loaders/GLTFLoader.js:2781]: Here is the other reversal.

File: examples/jsm/loaders/GLTFLoader.js [hunk 3]
```diff
@@ -685,7 +685,7 @@ var GLTFLoader = ( function () {
 
 				var scale = extension.clearcoatNormalTexture.scale;
 
-				materialParams.clearcoatNormalScale = new Vector2( scale, scale );
+				materialParams.clearcoatNormalScale = new Vector2( scale, -scale );
```
Comment (elalish) [inline examples/jsm/loaders/GLTFLoader.js:688]: And here.

**Comment by mrdoob** [comment]
@donmccurdy How do you feel about this PR? Do you think it's ready to merge (r125 due tomorrow) or should we leave it for r126?

File: examples/js/loaders/GLTFLoader.js (hunk 1 above)
Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js:2635]: Oops, I see. Seems a little more confusing to have inversions in three places, was there a specific reason you prefer that? If we keep it that way, we should include a link to the github issue above in all three places.

Comment (elalish) [reply examples/js/loaders/GLTFLoader.js:2635]: As I say, it was necessary in order to make the switch happen only inside a cached constructor, instead of every time `assignFinalMaterial` was called. That was the bug. I'll put in the comments.

**Review by donmccurdy — APPROVED** [review]

File: examples/js/loaders/GLTFLoader.js (hunk 1 above)
Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js:2636]: It seems like this will introduce the opposite problem if the mesh did have vertex tangents with variants, no?

**Review by donmccurdy — CHANGES_REQUESTED** [review]
Hm, sorry, I'm not sure what to do here. This fixes the reported issue, but creates a new, identical issue if the model does have vertex tangents, I think?

If it's a choice between the two, it would probably be better to ensure correct behavior for the users who have gone to the trouble of including vertex tangents.

Calling the `assignFinalMaterial` method from the application would handle either case, so then I guess the question is whether the remaining logic should still be changed?

File: examples/js/loaders/GLTFLoader.js (hunk 1 above)
Comment (elalish) [reply examples/js/loaders/GLTFLoader.js:2636]: No, I don't think so. Did you find that to be true in testing?

**Comment by elalish** [comment]
If the model does have vertex tangents then the first time the material is created, the normals will be flipped once, then flipped back again in assignFinalMaterial. If the variant is switched back, it will use the cached version in assignFinalMaterial instead of re-flipping the normals. This should solve it both ways, no?

File: examples/js/loaders/GLTFLoader.js (hunk 1 above)
Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js:2636]: We have exactly one sample using variants, and it doesn't have vertex tangents, so I'm limited to guessing at this point. I think I see what you mean though.

**Review by donmccurdy — APPROVED** [review]
OK, looks good to me.

**Comment by mrdoob** [comment]
Thanks! 🤞
