### PR TITLE
Editor: Fix persistent history.

### LINKED ISSUE #28395: Editor: Runtime error in history.
### Description

When using persistent history, a runtime error is thrown when deleting an object and refreshing the page.

> RemoveObjectCommand.js:17 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at new RemoveObjectCommand (RemoveObjectCommand.js:17:79)
    at History.fromJSON (History.js:204:16)
    at Editor.fromJSON (Editor.js:674:16)
    at async index.html:115:7

### Reproduction steps

1. Enable persistent history in the settings tab.
2. Add a box.
3. Delete it.
4. Refresh the site and check browser console.

### Code

-

### Live example

https://rawcdn.githack.com/mrdoob/three.js/dev/editor/index.html

### Screenshots

_No response_

### Version

r165dev

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #28395.

Closes #28360. Closes #28398. Closes #28362.

**Description**

This PR ensures commands can now properly serialized/deserialized when persistent history is enabled.

It makes sure all commands have proper default values and don't throw exceptions in their ctors when default parameters are used.

The PR also makes sure material commands use the correct material reference. This is done by not caching the material in the command but the material slot instead. With this information, the correct material can be requested with the object. Meaning this pattern:
```js
const material = editor.getObjectMaterial( object, materialSlot );
```

### CODE REVIEW

File: editor/js/Editor.js [hunk 1]
```diff
@@ -671,11 +671,12 @@ Editor.prototype = {
 
 		this.signals.cameraResetted.dispatch();
 
-		this.history.fromJSON( json.history );
 		this.scripts = json.scripts;
 
 		this.setScene( await loader.parseAsync( json.scene ) );
 
+		this.history.fromJSON( json.history );
```
Comment (Mugen87) [inline editor/js/Editor.js:678]: The commands restore references from the scene in thei `fromJSON()` methods. This history must be restored after the scene graph has loaded otherwise all references into the scene graph are wrong.

**Comment by Mugen87** [comment]
https://rawcdn.githack.com/Mugen87/three.js/531b6e537841194ea8dddd1d49d6cf6cb337d9df/editor/index.html

File: editor/js/Sidebar.Scene.js [hunk 2]
```diff
@@ -522,13 +522,13 @@ function SidebarScene( editor ) {
...
 
-		signals.objectChanged.dispatch( editor.selected );
+		if ( editor.selected !== null ) signals.objectChanged.dispatch( editor.selected );
 
 	} );
 
 	signals.scriptRemoved.add( function () {
 
-		signals.objectChanged.dispatch( editor.selected );
+		if ( editor.selected !== null ) signals.objectChanged.dispatch( editor.selected );
```
Comment (Mugen87) [inline editor/js/Sidebar.Scene.js:531]: The assumptions made in #28270 are not right. When scripts are added or removed, an object is _not_ necessarily selected. So when undo/redo script commands, `editor.selected` can be `null`. In this case, a runtime error occurs in `Viewport.Controls.js`.

**Comment by ycw** [comment]
Would you mind explain how this approach is less confused than https://github.com/mrdoob/three.js/pull/28345#issuecomment-2106854927 ? 

and how is it simpler than https://github.com/mrdoob/three.js/pull/28360#issuecomment-2114295402 ? 

Thanks.

**Comment by ycw** [comment]
I'm little lost, because other related PRs just all get closed in a sudden without a reason 🤔

**Comment by Mugen87** [comment]
They were closed because the changes should not be necessary anymore.

When you look at the constructor code of the commands, it already handled undefined arguments. This PR just introduced real default values instead of checking the `arguments` parameter. It also made sure no runtime errors occur when the commands are created with just the edior assigned. 

So I think this solution better fits to what already has been implemented.

**Comment by Mugen87** [comment]
Even if your PRs were not merged, they were very helpful to understand the issues in the editor and developing this solution. When writing the release notes, I'll definitely add your as a contributor for this PR.

**Comment by ycw** [comment]
> constructor code of the commands, it already handled undefined arguments.

If I understand correctly, this solution **cannot** reflect the fact that constructor parameters other than `editor` will be either **all** presented or **all** omitted, so there's few confusions still remain here ...

https://github.com/mrdoob/three.js/blob/cb24e42a65172ec475ff23a4abe520b724076a24/editor/js/commands/SetColorCommand.js#L22

By reading the constructor signature,  `this.object[this.attributeName]` can be undefined if attributeName is not present, in turn `.getHex()` could throw at runtime, "How to explain that a if-guard is needn't for `this.object[this.attributeName]`?" 

... and there ...

https://github.com/mrdoob/three.js/blob/cb24e42a65172ec475ff23a4abe520b724076a24/editor/js/commands/SetPositionCommand.js#L13

"How to explain that non optional parameters have default values?"

---

> Even if your PRs were not merged, they were very helpful to understand the issues in the editor and developing this solution. 

I appreciate that you submit a solution to show your though, but this solution _is not being less confusing_ than the other solutions; 

Since this solution had been adopted and others had been rejected, so could we reach a consensus on that ['confusion'](https://github.com/mrdoob/three.js/pull/28345#issuecomment-2106854927) doesn't matter now? **[Yes/No]** The reply would help others to find a better solution in the future. Thanks :)
