### PR TITLE
WebGPURenderer: Make `material.transparent` behave as in WebGLRenderer

### LINKED ISSUE #30861: WebGPU and WebGL backends handle blending and transparency properties differently
### Description

WebGL backend will use `material.blending` even when `material.transparent` is false:
```js
		( material.blending === NormalBlending && material.transparent === false )
			? setBlending( NoBlending )
			: setBlending( material.blending, material.blendEquation, material.blendSrc, material.blendDst, material.blendEquationAlpha, material.blendSrcAlpha, material.blendDstAlpha, material.blendColor, material.blendAlpha, material.premultipliedAlpha );
```
WebGPU backend ignores `material.blending` value when `material.transparent` is false:
```js
		if ( material.transparent === true && material.blending !== NoBlending ) {

			blending = this._getBlending( material );

		}
```

### Reproduction steps

See live example 
1. Run example in WebGPU-capable browser -> sphere hides axes
2. Pass `forceWebGL: true` to WebGPURenderer ctor -> axes are now visible

### Code

```js
    const material = new THREE.MeshPhongMaterial( {
        color: 0x00ffff, 
        flatShading: true,
        transparent: false,
        blending: THREE.AdditiveBlending,
    } );
```

### Live example

Live example: [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/Lwh3cjf9/)

### Screenshots

_No response_

### Version

171

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by rkreis-v**
Fixed #30861

**Description**

Make WebGPU backend apply `material.blending` even when `material.transparent` is false, just like WebGL backend.

### CODE REVIEW

**Comment by rkreis-v** [comment]
Can also be fixed by changing WebGL backend to behave like WebGPU, but I find the behavior of the WebGL backend more intuitive - it wasn't apparent to me why WebGPU backend would ignore an explicitly set `blending` property.

**Comment by Mugen87** [comment]
Aligning both backends makes of course sense. However, I find the WebGL behavior more confusing. It seems more intuitive to me that blending only works when `transparent` is set to `true`.

**Comment by WestLangley** [comment]
@Mugen87 See if the discussion in #14171 answers your question.

**Comment by rkreis-v** [comment]
@sunag thanks for the fixup! Clarification: It's specifically about the WebGPU backend, WebGPURenderer with `forceWebGL: true` behaves like WebGLRenderer already. Ok with you to revert the title?

Regarding expected behavior, I discovered the mismatch implementing a specific use case where I need blending without moving objects to the second render pass for transparent objects. I see no way to do that with current WebGPU backend.

**Comment by Mugen87** [comment]
How can you ensure that objects are properly sorted for blending if you don't set `transparent` to `true`?

**Comment by rkreis-v** [comment]
I'm using a full screen pass to draw an overlay on existing opaque geometry, which has to be rendered before other opaque geometry. I'd prefer not to derail the discussion, but focus on the bug and API design instead. Can we agree that there's a legitimate use case to have `blending` set without `transparent: true`, and there's existing code using that combination on WebGL backend?

**Comment by sunag** [comment]
> ... but focus on the bug and API design instead.

This is exactly what @Mugen87 is doing. The ordering works in reverse to transparent objects, rendering from closest to furthest for early-z rejection to work in an optimized way which seems like a real problem to me. We need to make sure that users are using the correct approach for each purpose so that the API design is not mistaken for a bug.

@Mugen87 Do you remember when we started using `material.id` difference to sort the render-order?
https://github.com/mrdoob/three.js/blob/c92a3ff1be840824a98470c3307658b98b197155/src/renderers/common/RenderList.js#L22-L24

**Comment by WestLangley** [comment]
There are so many issues with this thread...

@Mugen87 and @sunag The use of blending does not necessarily have anything to do with transparency. There are a lot of blending functions other than the familiar Porter-Duff formula that is used to model physical transparency.

@rkreis-v You are correct that the WebGLRenderer approach should be followed, but your formula is not quite correct. `transparent === true` is not the same as `transparent !== false`.

@sunag In the existing code (prior to this PR), `blending` can remain `undefined`. Is that intentional?

**Comment by sunag** [comment]
@WestLangley Currently the blending was working according to the user's luck creating one material after another as I demonstrated in the fiddle, so `painterSortStable()` will be redone and the opaque materials will be rendered behind the blending mode. Are you considering this?

**Comment by WestLangley** [comment]
@sunag My previous comments have nothing to do with sorting. I do not want to get sidetracked here. This PR is about making sure the `WebGPURenderer` blending formula matches `WebGLRenderer`. We can't require users to set `transparent = true` to get their custom blending to be applied.

Please do not assume the use of blending means the material is transparent. Doing so is a misconception.

**Comment by sunag** [comment]
It seems like you are linking `transparent` to the Porter-Duff formula, but practically all the `transparent` code is related to sorting, what about materials that use custom-blending or refraction that need `transparent` to do the correct sorting, they certainly don't use the Porter-Duff formula but they are still correct. What I mean is that when we fix `painterSortStable()`, `material.blending` won't work without considering `transparent` flag https://github.com/mrdoob/three.js/pull/30862#issuecomment-2783887201, either through the `material.transparent` or inside the `RenderList` through some extra conditional or custom sorting, somehow we will need to define it. All this can be discussed once we are considering all the limitations.

**Comment by rkreis-v** [comment]
I'm setting `renderer.sortObjects = false`, so none of the object sorting discussion is relevant to my use case or how we should align WebGPU and WebGL backend behaviour. Because many of my remarks and questions are ignored anyway, I don't have anything else to say at this point.

**Comment by Mugen87** [comment]
I'm afraid I still don't understand why `blending` should work without setting `transparent` to `true`. #14171 isn't a help here because all the discussion says it's _incorrect_ otherwise. I also don't understand what the "other blending functions" mentioned  in https://github.com/mrdoob/three.js/pull/30862#issuecomment-278410201 are. Maybe a fiddle could help clarifying this aspect?

Besides, answers to the following questions would also help:

- Before #14171 was implemented, developers eventually used the approach we have implemented in `WebGPURenderer` for eight years. Are there any user issues that requested a change?
- Why is it wrong to couple `Material.transparent` with `Material.blending`?
- Would it break user code if we ask users to set `Material.transparent` to `true` if blending is used.

**Comment by sunag** [comment]
> I'm setting renderer.sortObjects = false, so none of the object sorting discussion is relevant to my use case

Surely this use case is related to the luck of the back object being rendered first. This ignores a basic CG principle that blending should work when the back object has already been rendered, ordering them is to ensure that things work correctly, in a stable way.

File: src/renderers/webgpu/utils/WebGPUPipelineUtils.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ class WebGPUPipelineUtils {
 
 		let blending;
 
-		if ( material.transparent === true && material.blending !== NoBlending ) {
+		if ( material.blending !== NoBlending && ( material.blending !== NormalBlending || material.transparent === true ) ) {
```
Comment (WestLangley) [inline src/renderers/webgpu/utils/WebGPUPipelineUtils.js:91]: @rkreis-v @sunag @Mugen87 

As I mentioned in the discussion, to replicate the `WebGLRenderer` logic exactly, I think it should be:

```js
if ( material.blending !== NoBlending && ( material.blending !== NormalBlending || material.transparent !== false ) ) {
```

**Comment by WestLangley** [comment]
@sunag I think you missed my question in https://github.com/mrdoob/three.js/pull/30862#issuecomment-2784102018. Can you please have a look? 🙏

File: src/renderers/webgpu/utils/WebGPUPipelineUtils.js (hunk 1 above)
Comment (Mugen87) [reply src/renderers/webgpu/utils/WebGPUPipelineUtils.js:91]: Updated: https://github.com/mrdoob/three.js/commit/4e3db421aef677a668932b221b7dc2fc90ef1dd8

**Comment by sunag** [comment]
> blending can remain undefined. Is that intentional?

is intentional, if `undefined` blending is disabled

https://www.w3.org/TR/webgpu/#color-target-state
