### PR TITLE
WebGPURenderer: RenderBundle support transparent objects

### LINKED ISSUE #30681: BundleGroup not working with transparent material
### Description

When the material is transparent the BundleGroup dont render..

### Reproduction steps

1. create a BundleGroup and add object transparent.

### Code

```js

    let group = new THREE.BundleGroup()
    // mesh
    for(let i=0; i<10; i++){
    
    // material
    const material = new THREE.MeshBasicMaterial( {
        color: new THREE.Color(THREE.MathUtils.randInt(0,0xffffff)), 
        side: THREE.DoubleSide,
        transparent: true
    } );
          mesh = new THREE.Mesh( geometry, material );
          mesh.position.set(
            THREE.MathUtils.randFloat(-5,5),
            THREE.MathUtils.randFloat(-5,5),
            THREE.MathUtils.randFloat(-5,5)
          )
          group.add( mesh )
      group.needsUpdate = true
    }
    scene.add( group );
```

### Live example

https://jsfiddle.net/odkeut3n/4/

### Screenshots

_No response_

### Version

r174 dev

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by RenaudRohlinger**
Fixed #30681

**Description**

Support transparent objects with RenderBundle.

*This contribution is funded by [Utsubo](https://utsubo.com)*

### CODE REVIEW

File: src/renderers/common/Renderer.js [hunk 1]
```diff
@@ -1075,9 +1075,15 @@ class Renderer {
 
 			this._currentRenderBundle = renderBundle;
 
-			const opaqueObjects = renderList.opaque;
+			const {
+				lightsNode,
```
Comment (Mugen87) [inline src/renderers/common/Renderer.js:1079]: If you extract `lightsNode` from the render list, we can remove it from the method signature.

**Review by Mugen87 — APPROVED** [review]

**Comment by sunag** [comment]
This was intentional for opaque materials to avoid sorting issues. I think we will need two separate bundles for opaque and transparent if we want to use transmission as well.
