### PR TITLE
WebGLCubeUVMaps: Add support for render targets.

### LINKED ISSUE #22236: WebGLRenderer: fails to convert CubeCamera renderTarget to PMREM CubeUV format
Related: #22178

This use case must also be supported.

```js
const material = new THREE.MeshPhysicalMaterial( {
	envMap: cubeCamera.renderTarget.texture, // should be auto-converted to PMREM CubeUV format
} );
```
three.js version: [r131]

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #22236.

**Description**

This PR adds support for render targets in `WebGLCubeUVMaps`. That means the render targets of cube cameras can now be used with PBR materials.

@elalish I've have enhanced `PMREMGenerator` such that it is possible to reuse existing render targets for the conversion process. I'm not sure how to implement the details of https://github.com/mrdoob/three.js/issues/22236#issuecomment-948069315 though. 

TBH, it surprised me that the conversion per frame has such a decent performance (tested with `webgl_materials_cubemap_dynamic` and PBR materials). I had this different in mind when testing last year.

### CODE REVIEW

**Comment by elalish** [comment]
Wow, I'm  impressed the performance  is decent for a PMREM per frame too! I mean, I did try to make it as fast as I could, and it may well be that converting  to halfFloats sped it  up significantly. I too would love to see some frame rate comparisons. 

My comment was about bringing  back the old mipmaps-as-PMREM solution that was in three.js before my PMREMGenerator and was removed during @WestLangley's simplification. However, if this is adequately fast, then perhaps there's no need. Would be good to test a WebXR example with lighting estimation as well.

**Comment by mrdoob** [comment]
@Mugen87 Should I merge this so we have some time to test performance?

**Comment by WestLangley** [comment]
>bringing back the old mipmaps-as-PMREM solution that was in three.js

@elalish Yes, that is what #23144 is about -- just in case it is needed as a fall-back.

**Comment by Mugen87** [comment]
> @Mugen87 Should I merge this so we have some time to test performance?

Yes, that sounds good. We still need to fix the WebXR example with lighting estimation.

File: src/textures/Texture.js [hunk 1]
```diff
@@ -70,7 +70,8 @@ class Texture extends EventDispatcher {
 		this.version = 0;
 		this.onUpdate = null;
 
-		this.isRenderTargetTexture = false;
+		this.isRenderTargetTexture = false; // indicates whether a texture belongs to a render target or not
+		this.needsPMREMUpdate = false; // indicates whether this texture should be processed by PMREMGenerator or not (only relevant for render target textures)
```
Comment (WestLangley) [inline src/textures/Texture.js:74]: I am inclined to think these properties should be "private", since they are for renderer-use only.
```js
this._isRenderTargetTexture = false;
this._needsPMREMUpdate = false;
```

Comment (mrdoob) [reply src/textures/Texture.js:74]: Agreed 👍

Comment (WestLangley) [reply src/textures/Texture.js:74]: edit: I'm assuming it should be a double-underscore.

Comment (Mugen87) [reply src/textures/Texture.js:74]: Depending on how user or third-party code is developed, both flags are actually required. 

`isRenderTargetTexture` is just the pendant to all other `is*` properties and required for type checks. Besides, users have to set `needsPMREMUpdate` to `true` (similar to other `needsUpdate` flags) if they are using a dynamic render target as an env map applied to PBR materials and author the render target's data by themselves.

Comment (Mugen87) [reply src/textures/Texture.js:74]: I was actually thinking about suggesting something like `RenderTargetTexture`. However, this idea is not yet mature.

Comment (mrdoob) [reply src/textures/Texture.js:74]: Okay, lets test performance in the meantime.

**Comment by mrdoob** [comment]
Thanks!

**Comment by WestLangley** [comment]
@mrdoob build required

**Comment by mrdoob** [comment]
Done 👍

**Comment by WestLangley** [comment]
@Mugen87 Do the reflections look correct in your test cases?

**Comment by Mugen87** [comment]
After a closer look, it seems the reflections along the x axis are flipped. Let me file a PR to fix this issue.

**Comment by arpu** [comment]
@Mugen87 any plans for a sample to share?

**Comment by Mugen87** [comment]
In #23158, I've updated `webgl_materials_cubemap_dynamic.html` to use `MeshStandardMaterial`.

**Comment by ligaofeng0901** [comment]
I tested my page, and the performance is quite ok. I found there still is a framebuffer of `_pingPongRenderTarget` in `PMREMGenerator`, which updates in each frame.  After running a few minutes, the framebuffer has been created and destoryed thousands of times. I think it's not necessary and can be optimized. 
BTW, I also want to pass the rendertarget parameters to the `.fromScene`, in this way I can update a pmrem texture in each frame under my control. should the PMREMGenerator support better for the situation of updating textures in each frame.

**Comment by Mugen87** [comment]
> I found there still is a framebuffer of _pingPongRenderTarget in PMREMGenerator, which updates in each frame.

@elalish Do you think it's okay to remove the following line and add it to `dispose()` instead?

https://github.com/mrdoob/three.js/blob/ed1e47bd7e8d6501c847f94d8490e019af381ecd/src/extras/PMREMGenerator.js#L198

**Comment by elalish** [comment]
@Mugen87 Yes, that sounds  good to me. @WestLangley I believe those shaders all get disposed when the `dispose` method is called on PMREMGenerator, which seems reasonable.

**Comment by ligaofeng0901** [comment]
@Mugen87 Do you think if it's ok about adding a extra parameter to `.fromScene`? https://github.com/mrdoob/three.js/blob/dev/src/extras/PMREMGenerator.js#L103 .  In this way the method can be used by a user controlled renderTarget.

**Comment by WestLangley** [comment]
@Mugen87 @elalish  `PMREMGenerator.dispose()` is not being called. We used to do that at the app level.

Granted, we do not want to dispose() if PMREM is generated every frame, but that is not the typical use case.

**Comment by Mugen87** [comment]
> PMREMGenerator.dispose() is not being called.

It is called in `WebGLRenderer.dispose()`. 

`WebGLCubeUVMaps` only creates a single instance of `PMREMGenerator` and I think it's the only solution to buffer certain resources like the conversion process (3 materials and 1 render target) within the renderer. It's just important to ensure that we don't create these entities over and over again.

**Comment by Mugen87** [comment]
> Do you think if it's ok about adding a extra parameter to .fromScene? https://github.com/mrdoob/three.js/blob/dev/src/extras/PMREMGenerator.js#L103 . In this way the method can be used by a user controlled renderTarget.

I'm not sure about the dimensions but other render target parameters should not be configurable by the user, IMO.

**Comment by ligaofeng0901** [comment]
> I'm not sure about the dimensions but other render target parameters should not be configurable by the user, IMO.

@Mugen87 OK, thanks! Maybe my use case is not very common. Generating a realtime enviroment map can use CubeCamera now. I just guess using `.fromScene` can also implement the effect in example https://threejs.org/examples/webgl_materials_cubemap_dynamic.html , and maybe `fromScene` has a better performance with an outer render target. I tested the two different ways on two macbooks, and got the different results.
