### PR TITLE
BufferGeometry: Fix clone().

### LINKED ISSUE #8522: Clone cylinderGeometry Creates Geometry
##### Description of the problem

When cloning a cylinderGeometry the clone is a geometry not a cylinderGeometry.
simple fiddle,check the console:  http://jsfiddle.net/momve8hk/

Tested in r72 and i get a cylinderGeometry.
...
##### Three.js version
- [x] r75

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #8522.

**Description**

This PR fixes a long-standing issue in the engine. If you clone now a `BoxGeometry`, you actually get a new object of type `BoxGeometry` (and not `BufferGeometry`). The previous behavior produces an unexpected result and was confusing.

### CODE REVIEW

File: src/geometries/PolyhedronGeometry.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { Vector2 } from '../math/Vector2.js';
 
 class PolyhedronGeometry extends BufferGeometry {
 
-	constructor( vertices, indices, radius = 1, detail = 0 ) {
+	constructor( vertices = [], indices = [], radius = 1, detail = 0 ) {
```
Comment (Mugen87) [inline src/geometries/PolyhedronGeometry.js:8]: I personally consider `PolyhedronGeometry` as an abstract class (so one should always derive from `PolyhedronGeometry`). Since the class is public and the doc page shows a code example with a direct usage, I've added two additional optional parameters to ensure an object creation without parameters is possible. Previously there was a runtime error. Now, an empty geometry is returned (which is fine from my point of view since there is no proper default for a polyhedron geometry).

File: test/unit/utils/qunit-utils.js [hunk 2]
```diff
@@ -193,31 +187,6 @@ function checkGeometryJsonRoundtrip( geom ) {
 
 }
 
-// Look for undefined and NaN values in numerical fieds.
-function checkFinite( geom ) {
-
-	var allVerticesAreFinite = true;
-
-	var vertices = geom.vertices || [];
```
Comment (Mugen87) [inline test/unit/utils/qunit-utils.js:201]: This was some legacy code.

File: test/unit/utils/qunit-utils.js [hunk 3]
```diff
@@ -83,22 +83,18 @@ function checkGeometryClone( geom ) {
 	QUnit.assert.notEqual( copy.uuid, geom.uuid, "clone uuid should differ from original" );
 	QUnit.assert.notEqual( copy.id, geom.id, "clone id should differ from original" );
 
-	var excludedProperties = [ 'parameters', 'widthSegments', 'heightSegments', 'depthSegments' ];
-
-	var differingProp = getDifferingProp( geom, copy, excludedProperties );
+	var differingProp = getDifferingProp( geom, copy );
 	QUnit.assert.ok( differingProp === undefined, 'properties are equal' );
 
-	differingProp = getDifferingProp( copy, geom, excludedProperties );
```
Comment (Mugen87) [inline test/unit/utils/qunit-utils.js:91]: Excluding properties is now not necessary anymore.

**Comment by mrdoob** [comment]
Excellent!

**Comment by mrdoob** [comment]
Thanks!
