### PR TITLE
WebGPURenderer: WebGL viewport / scissors not working correctly with PostProcessing

### LINKED ISSUE #32882: WebGL viewport / scissors not working correctly with PostProcessing in WebGPURenderer
### Description

There seem to be issues when
1. `WebGPURenderer` is used in WebGL mode
2. A `PostProcessing` pipeline is used
3. `setScissor` / `setViewport` is setup

In below fiddle, I created a scene that should

1. Clear the whole screen with red
2. Draw a fullscreen blue quad, where the draw call is using a `setScissor` / `setViewport` to scissor it to the center of the screen

Under WebGPU everything is working as expected:

Image

Under WebGL (`forceWebGL = true`) the screen becomes white and the rectangle gets much smaller:

Image

This only happens if a `PostProcessing` pipeline is used

### Reproduction steps

1. Open the fiddle
2. See the correct rendering under WebGPU
3. Switch `forceWebGL` to `true`
4. See the wrong rendering under WebGL

### Code

See below fiddle

### Live example

* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/TobiasNoell/gryntx16/)

### Screenshots

_No response_

### Version

r182

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by TobiasNoell**
Fixed #32882

**Description**

When using `PostProcessing` with the WebGL backend (`forceWebGL: true`), viewport and scissor settings were incorrectly applied during nested render calls, causing rendered content to appear smaller than expected.

Root cause: In WebGL, scissor state is global. When `PassNode` renders the scene to a render target (triggering a nested `renderer.render()` call), the `beginRender` method didn't reset the scissor when `renderContext.scissor` was `false`. This left the outer scissor active, causing the render target to only receive content within the outer scissor area.

Fix in `WebGLBackend.js`:

In `beginRender`: Added else clause to reset scissor to the full render area when `renderContext.scissor` is `false
`
In `finishRender`: Added scissor state restoration (matching the existing viewport restoration pattern)
This ensures proper scissor state isolation between nested render calls, matching WebGPU's per-render-pass state model.

### CODE REVIEW

File: src/renderers/webgl-fallback/WebGLBackend.js [hunk 1]
```diff
@@ -450,6 +450,10 @@ class WebGLBackend extends Backend {
 
 			state.scissor( x, renderContext.height - height - y, width, height );
 
+		} else {
```
Comment (Mugen87) [inline src/renderers/webgl-fallback/WebGLBackend.js:451]: Can you use the new `updateScissor()` in the above if statement as well?

File: src/renderers/webgl-fallback/WebGLBackend.js [hunk 2]
```diff
@@ -450,6 +450,10 @@ class WebGLBackend extends Backend {
...
+
+			state.scissor( 0, 0, renderContext.width, renderContext.height );
```
Comment (Mugen87) [inline src/renderers/webgl-fallback/WebGLBackend.js]: Why not using 
```js
const { width, height } = this.getDrawingBufferSize();
state.scissor( 0, 0, width, height );
```

File: src/renderers/webgl-fallback/WebGLBackend.js (hunk 1 above)
Comment (TobiasNoell) [reply src/renderers/webgl-fallback/WebGLBackend.js:451]: Fixed

File: src/renderers/webgl-fallback/WebGLBackend.js (hunk 2 above)
Comment (TobiasNoell) [reply src/renderers/webgl-fallback/WebGLBackend.js]: Fixed

**Review by Mugen87 — APPROVED** [review]
I think scissor should be managed like viewport so this change looks good to me.
