### PR TITLE
WebGPURenderer: Align integer attribute check of WebGL backend.

### LINKED ISSUE #28898: WebGPURenderer error loading GLTF
### Description

When I load my glb file with THREE.WebGLRenderer, the console gets an error and doesn't show up, while WebGLRenderer works fine
Snipaste_2024-07-17_08-34-32

My glb file
[glb.zip](https://github.com/user-attachments/files/16257850/glb.zip)

### Reproduction steps

1.When I load my glb file using THREE.WebGLRenderer, the glb shows up normally.
2.After switching to WebGPURenderer, glb is not displayed and the console reports an error.

### Code

Normal：
```js
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>THREE.js Parallel Light Shadows</title>
    <style>
        body {
            margin: 0;
        }

        canvas {
            display: block;
        }
    </style>
</head>
<body>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/three@0.128/examples/js/loaders/GLTFLoader.js"></script>
</head>

<script>
    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(75, window.innerWidth / window.innerHeight, 0.1, 1000);
    const renderer = new THREE.WebGLRenderer();
    renderer.setSize(window.innerWidth, window.innerHeight);
    document.body.appendChild(renderer.domElement);
    const directionalLight = new THREE.DirectionalLight(0xffffff, 10);
    // 半球光.
    const fillLight = new THREE.HemisphereLight(0xffffff, 0xffffff, 1);
    scene.add(directionalLight);
    scene.add(fillLight);
    const loader = new THREE.GLTFLoader();
    loader.load(
        'http://192.168.1.37:5173/assets/gltfs/nvyishenghunhe.glb', // 替换为你的 GLB 文件的 URL
        function (gltf) {
            const model = gltf.scene;
            scene.add(model);
            animate(); // Start the animation loop once the model is loaded
        },
        function (xhr) {
            console.log((xhr.loaded / xhr.total * 100) + '% loaded');
        },
        function (error) {
            console.error('An error happened', error);
        }
    );

    const helper = new THREE.CameraHelper(directionalLight.shadow.camera);
    scene.add(helper);


    camera.position.set(0, 0, 5);
    camera.lookAt(0, 0, 0);

    // Animation loop
    function animate() {
        requestAnimationFrame(animate);

        renderer.render(scene, camera);
    }

    animate();
</script>
</body>
</html>

```
nor

### Screenshots

_No response_

### Version

0.166.1

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #28898.

**Description**

This PR aligns the WebGL backend of `WebGPURenderer` to `WebGLRenderer` when deciding whether buffer data are integer or not.

Only `gl.INT` or  `gl.UNSIGNED_INT` are integer data input or when `attribute.gpuType` is set to `IntType`.

https://github.com/mrdoob/three.js/blob/98341133faa4ebfebb71fbc870099f7c99b9ce34/src/renderers/webgl/WebGLBindingStates.js#L345

### CODE REVIEW

**Comment by Mugen87** [comment]
https://github.com/mrdoob/three.js/blob/98341133faa4ebfebb71fbc870099f7c99b9ce34/src/renderers/webgl/WebGLBindingStates.js#L345

Um, I think this policy can be changed. With WebGL 2 singed and unsigned int32 is also a valid input for float attributes in the shader. So maybe it's best to just change the line to:

```js
const integer = ( geometryAttribute.gpuType === IntType );
```

File: src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js [hunk 1]
```diff
@@ -476,7 +476,7 @@ ${ flowData.code }
 
 			const array = dataAttribute.array;
 
-			if ( ( array instanceof Uint32Array || array instanceof Int32Array || array instanceof Uint16Array || array instanceof Int16Array ) === false ) {
+			if ( ( array instanceof Uint32Array || array instanceof Int32Array || array instanceof Int16Array ) === false ) {
```
Comment (RenaudRohlinger) [inline src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js:479]: This just breaks `Uint16Array` support in the WebGL Backend. And now generate this kind of error:
```
[.WebGL-0x13000c4ea00] GL_INVALID_OPERATION: Vertex shader input type does not match the type of the bound vertex attribute.
```

 Are you sure about this one? /cc @Mugen87

Comment (Mugen87) [reply src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js:479]: This change was required to make compressed models work with the WebGL backend so I would say the previous approach was wrong.

Do you mind demonstrating with a fiddle how the error occurs?

In any event, the GLSL builder should only generate `iuvec*` if the `gpuType` is `IntType`  or when `Uint32Array` and `Int32Array` is used. In all other cases, the shader type should be float.
