### PR TITLE
OrbitControls: Introduce listenToKeyEvents().

### LINKED ISSUE #20805: OrbitControls keydown events not firing
**Describe the bug**

the keydown event is attached to the dom node as should be, but when you use the arrow keys no event is fired. I can see in the PR #17819 that you added the following code:

```js
if ( scope.domElement.tabIndex === -1 ) {
  scope.domElement.tabIndex = 0;
}
```

but in the latest release r123, this code is no longer there. If I re-add the code above the keydown events work as expected. After some digging I can see in #20617 this issue is known, but i've already written this bug so at least it's visible to others.

If I understand right, is it that the canvas isn't focussed so the keydown events don't fire? I'm happy to work on a PR to fix this.

**To Reproduce**

1. Go to - https://threejs.org/examples/?q=controls#misc_controls_orbit
2. try use the arrow keys

**Expected behavior**

The keydown events should fire moving the camera.

**Platform:**

 - Device: [Desktop, Mobile] desktop
 - OS: [Windows, MacOS, Linux, Android, iOS] macOS
 - Browser: [Chrome, Firefox, Safari, Edge] chrome/firefox
 - Three.js version: r123

### PR DESCRIPTION
**Pull request by Mugen87**
Related issue: Fixed #20805.

**Description**

See https://github.com/mrdoob/three.js/issues/20805#issuecomment-756913142. 

The internal event listener for `keydown` is now not set automatically anymore. Instead, `listenKeyEvents()` has to be called with a proper target for key events (e.g. `window`).

### CODE REVIEW

**Comment by Mugen87** [comment]
https://raw.githack.com/Mugen87/three.js/dev44/examples/misc_controls_orbit.html

File: examples/js/controls/OrbitControls.js [hunk 1]
```diff
@@ -79,6 +76,9 @@ THREE.OrbitControls = function ( object, domElement ) {
 	this.position0 = this.object.position.clone();
 	this.zoom0 = this.object.zoom;
 
+	// the target DOM element for key events
+	this._domElementKeyEvents = null;
```
Comment (mrdoob) [inline examples/js/controls/OrbitControls.js:80]: Hmm, does it need to be public?

Comment (Mugen87) [reply examples/js/controls/OrbitControls.js:80]: The object needs to be accessible in `dispose()`. With the current structure of `OrbitControls` (and also when using classes), I don't think there is another solution.

File: examples/misc_controls_orbit.html [hunk 2]
```diff
@@ -51,6 +51,7 @@
 				// controls
 
 				controls = new OrbitControls( camera, renderer.domElement );
+				controls.listenKeyEvents( window );
```
Comment (WestLangley) [inline examples/misc_controls_orbit.html:54]: Users copy these examples. I'd add a comment to make it clear that this is optional.
```js
controls.listenKeyEvents( window ); // optional
```

Comment (WestLangley) [reply examples/misc_controls_orbit.html]: Maybe rename to `.listenForKeyEvents()` -- or `.listenToKeyEvents()`.

Or just `.enableKeyEvents()`.

Comment (mrdoob) [reply examples/misc_controls_orbit.html]: Renaming to `.listenToKeyEvents()` sounds good to me 👍

@Mugen87 do you mind updating the PR?

Comment (Mugen87) [reply examples/misc_controls_orbit.html]: Updated the PR 🙌 .

**Comment by mrdoob** [comment]
Thanks!

**Comment by GabbyLin** [comment]
Hello,
I use `listenToKeyEvents`, but I find it cannot restrict like mouse event.
If I use followinf setting:
```
var orbit = new THREE.OrbitControls(camera, renderer.domElement);
orbit.listenToKeyEvents(window);
orbit.maxPolarAngle = 1.7;
orbit.minPolarAngle = 1.4;
orbit.maxAzimuthAngle = 0.4;
orbit.minAzimuthAngle = -0.4;
```
It cannot work when I use arrow keys.
Is any solution could handle it?

**Comment by WestLangley** [comment]
@GabbyLin Please use https://discourse.threejs.org for help questions.

**Comment by 731942771** [comment]
version **r132**. 
`
　var orbit = new THREE.OrbitControls(camera, renderer.domElement);        
　orbit.listenToKeyEvents(renderer.domElement);      
`
it dos't work.  
can't find "**enableKeys**" in OrbitControls.js .

**Comment by Mugen87** [comment]
The [official example](https://threejs.org/examples/misc_controls_orbit) uses the above pattern to create the controls. Do you mind demonstrating the error with a live example based on the demo's code?

**Comment by 731942771** [comment]
> The [official example](https://threejs.org/examples/misc_controls_orbit) uses the above pattern to create the controls. Do you mind demonstrating the error with a live example based on the demo's code?

my bad. I missed a sentence `this.controls.listenToKeyEvents(window);`
