### PR TITLE
WebGPURenderer: Fix shadow layers

### LINKED ISSUE #28438: WebGPURenderer: wrong layers testing in `AnalyticLightNode`
### Description

The `AnalyticLightNode` should test the scene camera layers property instead of the current shadow camera layers property (`light.shadow.camera.layers` in `_renderScene`).

We could introduce a `renderer._cameraLayersOverride` property or a getter/setter just like `_renderObjectFunction` (the latter being overkill in my opinion).

The main issue I currently have is that in updateShadow, if we use `frame.camera` as the reference and there are multiple lights casting shadows in the scene, the next value of `frame.camera `won't be the actual camera of the scene anymore but the previous Orthographic shadow camera from the previous light.
```js

renderer._cameraLayersOverride = camera.layers;

renderer.setRenderObjectFunction( ( object, ...params ) => {

	if ( object.castShadow === true ) {

		renderer.renderObject( object, ...params );

	}

} );
```
/cc @sunag

### Reproduction steps

in `webgpu_shadowmap.html` add `camera.layers.enableAll()`, then `pillar1.layers.set( 2 );` and no shadow pillar will be visible in the scene as it should.

### Version

r164

### PR DESCRIPTION
**Pull request by sunag**
Related issue: Closes https://github.com/mrdoob/three.js/issues/28438

**Description**

This fix prioritizes `camera.layers` during the renderer shadows instead of using the layers independently.

### CODE REVIEW

File: examples/jsm/nodes/lighting/AnalyticLightNode.js [hunk 1]
```diff
@@ -191,6 +191,7 @@ class AnalyticLightNode extends LightingNode {
 		rtt.setSize( light.shadow.mapSize.width, light.shadow.mapSize.height );
 
 		light.shadow.updateMatrices( light );
+		light.shadow.camera.layers.mask = camera.layers.mask;
```
Comment (RenaudRohlinger) [inline examples/jsm/nodes/lighting/AnalyticLightNode.js:194]: I like a lot this solution, currently the `WebGLRenderer` only relies on the main camera and never care about the `shadowCamera.layers`:
https://github.com/mrdoob/three.js/blob/b38ef166c7ed9efa1cac71b4fd16d0e168079ad7/src/renderers/webgl/WebGLShadowMap.js#L335
but I believe this new solution is as good if not better!

Comment (sunag) [reply examples/jsm/nodes/lighting/AnalyticLightNode.js:194]: An interesting point about WebGPURenderer is that we do not have a shadow class directly linked to the core, but it is part of the Node class integrated with the lights, allowing different approaches to shadow rendering as extensions.
