### PR TITLE
WebGPURenderer: Fix `compileAsync()` with target scenes.

### LINKED ISSUE #32523: WebGPURenderer: compileAsync ignores the target scenes fogNode
### Description

[Renderer.compileAsync](https://threejs.org/docs/#Renderer.compileAsync) is advertised as asynchronously compiling materials. It actually does this only partially as some settings from the target scene aren't handled. One if them is `Scene.fogNode` and consequentially also `Scene.fog`. If the material is then later used it includes the fogNode and everything compileAsync did is obsolete. Without fog in the target scene it works as intended. `Scene.environment` is affected the same way.

There is some special handling for lights by including them from the target scene. Something like this might be necessary here too.

### Reproduction steps

1. Use the WebGL backend. `WebGPURenderer({ forceWebGL: true })`
2. Have a scene with fogNode.
3. Watch `WebGLBackend._completeCompile` with a breakpoint.
4. Use `await renderer.compileAsync(object, camera, targetScene)`.
5. Add object to scene.
6. Observe `WebGLBackend._completeCompile` being called twice for the same object and material.

### Code

```js
// code goes here
```

### Live example

https://jsfiddle.net/Ljskxp1d/

### Screenshots

_No response_

### Version

0.181.2

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #32523.

**Description**

When `compileAsync()` is used with a target scene, the background must be updated with this scene to honor the respective fog, environment and background settings. Unlike with lights, background settings can not be additive. Meaning `compileAsync()` must update the background either with scene to compile _or_ the target scene.

### CODE REVIEW

File: src/renderers/common/Renderer.js [hunk 1]
```diff
@@ -930,7 +931,15 @@ class Renderer {
 
 		//
 
-		this._background.update( sceneRef, renderList, renderContext );
+		if ( targetScene !== scene ) {
```
Comment (Mugen87) [inline src/renderers/common/Renderer.js:934]: @sunag  This new code block makes sure the correct scene reference is used but it turned out that precompiling scene's with environment maps as backgrounds did not work in general with `WebGPURenderer`. 

The root cause is `this._handleObjectFunction`. This function is overwritten in `compileAsync()` with a stripped down version of `_renderObjectDirect()` that just prepares resources like bindings and pipelines for rendering.  However, when 3D objects perform nested renderings like the background mesh, the override of `this._handleObjectFunction` breaks the related rendering. Meaning the background is unable to convert the equirect env map to a cube map. 

I have changed the renderer such that `this._handleObjectFunction` does not apply to nested rendering. It is always resetted to `_renderObjectDirect()` in `renderScene()`.
