### PR TITLE
GLTFExporter: Add support for signed data types.

### LINKED ISSUE #20474: GLTFExporter: Add support for KHR_mesh_quantization.
In the past, my model was compressed with draco, and it was displayed on the web page normally, and it was also normal to export the file with GLTFExporter. However, due to the draco compressed model, the decompression speed is relatively slow, and the display is no problem if it is changed to GLTFPACK compression. But when I want to export the page, I am prompted that the bufferAttribute component type is not supported.

```js
var loader = new THREE.GLTFLoader();
loader.setMeshoptDecoder(MeshoptDecoder);
loader.load(model_path, function(gltf) {
theModel = gltf.scene;
theModel.position.y = -1.2;
modelg.add(theModel);
});
var urlsave = ‘http://192.168.101.113:8080/customProduct/saveCustomProduct’;
var qhxhr = new XMLHttpRequest();
qhxhr.open(‘POST’, urlsave, true);
var blobfile = null;
var fdata = new FormData();

var btnsave = document.getElementById(‘savejm’);
btnsave.addEventListener(‘click’, saves);
function saves() {
var exporter3D = new THREE.GLTFExporter();
exporter3D.parse(modelg, function(glbfile) {
if (glbfile instanceof ArrayBuffer) {
saveArrayBuffer(glbfile, ‘customize1.glb’);
} else {
var scenejson = JSON.stringify(glbfile, null, 2);
saveString(scenejson, ‘customize.glb’);
};
}, binary = true, onlyVisible = true );
};
function saveString(text, filename) {

  save(new Blob([text], {
  	type: 'text/plain'
  }), filename);
};
function saveArrayBuffer(buffer, filename) {
save(new Blob([buffer], {
type: ‘application/octet-stream’
}), filename);
};
function save(blob, filename) {
fdata.append(‘file’, blob, ‘customize.glb’);
qhxhr.upload.addEventListener(“progress”, function(result) {
if (result.lengthComputable) {
var percent = (result.loaded / result.total * 100).toFixed(2);
console.log(percent);
}
}, false);
qhxhr.send(fdata);
console.log(“ff”);
};
```

Hope to support bufferAttribute component type in GLTFExporter.

微信截图_20201008112427

### LINKED ISSUE #25310: `GLTFExporter` is missing support for attributes with `BYTE` and `SHORT` items
### Description

If you try to run the `GLTFExporter` on a mesh whose geometry contains `Int8Array`s or `Int16Array`s, it will crash with the error `THREE.GLTFExporter: Unsupported bufferAttribute component type`.

This doesn't seem too hard to fix - just a few missing `if` statements (I'll submit a PR soon). (Although it will be very rare that an `Int8Array` actually gets exported to a valid glTF file anyway until #25309 is fixed)

### Reproduction steps

1. Create a mesh whose geometry contains an attribute of type `Int8Array` or `Int16Array`
2. Export that mesh with the `GLTFExporter`
3. Enjoy failure

### Code

```js
const geom = new THREE.BufferGeometry()
geom.setAttribute(
  'position',
  new THREE.BufferAttribute(new Float32Array([0, 0, 0, 1, 0, 0, 0, 1, 0]), 3)
)
geom.setAttribute('uv', new THREE.BufferAttribute(new Int8Array([0, 0, 1, 0, 0, 1]), 2))

const mesh = new THREE.Mesh(geom)

const exporter = new GLTFExporter()
exporter.parse(
  mesh,
  data => {
   console.log('success')
  },
  err => {
   console.log('error', JSON.stringify(err))
  },
  { binary: false }
)
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/kyr6owb4/)

### Screenshots

_No response_

### Version

r148

### Device

Desktop

### Browser

Firefox

### OS

MacOS

### PR DESCRIPTION
**Pull request by spearwolf**
Fixed #20474
Fixed #25310

**Description**

Within the GLTFExporter only the buffer attributes types `float`, `uint`, `ushort` and `ubyte` are supported.
All other types cancel the export with an error: `An error happened during parsing Error: THREE.GLTFExporter: Unsupported bufferAttribute component type.`

What is missing are the _signed_ data types: `byte`, `short` and `int`. These are also valid data types according to the [KHR_mesh_quantization](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_mesh_quantization/README.md#extending-mesh-attributes) extension.

With this fix the _signed_ data types are now also supported in the GLTFExporter.

This will allow the export of meshes that have already been quantized (e.g. with tools like [gltf-transform](https://github.com/donmccurdy/glTF-Transform)):
- try https://github.com/mrdoob/three.js/issues/20474#issuecomment-706741550

### CODE REVIEW

**Comment by LeviPesin** [comment]
Related: https://github.com/mrdoob/three.js/pull/20762

**Comment by donmccurdy** [comment]
Thanks @spearwolf! 

> These are also valid data types according to the [KHR_mesh_quantization](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_mesh_quantization/README.md#extending-mesh-attributes) extension.

I think we'll need to detect when these types are used, and add the `KHR_mesh_quantization` extension to the export. Do you mind including that change here as well?

**Comment by Mugen87** [comment]
Yeah, https://github.com/mrdoob/three.js/pull/20762 was closed since `KHR_mesh_quantization` wasn't added at that time and without the extensions the PR was incomplete.

**Comment by spearwolf** [comment]
ok, I added a simple check that adds the `KHR_mesh_quantization` extension to the required (and used) list when non-standard vertex attribute data types are used 🕵🏻

File: examples/jsm/exporters/GLTFExporter.js [hunk 1]
```diff
@@ -1550,6 +1602,12 @@ class GLTFWriter {
 
 			if ( accessor !== null ) {
 
+				if ( isValidVertexAttribute ) {
```
Comment (donmccurdy) [inline examples/jsm/exporters/GLTFExporter.js:1605]: nit: do you mind removing the new `isValidVertexAttribute` variable, and instead testing `attributeName.startsWith( '_' )` here? A bit more concise, and I kind of regret our using the word "valid", as custom attributes are still valid.

File: examples/jsm/exporters/GLTFExporter.js [hunk 2]
```diff
@@ -1730,6 +1788,55 @@ class GLTFWriter {
...
+			} else if ( attributeName.startsWith( 'TEXCOORD_' ) ) {
+
+				const isUnsignedByte = attribute.array.constructor === Uint8Array;
+				const isUnsignedShort = attribute.array.constructor === Uint16Array;
+
+				if ( ! ( attribute.normalized && ( isUnsignedByte || isUnsignedShort ) ) ) {
+
+					useMeshQuantization = true;
+
+				}
```
Comment (donmccurdy) [inline examples/jsm/exporters/GLTFExporter.js:1825]: I think it'd be clearer if we checked what the array is, rather than what it is not, here — perhaps:

```javascript
if ( attribute.normalized && ( isByte || isShort ) ) {

  useMeshQuantization = true;

}
```

File: examples/jsm/exporters/GLTFExporter.js [hunk 3]
```diff
@@ -1730,6 +1788,55 @@ class GLTFWriter {
...
+	 * @param {string} attributeName
+	 * @param {THREE.BufferAttribute} attribute
+	 */
+	detectMeshQuantization( attributeName, attribute ) {
+
+		if ( this.extensionsUsed[ KHR_MESH_QUANTIZATION ] ) return;
+
+		let useMeshQuantization = false;
+
+		const isNonFloatAttribute = attribute.array.constructor !== Float32Array;
```
Comment (donmccurdy) [inline examples/jsm/exporters/GLTFExporter.js:1808]: To avoid adding KHR_mesh_quantization for assets with vertex attributes that aren't valid under _both_ the core spec and the extension, perhaps we should check that the component size is <= 2 here, instead of checking against float32? Hoping rule out uint32 and int32 types as well.

**Review by donmccurdy — COMMENTED** [review]
A couple bits of feedback, but would love to get this merged in soon – thank you!

File: examples/jsm/exporters/GLTFExporter.js (hunk 1 above)
Comment (spearwolf) [reply examples/jsm/exporters/GLTFExporter.js]: added an extra variable here to keep the readability and the intension of the code simple at this point (it's not immediately obvious why the name is checked for a _ prefix here), but i'm fine with the adjustment too - so it is one variable less 😉

File: examples/jsm/exporters/GLTFExporter.js (hunk 2 above)
Comment (spearwolf) [reply examples/jsm/exporters/GLTFExporter.js]: absolutely agree with you that a negation is difficult to understand here, but a positive formulation would have to cover much more cases and thus become more complex. so i have rethought the whole thing in detail and reworked the check as a whole.... hope it is more readable this way, in any case it is more correct and strictly adheres to the specification of the KHR_mesh_quantization extension

File: examples/jsm/exporters/GLTFExporter.js (hunk 3 above)
Comment (spearwolf) [reply examples/jsm/exporters/GLTFExporter.js]: see https://github.com/mrdoob/three.js/pull/25297#discussion_r1089028220

**Comment by spearwolf** [comment]
@donmccurdy so have your feeback implemented - hope it fits so

**Review by donmccurdy — APPROVED** [review]
Thank you!

Tested with https://github.com/mrdoob/three.js/pull/25354.
