### PR TITLE
Box3: Fixed bug in .intersectsPlane().

### LINKED ISSUE #14834: box3.intersectsPlane bug
In the following example, the plane obviously intersects with the box, but the function intersectsPlane returns false.
[example](https://jsfiddle.net/rn6jzdub/4/)
I find that adding two negative sign before both of the plane.constant can fix the bug.
https://github.com/mrdoob/three.js/blob/c570b9bd95cf94829715b2cd3a8b128e37768a9c/src/math/Box3.js#L387
Also, I think the definition of the constant of the plane is not distinct, which cause the bug.

##### Three.js version

- [x] Dev
- [x] r96
- [x] ...

##### Browser

- [x] All of them

##### OS

- [x] All of them

### PR DESCRIPTION
**Pull request by shyf1301**
add two negative sign before both of the plane.constant and update the unit test

Fixes #14834

### CODE REVIEW

File: src/math/Box3.js [hunk 1]
```diff
@@ -384,7 +384,7 @@ Object.assign( Box3.prototype, {
 
 		}
 
-		return ( min <= plane.constant && max >= plane.constant );
+		return ( min <= -plane.constant && max >= -plane.constant );
```
Comment (Mugen87) [inline src/math/Box3.js]: Please insert a space after the signs. Otherwise the linter won't be happy...

**Review by Mugen87 — CHANGES_REQUESTED** [review]

File: src/math/Box3.js (hunk 1 above)
Comment (shyf1301) [reply src/math/Box3.js]: Thank you for your remind. Whitespaces added.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!
