### PR TITLE
HTMLMesh: Add image support.

### LINKED ISSUE #25655: Unable to add image + text to HTML Mesh
### Description

Hi,

I'm trying to embed some HTML containing both images and text into HTML Mesh and adding the group to a scene. But so far only texts appear in the mesh, not images. Does HTML Mesh support embedding images? 

Thank You!

### Reproduction steps

1. Create an HTML element containing images and text
2. Create an HTML mesh object using new HTMLMesh()
3. Add mesh to scene

### Code

```js
const group = new InteractiveGroup( renderer, camera );
scene.add( group );
const test = document.querySelector('#test')
const htmlMesh = new HTMLMesh(test)
htmlMesh.scale.setScalar(10)
htmlMesh.position.set(-2, 0, 0)
group.add(htmlMesh)
```

### Live example

* [jsfiddle-dev](https://jsfiddle.net/jcy089/vhu8kmzt/4/)

### Screenshots

2023-03-11 at 11 48 41

### Version

r137

### Device
Mac

### Browser
Safari

### OS
Mac OS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #25655.

**Description**

Instances of `HTMLImageElement` are now honored by `HTMLMesh`.

### CODE REVIEW

File: examples/jsm/interactive/HTMLMesh.js [hunk 1]
```diff
@@ -273,6 +273,12 @@ function html2canvas( element ) {
 			context.drawImage( element, 0, 0 );
 			context.restore();
 
+		} else if ( element instanceof HTMLImageElement ) {
+
+			if ( element.style.display === 'none' ) return;
+
+			context.drawImage( element, 0, 0, element.width, element.height );
```
Comment (LeviPesin) [inline examples/jsm/interactive/HTMLMesh.js:280]: Shouldn't this be `buildRectPath( x, y, width, height, 2 ); context.drawImage( element, x, y, element.width, element.height );`, as in https://github.com/mrdoob/three.js/pull/24043?

Comment (Mugen87) [reply examples/jsm/interactive/HTMLMesh.js:280]: I think it's less confusing to just draw the image and not an additional path.

Comment (vincentfretin) [reply examples/jsm/interactive/HTMLMesh.js:280]: Having `0, 0` here will always draw the image starting on the left top corner. That's definitely not my use case.
I'm using a variant of the above, this:
```js
		} else if ( element instanceof HTMLImageElement ) {

			if ( element.style.display === 'none' ) return;

			const rect = element.getBoundingClientRect();

			x = rect.left - offset.left - 0.5;
			y = rect.top - offset.top - 0.5;
			width = rect.width + 0.5;
			height = rect.height + 0.5;
			
			context.drawImage( element, x, y, width, height );
		} else {
```

It works great for my use case of having a wrist UI to change the texture of a furniture.
Here is the screenshot from chrome, but that's exactly the same render in VR:
Capture d’écran du 2023-04-24 16-55-47

Do you want me to create a PR with those changes?

cc @msub2

Comment (vincentfretin) [reply examples/jsm/interactive/HTMLMesh.js:280]: PR created https://github.com/mrdoob/three.js/pull/25916
