### PR TITLE
WebGLState: fix clear color bug

### LINKED ISSUE #11001: Setting clearColor to black doesn't work if sprites are in scene
##### Description of the problem 

If Sprites are in the scene, the clear color cannot be changed back to black

http://jsfiddle.net/ak35o645/7/

uncomment out the //scene.add( sprite ); to see bug

##### Three.js version

- [ X ] Dev
- [ X ] r84

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #11001 and related issues discussed in the thread.

Sets the initial value of `currentClearColor` to be consistent with the default gl clear color.

On reset, sets the current value to an invalid value, as is done with the other current values.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

File: src/renderers/webgl/WebGLState.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ function WebGLState( gl, extensions, paramThreeToGL ) {
 
 		var color = new Vector4();
 		var currentColorMask = null;
-		var currentColorClear = new Vector4();
+		var currentColorClear = new Vector4( 0, 0, 0, 0 );
```
Comment (mrdoob) [inline src/renderers/webgl/WebGLState.js]: Oh my... Sorry 😣

**Comment by mrdoob** [comment]
Thanks!

File: src/renderers/webgl/WebGLState.js (hunk 1 above)
Comment (WestLangley) [inline src/renderers/webgl/WebGLState.js]: This is a gotcha, IMO.

I think it would be better to default `Vector4` to all zeros. We have a separate `Quaternion` class for representing rotations, for which setting the w-component to 1 makes sense.

Also, a `Vector4` instance can represent something other than a homogeneous coordinate (another example for which setting `w` to 1 makes sense.)
