### PR TITLE
ShadowNode: Fix shadows in first frame.

### LINKED ISSUE #31925: WebGPU: The shadow cannot be displayed correctly in the first frame. The second frame must be rendered for it to be displayed normally
### Description

Why doesn't the shadow appear properly in the first frame?

example:

https://jsfiddle.net/dzu5mqos/

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/mnqr9oj0/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/xno7bmw0/)

### Screenshots

_No response_

### Version

0.180.0

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #31925.

**Description**

The PR makes sure shadows are rendered correctly in the first frame for the WebGPU backend.

The root cause was a wrong shadow matrix uniform that was always computed in the WebGL coordinate system. That's why the WebGL backend wasn't affected. In the second frame, the coordinate system was correctly set by the renderer. Too late for the initial uniform update though.

Many thanks to @greggman for the valuable help in #31925 🙌 . Besides, the results of [WebGPU Recorder](https://github.com/brendan-duncan/webgpu_recorder) made it much easier to pinpoint the root cause. Very useful tool!

### CODE REVIEW

File: src/nodes/accessors/Lights.js [hunk 1]
```diff
@@ -32,6 +32,9 @@ export function lightShadowMatrix( light ) {
 
 	return data.shadowMatrix || ( data.shadowMatrix = uniform( 'mat4' ).setGroup( renderGroup ).onRenderUpdate( ( frame ) => {
 
+		// normally, shadow matrices are updated in ShadowNode. However, if the shadow matrix is used outside
+		// of shadow rendering (like in ProjectorLightNode), the shadow matrix still requires an update.
```
Comment (Mugen87) [inline src/nodes/accessors/Lights.js:36]: Just an additional comment to clarify the below update.

File: src/nodes/accessors/Lights.js [hunk 2]
```diff
@@ -32,8 +32,18 @@ export function lightShadowMatrix( light ) {
 
 	return data.shadowMatrix || ( data.shadowMatrix = uniform( 'mat4' ).setGroup( renderGroup ).onRenderUpdate( ( frame ) => {
 
+		// normally, shadow matrices are updated in ShadowNode. However, if the shadow matrix is used outside
+		// of shadow rendering (like in ProjectorLightNode), the shadow matrix still requires an update
+
 		if ( light.castShadow !== true || frame.renderer.shadowMap.enabled === false ) {
 
+			if ( light.shadow.camera.coordinateSystem !== frame.camera.coordinateSystem ) {
```
Comment (Mugen87) [inline src/nodes/accessors/Lights.js:40]: The problem is we can't fix the projection matrix in `LightShadow.updateMatrices()` because there is no reference to the coordinate system. So all callers of `LightShadow.updateMatrices()` must ensure the shadow camera's projection matrix is correct.
