### PR TITLE
GLTFLoader: Honor Firefox version when checking for ImageBitmap.

### LINKED ISSUE #23906: ImageBitmapLoader (GLTFLoader) fails in Firefox ESR
**Describe the bug**

GLTF models don´t load in Firefox ESR due to lack of support for ImageBitLoader. 

**To Reproduce**

1. Install Firefox ESR (version number 91) from https://www.mozilla.org/en-GB/firefox/all/#product-desktop-esr
2. Open https://www.geofront.eu/tmp/ironmen_bugreport_fail
3. GLTF model is not being loaded. See also error: THREE.GLTFLoader: Couldn´t load texture tex.webp 

***Code***

The problem lies in the removal of a check for Firefox to avoid usage of ImageBitmapLoader (compare r130). 
The most recent Firefox version works fine with this - but Firefox ESR (used internally in the museum that has published this webpage) is not yet capable of handling ImageBitmapLoader. 
We therefore suggest an additional check for Firefox and its ESR-channel version number 91 in this code snippet of GLTFLoader.js: 

```js
 if ( typeof createImageBitmap !== 'undefined' && /^((?!chrome|android).)*safari/i.test( navigator.userAgent ) === false  && /Firefox\/91/.test( navigator.userAgent ) === false) {
this.textureLoader = new ImageBitmapLoader( this.options.manager );
} else {
this.textureLoader = new TextureLoader( this.options.manager );
}

```

Note: This will have to be extended to later Firefox ESR versions (we did not track down the exact version where Firefox´ ImageBitmapLoader starts working). 

***Live example***

* Fail:  https://www.geofront.eu/tmp/ironmen_bugreport_fail
* Fixed: https://www.geofront.eu/tmp/ironmen_bugreport_fixed

**Expected behavior**

The GLTF should have loaded and displayed, just like in Firefox 99. 

**Platform:**

 - Device: Desktop
 - OS: Windows
 - Browser: Firefox ESR release 91.8.0esr (64-bit) https://support.mozilla.org/en-US/kb/firefox-esr-release-cycle
 - Three.js version: r139

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #23906.

**Description**

Only use `ImageBitmapLoader` when the version of Firefox is => 98.

### CODE REVIEW

File: examples/jsm/loaders/GLTFLoader.js [hunk 1]
```diff
@@ -2315,7 +2315,7 @@ class GLTFParser {
 
 		// Use an ImageBitmapLoader if imageBitmaps are supported. Moves much of the
 		// expensive work of uploading a texture to the GPU off the main thread.
-		if ( typeof createImageBitmap !== 'undefined' && /^((?!chrome|android).)*safari/i.test( navigator.userAgent ) === false ) {
+		if ( typeof createImageBitmap !== 'undefined' && /^((?!chrome|android).)*safari/i.test( navigator.userAgent ) === false && navigator.userAgent.match( /Firefox\/([0-9]+)\./ )?.[ 1 ] < 98 === false ) {
```
Comment (donmccurdy) [inline examples/jsm/loaders/GLTFLoader.js:2318]: Could we do this without `?.` optional chaining?

**Review by donmccurdy — COMMENTED** [review]
Didn't we have code in ImageBitmapLoader to feature-detect support, at one point? Did that just not work because failure cases in Firefox were hard to detect? 

Fine to keep UA-sniffing for now though, thanks!

File: examples/jsm/loaders/GLTFLoader.js (hunk 1 above)
Comment (Mugen87) [reply examples/jsm/loaders/GLTFLoader.js:2318]: I'll rewrite the check without optional chaining tomorrow 👍 . 

It's indeed more safe to avoid the syntax for now.

Comment (takahirox) [reply examples/jsm/loaders/GLTFLoader.js:2318]: I can understand that we want to write the version detection code short but `navigator.userAgent.match( /Firefox\/([0-9]+)\./ )?.[ 1 ] < 98 === false` might a little bit tricky especially for first readers? They may think why it isn't `navigator.userAgent.match( /Firefox\/([0-9]+)\./ )?.[ 1 ] >= 98`.

I know this detection code works fine because `navigator.userAgent.match( /Firefox\/([0-9]+)\./ )?.[ 1 ]` will be `undefined` on non-Firefox and `undefined < 98` will be `false`. But it took time a bit for me to understand.

(Sorry if my overthinking.)

And not a big preference, but personally I like adding a comment about likely when we can remove the version detection code https://github.com/mrdoob/three.js/issues/23906#issuecomment-1101405508

By the way I didn't know that numbers and strings can be compared in JavaScript.

Comment (Mugen87) [reply examples/jsm/loaders/GLTFLoader.js]: What do you think about the new version of the PR? Tried to make the check easier to read.

Comment (takahirox) [reply examples/jsm/loaders/GLTFLoader.js]: Much more straightforward, thanks.

Nit:

```
const isFirefox = navigator.userAgent.toLowerCase().indexOf( 'firefox' ) > - 1;
const firefoxVersion = isFirefox ? navigator.userAgent.match( /Firefox\/([0-9]+)\./ )[ 1 ] : - 1;
```
The first line uses `toLowerCase()` while the second line doesn't. I think it would be better to make them consistent unless there is any special reason.

Comment (Mugen87) [reply examples/jsm/loaders/GLTFLoader.js]: Good catch! Updated!

**Review by takahirox — APPROVED** [review]
Looking good, if it's ok for others to add a version detection code, too, thanks.

**Review by donmccurdy — APPROVED** [review]
Thank you! 🙏

**Comment by mrdoob** [comment]
Thanks!
