### PR TITLE
EXRLoader: handle unsupported BigInt Safari mobile

### LINKED ISSUE #23260: EXRLoader:  Throws error in r136 on iOS below 15.1
When loading a exr texture on iOS 14 or below the device throw a runtime error and prevent the texture from being loaded. 

The line that triggers the error: https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/EXRLoader.js#L2165 (if using DWA compression the error is also triggered during decoding pre r136) The change was added in this commit: https://github.com/mrdoob/three.js/commit/ab528acacdf43eadaf39709a17a46e8319428606

1. Load exr texture with any compression type
2. Build to device/webview or run in mobile Safari running iOS 14.x
3. See the following error: TypeError: t.getBigInt64 is not a function. (In 't.getBigInt64(e.value,!0)', 't.getBigInt64' is undefined)

**Expected behavior**
The loader should detect or workaround the missing support.

The current workaround is to downgrade to version 135 and use a different compression than DWAA or DWAB.

**Platform:**

 - Device: Mobile
 - OS: iOS
 - Browser: Safari, WebView
 - Three.js version: r136

### PR DESCRIPTION
**Pull request by sciecode**
Fixed #23260

Utilizes alternative Int64 handling when `DataView.prototype.getBigInt64` isn't available.

Also fixes a small mistake on my part on retrieving specification flags information, it should be properly reflecting the actual file information now.

[DWAA Example](https://rawcdn.githack.com/sciecode/three.js/8a20ad90238aaccdc0a07af0d2d1076d96712f5e/examples/webgl_loader_texture_exr.html) - @inear please validate the example loads correctly.

### CODE REVIEW

File: examples/jsm/loaders/EXRLoader.js [hunk 1]
```diff
@@ -1756,9 +1756,18 @@ class EXRLoader extends DataTextureLoader {
 
 		}
 
-		function parseInt64( dataView, offset ) {
+		const parseInt64 = function( dataView, offset ) {
 
-			var int = Number( dataView.getBigInt64( offset.value, true ) );
+			let int;
+
+			if ( DataView.prototype.getBigInt64 ) {
```
Comment (mrdoob) [inline examples/jsm/loaders/EXRLoader.js:1763]: Nit: We usually do `if ( 'getBigInt64' in DataView.prototype )`

Comment (sciecode) [reply examples/jsm/loaders/EXRLoader.js:1763]: Sure, will change.

**Comment by mrdoob** [comment]
Seems like this PR introduced a LGTM issue:
https://lgtm.com/projects/g/mrdoob/three.js/rev/f274b4464ebe9027c74918ea8ff7069b48360cf3

**Comment by sciecode** [comment]
Yeah. Right-side shift is supposed to be a BigInt shift operation, not integer. 

I'm working on a PR to implement Tiled EXR ( data generated mipmaps ), is ok if I ship the fix alongside that? I don't actually expect this to affect many people, as we only start needing the upper 32b if the users are loading 4K+ res images.
