### PR TITLE
WebGPURenderer: Persistent video texture approach

### LINKED ISSUE #31330: ProjectorLight : VideoTexture projected on multiple meshes fails with multiple "Destroyed texture" warnings
### Description

Modify webgpu_lights_projector.html to include multiple copies of the Lucy100k mesh. 
Procedural and Texture projections work fine. 
VideoTexture fails after a second or two. 

Warning:
```
Destroyed texture [Texture "D3DImageBacking_D3DSharedImage_CanvasResourceRaster_Pid:75204"] used in a submit.
 - While calling [Queue].Submit([[CommandBuffer from CommandEncoder "renderContext_0"]])
```

Thanks for the work on the ProjectorLight, it's exactly  what I need for a project I'm working on :) 

### Reproduction steps

1.Modify webgpu_lights_projector.html to include multiple copies of the Lucy100k mesh.
2. Run the example

### Code

```js
// Models

				new PLYLoader().load( 'models/ply/binary/Lucy100k.ply', function ( geometry ) {

					geometry.scale( 0.0024, 0.0024, 0.0024 );
					geometry.computeVertexNormals();

					const material = new THREE.MeshLambertMaterial();

					const mesh = new THREE.Mesh( geometry, material );
					mesh.rotation.y = - Math.PI / 2;
					mesh.castShadow = true;
					mesh.receiveShadow = true;
					
					for (let i = 0; i < 5; i++) {
						const copyOfMesh = mesh.clone();
						copyOfMesh.position.y=0.8;
						copyOfMesh.position.x=-i*1;
						scene.add( copyOfMesh);
                	}				

				} );
```
https://github.com/pmhn/three.js/tree/issue-31330-projector-light-live-example

### Live example

N/A

### Screenshots

_No response_

### Version

r177

### Device

Desktop

### Browser

Edge

### OS

Windows

### PR DESCRIPTION
**Pull request by sunag**
Closes https://github.com/mrdoob/three.js/issues/31330, https://github.com/mrdoob/three.js/pull/31397

**Description**

Replaces `texture_external` with a persistent texture using `copyExternalImageToTexture()` updating by `requestVideoFrameCallback` of `VideoTexture`, reusing all of the core's texture management, including sharing between materials, and adds support for vertex stage usage too.

@Mugen87 I think this is the best way, in addition to the benefits, it reduces the total code.

### CODE REVIEW

**Comment by Mugen87** [comment]
Yes, that sounds like a good solution 👍 .

Are parts of the PR missing though? I don't see any changes to `VideoTexture` or usage of `copyExternalImageToTexture()`?

**Comment by sunag** [comment]
Great, right? The current texture system was reused, and most things worked auto-magically.

**Comment by Mugen87** [comment]
Ah I see, the code goes now in the `WebGPUTextureUtils._copyImageToTexture()` branch. Neat!

File: src/renderers/webgpu/nodes/WGSLNodeBuilder.js [hunk 1]
```diff
@@ -219,7 +219,14 @@ class WGSLNodeBuilder extends NodeBuilder {
 	 */
 	needsToWorkingColorSpace( texture ) {
 
-		return texture.isVideoTexture === true && texture.colorSpace !== NoColorSpace;
```
Comment (Mugen87) [inline src/renderers/webgpu/nodes/WGSLNodeBuilder.js:222]: I think this bit isn't 100%. `needsToWorkingColorSpace()` was implemented as a workaround for video textures. Since they are now treated as all other textures in WebGPU, we can simply remove the method and use the one from `NodeBuilder` (which always returns `false`). 

This method should not affect normal textures.

**Comment by Mugen87** [comment]
It seems this PR broke `VideoFrameTexture` in `webgpu_video_frame` when using WebGPU. The WebGL backend works fine.

File: src/renderers/webgpu/nodes/WGSLNodeBuilder.js (hunk 1 above)
Comment (sunag) [reply src/renderers/webgpu/nodes/WGSLNodeBuilder.js:222]: `copyExternalImageToTexture()`  copy the video using srgb, this is a bypass because of the copy. You can test it through the example `webgpu_video_panorama`.

Comment (Mugen87) [reply src/renderers/webgpu/nodes/WGSLNodeBuilder.js:222]: The example looks good to me after removing this overwrite. Do I miss something on my side?

The colors in the TRAA example are now fixed again as well.

Comment (sunag) [reply src/renderers/webgpu/nodes/WGSLNodeBuilder.js:222]: Thanks for the fix.

**Comment by ycw** [comment]
This PR ensures "re-import external texture of `<video>` at most once per rAF", but  it doesn't ensure that destroyed texture must be re-imported once, how come is this fixing #31330?

**Comment by ycw** [comment]
This introduced copy overheads that would be hamstringed by LPDDR bandwidth in mobiles.

**Comment by Mugen87** [comment]
> This introduced copy overheads that would be hamstringed by LPDDR bandwidth in mobiles.

@greggman We were hoping to simplify our code base by not using `texture_external` and `importExternalTexture()` for video textures in `WebGPURenderer`. Instead the idea is to copy the video frame via `copyExternalImageToTexture()` and then treat it as a normal texture.

Does this approach via `copyExternalImageToTexture()` indeed introduce a performance issue?

**Comment by greggman** [comment]
> Does this approach via copyExternalImageToTexture() indeed introduce a performance issue?

I'm not really sure how to define "performance issue" 😛

copying is slower than not copying. `importExternalTexture` is designed to allow no copy. Conceptually you're directly using some external texture. That said, it's up to the implementation whether or not it lets you directly use some external texture or makes a temporary copy.

In Chrome, if you enable `webgpu-developer-features`, then `GPUExternalTexture` has a `isZeroCopy` boolean you can use to see if it's using the external texture directly or making a temporary copy. This is affected by platform/OS/gpu/video format.

`copyExternalImageToTexture` on the other hand, definitely always makes a copy. This is the same as `texImage2D(,,,, someElement)` which also always makes a copy. Whether either is fast (GPU based copy) or slow (CPU based copy) up to the implementation. That said, making a copy was your only option in WebGL and people have been using video there so it's not bad/wrong to use this path. And, as you discovered, it's easier and more flexible since you don't have to change any shaders.

**Comment by Mugen87** [comment]
Then I would say we keep the status quo and see how it performs in production. Maintaining a separate code path for video textures in the WebGPU backend was a bit of a pain and the new approach is so much more elegant.
