### PR TITLE
WebGPUBackend: Fix Depth Buffer

### LINKED ISSUE #26381: WebGPURenderer depth/stencil buffer duplication/confusion
### Description

When rendering to the screen in multiple passes, multiple depth buffers are created associated with the multiple render contexts created, combined with the use of current and last render contexts in the clear() call, this leads to unexpected results.

Is it a deliberate intention to have multiple depth buffers associated with the display buffer?

### Reproduction steps

With no render targets set and the following sequence in a render loop, the two clear calls do not have the expected effects.

1. renderer.clear();  // clears depth buffer B
2. renderer.render( sceneA, cameraA );  // render context (a) with depth buffer A
3. render.clearDepth();  // clears depth buffer A
4. renderer.render( sceneB, cameraB ); // render context (b) with depth buffer B

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

_No response_

### Version

154

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by sunag**
Related issue: Fixes https://github.com/mrdoob/three.js/issues/26381

**Description**

Fix the use of the same Depth Buffer used in different `RenderContext`.

### CODE REVIEW

File: examples/jsm/renderers/webgpu/WebGPUBackend.js [hunk 1]
```diff
@@ -753,63 +754,49 @@ class WebGPUBackend extends Backend {
 
 	_getDepthBufferGPU( renderContext ) {
 
-		const { depthBuffers } = this;
 		const { width, height } = this.getDrawingBufferSize();
 
-		let depthTexture = depthBuffers.get( renderContext );
+		const depthTexture = this.defaultDepthTexture;
```
Comment (LeviPesin) [inline examples/jsm/renderers/webgpu/WebGPUBackend.js:759]: Should we clone it here? Or is this unneeded?

Comment (sunag) [reply examples/jsm/renderers/webgpu/WebGPUBackend.js:759]: It's unneeded... I thought to add a cache to stencil/depth variations soon if needed too.
