### PR TITLE
LightsNode: Honor spotlight maps in cache key.

### LINKED ISSUE #30930: WebGPURenderer: Unable to remove map from SpotLight.
### Description

Removing a map assigned to a spot light triggers a runtime error:

> three.webgpu.js:26114 Uncaught TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at Textures.get (three.webgpu.js:26114:14)
    at Textures.updateTexture (three.webgpu.js:28797:28)
    at Bindings._update (three.webgpu.js:27704:20)
    at Bindings._updateBindings (three.webgpu.js:27606:9)
    at Bindings.updateForRender (three.webgpu.js:27593:8)
    at WebGPURenderer._renderObjectDirect (three.webgpu.js:52189:19)
    at WebGPURenderer.renderObject (three.webgpu.js:52128:9)
    at WebGPURenderer._renderObjects (three.webgpu.js:52043:9)
    at WebGPURenderer._renderScene (three.webgpu.js:50726:64)

I believe this happens since the renderer does not detect a new render object with a new node builder state is required in that case.

### Reproduction steps

1. Open https://threejs.org/examples/webgpu_lights_spotlight
2. Use the GUI to change the map to `null`.
3. Observe runtime error in browser console.

### Code

see live example

### Live example

https://threejs.org/examples/webgpu_lights_spotlight

Expected behavior visible in: https://threejs.org/examples/webgl_lights_spotlight

### Screenshots

_No response_

### Version

r175dev

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #30930.

**Description**

The existence of a spot light map must be honored in the dynamic light cache key which is computed per frame. Otherwise dynamic changes to a spot light like described in #30930 produce runtime errors.

### CODE REVIEW

File: src/nodes/lighting/LightsNode.js [hunk 1]
```diff
@@ -107,23 +107,31 @@ class LightsNode extends Node {
...
 		for ( let i = 0; i < lights.length; i ++ ) {
 
-			lightIDs.push( lights[ i ].id );
+			const light = lights[ i ];
+
+			hashData.push( light.id );
+
+			if ( light.isSpotLight === true ) {
+
+				hashData.push( Number( light.map !== null ) );
```
Comment (sunag) [inline src/nodes/lighting/LightsNode.js:128]: We may need to consider other texture data that needed to be recompiled if it changes.

Comment (Mugen87) [reply src/nodes/lighting/LightsNode.js:128]: If the user sets a material property that holds a texture to `null`, the user must set `material.needsUpdate` to `true`. However, this isn't doable for lights since it would be required to set `material.needsUpdate` to `true` for all  lit materials in the scene.

Hence, the code in `LightsNode` only needs to focus on light properties.

Comment (sunag) [reply src/nodes/lighting/LightsNode.js:128]: Hmm... my concern is the user changing from a `Texture` to a `VideoTexture` for example.

Comment (Mugen87) [reply src/nodes/lighting/LightsNode.js:128]: Does a video texture require a different kind of binding? If not, switching from one texture to another shouldn't be an issue.

In any event, textures have an `id` property as well so we could store it in the hash.

Comment (sunag) [reply src/nodes/lighting/LightsNode.js:128]: > Does a video texture require a different kind of binding? If not, switching from one texture to another shouldn't be an issue.

This will require a different gpu-program, consequently different bindings settings. `id` would make it more stable, and we can think about optimizing it later. an "id/hash" based on the type of texture would be ideal.

Comment (Mugen87) [reply src/nodes/lighting/LightsNode.js]: Okay, I added now the ID and use `-1` if not texture is set. That should make the hash more robust.
