### PR TITLE
Audio: Add checks for detune on audio buffer for Safari

### LINKED ISSUE #15566: audio play() fail at ios 12
##### Description of the problem
After my test, due to the addition of this line of code, the Google browser audio playback in ios (12.1) failed.(经过我测试,由于添加了这行代码,使得在ios(12.1) 的谷歌浏览器音频播放失败.)
file path is: `src/audio/Audio.js`
```js
source.detune.value = this.detune;
```

##### Three.js version

- [ ] Dev
- [x] r100
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome for iOS
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

### PR DESCRIPTION
**Pull request by ngokevin**
Fixes #15566

### CODE REVIEW

File: src/audio/Audio.js [hunk 1]
```diff
@@ -95,7 +95,13 @@ Audio.prototype = Object.assign( Object.create( Object3D.prototype ), {
 		var source = this.context.createBufferSource();
 
 		source.buffer = this.buffer;
-		source.detune.value = this.detune;
+
+		if ( source.detune ) {
```
Comment (WestLangley) [inline src/audio/Audio.js]: What if it is zero? Test for `undefined`?

File: src/audio/Audio.js [hunk 2]
```diff
@@ -228,6 +234,8 @@ Audio.prototype = Object.assign( Object.create( Object3D.prototype ), {
 
 		this.detune = value;
 
+		if ( !this.source.detune ) return;
```
Comment (WestLangley) [inline src/audio/Audio.js]: if ( ! this.source.detune ) return;

Comment (Mugen87) [reply src/audio/Audio.js]: I would log a warning in this case:
```js
console.warn( 'THREE.Audio: AudioBufferSourceNode.detune not supported by the browser.' );
```

```

Comment (Mugen87) [reply src/audio/Audio.js]: I would add a warning here:
```js
console.warn( 'THREE.Audio: AudioBufferSourceNode.detune not supported by the browser.' );

```

**Comment by ngokevin** [comment]
Updated.

**Review by Mugen87 — APPROVED** [review]

File: src/audio/Audio.js [hunk 3]
```diff
@@ -95,7 +95,7 @@ Audio.prototype = Object.assign( Object.create( Object3D.prototype ), {
 		var source = this.context.createBufferSource();
 
 		source.buffer = this.buffer;
-		source.detune.value = this.detune;
+		this.setDetune( this.detune );
```
Comment (Mugen87) [inline src/audio/Audio.js]: I think there is a problem if you set `detune` like this. Since `isPlaying` is still false at this line, the value is actually not set to the `AudioBufferSourceNode`.

**Review by Mugen87 — CHANGES_REQUESTED** [review]

File: src/audio/Audio.js (hunk 3 above)
Comment (mrdoob) [reply src/audio/Audio.js]: Merging this for now so we no longer break in iOS 12.

**Comment by mrdoob** [comment]
Thanks!
