### PR TITLE
MathNode: Fix `transformDirection()`.

### LINKED ISSUE #33309: TSL: transformDirection operation is incorrect
### Description

When using the `transformDirection` operation I believe the inner operation is incorrect.

The generated wgsl code is -
```ts
normalize( ( direction * matrix ).xyz )
```
When it shall be -
```ts
normalize( ( matrix * direction ).xyz )
```

Function signature - 
```ts
transformDirection( direction : Node.<(vec2|vec3|vec4)>, matrix : Node.<(mat2|mat3|mat4)> ) : Node
```

### Reproduction steps

1. Create a node material
2. Use transformDirection node
3. Display generated wgsl

### Code

```ts
if ( method === MathNode.TRANSFORM_DIRECTION ) {

	// dir can be either a direction vector or a normal vector
	// upper-left 3x3 of matrix is assumed to be orthogonal

	let tA = aNode;
	let tB = bNode;

	if ( builder.isMatrix( tA.getNodeType( builder ) ) ) {

		tB = vec4( vec3( tB ), 0.0 );

	} else {

		tA = vec4( vec3( tA ), 0.0 );

	}

	const mulNode = mul( tA, tB ).xyz; // shall be const mulNode = mul( tB, tA ).xyz;

	outputNode = normalize( mulNode );

}
```

### Live example

Self explanatory

### Screenshots

_No response_

### Version

r183

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #33309.

**Description**

The PR makes sure the TSL function `transformDirection()` produces a consistent result no matter how the function is used. Meaning `matrix.transformDirection( dirVector )` or `dirVector.transformDirection( matrix )`.

To avoid breakage, it was necessary to update some TSL code that used `transformDirection()` unintentionally incorrect. Modules like `Normal.js` have to transform a view space vector into world space and used this style:

``` 
cameraViewMatrix * viewVec   (= "apply world→view transform to a vec that's already in view space")
```
Which is of course wrong. It should use camera's world matrix instead. The previous code did only work because the bug in `transformDirection()` accidentally produced the inverse of the view matrix for free. Now we are doing it correctly.

### CODE REVIEW

**Comment by Mugen87** [comment]
To further explain: The previous style did only work because the wrong operand order in `transformDirection()` produced
```
vec4(dir, 0) * M).xyz
```
which is mathematically
```
transpose(M) * vec
```
Because the upper-left 3×3 portion of the view matrix is orthogonal, `cameraViewMatrix` ended up as the `cameraWorldMatrix` (transpose is an inverse op in this case). Now with the fixed `transformDirection()`, this code would be broken. By using directly `cameraWorldMatrix`, the code is correct again and also syntactically like it should be.

**Comment by sunag** [comment]
@WestLangley already caught my attention regarding the order; I initially thought I was dealing with inversions similar to matrices in the “practical concept,” but it seems to be something different. `transformDirection` should be oriented toward direction vectors, while the `inverseTransformDirection()` to handle normal vectors.

I would like to know what he has to say about these changes 😇

**Comment by Mugen87** [comment]
To me, it is nonsense to code `normalView.transformDirection( cameraViewMatrix )` if you want the normal vector in _world space_. That and all similar occasions should be changed in any event.

**Comment by sunag** [comment]
> To me, it is nonsense to code normalView.transformDirection( cameraViewMatrix ) if you want the normal vector in world space.

Yes, I agree with that. The issues we were discussing were more about polishing the implementation of `transformDirection`, how to implement `inverseTransformNormal`, or simpler methods like `directionToWorld` or `normalToView`, `normalToWorld`, etc.

**Review by sunag — APPROVED** [review]

**Comment by WestLangley** [comment]
>Which is of course wrong. It should use camera's world matrix instead. The previous code did only work because the bug in transformDirection() accidentally produced the inverse of the view matrix for free. Now we are doing it correctly.

The code was correct, but the API is confusing to users.  We just need to fix the API.

>To me, it is nonsense to code normalView.transformDirection( cameraViewMatrix ) if you want the normal vector in world space. That and all similar occasions should be changed in any event.

Agreed. We can do better.

>I would like to know what @WestLangley has to say about these changes 😇

Gladly. I am working on it...

File: src/nodes/accessors/Normal.js [hunk 1]
```diff
@@ -74,7 +74,7 @@ export const normalViewGeometry = /*@__PURE__*/ ( Fn( ( builder ) => {
  */
 export const normalWorldGeometry = /*@__PURE__*/ ( Fn( ( builder ) => {
 
-	let normal = normalViewGeometry.transformDirection( cameraViewMatrix );
+	let normal = normalViewGeometry.transformDirection( cameraWorldMatrix );
```
Comment (WestLangley) [inline src/nodes/accessors/Normal.js:77]: You are using the same method to transform a normal vector as is used to transform a reflection or tangent vector. That is only correct in certain circumstances. The API needs to be improved.

**Comment by WestLangley** [comment]
__Overview__

Since the early days of three.js, we differentiate between _normal_ vectors and _direction_ vectors -- and for good reason.

Direction vectors, when transformed, remain in the plane of the mesh (assuming they begin in the plane of the mesh). Normal vectors, when transformed, remain orthogonal to the surface of the mesh.

We would never pass a normal into a method called "transformDirection()". This is why, in the math library, we have separate methods: `Vector3.transformDirection( m )` and `Vector3.applyNormalMatrix( m )`.

This PR, and TSL in general, do not maintain this distinction.

__WebGLRenderer__

In the `WebGLRenderer` shader code, we need to transform a normal from view space to world space, but we do not have access to `cameraMatrixWorld` in the shader. However, we do have access to the `viewMatrix`. Since the view matrix is orthogonal, it's inverse is equal to its transpose, so we can simply multiply the vector on the right by the view matrix to get the result we need. (see https://en.wikibooks.org/wiki/GLSL_Programming/Applying_Matrix_Transformations)

Here is the code from `common.js`:

```js
vec3 transformDirection( in vec3 dir, in mat4 matrix ) {

	return normalize( ( matrix * vec4( dir, 0.0 ) ).xyz );

}

vec3 inverseTransformDirection( in vec3 dir, in mat4 matrix ) {

	// dir can be either a direction vector or a normal vector
	// upper-left 3x3 of matrix is assumed to be orthogonal

	return normalize( ( vec4( dir, 0.0 ) * matrix ).xyz );

}
```

This is correct from an implementation standpoint, but not very good from an API standpoint.

Furthermore, following #32805, the inverse of the view matrix is no longer necessarily `cameraMatrixWorld`. So you would not want to try to transform a position vector using this trick.

__TSL__

The implementation of `transformDirection()` in TSL was based on the above `WebGLRenderer` shader code, but the two functions above were merged into one.

As a result, TSL `vector.transformDirection( matrix )` and `matrix.transformDirection( vector )` became vastly different things. That is very confusing.

__Suggestions for now...__

1. In the `WebGLRenderer` shader code, rename `inverseTransformDirection()` to `normalViewToWorld()`, or something like that, and pass in the view matrix. Currently, the shaders only use this method for transforming normals.

2. @sunag suggested that TSL could include more generic functions like `normalToWorld()`, `normalToView()`, `directionToWorld()`, `directionToView()`. I think that may be a good idea. In TSL, we hide the implementation details, so the above issues are transparent to the user.

I'd prefer more explicit nomenclature, such as: `normalViewToWorld()`, `normalWorldToView()`, `directionViewToWorld()`, `directionWorldToView()`. IMO, the nomenclature should include "from-to" terminology, unless one or the other is implicit.


The point of all this is that if we know the transform matrix is orthogonal, such as the view matrix, we can use some tricks to transform the normal. Otherwise, we have to use the normal matrix. Fortunately, if implemented correctly, TSL can hide the implementation details from the user.

**Comment by Mugen87** [comment]
> normalViewToWorld(), normalWorldToView(), directionViewToWorld(), directionWorldToView()

These sound good to me. However, we can't always "hide" the matrices in these methods because in context of post processing, the camera we are rendering with is the one from the quad mesh. So if a function like `normalViewToWorld()` would use `cameraWorldMatrix`, it would point to the orthographic one from the fullscreen pass (not the one we want e.g. in SSS). 

https://github.com/mrdoob/three.js/blob/8b169b04fffa5fdaf546b7c53159c78288dd69f3/examples/jsm/tsl/display/SSSNode.js#L384

So we need methods that accept matrices as parameters. 

@WestLangley I understand your reasoning but isn't this PR still an improvement of the current code? I do not fully understand the revert, tbh. Now the issue https://github.com/mrdoob/three.js/issues/33309 is reopened and we have this (confusing) pattern again:
```js
const normalWorld = normalView.transformDirection( cameraViewMatrix )
```

**Comment by WestLangley** [comment]
> So we need methods that accept matrices as parameters.

That's fine. The methods could have default values, which makes the API implicit, but doing so is not required.

> isn't this PR still an improvement of the current code?

It's a continuation of the current mess. We need to avoid passing a normal matrix into `transformDirection()`.

//

However, we can fix it. A quick solution is to add a new method

```js
const normalWorld = normalView.transformNormalByInverseViewMatrix( cameraViewMatrix );
```
but I am hoping for a comprehensive solution. Something like this:

```js
normal.transformNormalByInverseViewMatrix( viewMatrix ) // _post-multiplies_ by viewMatrix and normalizes (viewMatrix assumed to be orthonormal or uniformly-scaled)

normal.transformNormalByViewMatrix( viewMatrix ) // _pre-multiplies_ by viewMatrix and normalizes (same assumptions)

normal.transformNormal( matrix ) // pre-multiplies by the _normal matrix of the matrix_ and normalizes

direction.transformDirection( matrix ) // pre-multiplies by matrix and normalizes
```

The above API is akin to `Vector3.transformDirection( m )` and `Vector3.applyNormalMatrix( m )`.

Here's an alternative nomenclature (in the same order), but I think I prefer the former:

```js
normal.normalViewToWorld( viewMatrix )

normal.normalWorldToView( viewMatrix )

normal.transformNormal( matrix )

direction.transformDirection( matrix )
```

TBH, I am not a fan of including the following additional corresponding patterns, unless there is a compelling reason to add them.

```js
matrix.transformNormal( normal )

matrix.transformDirection( direction )
```

**Comment by Mugen87** [comment]
> normal.normalViewToWorld( viewMatrix )

I find this non-intuitive, tbh (meaning using the view matrix to get to world space). And I'm afraid I still don't understand why `cameraWorldMatrix` isn't used instead which is the most obvious approach to me.

**Comment by WestLangley** [comment]
@Mugen87 In `WebGLRenderer`, only `viewMatrix` is available as a uniform.

In `WebGPURenderer`, both `cameraViewMatrix` and `cameraWorldMatrix` are available as built-in nodes.

So you are correct, we can use `cameraWorldMatrix` -- but only if it's normal matrix is the identity or a scalar.

Remember, `cameraWorldMatrix` is not necessarily the inverse of `viewMatrix`, because of  #32805.

//

Perhaps `Camera` should have both a `.matrixWorldInverse` and a `.viewMatrix` property, since they are not necessarily the same.

**Comment by Mugen87** [comment]
> Perhaps Camera should have both a .matrixWorldInverse and a .viewMatrix property, since they are not necessarily the same.

Um, I have the feeling this over-complicates things. I would prefer a simple solution. And then we just document our assumptions or potential restrictions.

**Comment by WestLangley** [comment]
>Um, I have the feeling this over-complicates things

OK, that's fine.

@Mugen87 This is a long thread. Here is a summary.

(1) After you filed #32805, `camera.matrixWorldInverse` is not necessarily the inverse of `camera.matrixWorld`. I find that very confusing, but that is where we are at the moment. That is not going to be changed, AFAIK.

(2) `camera.matrixWorldInverse` (i.e., the view matrix) is now orthonormal. That means we can use it to transform normals directly, without having to involve the "normal matrix".

(3) The changes I have suggested are nomenclature-only, and allow us to also improve the confusing implementation of the TSL method `transformDirection()`, a change you support. It will be modified to simply premultiply the vector by the matrix.

(4) We can now stop passing a normal into a method designed to transform direction vectors, such as tangents and reflection vectors. (This has been my biggest concern.)

(5) I suggest we implement the following methods, as I discussed above.

```js
normal.transformNormalByInverseViewMatrix( viewMatrix ) // _post-multiplies_ by viewMatrix and normalizes (viewMatrix assumed to be orthonormal or uniformly-scaled)

normal.transformNormalByViewMatrix( viewMatrix ) // _pre-multiplies_ by viewMatrix and normalizes (same assumptions as above)

normal.transformNormal( matrix ) // pre-multiplies by the _normal matrix of the matrix_ and normalizes

direction.transformDirection( matrix ) // pre-multiplies by matrix and normalizes
```

(6) The first method is also used by `WebGLRenderer`. If you can find a way to follow @sunag's suggestion and hide the implementation, that is fine with me.

(7) It is also fine with me if you want to modify the `Camera` API so it can only be _uniformly-scaled_. (e.g, add `Camera.setScale( scaleFactor )` and make `Camera.scale` private).

It is unfortunate that this is so confusing, but I think we are on the right track to making things better.

**Comment by Mugen87** [comment]
After some thought I'm convinced the methods have a precise naming. The term `ByInverseViewMatrix` makes it more clear a vector in world space is the result.
