### PR TITLE
GLSLNodeBuilder: Fix `texelFetch*()` code generation with depth textures.

### LINKED ISSUE #31759: TSL: Mismatched type assignment from pass texture on WebGL fallback
### Description

Using WebGPURenderer with WebGLBackend, sampling a depth pass texture using `TextureNode.load()` attempts to assign a `vec4` value to a `float` variable, resulting in a compilation error. This doesn't reproduce when using `TextureNode.sample()`.

### Reproduction steps

1. Render a scene using `PassNode`.
2. Sample the depth texture using `TextureNode.load()`.

### Code

```ts
const renderer = new WebGPURenderer({ forceWebGL: true })
await renderer.init()

const passNode = pass(scene, camera)
const depthNode = passNode.getTextureNode('depth')

// This will be transpiled to:
//   float nodeVar0;
//   nodeVar0 = texelFetch( nodeUniform0, ..., 0 );
// Expected:
//   float nodeVar0;
//   nodeVar0 = texelFetch( nodeUniform0, ..., 0 ).x;
const outputNode = depthNode.load(ivec2(0, 0))

const material = new NodeMaterial()
material.fragmentNode = outputNode
const mesh = new QuadMesh(material)
mesh.render(renderer)
```

### Live example

https://jsfiddle.net/shotamatsuda/r7ms2wfk/
(See errors in the console output)

### Screenshots

_No response_

### Version

r179

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by shotamatsuda**
Fixed #31759.

**Description**

This PR fixes `TextureNode.load()` incorrectly returns `vec4` when sampling a depth texture on WebGL fallback.

### CODE REVIEW

File: src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js [hunk 1]
```diff
@@ -426,32 +440,28 @@ ${ flowData.code }
 	 */
 	generateTexture( texture, textureProperty, uvSnippet, depthSnippet, offsetSnippet ) {
 
-		if ( texture.isDepthTexture ) {
-
-			if ( depthSnippet ) uvSnippet = `vec4( ${ uvSnippet }, ${ depthSnippet } )`;
```
Comment (shotamatsuda) [inline src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js]: I'm afraid this should be `vec3`. `vec4` is only valid when the sampler type is `sampler2DShadow` or `sampler2DArrayShadow` and the argument to`uvSnippet` is a `vec3`.

File: src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js [hunk 2]
```diff
@@ -390,28 +390,42 @@ ${ flowData.code }
 	 */
 	generateTextureLoad( texture, textureProperty, uvIndexSnippet, depthSnippet, offsetSnippet, levelSnippet = '0' ) {
 
+		let snippet;
```
Comment (Mugen87) [inline src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js:393]: Would you also be okay with this approach:
```js

generateTextureLoad( texture, textureProperty, uvIndexSnippet, depthSnippet, offsetSnippet, levelSnippet = '0' ) {

    const depthSwizzle = ( texture && texture.isDepthTexture ) ? '.x' : '';

    if ( depthSnippet ) {

        if ( offsetSnippet ) {

            return `texelFetchOffset( ${ textureProperty }, ivec3( ${ uvIndexSnippet }, ${ depthSnippet } ), ${ levelSnippet }, ${ offsetSnippet } )${depthSwizzle}`;

        }

        return `texelFetch( ${ textureProperty }, ivec3( ${ uvIndexSnippet }, ${ depthSnippet } ), ${ levelSnippet } )${depthSwizzle}`;

    } else {

        if ( offsetSnippet ) {

            return `texelFetchOffset( ${ textureProperty }, ${ uvIndexSnippet }, ${ levelSnippet }, ${ offsetSnippet } )${depthSwizzle}`;

        }

        return `texelFetch( ${ textureProperty }, ${ uvIndexSnippet }, ${ levelSnippet } )${depthSwizzle}`;

    }

}
```

File: src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js [hunk 3]
```diff
@@ -380,7 +380,7 @@ ${ flowData.code }
 	/**
 	 * Generates the GLSL snippet that reads a single texel from a texture without sampling or filtering.
 	 *
-	 * @param {Texture} texture - The texture.
+	 * @param {?Texture} texture - The texture.
```
Comment (shotamatsuda) [inline src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js:383]: Made the texture parameter nullable because of its use in `generatePBO`.
https://github.com/mrdoob/three.js/blob/105a9940bde9b8a6ee9f3fb1210cbd448143ab18/src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js#L353

File: src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js (hunk 1 above)
Comment (Mugen87) [reply src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js]: see https://github.com/mrdoob/three.js/pull/30830/files#r2303794534

Comment (Mugen87) [reply src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js]: Let's focus on this issue in a different PR though.

File: src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js (hunk 2 above)
Comment (shotamatsuda) [reply src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js:393]: I initially came up with that approach, but changed it to align with WGSLNodeBuilder.
https://github.com/mrdoob/three.js/blob/105a9940bde9b8a6ee9f3fb1210cbd448143ab18/src/renderers/webgpu/nodes/WGSLNodeBuilder.js#L515

I'm happier with that approach. It it okay to modify WGSLNodeBuilder to align it?

Comment (Mugen87) [reply src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js:393]: Let's keep the code as it is. In `WGSLNodeBuilder`, the approach makes sense and I'm okay when both `generateTextureLoad()` are aligned.

File: src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js (hunk 1 above)
Comment (shotamatsuda) [reply src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js]: OK. I will roll it back to `vec4`, and use the `depthSwizzle` approach above.

**Review by Mugen87 — DISMISSED** [review]

File: src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js (hunk 1 above)
Comment (Mugen87) [reply src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js]: > use the depthSwizzle approach above.

Please let `generateTextureLoad()` as it is so it is aligned with `WGSLNodeBuilder`. When writing my comment, I wasn't aware of the implementation on the WebGPU side.

Comment (shotamatsuda) [reply src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js]: Just to confirm, should the `uvSnippet` be rolled back to `vec4`?

Comment (Mugen87) [reply src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js]: Yes, let's focus in this PR on `generateTextureLoad()`.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
@shotamatsuda Could you please open a new PR with your changes to fix `generateTexture()`? I'm afraid the issue became not clear when trying to explain it in https://github.com/mrdoob/three.js/pull/30830#discussion_r2303794534. A new PR would help to launch a new discussion.
