### PR TITLE
MeshNormalNodeMaterial: Convert packed normal to working color space

### LINKED ISSUE #30575: MeshNormalMaterial Color Differences Across Renderers
### Description

I was experimenting with MeshNormalMaterial in the WebGPURenderer when I noticed the colors of the normals seemed off when compared to the WebGLRenderer. I was wondering if this is expected behavior based on the differences between the two rendering APIS or whether this was a bug. I assume this might also just be differences in default color spaces, but just wanted to confirm.

### Reproduction steps

1. Create three renderers (WebGPURenderer with WebGPUBackend, WebGPURenderer with WebGLBackend, WebGLRenderer) that each render the same scene, containing a mesh with a MeshNormalMaterial.

### Code

// NA

### Live example

[Live WebGPU Example](https://raw.githack.com/cmhhelgeson/three.js/normal_material/examples/webgl_geometry_cube.html)

### Screenshots

Image

### Version

r173

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by WestLangley**
Fixes #30575.

Also https://github.com/mrdoob/three.js/issues/28831#issuecomment-2214495667.

By convention, the packed normal, when interpreted as a color, is assumed to be in sRGB color space. It must be converted to linear working color space.

### CODE REVIEW

File: src/materials/nodes/MeshNormalNodeMaterial.js [hunk 1]
```diff
@@ -54,7 +56,9 @@ class MeshNormalNodeMaterial extends NodeMaterial {
 
 		const opacityNode = this.opacityNode ? float( this.opacityNode ) : materialOpacity;
 
-		diffuseColor.assign( vec4( directionToColor( transformedNormalView ), opacityNode ) );
+		// By convention, a normal packed to RGB is in sRGB color space. Convert it to working color space.
+
+		diffuseColor.assign( toWorkingColorSpace( vec4( directionToColor( transformedNormalView ), opacityNode ), SRGBColorSpace ) );
```
Comment (Mugen87) [inline src/materials/nodes/MeshNormalNodeMaterial.js:61]: Do you mind removing the `SRGBColorSpace` from that line. `toWorkingColorSpace()` has just one parameter.

**Comment by Mugen87** [comment]
It seems a few examples using `WebGPURenderer` and a normal material require updated E2E screenshots.

File: src/materials/nodes/MeshNormalNodeMaterial.js (hunk 1 above)
Comment (WestLangley) [reply src/materials/nodes/MeshNormalNodeMaterial.js:61]: Oops... but can you explain how it converts to working color space without knowing what color space to convert from?

Comment (Mugen87) [reply src/materials/nodes/MeshNormalNodeMaterial.js:61]: The function _assumes_ the given color node is already in output color space.

There is an alternative TSL function that is more flexible in that regard:

https://github.com/mrdoob/three.js/blob/3bb6e70ca2107d709c003b4a7df9853d9fc51717/src/nodes/display/ColorSpaceNode.js#L160-L169

**Comment by WestLangley** [comment]
>It seems a few examples using WebGPURenderer and a normal material require updated E2E screenshots.

I have been unable to successfully update screenshots for some time now, unfortunately.

File: src/materials/nodes/MeshNormalNodeMaterial.js (hunk 1 above)
Comment (WestLangley) [reply src/materials/nodes/MeshNormalNodeMaterial.js]: >The function (`toWorkingColorSpace`) assumes the given color node is in output color space.

Then it should be called `toWorkingColorSpaceFromOutputColorSpace`.

Is "output color space" the renderer's output color space?...  I guess that is true...

Then the inverse method should be `toOutputColorSpaceFromWorkingColorSpace`.

**Comment by Mugen87** [comment]
There is a trick that you can use: If you open the failed CI job, you can actually download the actual and expected screenshots but only from the failed examples.

image

The artifact download link is at the bottom of the section "Upload Output Screenshots". If you now replace the `_actual` screenshots with the ones from `examples/screenshots`, the CI should work again.

**Review by Mugen87 — APPROVED** [review]

File: src/materials/nodes/MeshNormalNodeMaterial.js (hunk 1 above)
Comment (WestLangley) [reply src/materials/nodes/MeshNormalNodeMaterial.js]: These are fine, since the source and destination are clear -- although I prefer using the more specific terms: `targetColorSpace` and `sourceColorSpace`.

https://github.com/mrdoob/three.js/blob/972f726d6f07738e77d9759f44f0d649bf1f849c/src/nodes/display/ColorSpaceNode.js#L158
https://github.com/mrdoob/three.js/blob/972f726d6f07738e77d9759f44f0d649bf1f849c/src/nodes/display/ColorSpaceNode.js#L169

//

These are also fine, for the same reason -- although I would rename them. and adhere to the same nomenclature as above: `workingToColorSpace( color, targetColorSpace )` and `colorSpaceToWorking( color, sourceColorSpace )`.

https://github.com/mrdoob/three.js/blob/972f726d6f07738e77d9759f44f0d649bf1f849c/src/math/ColorManagement.js#L79-L89

//

But I think these should be removed, as is it not clear from the name what they do, and it is not clear to me why they are needed.

https://github.com/mrdoob/three.js/blob/972f726d6f07738e77d9759f44f0d649bf1f849c/src/nodes/display/ColorSpaceNode.js#L137
https://github.com/mrdoob/three.js/blob/972f726d6f07738e77d9759f44f0d649bf1f849c/src/nodes/display/ColorSpaceNode.js#L147

/ping @gkjohnson

Comment (gkjohnson) [reply src/materials/nodes/MeshNormalNodeMaterial.js]: > But I think these should be removed, as is it not clear from the name what they do, and it is not clear to me why they are needed.

I haven't used nodes much yet but I tend to agree that more explicit functions are better and using functions that assume information about color spaces can make code unclear.

Comment (WestLangley) [reply src/materials/nodes/MeshNormalNodeMaterial.js]: @Mugen87 When you get a chance, can you think about this a bit? 🙏 

All we need are these two methods: `workingToColorSpace()` and `colorSpaceToWorking()` -- in both `ColorSpaceNode.js` and `ColorManagement.js`. This avoids having different nomenclatures for the same thing.

Comment (Mugen87) [reply src/materials/nodes/MeshNormalNodeMaterial.js]: I'll try to revisit this issue when the JSDoc migration has been finished.

Comment (WestLangley) [reply src/materials/nodes/MeshNormalNodeMaterial.js]: /bump @Mugen87 🙏
