### PR TITLE
WebXRManager: Fix XRCamera Local Space Behavior by Reverting #21964

### LINKED ISSUE #22884: PositionalAudio breaks in webxr when moving the user
Adding THREE.PositionalAudio to a mesh inside a group (Object3D or Group)  alongside the user (camera) works as expected, but if the group is then moved the audio breaks.

**To Reproduce**

1. create a container to hold the "vehicle"
2. create and add a webxr "user" to the container
3. create an AudioListener and add it to the camera
4. create and add a PositionalAudio to the container
5. move the container "vehicle"

***Code***

```js
let carContainer = new THREE.Object3D();
scene.add(carContainer);

// create a "user" so that the webxr camera moves with the carContainer
let user = new THREE.Group();
carContainer.add(user);
user.add( camera );

// create an AudioListener and add it to the camera
const listener = new THREE.AudioListener();
camera.add( listener );

function tick() {
carContainer.position.z += 0.01;
}
```

***Live example***

(for some reason the fiddle doesn't show the VRButton button. I don't use jsfiddle much sorry...)
[https://jsfiddle.net/mayamoss/zgj5cvpk/90/](https://jsfiddle.net/mayamoss/zgj5cvpk/90/)

**Expected behavior**

Audio follows the user in local(sic) space.

**Platform:**

 - Device: Oculus Quest 2
 - Browser: Chrome
 - Three.js version: dev

### LINKED ISSUE #23597: `camera.getWorldPosition/...` returning the wrong result in XR mode
Hey guys we recently upgraded our threejs version and encountered some wierd behavior from camera in XR mode. After some debugging turns out this PR was the clurpit

https://github.com/mrdoob/three.js/pull/21964/files#diff-a27b9d3ba68457069cc8ff521208ae9d0cc6d9256f6f48ada6316fc2d732ba7e

So basically before that PR the code was

https://github.com/mrdoob/three.js/blob/ec96437a05b7c3f9f3e64951a9b17f6be6314129/src/renderers/webxr/WebXRManager.js#L381-L385

Which took the position/rotation/scale from the local matrix of VR camera

but after the PR it's doing this now

https://github.com/mrdoob/three.js/blob/31565e65385ec6f61a567dba2678e6689601d4f9/src/renderers/webxr/WebXRManager.js#L381-L389

which updates camera's position/rotation/scale from the global  matrix of the VR camera

But that means that if the camera has got a parent then `camera.getWorldPosition(...)` would return the wrong result since now we'll be counting the transform 2 times. Since the camera's position (same for rotation ...) has already the world position that was copied from VR camera's global matrix

Was this ane expected behavior from the PR? because now every code that relies on `getWorldXXX` would break in XR

### PR DESCRIPTION
**Pull request by zalo**
Fixed #23597.
Fixed #22884.

This PR fixes a bug introduced in r130 by reverting how XR Camera calculations handle local space (by partially undoing #21964 (which appears to conflate `matrixWorld` and `matrix`)).

This enables the XR camera to be parented to another moving object without odd behavior once again.

If this isn't the correct fix; I'd be happy to test alternatives in the context of my application.

Related issues: #21964 , https://github.com/google/model-viewer/pull/2464/files#r647866462

### CODE REVIEW

**Comment by mrdoob** [comment]
Apologies, I should have written the reasoning in #21964.

It has been just 2 months and I've already forgotten... @elalish do you remember what it was?

**Comment by elalish** [comment]
https://github.com/mrdoob/three.js/pull/21964#issuecomment-902074459

**Comment by zalo** [comment]
@elalish Apologies for the delay, I just re-added [the decompose from the prior PR](https://github.com/mrdoob/three.js/pull/21964/files#diff-a27b9d3ba68457069cc8ff521208ae9d0cc6d9256f6f48ada6316fc2d732ba7eR381) so the `cameraVR`'s position/rotation/scale should be synced with its _own_ matrix.

However, given that the `cameraVR` operates outside of the scene hierarchy, does it make sense to sync the `cameraVR` and scene `camera`'s worldMatrix data directly?

**Comment by a-dpq** [comment]
https://github.com/mrdoob/three.js/pull/21964#issuecomment-955605614

File: src/renderers/webxr/WebXRManager.js [hunk 1]
```diff
@@ -503,11 +503,8 @@ class WebXRManager extends EventDispatcher {
 
 			// update user camera and its children
 
-			camera.position.copy( cameraVR.position );
-			camera.quaternion.copy( cameraVR.quaternion );
-			camera.scale.copy( cameraVR.scale );
 			camera.matrix.copy( cameraVR.matrix );
-			camera.matrixWorld.copy( cameraVR.matrixWorld );
+			camera.matrix.decompose( camera.position, camera.quaternion, camera.scale );
```
Comment (elalish) [inline src/renderers/webxr/WebXRManager.js:507]: Is  there any reason doing a second decompose is better than copying the results like it was before? I think decompose is a bit expensive, so probably best not to call it more than it needs to. 

Then the only difference would be not copying the `matrixWorld`. I don't remember the details of how three decides when to update that or not. @mrdoob do you see  any  trouble with this?

Comment (zalo) [reply src/renderers/webxr/WebXRManager.js:507]: The subtle difference is between local and global space.

The old method of:
```javascript
cameraVR.matrixWorld.decompose( cameraVR.position, cameraVR.quaternion, cameraVR.scale );
camera.position.copy( cameraVR.position );
camera.quaternion.copy( cameraVR.quaternion );
camera.scale.copy( cameraVR.scale );
```
is copying **world**Matrix values into **local** position/rotation/scale variables.

This broke any VR application that had the VRCamera as the child of another transform.

**Comment by a-dpq** [comment]
Any chance this could get included in the next release? My VR apps have not been working properly for months because of this bug.

**Review by Mugen87 — APPROVED** [review]

**Comment by DePasqualeOrg** [comment]
Since this has already been approved, could we pull it into the next release? VR apps with a parented camera haven't been working properly for about half a year now.

**Comment by Mugen87** [comment]
@mrdoob I think this PR should be merged.

**Comment by marcofugaro** [comment]
Bump

**Comment by zalo** [comment]
I've got a cool three.js OpenXR demo waiting in the wings that could use this PR...
LeapShape Cylinders
LeapShape Hollowing

**Comment by LeviPesin** [comment]
Wow! Can you please share its code?

**Comment by kalegd** [comment]
+1, I think 9 months is a good amount of time for this pull request to have gestated (I say this with only humorous intentions without animosity)

**Comment by kalegd** [comment]
+1, I think 9 months is a good amount of time for this pull request to have gestated (I say this with only humorous intentions without animosity)

**Comment by ashconnell** [comment]
This issue has been resolved for quite some time now

**Comment by LeviPesin** [comment]
@ashconnell When and where was it fixed?

**Comment by msub2** [comment]
@LeviPesin I think he means to say there's been a consensus on this for months that it's good to go and yet it hasn't been merged in yet

**Comment by ashconnell** [comment]
@LeviPesin Apologies. I meant this should be merged as there are no objections.

I can also verify this PR does indeed fix the crackling PositionalAudio issues in WebXR, so would be delighted to decomission my fork once this is merged :)

**Comment by ashconnell** [comment]
Is there an issue with this PR? It keeps getting pushed back but seems like a trivial merge.

**Comment by zalo** [comment]
I suspect it's waiting for an example or test that would break (in the case that this functionality gets broken again at some point in the future...)

**Comment by DePasqualeOrg** [comment]
Plenty of things have been broken for nearly a year because of this.

**Comment by cktben** [comment]
Please go ahead and merge this.  It fixes a number of problems that just can't be worked around without it.

**Comment by Mugen87** [comment]
@elalish Would it be a problem for model-viewer if this PR gets merged?

**Comment by elalish** [comment]
> @elalish Would it be a problem for model-viewer if this PR gets merged?

I don't think so. Our usage of XR is pretty vanilla, so I'd expect what's good for others is good for us too.

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
@zalo 

> I've got a cool three.js OpenXR demo waiting in the wings that could use this PR...
LeapShape Cylinders
LeapShape Hollowing

That looks amazing! 🤩
