### PR TITLE
WebXRManager: Fix caching of baseReferenceFrame and teleport example.

### LINKED ISSUE #24033: Teleport example is broken on Meta Quest 2
It seems to be offsetting my by strange amounts.

### PR DESCRIPTION
**Pull request by richardanaya**
Fixed https://github.com/mrdoob/three.js/issues/24033

**Description**

The teleporter example was broken in a few ways.

* the example wasn't creating a transform from the original baseReferenceFrame acquired from the WebXR manager, leading to really strange offsets after the initial teleport.  The first teleport would look correct, but then you'd be modifying a modified space.
* the baseReferenceFrame wasn't nulled out on sub-sequent entering of vr sessions, only allowing you to enter into the example with VR once
* the example needs to watch for changes in the session to re-grab baseReferenceFrame again

Video of it working:

https://user-images.githubusercontent.com/294042/168413544-1210d3cf-7c82-4fdf-9191-d95c42300265.mp4

### CODE REVIEW

File: src/renderers/webxr/WebXRManager.js [hunk 1]
```diff
@@ -228,6 +228,19 @@ class WebXRManager extends EventDispatcher {
 
 		this.setSession = async function ( value ) {
 
+			if ( session ) {
```
Comment (arodic) [inline src/renderers/webxr/WebXRManager.js:231]: Without this we would have multiple event listeners on session restart. I guess there is no harm trying to remove listeners which are not added already on first session.

Would it make more sense to do this in `onSessionEnd`?

File: examples/webxr_vr_teleport.html [hunk 2]
```diff
@@ -104,8 +104,15 @@
 					this.userData.isSelecting = false;
 
 					if ( INTERSECTION ) {
+						// reuse the same base reference space and watch out if our session changed
+						
+						if ( !baseReferenceSpace || session !== renderer.xr.getSession() ) {
```
Comment (arodic) [inline examples/webxr_vr_teleport.html:109]: Is this check really necessary considering that you reset `customReferenceSpace`to `null` in WebXRManager on every session start?

File: src/renderers/webxr/WebXRManager.js (hunk 1 above)
Comment (richardanaya) [reply src/renderers/webxr/WebXRManager.js:231]: Makes sense!

File: examples/webxr_vr_teleport.html (hunk 2 above)
Comment (richardanaya) [reply examples/webxr_vr_teleport.html:109]: I believe it is actually.  Here's the scenario this tries to address:

1. user enters VR session A
2. user teleports to location A, but before we do this we need to cache the original starting reference space of VR session A, because once we call setReferenceSpace, we'll never be able to get it again.
3. user teleports a second time, since we have the cached original starting  reference we can just make a new reference space again.
4. user exits VR.  Our example has no way of knowing about this right now, so that cached `baseReferenceFrame` is from a VR session A that is no longer valid.
5. User enters into VR session B and tries to teleport.  If we use baseReferenceFrame as it is we'll get errors about modifying a reference frame of a session longer longer valid.

We needed some way to indicate that the baseReferenceFrame was from a session that is different from the current session.  I do this by comparing the active sessions to know whether to re-cache the original baseReference frame of the new VR Session B.

**Comment by richardanaya** [comment]
@arodic thanks for the review :) made that change on removing event handlers as you suggested, I left a comment on why I need to cache the session.

**Comment by arodic** [comment]
Excellent! I can confirm that this fix works as intended (tested in Oculus Quest 2). I can also confirm that without this fix, the example is broken if multiple sessions are attempted.

File: examples/webxr_vr_teleport.html (hunk 2 above)
Comment (LeviPesin) [reply examples/webxr_vr_teleport.html:109]: Can't we just listen to the renderer's `sessionstart` event instead of this check?

Comment (arodic) [reply examples/webxr_vr_teleport.html:109]: Thats a good suggestion! Less brute force checking and informs the user about the sessionstart/end events.

**Comment by LeviPesin** [comment]
@richardanaya Can you please update the PR with a `sessionstart` listener instead of that check?

**Comment by mrdoob** [comment]
@LeviPesin Where would that listener go?

**Comment by LeviPesin** [comment]
I think https://github.com/mrdoob/three.js/pull/24058/files#diff-28e2f2792c9f311cb52ce985452165df772dcfde81e80f00cd699426ede935c6R107-R116 should be reverted and to the `init()` function line `renderer.xr.on( 'sessionstart', () => { baseReferenceSpace = renderer.xr.getReferenceSpace(); } )` should be added.

**Comment by richardanaya** [comment]
@LeviPesin fixed according to your suggestion, it's much cleaner :) thank you

**Comment by mrdoob** [comment]
Thanks!
