### PR TITLE
OrbitControls: Use `onPointerUp()` for `pointercancel` events.

### LINKED ISSUE #25505: OrbitControls stays in incorrect state after pointercancel event
### Description

Opening a page with OrbitControls on an iPad can result in several errors when moving the scene with two fingers closely pinched together. 

Probably it's the same in any case where `pointercancel` would be fired, but this is the scenario which we can consistently reproduce on multiple devices. Surface tables or Android phones don't fire this event (in this case at least).

### Reproduction steps

1. Open a page with OrbitControls (even [the official example](https://threejs.org/docs/#examples/en/controls/OrbitControls) works) on an iPad (tested on multiple devices, the latest is iOS 16.3 Safari)
2. Add a global error listener (`window.addEventListener('error', e=>{...})`)
3. Start panning the scene with two fingers pinched closely together

The error handler will fire several times.

### Code

The error triggered regardless of user code.

As far as I could tell, the problem is that in `OrbitControls.js`, in `onPointerCancel`, the pointer is removed, but `state` is not changed. So if we were in the middle of a panning or zooming gesture for example (`state = TOUCH_DOLLY_PAN`), the next call to `onPointerMove` will eventually end up in `getSecondPointerPosition`, which will throw when trying to read the position of the nonexistent second pointer.

### Live example

* [jsfiddle-dev](https://jsfiddle.net/0s5f6gqa/)

### Screenshots

_No response_

### Version

r149

### Device

Mobile

### Browser

Safari

### OS

iOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #25505.

**Description**

The `pointercancel` event is now handled like `pointerup`. This will ensure correct internal state if `pointercancel` is fired.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawcdn.githack.com/Mugen87/three.js/dev75/examples/misc_controls_orbit.html

File: examples/jsm/controls/OrbitControls.js [hunk 1]
```diff
@@ -883,26 +883,20 @@ class OrbitControls extends EventDispatcher {
...
 
-		    }
+			if ( pointers.length === 0 ) {
 
-		    scope.dispatchEvent( _endEvent );
+				scope.domElement.releasePointerCapture( event.pointerId );
 
-		    state = STATE.NONE;
+				scope.domElement.removeEventListener( 'pointermove', onPointerMove );
+				scope.domElement.removeEventListener( 'pointerup', onPointerUp );
```
Comment (LeviPesin) [inline examples/jsm/controls/OrbitControls.js:893]: Shouldn't `pointercancel` listener also be removed here?

Comment (Mugen87) [reply examples/jsm/controls/OrbitControls.js:893]: `pointermove` and `pointerup` are added differently and thus have to be removed in a different way, too.
