### PR TITLE
WebGPURenderer: New normal nodes approach

### LINKED ISSUE #28939: WebGPURenderer: AttributeNode: Vertex attribute "normal" not found on geometry
### Description

Cleaning up the examples a bit...

The following examples display the warning:

    AttributeNode: Vertex attribute "normal" not found on geometry.

Due to use of QuadMesh

	- webgpu_rtt.html
	- webgpu_multisampled_renderbuffers.html
	- webgpu_multiple_rendertargets_readback.html
	- webgpu_depth_texture.html

Due to Horse.glb

	- webgpu_instancing_morph.html

Due to RectAreaLightHelper

	- webgpu_lights_rectarealight.html

Perhaps the warning can be suppressed?

### Reproduction steps

see example list above

### Code

n/a

### Live example

see example list above

### Screenshots

_No response_

### Version

r167 dev

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by sunag**
Related issue: Closes https://github.com/mrdoob/three.js/issues/28939, https://github.com/mrdoob/three.js/pull/29121

**Description**

Thanks to the once deferred function we can use constants as functions that will be executed at compile time. This approach is superior to the current ones that use `transformedNormalView.assign()` and I think we can use it not so soon in `positionLocal` and `positionPrevious` as well.

### CODE REVIEW

File: src/nodes/materials/NodeMaterial.js [hunk 1]
```diff
@@ -40,7 +39,6 @@ class NodeMaterial extends Material {
 
 		this.fog = true;
 		this.lights = false;
-		this.normals = true;
```
Comment (Mugen87) [inline src/nodes/materials/NodeMaterial.js:43]: Glad to see `normals` is gone! 🎉

File: src/nodes/functions/material/getGeometryRoughness.js [hunk 2]
```diff
@@ -1,9 +1,9 @@
-import { normalGeometry } from '../../accessors/NormalNode.js';
+import { normalView } from '../../accessors/NormalNode.js';
 import { Fn } from '../../shadernode/ShaderNode.js';
 
 const getGeometryRoughness = Fn( () => {
 
-	const dxy = normalGeometry.dFdx().abs().max( normalGeometry.dFdy().abs() );
+	const dxy = normalView.dFdx().abs().max( normalView.dFdy().abs() );
```
Comment (RenaudRohlinger) [inline src/nodes/functions/material/getGeometryRoughness.js:6]: I've noticed that a lot of code relies on normalView for lighting calculations and PBR purposes. However, we can't depend on it as-is because, as far as I understand, normalView is only assigned once using once() and is never reassigned.

This creates a limitation where the node-based approach doesn't seem to fully support normalNode. For example, in the current PR, roughness calculations would only work if there's a roughnessMap. Otherwise, it defaults to using normalView, which is derived from normalLocal rather than normalNode.

If my understanding is correct, normalNode effectively resolves to normalView, making normalNode incompatible with the current node system. Or am I missing something here, @sunag?

Comment (WestLangley) [reply src/nodes/functions/material/getGeometryRoughness.js:6]: `transformedNormalView` still exists. Was that intentional?
