### PR TITLE
WebGPURenderer: Implement `WEBGL_multi_draw` fallback.

### LINKED ISSUE #31070: WebGPURenderer: BatchedMesh in WebGL fallback breaks in Firefox
### Description

Nothing is rendered when using BatchedMesh and WebGPURenderer in Firefox (on Mac at least).
The WebGLRenderer version works fine.

I had a broken behavior on iOS Safari in my project, too, but the example works fine, so let's just say it's Firefox for now. I'll add Safari details if I manage to reproduce it reliably.

### Reproduction steps

1. Go to https://threejs.org/examples/webgpu_mesh_batch.html with Firefox
2. Nothing shows up

### Code

WebGPURenderer

### Live example

https://threejs.org/examples/webgpu_mesh_batch.html

### Screenshots

WebGPURenderer (webgpu):
Image

WebGPURenderer (webgl):
Image

WebGLRenderer:
Image

### Version

176

### Device

Desktop

### Browser

Firefox

### OS

MacOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #31070.

**Description**

The PR makes sure `BatchedMesh` can be used with WebGPURenderer and its WebG 2 backend even if `WEBGL_multi_draw` isn't supported like in Firefox.

I was able to implement this fallback without any changes to `BatchNode`. The idea is to fallback to a uniform if `WEBGL_multi_draw` isn't supported and update it directly right before performing the drawing command. That matches the existing approach in `WebGLRenderer`.

### CODE REVIEW

File: src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js [hunk 1]
```diff
@@ -1556,6 +1558,20 @@ void main() {
 			stageData.transforms = this.getTransforms( shaderStage );
 			stageData.flow = flow;
 
+			// fallbacks
```
Comment (Mugen87) [inline src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js:1561]: @sunag I've created a new section for fallbacks here since this a good place where you have access to all parts of the shader. We could also move below code to `getUniforms()` but other fallbacks might require access to more than just one snippet. Having the fallbacks at one place seems clearer to me. Is that okay with you?

Comment (sunag) [reply src/renderers/webgl-fallback/nodes/GLSLNodeBuilder.js:1561]: Looks good for me 👍
