### PR TITLE
Fix Object3D, Material and Texture toJSON method

### LINKED ISSUE #8581: Can't convert a Texture to json without passing in an empty object
##### Description of the problem

[This commit](https://github.com/mrdoob/three.js/commit/25ffb41e6467468d26a9dc317926f9832f17da35) introduced a parameter to the Texture.toJSON API [on line 102](https://github.com/mrdoob/three.js/blob/bc0d71431e9a979926bd01d57cfee8ec28c6b59f/src/textures/Texture.js#L102):

```
toJSON: function ( meta ) {
```

If this parameter is not passed in, anyone calling `toJSON()` will get a hard crash.

```
$ node
    > var three = require('three');
    > new three.Texture().toJSON();

TypeError: Cannot read property 'textures' of undefined
at THREE.Texture.toJSON (node_modules/three/three.js:21524:12)
```

One solution here is to pass in an empty object. That doesn't really make sense, though, because it would be a confusing and undocumented API. Also consider the `JSON.stringify()` case:

```
$ node
    > var three = require('three');
    > JSON.stringify(new three.Texture());

TypeError: Cannot read property '8D889934-01AE-4074-BDC9-9CA926CF1270' of undefined
at THREE.Texture.toJSON (node_modules/three/three.js:21524:21)
```

**If a `Texture` is ever converted to JSON, it will crash.** `JSON.stringify` recursively calls `.toJSON()` on each nested object (if that method is defined), which also means that there's no easy way to convert an object containing a `Texture` to JSON without manually walking each key recursively and passing in an empty object myself. The following would crash, for example:

```
    > JSON.stringify({ a: ''cow', b: new three.Texture() });
```

[The commit in question](https://github.com/mrdoob/three.js/commit/25ffb41e6467468d26a9dc317926f9832f17da35) by @mrdoob references [this pull request](https://github.com/mrdoob/three.js/pull/6509) by @elephantatwork. I've looked at it briefly but can't figure out what's actually happening in this change.

This affects people who need to serialize Three.js data to save on a server. I ran in to it trying to export shaders that have textures from [ShaderFrog](http://shaderfrog.com/app).

**A quick solution** is just to check for if `meta` is passed in to the `toJSON` function in the source before using. I'm happy to make this change, however because of the confusing nature of the commits and API, I don't know if that's the correct change in this case.
##### Three.js version
- :white_check_mark: Dev
- :white_check_mark: r75

### PR DESCRIPTION
**Pull request by autra**
This makes their toJSON method compatible with JSON.stringify.

This PR does not attempt to fix `AnimationClip` and `KeyframeTrack` `toJSON` objects, as they are not attached to their prototype and won't get used in a JSON.stringify call anyway.

Fixes #8581 #10236 #10248.

### CODE REVIEW

File: src/materials/Material.js [hunk 1]
```diff
@@ -131,7 +131,7 @@ Object.assign( Material.prototype, EventDispatcher.prototype, {
 
 	toJSON: function ( meta ) {
 
-		var isRoot = meta === undefined;
+		var isRoot = (meta === undefined || typeof meta === 'string' );
```
Comment (Mugen87) [inline src/materials/Material.js]: Just some code style issues: There must be a space inside this paren.
```javascript
var isRoot = ( meta === undefined || typeof meta === 'string' );
```

File: src/textures/Texture.js [hunk 2]
```diff
@@ -223,7 +225,9 @@ Object.assign( Texture.prototype, EventDispatcher.prototype, {
 
 		}
 
-		meta.textures[ this.uuid ] = output;
+		if ( !isRootObject ) {
```
Comment (Mugen87) [inline src/textures/Texture.js]: Block must be padded by blank lines:
```javascript
if ( ! isRootObject ) {

    meta.textures[ this.uuid ] = output;

}
```

File: src/textures/Texture.js [hunk 3]
```diff
@@ -126,7 +126,9 @@ Object.assign( Texture.prototype, EventDispatcher.prototype, {
 
 	toJSON: function ( meta ) {
 
-		if ( meta.textures[ this.uuid ] !== undefined ) {
+		var isRootObject = (meta === undefined || typeof meta === 'string' );
```
Comment (Mugen87) [inline src/textures/Texture.js]: same here...

File: src/textures/Texture.js [hunk 4]
```diff
@@ -126,7 +126,9 @@ Object.assign( Texture.prototype, EventDispatcher.prototype, {
...
+
+		if ( !isRootObject && meta.textures[ this.uuid ] !== undefined ) {
```
Comment (Mugen87) [inline src/textures/Texture.js]: Unary operator '!' must be followed by whitespace. These happens several times in your code.

```javascript
if ( ! isRootObject && meta.textures[ this.uuid ] !== undefined ) {
```

**Review by Mugen87 — CHANGES_REQUESTED** [review]

File: src/textures/Texture.js (hunk 2 above)
Comment (Mugen87) [reply src/textures/Texture.js]: You can use `npm run lint` to ensure your code is free of warnings...

**Comment by autra** [comment]
@Mugen87 I forgot to execute `npm run lint` before opening, sorry for that :-)

**Review by Mugen87 — APPROVED** [review]

**Comment by autra** [comment]
Thanks @Mugen87 ! Is there any action I need to do to get this merged?

**Comment by Mugen87** [comment]
@autra No, but @mrdoob needs to review this, too.

**Comment by mrdoob** [comment]
Thanks!
