### PR TITLE
LDrawLoader: Don't clear already-loaded materials onload.

### LINKED ISSUE #31149: LDrawLoader: Preloaded materials are discarded when loading non-packed models
### Description

If you preload LDraw materials in order to load an unpacked model, then when load() is called, the materials are discarded by this line:

https://github.com/mrdoob/three.js/blob/ed4a0fe55438c633817d1e07d5ee698cae156ed4/examples/jsm/loaders/LDrawLoader.js#L1910

That causes lots of "missing material" warnings, and a fatal error when rendering. If I comment that line out, then the materials load as expected and rendering works.

@Mugen87, you added that as part of the WebGPU support PR, #29752; does that affect how or when users should be loading the materials?

(This doesn't show in the example, as all the models are packed.)

### Reproduction steps

1. Preload LDraw materials
2. Load an unpacked LDraw file
3. Render

### Code

```
        loader.setConditionalLineMaterial(LDrawConditionalLineMaterial);
        loader.setPartsLibraryPath('https://raw.githubusercontent.com/gkjohnson/ldraw-parts-library/master/complete/ldraw/');
        await loader.preloadMaterials('https://raw.githubusercontent.com/gkjohnson/ldraw-parts-library/master/complete/ldraw/LDConfig.ldr');
```

### Live example

none at the moment

### Screenshots

_No response_

### Version

r0.176.0

### Device

Desktop

### Browser

_No response_

### OS

MacOS

### PR DESCRIPTION
**Pull request by Floppy**
Fixed #31149

LDraw materials that had been preloaded were being discarded by the load() method. Following suggestions by @Mugen87, this PR:

* renames `setMaterials` to `addMaterials`, and removes the reset of the material arrays.
* adds `clearMaterials` to explicitly clear the material arrays.
* re-adds `setMaterials` which calls clear then add, to reproduce the old behaviour and API.

### CODE REVIEW

**Comment by Floppy** [comment]
Tested and working!

Screenshot 2025-05-22 at 22 34 12

File: examples/jsm/loaders/LDrawLoader.js [hunk 1]
```diff
@@ -1949,9 +1949,17 @@ class LDrawLoader extends Loader {
...
+		this.clearMaterials();
+		this.addMaterials( materials );
+	}
 
+	clearMaterials() {
 		this.materialLibrary = {};
 		this.materials = [];
+	}
+
+	addMaterials( materials ) {
```
Comment (Mugen87) [inline examples/jsm/loaders/LDrawLoader.js:1961]: If `addMaterials()` would be called multiple times (and the `add*()` syntax implies this is intended), then the default materials get added twice. Can you make sure the default triangle and line edge materials are only added once?

Comment (Floppy) [reply examples/jsm/loaders/LDrawLoader.js:1961]: I'll take a look 👍🏻

**Comment by Floppy** [comment]
Just in case anyone wants to see it in action... https://manyfold.floppy.org.uk/models/5mhxr25tck64/model_files/lnd3c43pl62w

File: examples/jsm/loaders/LDrawLoader.js [hunk 2]
```diff
@@ -1949,15 +1949,29 @@ class LDrawLoader extends Loader {
 	}
 
 	setMaterials( materials ) {
+		this.clearMaterials();
+		this.addMaterials( materials );
```
Comment (gkjohnson) [inline examples/jsm/loaders/LDrawLoader.js:1953]: nit: lets adhere to the code style (blank lines to pad before / after function braces), and return `this` from the new functions so we're consistent with the existing function behavior.

File: examples/jsm/loaders/LDrawLoader.js (hunk 1 above)
Comment (Floppy) [reply examples/jsm/loaders/LDrawLoader.js:1969]: I've separated out the defaults into their own method, and explicitly called that on load(); I think that makes all the intents clearer.

File: examples/jsm/loaders/LDrawLoader.js (hunk 2 above)
Comment (Floppy) [reply examples/jsm/loaders/LDrawLoader.js]: Done! I was fighting against my own linter a bit :)

**Review by Mugen87 — APPROVED** [review]

**Review by gkjohnson — APPROVED** [review]

**Comment by Floppy** [comment]
Amazing, thank you all for your reviews and suggestions :)
