### PR TITLE
TSL: Fix `onDispose` listener not being removed in `Sampler`

### LINKED ISSUE #31866: TSL: `onDispose` listeners on PMREM textures grow indefinitely
### Description

Very similar to #31600, the event listeners on `PMREMNode`'s dispose event grow indefinitely. [webgpu_cubemap_dynamic](https://threejs.org/examples/?q=webgpu%20cube#webgpu_cubemap_dynamic) also reproduces this issue.

The code in question would be https://github.com/mrdoob/three.js/blob/r180/src/renderers/common/Textures.js#L349, which unconditionally adds event listener without checking whether it has already been added.

This prevents `WebGPURenderer` from running for more than an hour, because it has a significant impact on frame performance (presumably due to operations on a very large array in `EventDispatcher`).

### Reproduction steps

1. Open the [webgpu_cubemap_dynamic](https://threejs.org/examples/?q=webgpu%20cube#webgpu_cubemap_dynamic) in Chrome (it should also reproduce in other browsers).
2. Open the developer console, and select the “Memory” tab.
3. After running it for a few minutes, take a heap snapshot, navigate to Array > Array, sort by "Retained Size", and look the top entries (first and second).

### Code

A minimal reproduction follows. You can inspect the leak in the same steps as above.

```ts
const cubeRT = new WebGLCubeRenderTarget(64)
const cubeCamera = new CubeCamera(1, 1000, cubeRT)
const cubeScene = new Scene()
const material = new MeshStandardNodeMaterial({
  envMap: cubeRT.texture
})

const mesh = new Mesh(new PlaneGeometry(), material)
const camera = new PerspectiveCamera()
const scene = new Scene().add(mesh)

void renderer.setAnimationLoop(() => {
  cubeCamera.update(renderer, cubeScene)
  void renderer.render(scene, camera)
})
```

### Live example

https://jsfiddle.net/shotamatsuda/0Lfvz3yt/ (this directly counts the number of listeners)

### Screenshots

_No response_

### Version

r180

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by shotamatsuda**
Fixes: #31866

**Description**

This PR fixes that the event listeners on textures are not removed and grow indefinitely. Heap snapshots of `webgpu_cubemap_dynamic` no longer contain a large array of `onDispose` listeners.

### CODE REVIEW

File: src/renderers/common/Sampler.js [hunk 1]
```diff
@@ -52,6 +52,19 @@ class Sampler extends Binding {
...
 	}
 
+	/**
+	 * An event listener which is added to {@link texture}'s dispose event.
+	 *
+	 * @private
+	 */
+	_onTextureDispose() {
+
+		this._texture = null;
```
Comment (Mugen87) [inline src/renderers/common/Sampler.js]: I'm afraid this does not work. When `EventDispatcher` executes the callback, `this` will point to the texture, not the `Sampler` class.

Comment (shotamatsuda) [reply src/renderers/common/Sampler.js]: Oh, that's correct. It needs binding or to be an arrow function.

File: src/renderers/common/Sampler.js [hunk 2]
```diff
@@ -60,17 +73,9 @@ class Sampler extends Binding {
...
-
-			this._texture = null;
-			this.generation = null;
-			this.version = 0;
-
-		};
-
 		if ( this._texture ) {
 
-			this._texture.removeEventListener( 'dispose', onDispose );
```
Comment (Mugen87) [inline src/renderers/common/Sampler.js:73]: I understand now why this line fails. When the remove is eventually executed, `onDispose` represents a different listener, not the one that was originally added.

File: src/renderers/common/Sampler.js (hunk 1 above)
Comment (Mugen87) [reply src/renderers/common/Sampler.js]: Now the version is restored before #31751, introducing a different bug.

Comment (shotamatsuda) [reply src/renderers/common/Sampler.js]: Does `_onTextureDispose` have to be recreated when cloned?

Comment (Mugen87) [reply src/renderers/common/Sampler.js]: A sampler binding always has a reference to a texture. Before #31751, disposing textures can lead to sampler bindings which point to a destroyed textures. The texture is of course not rendered correctly and WebGPU warnings are displayed.

#31751 made sure that cloned samplers have correct dispose handlers by creating them inline. The issue is the removal is not implemented correctly since it refers to the wrong dispose handler. I think we can fix this issue by keeping track of the current dispose handler in a sampler property and use it in `removeEventListener()`.

Comment (Mugen87) [reply src/renderers/common/Sampler.js]: I'm not sure anymore if we need to create dispose inline. Can you please make a test with the fiddles from https://github.com/mrdoob/three.js/issues/31747#issuecomment-3223453560 and verify if the error pops up again.

Maybe just adding `clone()` was already sufficient to fix the issue.

Comment (shotamatsuda) [reply src/renderers/common/Sampler.js]: I'm seeing only the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at Texture.dispatchEvent (EventDispatcher.js:118:1)
    at Texture.dispose (Texture.js:644:1)
```

This should be caused by `this.texture = texture` in the constructor before populating `_onTextureDispose`, which needs to be moved before that line.

File: src/renderers/common/Sampler.js [hunk 3]
```diff
@@ -128,6 +136,13 @@ class Sampler extends Binding {
 		// TODO: Find better solution, see #31747
 
 		clonedSampler._texture = null;
+
+		clonedSampler._onTextureDispose = () => {
+
+			clonedSampler.texture = null;
+
+		};
```
Comment (shotamatsuda) [inline src/renderers/common/Sampler.js:144]: Because its an arrow function, it points to the original sampler if we just assign it to the cloned sampler.

File: src/renderers/common/Sampler.js [hunk 4]
```diff
@@ -21,8 +21,24 @@ class Sampler extends Binding {
 		/**
 		 * The texture the sampler is referring to.
 		 *
+		 * @private
 		 * @type {?Texture}
 		 */
+		this._texture = null;
```
Comment (shotamatsuda) [inline src/renderers/common/Sampler.js:27]: Since `texture` is compared with the strict equality operator in `set texture()`, we need to initialize it with `null` before setting it via the setter.

Comment (Mugen87) [reply src/renderers/common/Sampler.js:27]: Would this version work:
```js
import Binding from './Binding.js';

/**
 * Represents a sampler binding type.
 *
 * @private
 * @augments Binding
 */
class Sampler extends Binding {

	/**
	 * Constructs a new sampler.
	 *
	 * @param {string} name - The samplers's name.
	 * @param {?Texture} texture - The texture this binding is referring to.
	 */
	constructor( name, texture ) {

		super( name );

		/**
		 * The texture the sampler is referring to.
		 *
		 * @type {?Texture}
		 */
		this.texture = texture;

		/**
		 * The binding's version.
		 *
		 * @type {number}
		 */
		this.version = texture ? texture.version : 0;

		/**
		 * The binding's generation which is an additional version
		 * qualifier.
		 *
		 * @type {?number}
		 * @default null
		 */
		this.generation = null;

		/**
		 * This flag can be used for type testing.
		 *
		 * @type {boolean}
		 * @readonly
		 * @default true
		 */
		this.isSampler = true;

		/**
		 * An event listener which is added to {@link texture}'s dispose event.
		 *
		 * @private
		 * @type {Function}
		 */
		this._currentDispose = null;

	}

	/**
	 * Sets the texture of this sampler.
	 * @param {?Texture} value - The texture to set.
	 */
	set texture( value ) {

		if ( this._texture === value ) return;

		if ( this._texture ) {

			this._texture.removeEventListener( 'dispose', this._currentDispose );
			this._currentDispose = null;

		}

		this._texture = value;

		this.generation = null;
		this.version = 0;

		if ( this._texture ) {

			this._currentDispose = () => {

				this._texture = null;
				this.generation = null;
				this.version = 0;

			};

			this._texture.addEventListener( 'dispose', this._currentDispose );

		}

	}

	/**
	 * Gets the texture of this sampler.
	 * @return {?Texture} The texture.
	 */
	get texture() {

		return this._texture;

	}

	/**
	 * Updates the binding.
	 *
	 * @return {boolean} Whether the texture has been updated and must be
	 * uploaded to the GPU.
	 */
	update() {

		const { texture, version } = this;

		if ( version !== texture.version ) {

			this.version = texture.version;

			return true;

		}

		return false;

	}


	clone() {

		const clonedSampler = super.clone();

		// fix dispose handler for cloned instances
		// TODO: Find better solution, see #31747

		clonedSampler._texture = null;
		clonedSampler.texture = this.texture;

		return clonedSampler;

	}

}

export default Sampler;
```

Comment (shotamatsuda) [reply src/renderers/common/Sampler.js:27]: Yes, your code does basically the same thing as the changes I made. The only difference is whether to lazily initialize the dispose listener.

But your `_currentDispose` is recreated on every call (though it removes the previous one correctly). Is it really necessary?

Comment (Mugen87) [reply src/renderers/common/Sampler.js:27]: No, you version looks cleaner. Let's go with it. 

Like mentioned in the comments, the entire module needs some refactoring since the binding/texture handling is quite fragile and hard to follow right now.

**Review by Mugen87 — APPROVED** [review]

File: src/renderers/common/Sampler.js (hunk 4 above)
Comment (shotamatsuda) [reply src/renderers/common/Sampler.js:27]: I mean, doesn't it work just lazily initialize the listener like the following:

```ts
// Note that the strict equality operator doesn't work here because the assignment 
// via the setter occurs before `_currentDispose` is initialized with `null`.
if ( this._currentDispose == null ) {

	this._currentDispose = () => {

		this._texture = null;
		this.generation = null;
		this.version = 0;

	};

}
```

Comment (Mugen87) [reply src/renderers/common/Sampler.js:27]: Oh, did I merge too soon? If so, please make a new PR with your suggestion.

Comment (Mugen87) [reply src/renderers/common/Sampler.js:27]: > I mean, doesn't it work just lazily initialize the listener like the following:

I'm okay with it as long as the use case from https://github.com/mrdoob/three.js/issues/31747#issuecomment-3223453560 does not break again.

Comment (shotamatsuda) [reply src/renderers/common/Sampler.js:27]: > Oh, did I merge too soon?

No, our messages crossed. 😓
The code in `clone()` and the timing issue in the `texture` setter are hard to notice, though.
