### PR TITLE
Helpers: Clarify the usage of `update()`.

### LINKED ISSUE #32713: directional light camera helper is distorted
### Description

A `DirectionalLightHelper` for a `DirectionalLight` appears to be distorted.

### Reproduction steps

1. add a `DirectionalLight` 
2. add a `DirectionalLightHelper` for the light
3. add a `CameraHelper` for its `shadow.camera` just to compare

### Code

```js
  const dirLightHelper = new THREE.DirectionalLightHelper( dirLight, 5 );
  scene.add( dirLightHelper );

  const dirLightCameraHelper = new THREE.CameraHelper( dirLight.shadow.camera );
  scene.add( dirLightCameraHelper );
```

### Live example

* https://jsfiddle.net/9smjwdpk

### Screenshots

I think the expectation is that the light helper's direction line should be aligned and parallel with that of the shadow camera helper's direction line, but we see that it wobbles around during animation:

https://github.com/user-attachments/assets/c84856bb-1484-404e-96c8-d012362c43d0

### Version

r182

### Device

Desktop

### Browser

Safari

### OS

MacOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #32713.

**Description**

As suggested in https://github.com/mrdoob/three.js/issues/32713#issuecomment-3734091873, the PR clarifies the usage of `update()` method in some helper classes.

### CODE REVIEW

File: src/helpers/DirectionalLightHelper.js [hunk 1]
```diff
@@ -11,9 +11,12 @@ const _v3 = /*@__PURE__*/ new Vector3();
 
 /**
  * Helper object to assist with visualizing a {@link DirectionalLight}'s
- * effect on the scene. This consists of plane and a line representing the
+ * effect on the scene. This consists of a plane and a line representing the
  * light's position and direction.
  *
+ * When the directional light is transformed or its light properties are changed,
```
Comment (WestLangley) [inline src/helpers/DirectionalLightHelper.js]: Also `light.target`.
