### PR TITLE
BatchedMesh: Fix exception when using Geometry with InterleavedBuffers

### LINKED ISSUE #27973: BatchedMesh: Exception with InterleavedBufferAttribute
### Description

Batched mesh `addGeometry` throws exception for geometry with InterleavedBufferAttributes

### Reproduction steps

1. checkout https://github.com/needle-tools/three.js/tree/batched-mesh-interleaved-buffer
2. run webgl_mesh_batch example
3. observe error

The mesh was processed with gltf-transform and simplified
```
weld: primitive[0] of mesh "Sphere" → tolerance: 0.0001
weld: Tolerance thresholds: POSITION=0.0001, NORMAL=0.05, TANGENT=0.05, TEXCOORD_0=0.0001, TEXCOORD_1=0.0001
weld: 515 → 515 (+0.00%) vertices.
simplify: primitive[0] of mesh "Sphere" → ratio: 0.0625, error: 0.3, lockBorder: true
simplify: 515 → 92 (–82.14%) vertices, error: 0.1558.
sparse: Updated 0 accessors.
sparse: Complete.
```

### Code

see https://github.com/mrdoob/three.js/commit/54b78a08828f71dca2135c0c52645465aa5eac8c

[Sphere.zip](https://github.com/mrdoob/three.js/files/14728012/Sphere.zip)

### Live example

I have to submit this another time if necessary

### Screenshots

image
image

image

### Version

162

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by marwie**
Fixed https://github.com/mrdoob/three.js/issues/27973

**Description**

Adding geometry that has interleaved buffers currently throws because `setUsage` is not defined on the InterleavedBufferAttribute.
The PR enforces dstAttribute to `new BufferAttribute` and removes the call to `setUsage` as suggested by @gkjohnson 

*This contribution is funded by [🌵 Needle](https://needle.tools)*

### CODE REVIEW

**Comment by gkjohnson** [comment]
I haven't tested it but this looks good to me.

**Review by gkjohnson — APPROVED** [review]

File: src/objects/BatchedMesh.js [hunk 1]
```diff
@@ -195,8 +195,7 @@ class BatchedMesh extends Mesh {
 				const { array, itemSize, normalized } = srcAttribute;
 
 				const dstArray = new array.constructor( maxVertexCount * itemSize );
-				const dstAttribute = new srcAttribute.constructor( dstArray, itemSize, normalized );
-				dstAttribute.setUsage( srcAttribute.usage );
```
Comment (Mugen87) [inline src/objects/BatchedMesh.js:199]: But...isn't honoring `usage` a good thing. Let's say you are using `DynamicDrawUsage` because you frequently want to update attribute data then the original setting is now lost.

Comment (gkjohnson) [reply src/objects/BatchedMesh.js:199]: I think if the user need to do this they can set it on `BatchedMesh.geometry` attributes directly. I'm not sure if this is something that I see needs to be copied from the original geometry but I could be convinced. The update usage of BatchMesh may not match the update usage for the first geometry passed to the function.

Comment (Mugen87) [reply src/objects/BatchedMesh.js:199]: Okay, we can add it back later, too, if a user reports any issues with this change.
