### PR TITLE
BufferGeometryUtils: Add mergeBufferGeometries() helper.

### LINKED ISSUE #9468: BufferGeometry.prototype.merge not working
```
a = new THREE.PlaneBufferGeometry( 1, 1, 2 )
b = new THREE.PlaneBufferGeometry( 1, 1, 2 )
console.log( a.attributes.position.array.length )
a.merge( b )
console.log( a.attributes.position.array.length )

Output:
18
18 (should be 36)
```

r79

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes #9468, #6188, and partially addresses #11944.

Alternative to #8162, #9529, #12795, and #12804.

I'd like to have this utility for GLTFLoader, so that primitives can be loaded as BufferGeometry groups. Adds a warning to `BufferGeometry.prototype.merge()` when it is called without an offset, as I believe the current behavior is probably not what many are expecting.

I think this approach is comparatively complete, covering indexed and non-indexed geometry, preserving morph targets, ~~and creating geometry groups. Users who do not want the groups may simply call `.clearGroups()` on the result. Although, perhaps a better name would be `groupBufferGeometries( geometries )`?~~

### CODE REVIEW

**Comment by donmccurdy** [comment]
> I believe it does not make sense to merge geometries that require different materials, as the merged geometry must be rendered with separate draw calls anyway.

For the multi-materials case I'm thinking of #11944 in GLTFLoader, and just trying to have a simpler single-mesh output when glTF specifies one mesh with multiple materials. But optimizing performance seems like the more important use case for merging geometry, so happy to treat that as the primary goal here, not multiple materials.

> If I understand correctly, it seems you are ignoring the existing groups in each geometry, while simultaneously creating new groups by assigning each merged geometry a different material index. 

Correct, this code isn't checking for existing groups.

> I'm thinking a reasonable argument can be made that it makes sense to ignore groups altogether when merging. But I don't have a strong opinion on this one way or the other.

Groups could still be added after calling this method, yes. It would also be fairly easy to change the signature to: `mergeBufferGeometries( geometries, useGroups = false )`, creating groups and retaining existing ones only if `useGroups=true`. I'm fine with either.

**Comment by WestLangley** [comment]
I'm fine with however you want to handle this. :)

**Comment by donmccurdy** [comment]
Ok thanks — removed the creation of groups. I think that part could be generalized to a `mergeMeshes()` method later, where dealing with multiple materials would feel more appropriate.

With that change, this doesn't fully address #11944, but still covers everything else. I'll adjust GLTFLoader accordingly soon.

**Comment by donmccurdy** [comment]
Removed the GLTFLoader part of this PR for now, since that would need to deal with multiple materials.

**Comment by mrdoob** [comment]
Do you mind resolving the conflicts? 😇

**Comment by donmccurdy** [comment]
Done ✅

**Comment by mrdoob** [comment]
Thanks!

**Comment by makc** [comment]
too bad you guys lost matrices args along the way. the use case I was hoping to use this for was to group a bunch of separate objects together, but it looks like now I have to explicitly apply their transformations to geometries before merging.

**Comment by looeee** [comment]
The matrix transformation is applied at the `Object3D` level anyway, it wouldn't make sense to apply it to `BufferGeometry` when merging since geometries don't have a matrix. 

But a `mergeMeshes` utility that does this would be a nice addition.

File: examples/js/BufferGeometryUtils.js [hunk 1]
```diff
@@ -182,6 +182,194 @@ THREE.BufferGeometryUtils = {
...
+
+			}
+
+			// gather .userData
+
+			if ( geometry.userData !== undefined ) {
+
+				mergedGeometry.userData = mergedGeometry.userData || {};
+				mergedGeometry.userData.mergedUserData = mergedGeometry.userData.mergedUserData || [];
+				mergedGeometry.userData.mergedUserData.push( geometry.userData );
```
Comment (takahirox) [inline examples/js/BufferGeometryUtils.js]: `BufferGeometry` doesn't have `.userData` property. Perhaps only `GLTFLoader` can set from glTF `primitive.extras`. (Any other loaders/modules can also set?) So, is this merging for `GLTFLoader` special?

**Comment by donmccurdy** [comment]
Oh, good point. Yes apparently it is glTF-specific. Probably deserves a comment, or maybe we can revisit whether GLTFLoader should do this..

File: examples/js/BufferGeometryUtils.js (hunk 1 above)
Comment (donmccurdy) [reply examples/js/BufferGeometryUtils.js]: Oh, good point. Yes apparently it is glTF-specific. Probably deserves a comment, or maybe we can revisit whether GLTFLoader should do this..

Comment (takahirox) [reply examples/js/BufferGeometryUtils.js]: I don't think it's a good idea to pollute `BufferGeometry` with Three.js unofficial property. For example, it can be lost in serialization. I prefer officially adding `.userData` property to `BufferGeometry`.

@mrdoob What do you think of adding `.userData` property to `BufferGeometry`?
