### PR TITLE
GLTFLoader: Fix node parse

### LINKED ISSUE #25332: GLTFLoader: Unable to load some SkinnedMesh objects in r148
### Description

GLTFLoader did load correctly with this file before the GLTFloader optimisations : 
https://github.com/mrdoob/three.js/pulls?q=is:pr+GLTFLoader+is:closed+milestone:r148+in:title

File : 
https://res.cloudinary.com/oncyber-io/image/upload/v1666818159/assets/WorkerBot_Posed_10_24_1_eyoaob.glb

Recursive errors on it on threejs editor loader

Screenshot 2023-01-25 at 16 37 39

### Reproduction steps

1. Go to threejs editor
2. Drap and drop glb
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

_No response_

### Version

last

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by takahirox**
Fixed #25332.

**Description**

This commit fixes a `GLTFLoader` node parse bug that can cause an infinite loop in node parse - skin parse - node parse.

The solution is adding `._loadNode()` that parses a single node without child nodes or skin to the parser. `.loadNode()` and `.loadSkin()` call `._loadNode()` to get dependent nodes. `._loadNode()` doesn't have dependency with other nodes so infinite loop can be avoided.

`._loadNode()` caches created nodes to avoid duplication because it is called from two different methods, `.loadNode()` and `.loadSkin()`.

/cc @donmccurdy

### CODE REVIEW

File: examples/jsm/loaders/GLTFLoader.js [hunk 1]
```diff
@@ -3631,6 +3635,10 @@ class GLTFParser {
 			const inverseBindMatrices = results.pop();
 			const jointNodes = results;
 
+			// Note that bones (joint nodes) may or may not be in the
+			// scene graph at this time.
+			// Child nodes are added in .loadNode() (no '_' prefix).
```
Comment (donmccurdy) [inline examples/jsm/loaders/GLTFLoader.js:3640]: The comment might be a little misleading because this function, .loadSkin, has just been invoked by .loadNode, but not necessarily the same .loadNode call that is going to populate the joints of this skin. I would probably just remove the second sentence, "Child nodes are..." and try to clarify the method names instead. How about this?

- `.loadNode`
- `.loadNodeShallow`

With or without the underscore is fine with me!

File: examples/jsm/loaders/GLTFLoader.js [hunk 2]
```diff
@@ -3879,18 +3887,91 @@ class GLTFParser {
...
+
+		}
+
 		const nodeDef = json.nodes[ nodeIndex ];
 
 		// reserve node's name before its dependencies, so the root has the intended name.
 		const nodeName = nodeDef.name ? parser.createUniqueName( nodeDef.name ) : '';
 
-		return ( function () {
+		this.nodeCache[ nodeIndex ] = ( function () {
```
Comment (donmccurdy) [inline examples/jsm/loaders/GLTFLoader.js:3972]: if we remove the IIFE here, we could move this cache assignment about 40 lines closer to the end of the function, so it may be easier to read and see what it caches — would that be OK?

File: examples/jsm/loaders/GLTFLoader.js [hunk 3]
```diff
@@ -3879,18 +3887,91 @@ class GLTFParser {
...
+				? Promise.resolve( null )
+				: parser.getDependency( 'skin', nodeDef.skin );
+
+			return Promise.all( [
+				nodePending,
+				Promise.all( childPending ),
+				skeletonPending
+			] );
+
+		}() ).then( function ( results ) {
```
[the remark this answers is not in the document]
Comment (takahirox) [reply examples/jsm/loaders/GLTFLoader.js:3918]: This IIFE closure seems to have been introduced at some point for a certain reason but I couldn't track.

I agree with wriging without IIFE closure because it would be more readable. But do you think it's ok for you to do that in another PR? It will be easier to revert if this IIFE closure is really needed for something special reasons.

File: examples/jsm/loaders/GLTFLoader.js (hunk 2 above)
Comment (takahirox) [reply examples/jsm/loaders/GLTFLoader.js:3972]: Yes, that sounds good to me.

File: examples/jsm/loaders/GLTFLoader.js (hunk 1 above)
Comment (takahirox) [reply examples/jsm/loaders/GLTFLoader.js]: Thanks for renaming suggestion. I know I'm bad at naming in English so renaming suggestion is always helpful to me.

I renamed `._loadNode` to `._loadNodeShallow`. I'm not sure we should really expose the method from the parser so didn't remove the underscore but we may rename later if users request.

Comment (donmccurdy) [reply examples/jsm/loaders/GLTFLoader.js]: Doesn't need to be a public method, agreed! :)

**Review by donmccurdy — APPROVED** [review]
