### PR TITLE
GLTFExporter: Fix export of multi-material meshes.

### LINKED ISSUE #16263: GLTFExporter: Unable to export multi material object.
##### Description of the problem

If you import the following `OBJ` file into the editor, it looks like so:

[house.obj.zip](https://github.com/mrdoob/three.js/files/3084700/house.obj.zip)

image

If you now export to `glTF` and load it into a [glTF viewer](https://gltf-viewer.donmccurdy.com/), it seems certain parts of the model are missing:

image

The house model is a multi-material asset. It seems the exporter only respect the parts with the first material applied.

Original issue: https://discourse.threejs.org/t/scene-quality-doesnt-match-when-exported-compared-to-first-time-load-scene/7099

##### Three.js version

- [x] Dev
- [x] r103
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #16263

### CODE REVIEW

**Review by donmccurdy — APPROVED** [review]

**Comment by takahirox** [comment]
I remember that `.uuid` has memory consumption problem and we discussed if we should introduce lazy `.uuid` generation. We haven't introduced yet but I think just in case I prefer less using `uuid` as much as possible.

And `cachedData.attributes` is also used for `geometry.attributes` and `geometry.morphAttributes`. Cache key is `attribute` (`BufferAttribute` instance) for them. So, I know it's very rare case but, if `geometry.attributes/morphAttributes` and `geometry.index` refer to the same `BufferAttribute` instance, they're distinguished.

I think even if it's a bit complicated but making utility functions like below may be less problematic. What do you think? 

```javascript

// geometry.attributes/morphAttributes

if ( hasAttributeCache( attribute ) ) {

    result = getAttributeCache( attribute );

} else {

    result = foo;
    setAttributeCache( result, attribute );

}


// geometry.index

if ( hasAttributeCache( attribute, start, count ) ) {

    result = getAttributeCache( attribute, start, count );

} else {

    result = foo;
    setAttributeCache( result, attribute, start, count );

}

function hasAttributeCache( attribute, start, count ) {

    return cachedData.attributes.has( attribute ) &&
        cachedData.attributes.get( attribute ).has( start ) &&
        cachedData.attributes.get( attribute ).get( start ).has( count );

}

function getAttributeCache( attribute, start, count ) {

    return cachedData.attributes.get( attribute ).get( start ).get( count );

}

function setAttributeCache( data, attribute, start, count ) {

    if ( ! cachedData.attributes.has( attribute ) ) {

        cachedData.attributes.set( attribute, new Map() );

    }

    if ( ! cachedData.attributes.get( attribute ).has( start ) ) {

        cachedData.attributes.get( attribute ).set( start, new Map() );

    }

    cachedData.attributes.get( attribute ).get( start ).set( count, data );

}
```

**Comment by takahirox** [comment]
```
var cacheKey = geometry.uuid + ':' + groups[ i ].start + ':' + groups[ i ].count;
```

Plus, using `geometry.uuid` for cache key. So even if another `geometry.index` refers to the same `BufferAttribute` instance, it's distinguished.

**Review by takahirox — CHANGES_REQUESTED** [review]
https://github.com/mrdoob/three.js/pull/16265#issuecomment-483727813

**Comment by Mugen87** [comment]
> So even if another geometry.index refers to the same BufferAttribute instance, it's distinguished.

You mean `BufferGeometry` instance, right? Otherwise I do not understand this statement.

I suggest we merge this PR for now so the user in the forum has a fixed version of `GLTFExporter`. Further improvements can be done in a separate PR. It feels weird to copy/paste all of your code so it's better when you make the PR 😊

**Comment by takahirox** [comment]
TBH, I don't think we should merge because this PR solves an issue but adds another regression. If you're in hurry, I can make another PR now.

**Comment by takahirox** [comment]
Ah, you already merged. OK I'll make PR.

**Comment by donmccurdy** [comment]
> I remember that .uuid has memory consumption problem and we discussed if we should introduce lazy .uuid generation (or other solutions). We haven't concluded whether we should but I think just in case I prefer less using uuid as much as possible.

I don't think I agree with this... export is an expensive operation, and a very reasonable time to use `.uuid` even if it has overhead. That overhead is small compared to serializing the entire scene. Avoiding UUID within the render loop is reasonable of course.

**Comment by takahirox** [comment]
My concern in not time but memory consumption. If we introduce lazy uuid generation and if exporter refers objects uuid which are not generated yet, uuids are generated at that time. Total memory consumption increases. And the objects don't release their uuids. If the objects are kept using, total memory consumption keeps big.

File: examples/js/exporters/GLTFExporter.js [hunk 1]
```diff
@@ -1358,14 +1358,16 @@ THREE.GLTFExporter.prototype = {
 
 				if ( geometry.index !== null ) {
 
-					if ( cachedData.attributes.has( geometry.index ) ) {
+					var cacheKey = geometry.uuid + ':' + groups[ i ].start + ':' + groups[ i ].count;
+
+					if ( cachedData.attributes.has( cacheKey ) ) {
 
 						primitive.indices = cachedData.attributes.get( geometry.index );
```
Comment (takahirox) [inline examples/js/exporters/GLTFExporter.js]: Already merged and I'm fixing in #16267, but just in case. Not `cachedData.attributes.get( geometry.index )` but `cachedData.attributes.get( cacheKey )`.

Comment (Mugen87) [reply examples/js/exporters/GLTFExporter.js]: Thanks for that. Already fixed with #16272.

**Comment by mrdoob** [comment]
Thanks!
