### PR TITLE
WebGLTextures: More flexible image dimensions computation.

### LINKED ISSUE #23164: Couldn't create Texture from resized DOM Image
**Describe the bug**
If the DOM image is resized with CSS, like: `width: 10%`, and you try to create texture with THREE.Texture(DOM_ELEMENT) class, that will result in:
```GL ERROR :GL_INVALID_VALUE : glTexSubImage2D: bad dimensions.```
The behaviour appears since v135. It is not present in v134.

**To Reproduce**

1. Create a DOM image in HTML
2. Resize it with CSS: img{width: 10%}
3. Create a texture from image with THREE.Texture(DomElement) class
4. Use texture on any material
5. You will get: GL ERROR :GL_INVALID_VALUE : glTexSubImage2D: bad dimensions. in latest Chrome.

***Code***

```js
  let material = new THREE.MeshBasicMaterial();
  let img = document.querySelector('img')
  let texture = new THREE.Texture(img)
  texture.needsUpdate = true;
  material.map = texture;
  mesh = new THREE.Mesh( geometry, material );
  scene.add( mesh );
```

***Live example***

* ~[jsfiddle-latest-release](https://jsfiddle.net/akella/roncdu7g/1/) (forgot to set display:block here, hence new demo)~
* [bug](https://jsfiddle.net/akella/roncdu7g/4/)

**Expected behavior**

To see sphere with kitten texture.

**Screenshots**

This is the expected result of demo.
Screenshot 2022-01-07 at 01 51 56

**Platform:**

 - Device: Desktop
 - OS: MacOs
 - Browser: Chrome
 - Three.js version: r136

### LINKED ISSUE #27783: `VideoFrame` not supported as Texture source
### Description

Passing a [VideoFrame](https://developer.mozilla.org/en-US/docs/Web/API/VideoFrame/VideoFrame) to a `Texture` causes GL_INVALID issues even though the texture type says it supports all `TexImageSource`'s of which `VideoFrame` is included, which is why I'm classifying this as a bug.

### Reproduction steps

See jsfiddle.

### Code

```
// throws GL_INVALID_VALUE and GL_INVALID_OPERATION errors on render
const texture = new CanvasTexture(videoFrame);
```

```
// does not throw GL_INVALID_VALUE and GL_INVALID_OPERATION errors on render and works fine
videoFrame.width = videoFrame.displayWidth;
videoFrame.height = videoFrame.dispayHeight;

const texture = new CanvasTexture(videoFrame);
```

### Live example

If code in example that sets width/height is uncomment, VideoFrames would be supported.

NOTE: looks like the fiddle needs to be saved before it runs or else it errors because the video element can't be played.

https://jsfiddle.net/snosenzo/qtn4fazy/32/

### Screenshots

image

### Version

r161

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #23164.
Fixed #27783.

**Description**

The above issues convinced me to make the renderer a bit more flexible in the way it derives image dimensions. This PR introduces a new function in `WebGLTextures` called `getDimensions()` that derives the image dimensions depending on the image type. So `width` and `height` are still the defaults but instances of `HTMLImageElement` now use `naturalWidth` and `naturalHeight` if available. Instances of `VideoFrame` are now supported by using `displayWidth` and `displayHeight`.

To minimize the change set, `getDimensions()` is only used at places in `WebGLTextures` where instances of `HTMLImageElement` or `VideoFrame` can actually occur. So e.g. not in the code paths for data or compressed textures.

### CODE REVIEW

File: src/renderers/webgl/WebGLTextures.js [hunk 1]
```diff
@@ -2153,6 +2165,28 @@ function WebGLTextures( _gl, extensions, state, properties, capabilities, utils,
 
 	}
 
+	function getDimensions( image ) {
+
+		const dimensions = new Vector2( image.width, image.height );
```
Comment (WestLangley) [inline src/renderers/webgl/WebGLTextures.js:2170]: Create one instance and reuse it?

**Comment by Mugen87** [comment]
Side note: If it turns out in production that this change works well, we can adapt the same policy to `WebGPURenderer`.
