### PR TITLE
SSAO: New implementation

### LINKED ISSUE #8576: SSAO example is broken, just darkening based on normal direction
##### Description of the problem

The SSAO shader should produce darker output in areas that are more enclosed.  The current SSAO example actually is just using the normal derived from the depth buffer and making it darker the more they are not facing the camera.

Not sure what it is trying to do but the current implementation is just broken - it is more like a directional light facing in the same direction as the camera:

image

Link: http://threejs.org/examples/#webgl_postprocessing_ssao

Here is what an SSAO/SAO implementation should look like - enclosed regions are darkened, everything else (including non-camera facing normals) should be left alone:

ao comparison 1

Link: https://clara.io/view/76f2e700-042d-4c80-bf0b-19e18d262513
...
##### Three.js version
- [x] Dev
- [x] r75
- [ ] ...
##### Browser
- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
##### OS
- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

### PR DESCRIPTION
**Pull request by Mugen87**
This PR introduces a new screen space ambient occlusion (SSAO) shader. Most of the implementation is based on John  Chapman's [article](http://john-chapman-graphics.blogspot.com/2013/01/ssao-tutorial.html) about SSAO.

The code hopefully fixes #8576 since it's provides a more or less real ambient occlusion effect.

As mentioned by a [user](http://john-chapman-graphics.blogspot.com/2013/01/ssao-tutorial.html?showComment=1367624542487#c1527234297842232685) in the linked article, the implemented blur shader produces a thin halo of non-occlusion when there are high frequencies in the depth buffer (steep changes of depth values). I guess the usage of `DepthLimitedBlurShader` might solve this issue, but it's a more complex blur and thus computationally more expensive (and in general not necessary in all use cases).

### CODE REVIEW

**Comment by mrdoob** [comment]
Sweet!

**Comment by mrdoob** [comment]
Many thanks!

**Comment by looeee** [comment]
On my laptop it looks great:

ssao-laptop

But on my mobile it's very jagged:

ssao-mobile

Is it dependant on device resolution? 

Also, "Beauty" output is just the diffuse color, right? Is there a reason why it's called "Beauty" and not "Diffuse"?

**Comment by Mugen87** [comment]
> Is it dependant on device resolution?

The render result gets better when the device has a higher resolution, sure. The demo does currently not regard the pixel device ratio since `SSAO` is already an expensive post-processing pass and because of #14340.

> Is there a reason why it's called "Beauty" and not "Diffuse"?

Yes. It's actually a common term in context of post processing to name the default render pass "beauty pass". I think this is actually better than "diffuse" since "diffuse" is already used in context of lighting models. 

BTW: You find the term "Beauty" in other demos, too (e.g. [here](https://threejs.org/examples/#webgl_postprocessing_sao)).

**Comment by looeee** [comment]
>  I think this is actually better than "diffuse" since "diffuse" is already used in context of lighting models

OK, makes sense, although the choice of the word "Beauty" still seems a little random to me in this context. 

> The demo does not currently set the pixel device ratio since SSAO is already an expensive post-processing pass 

My mobile (Moto G6) has a pixel ratio of 3, so that's probably the issue here.

File: examples/js/postprocessing/SSAOPass.js [hunk 1]
```diff
@@ -1,190 +1,375 @@
...
-				return this.uniforms[ 'radius' ].value;
+		renderer.setClearColor( 0x000000 );
+		renderer.render( this.scene, this.camera, this.beautyRenderTarget, true );
 
-			},
-			set: function ( value ) {
+		// render normals
 
-				this.uniforms[ 'radius' ].value = value;
+		this.renderOverride( renderer, this.normalMaterial, this.normalRenderTarget, 0x7777ff, 1.0 );
```
Comment (WestLangley) [inline examples/js/postprocessing/SSAOPass.js]: This is changing the background color and not being reset to the original value, apparently.

Comment (Mugen87) [reply examples/js/postprocessing/SSAOPass.js]: `.renderOverride()` should actually reset the original state at the end of the method.

Comment (WestLangley) [reply examples/js/postprocessing/SSAOPass.js]: To demonstrate, in `webgl_postprocessing_ssao.html`, remove the scene background:
```javascript
//scene.background = new THREE.Color( 0xa0a0a0 );
```
and add a call to render
```javascript
effectComposer.render();
renderer.render( scene, camera );
```

Comment (Mugen87) [reply examples/js/postprocessing/SSAOPass.js]: I think I've found the problem right [here](https://github.com/mrdoob/three.js/blob/e94fd574f52bd8d2e6f03e47913d577806c0f5ad/examples/js/postprocessing/SSAOPass.js#L262). `WebGLRenderer.getClearColor()` returns no copy of the color. If the color is [later](https://github.com/mrdoob/three.js/blob/e94fd574f52bd8d2e6f03e47913d577806c0f5ad/examples/js/postprocessing/SSAOPass.js#L275) modified, it also affects the original value. A simple fix would be:
```js
this.originalClearColor.copy( renderer.getClearColor() );
```
and later
```js
renderer.setClearColor( this.originalClearColor );
```

Comment (WestLangley) [reply examples/js/postprocessing/SSAOPass.js]: Would #15212 have been helpful in this case, or are there problems with that, too?

Comment (Mugen87) [reply examples/js/postprocessing/SSAOPass.js]: Not sure. This seems app-level logic to me. Maybe it's better if the app saves and restores these values. Especially if you need to save/restore more than just a single pair of clear color and alpha values.

Comment (WestLangley) [reply examples/js/postprocessing/SSAOPass.js]: >This seems app-level logic to me.

Granted. I just see the same patterns used over and over...

Comment (Mugen87) [reply examples/js/postprocessing/SSAOPass.js]: If these methods are added, users could ask for the possibility to save multiple states (think of vertex array objects that represent binding states) and restore/load them with a ID or a name. I think stuff like that would bloat the API of `WebGLRenderer`.

Comment (WestLangley) [reply examples/js/postprocessing/SSAOPass.js]: >If these methods are added, users could ask for the possibility...

Anything could happen. Sorry, I'm not buying that as a very compelling argument.

>This seems app-level logic to me.

That's a reasonable argument.

File: examples/js/postprocessing/SSAOPass.js [hunk 2]
```diff
@@ -1,190 +1,375 @@
...
- * @class SSAOPass
+ * @author Mugen87 / https://github.com/Mugen87
  */
+
 THREE.SSAOPass = function ( scene, camera, width, height ) {
 
+	THREE.Pass.call( this );
+
+	this.width = ( width !== undefined ) ? width : 512;
+	this.height = ( height !== undefined ) ? height : 512;
```
Comment (moraxy) [inline examples/js/postprocessing/SSAOPass.js]: `this.width` and `this.height` are set here, but the code below still uses normal `width` and `height` to setup the `WebGLRenderTarget`s and the `resolution` uniforms. This causes `WebGLRenderTarget` to be created with `undefined` dimensions on start before getting resized by `onWindowResize`.  
Could that cause any strange problems on devices with bad WebGL implementations later on (the jaggedness on mobile devices for example)?

Comment (Mugen87) [reply examples/js/postprocessing/SSAOPass.js]: Good catch! Let me fix this.
