### PR TITLE
WebGLRenderer: convert to ES6 class 

### LINKED ISSUE #25595: Build Size grows 5x with ThreeJs 0.150.0
### Description

I installed **threejs** in a vite project ( **vite ^4.0.0**). 
The threejs version was 0.150.0, the build size was 500kb. 
After changing the the three js version to 0.148.0 the build size reduced to 100kb.

There is a huge difference in build size between these threejs versions. Whats causing this issue?

### Reproduction steps
1. Create a vanilla typescript vite project
2. Install threejs v ^0.150.0 and import it
3. run vite build 
4. remove threejs v ^0.150.0
5. Install threejs v ^0.148.0 and import it
6. run vite build

Check the difference in build size.

### Screenshots

**three V 0.150.0 Build**
high

**three V 0.148.0 Build**
low

**Vite config**
viteconfig

### Version

0.150.0

### Device

Desktop

### Browser

Chrome

### OS

_No response_

### PR DESCRIPTION
**Pull request by marcofugaro**
Related issue: Fixes #25595

**Description**
In order to prevent the same issue in the future, I think it's safer to convert the WebGLRenderer to ES6 class as well.

This way the `physicallyCorrectLights` can be a getter/setter of the class, which doesn't break tree-shaking.

### CODE REVIEW

File: src/renderers/WebGL1Renderer.js [hunk 1]
```diff
@@ -1,7 +1,13 @@
 import { WebGLRenderer } from './WebGLRenderer.js';
 
-class WebGL1Renderer extends WebGLRenderer {}
+class WebGL1Renderer extends WebGLRenderer {
 
-WebGL1Renderer.prototype.isWebGL1Renderer = true;
+	constructor( parameters = {} ) {
+
+		super( { ...parameters, isWebGL1Renderer: true } );
```
Comment (mrdoob) [inline src/renderers/WebGL1Renderer.js:7]: Can we do like in [`Vector3`](https://github.com/mrdoob/three.js/blob/dev/src/math/Vector3.js#L8) instead?

```js
WebGL1Renderer.prototype.isWebGL1Renderer = true;
```

Comment (marcofugaro) [reply src/renderers/WebGL1Renderer.js]: You are right, for some reason I tought it wouldn't work with a class, but it does.

Done!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Should we merge this after #25615 so we can test the new CI feature?

**Comment by marcofugaro** [comment]
Hmm the action worked but there has been a problem in the CI, fixed it in #25625

**Comment by LeviPesin** [comment]
> -0.04%

Maybe the action should also report an absolute value by how the size changed? I.e. not in percents but in KB.

**Comment by mrdoob** [comment]
> Maybe the action should also report an absolute value by how the size changed? I.e. not in percents but in KB.

That'd be nice yeah.
