### PR TITLE
SkeletonUtils: Add clone() helper for skinned meshes.

### LINKED ISSUE #5878: geometry.clone() doesn't copy reference to bones/skinweights/animations etc.
There are a few things which geometry.clone() doesn't copy a reference to, which it should.

.bones
.skinWeights
.skinIndices
.animations
.animation

are all left without references to the original, which leads to skinning being broken unless the references to those are manually copied. I think references should be passed as it's less confusing, but I don't think they should be deep copies, or this would lead to mostly wasted memory.

### LINKED ISSUE #11574: No way of cloning a mesh so it works with a skinning material
Skinned material need their own geometry to work. This is because the material deforms the geometry, so if you share the same geometry between two meshes with deformation, things are going to get weird (at least that's how I understand it).

Now the problem is, if you load a mesh from a FBX or something else and it contains at some point a skinned mesh, and you need multiple instances of it, here's what happens:

* You call `clone();` on the mesh to generate your new instances
* The `clone` function doesn't generate a new geometry, so both models share geometry, and things gets bad (the mesh doesn't appear at all).

Here's a code sample: I was able to replicate this problem in the `webgl_loader_fbx.html` demo with a simple modification: Just clone the mesh once loaded before using it, and you'll see that the cloned version of it doesn't work:

```js
loader.load( 'models/fbx/xsi_man_skinning.fbx', function( originalObject ) {

	// Using a clone of the mesh, it won't work
	var object = originalObject.clone();
	object.mixer = new THREE.AnimationMixer( object );
	mixers.push( object.mixer );

	var action = object.mixer.clipAction( object.animations[ 0 ] );
	action.play();

	scene.add( object );


}, onProgress, onError );
```

Is there a way to fix this behaviour? Like a deep clone function that also recreates geometries?

If not, should I just write a function that recursively recreates all the meshes in my object, regenerating their geometry? Or is it a bad idea?

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes https://github.com/mrdoob/three.js/issues/5878, fixes https://github.com/mrdoob/three.js/issues/11574.

Adds a helper method, `SkeletonUtils.clone( object )` that preserves SkinnedMesh/Bone relationships. Ideally this would "just work" with the usual `object.clone()`, but I can't see any clean way of doing that — bones are not necessarily children of the SkinnedMesh(es?) they're associated with, and trying to connect them requires logic that would need to live somewhere outside the recursive callback series. This helper method provides an easy way to work around the problem.

Based on https://gist.github.com/zellski/be4e9207ab8e70c4e89062d48ce345ba#file-gltf_utils-js-L19 by @zellski and https://gist.github.com/cdata/f2d7a6ccdec071839bc1954c32595e87 by @cdata.

### CODE REVIEW

**Comment by Mugen87** [comment]
I think it's good to have this function as a work around until we solve the real problem and have a consistent approach for skeleton animation in `three.js`.

**Comment by takahirox** [comment]
I haven't follow up the discussion yet, but why is cloning method for `SkinnedMesh` in `AnimationUtils`?

File: src/animation/AnimationUtils.js [hunk 1]
```diff
@@ -158,6 +158,50 @@ var AnimationUtils = {
...
+	clone: function ( source ) {
+
+		var sourceNodes = {};
+		var clonedNodes = {};
+
+		var clone = source.clone();
+
+		source.traverse( function ( node ) {
+
+			sourceNodes[ node.name ] = node;
```
Comment (takahirox) [inline src/animation/AnimationUtils.js]: Do you assume node has an unique name?

Comment (donmccurdy) [reply src/animation/AnimationUtils.js]: Unique within the subtree being cloned, yes.

**Comment by donmccurdy** [comment]
> I haven't followed up the discussion yet, but why is cloning method for SkinnedMesh in AnimationUtils?

I'd rather it just work via `mesh.clone()` of course, but bones may not be children of the mesh. Consider this subtree:

- object
- object
- object
  - bone
    - bone
      - bone
- object
  - skinned mesh

There's no guarantee the new bones will exist at the time the skinned mesh is recursively cloned. It seems like we need somewhere else to put that logic, and so a Utils class seems as good as any. [This solution](https://gist.github.com/zellski/be4e9207ab8e70c4e89062d48ce345ba#file-gltf_utils-js-L19) is another, but relies on cloning happening at the Scene level, and not all loaders return Scene objects.

**Comment by takahirox** [comment]
Sorry I wrote poorly. I think it's good to have a workaround in Utils for now. My question is why is it in `"Animation"Utils` tho cloning `SkinnedMesh` isn't animation special.

File: src/animation/AnimationUtils.js [hunk 2]
```diff
@@ -158,6 +158,50 @@ var AnimationUtils = {
...
+			var clonedMesh = node;
+			var sourceMesh = sourceNodes[ node.name ];
+			var sourceBones = sourceMesh.skeleton.bones;
+
+			clonedMesh.skeleton = sourceMesh.skeleton.clone();
+			clonedMesh.bindMatrix = sourceMesh.bindMatrix;
+
+			clonedMesh.skeleton.bones = sourceBones.map( function ( bone ) {
+
+				return clonedNodes[ bone.name ];
```
Comment (takahirox) [inline src/animation/AnimationUtils.js]: Similarly do you assume bones are in a subtree?

**Comment by donmccurdy** [comment]
> My question is why is it in "Animation"Utils tho cloning SkinnedMesh isn't animation special.

Because I can't think of a better place to put it, and skinning is at least somewhat related to animation. Suggestions welcome. 😉

File: src/animation/AnimationUtils.js (hunk 2 above)
Comment (donmccurdy) [reply src/animation/AnimationUtils.js]: This assumes the bones are within the subtree of the object being cloned, but not necessarily descendants of the SkinnedMesh they're associated with.

**Comment by takahirox** [comment]
Hm, `SceneUtils` or `(Skinned)MeshUtils`?

File: src/animation/AnimationUtils.js (hunk 2 above)
Comment (takahirox) [reply src/animation/AnimationUtils.js]: I think we need to check if bones are in a subtree and halt with warn/error log if they aren't. Because it isn't guaranteed, for example users might call `Utils.clone( object2 )` for the following graph. Sometimes even bones wouldn't be in the scene graph.

- object1
  - bone1
    - bone2
- object2
  - skinned mesh

File: examples/js/loaders/GLTFLoader.js [hunk 3]
```diff
@@ -2979,6 +2981,10 @@ THREE.GLTFLoader = ( function () {
 
 				node.name = THREE.PropertyBinding.sanitizeNodeName( nodeDef.name );
 
+			} else {
+
+				node.name = 'gltfNode' + ( nextNodeIndex++ );
```
[the remark this answers is not in the document]
Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js]: Right. 👍

File: src/animation/AnimationUtils.js [hunk 4]
```diff
@@ -158,6 +158,50 @@ var AnimationUtils = {
...
+		clone.traverse( function ( node ) {
+
+			if ( ! node.isSkinnedMesh ) return;
+
+			var clonedMesh = node;
+			var sourceMesh = sourceNodes[ node.name ];
+			var sourceBones = sourceMesh.skeleton.bones;
+
+			clonedMesh.skeleton = sourceMesh.skeleton.clone();
+			clonedMesh.bindMatrix = sourceMesh.bindMatrix;
```
Comment (takahirox) [inline src/animation/AnimationUtils.js]: We should copy the matrix, rather than we share?

Comment (donmccurdy) [reply src/animation/AnimationUtils.js]: Done ✅

**Comment by donmccurdy** [comment]
Updated to ensure cloning does not depend on names. I removed the part adding unique names to glTF nodes for now, but will probably try another PR for that in the future since animation tracks still require it.

File: src/animation/AnimationUtils.js [hunk 5]
```diff
@@ -158,9 +158,59 @@ var AnimationUtils = {
...
+			clonedMesh.skeleton = sourceMesh.skeleton.clone();
+			clonedMesh.bindMatrix.copy( sourceMesh.bindMatrix );
+
+			clonedMesh.skeleton.bones = sourceBones.map( function ( bone ) {
+
+				return cloneLookup.get( bone );
+
+			} );
+
+			clonedMesh.bind( clonedMesh.skeleton, clonedMesh.bindMatrix );
```
Comment (takahirox) [inline src/animation/AnimationUtils.js]: Copying matrix to `.bindMatrix` is done in `SkinnedMesh.bind()`.

https://github.com/mrdoob/three.js/blob/dev/src/objects/SkinnedMesh.js#L112

So I think you can replace this line with

    clonedMesh.bind( clonedMesh.skeleton, sourceMesh.bindMatrix );

and remove the line above `clonedMesh.bindMatrix.copy( sourceMesh.bindMatrix );`.

Comment (donmccurdy) [reply src/animation/AnimationUtils.js]: Done ✅

File: src/animation/AnimationUtils.js [hunk 6]
```diff
@@ -158,9 +158,58 @@ var AnimationUtils = {
...
+
+		} );
+
+		return clone;
+
```
Comment (takahirox) [inline src/animation/AnimationUtils.js]: Can't we remove `sourceLookup`?

    source.traverse( function ( node ) {

        if ( ! node.isSkinnedMesh ) return;

        var sourceMesh = node;
        var sourceBones = sourceMesh.skeleton.bones;
        var clonedMesh = cloneLookup.get( node );

        clonedMesh.skeleton = sourceMesh.skeleton.clone();

        clonedMesh.skeleton.bones = sourceBones.map( function ( bone ) {

            return cloneLookup.get( bone );

        } );

        clonedMesh.bind( clonedMesh.skeleton, sourceMesh.bindMatrix );

    } );

    return clone;

File: src/animation/AnimationUtils.js (hunk 5 above)
Comment (takahirox) [reply src/animation/AnimationUtils.js]: You need to pass `"source"Mesh.bindMatrix`.

File: src/animation/AnimationUtils.js (hunk 6 above)
Comment (donmccurdy) [reply src/animation/AnimationUtils.js]: Fixed ✅

File: src/animation/AnimationUtils.js (hunk 5 above)
Comment (donmccurdy) [reply src/animation/AnimationUtils.js]: Fixed ✅

**Comment by takahirox** [comment]
Thanks for the update.

So, you still want this method in `AnimationUtils`? Or do you move it to `SceneUtils` or somewhere?

File: src/animation/AnimationUtils.js [hunk 7]
```diff
@@ -158,9 +158,55 @@ var AnimationUtils = {
...
+			if ( ! sourceMesh.isSkinnedMesh ) return;
+
+			var sourceBones = sourceMesh.skeleton.bones;
+			var clonedMesh = cloneLookup.get( sourceMesh );
+
+			clonedMesh.skeleton = sourceMesh.skeleton.clone();
+
+			clonedMesh.skeleton.bones = sourceBones.map( function ( bone ) {
+
+				return cloneLookup.get( bone );
```
Comment (takahirox) [inline src/animation/AnimationUtils.js]: Do you wanna check the existence of bones in the subtree as I mentioned?

Comment (donmccurdy) [reply src/animation/AnimationUtils.js]: Done ✅

**Comment by donmccurdy** [comment]
I'm OK with whatever namespace for this, but I don't think I have a better idea than the current name... maybe `cloneWithBones` or `cloneWithSkinning`? It is all a less-preferable solution than fixing `.clone()` directly but I don't see any straightforward way to do that. /cc @mrdoob

File: src/animation/AnimationUtils.js [hunk 8]
```diff
@@ -158,9 +158,63 @@ var AnimationUtils = {
...
+
+			clonedMesh.skeleton.bones = sourceBones.map( function ( sourceBone ) {
+
+				var clonedBone = cloneLookup.get( sourceBone );
+
+				if ( ! clonedBone ) {
+
+					throw new Error( 'THREE.AnimationUtils: Required bones are not descendants of the given object.' );
+
+				}
```
Comment (takahirox) [inline src/animation/AnimationUtils.js]: nit: Using `.has()` may look more natural?

    if ( ! cloneLookup.has( sourceBone ) ) {

        throw new Error( 'THREE.AnimationUtils: Required bones are not descendants of the given object.' );

    }

    var clonedBone = cloneLookup.get( sourceBone );

Comment (donmccurdy) [reply src/animation/AnimationUtils.js]: Done ✅

**Comment by takahirox** [comment]
Voting for `SceneUtils.cloneWithSkinning`.

**Comment by donmccurdy** [comment]
If https://github.com/mrdoob/three.js/pull/14574 goes in, SkeletonUtils seems like a good place to put this. 🤔

**Comment by takahirox** [comment]
Agreed.

**Comment by mrdoob** [comment]
> If https://github.com/mrdoob/three.js/pull/14574 goes in, SkeletonUtils seems like a good place to put this. 🤔

Merged.

**Comment by donmccurdy** [comment]
@takahirox @mrdoob Does `SkeletonUtils.clone()` seem OK as a name? Or something like more explicit like `.cloneWithSkinning()`?

**Comment by takahirox** [comment]
I prefer the explicit one.

**Comment by Mugen87** [comment]
I have lately used this code in a project and it works great. Would love to see it in the code base :blush:

**Comment by Eketol** [comment]
Me too. I've also tested it and it works fine for me. Just one question: the use of Map() is "es2015" (ES6), is that ok?
Also, in case it helps other noobs like me: Materials are not cloned, but referenced. In my case I think it is the right behaviour. If you want to customise some of the cloned object's materials, bear that in mind.

**Comment by Mugen87** [comment]
I think using `Map` in this case is okay since it's no part of the core.

**Comment by donmccurdy** [comment]
Thanks!

I've moved the `clone()` method from AnimationUtils to SkeletonUtils, and added documentation for SkeletonUtils. I think this is ready to go. 👍

**Review by Mugen87 — APPROVED** [review]

**Comment by donmccurdy** [comment]
@mrdoob could this be included with r103?

**Comment by titansoftime** [comment]
This just solved a huge issue I was having. Thank you.

**Comment by Mugen87** [comment]
> This just solved a huge issue I was having.

https://discourse.threejs.org/t/solved-issue-with-gltfloader-and-reusing-geometry/6697

**Comment by mrdoob** [comment]
> @mrdoob could this be included with r103?

Done! 😇

**Comment by mrdoob** [comment]
Thanks!

**Comment by canadaduane** [comment]
> Also, in case it helps other noobs like me: Materials are not cloned, but referenced. In my case I think it is the right behaviour. If you want to customise some of the cloned object's materials, bear that in mind.

Is there an option to clone the materials as well? In my case, I'd like some of my skinnedmesh objects to be transparent (but not all), even though they've been cloned from the same original.

**Comment by Mugen87** [comment]
`SkeletonUtils.clone()` does not touch materials. You have to apply the material changes in a subsequent step.

**Comment by enricocantori** [comment]
Three.is is frequently used in the world of character animations. I can’t find no functions, no working examples related to the replace of parts of characters. Almost all characters are composed by skinnedMesh children and a lot of time is necessary change a part of the character like clothes, hair, face within characters that have same skeleton without broke animation (ex. Readyplayes characters). Clone and SkeletonUtils.Clone doesn’t solve this problem. Exist one more specific function?
