### PR TITLE
FBXLoader: Fix rotation discontinuities.

### LINKED ISSUE #27056: FBXLoader adds rotation discontinuities into animation
### Description

**FBXLoader adds rotation discontinuities into animation**
When loading the FBX onto threeJS editor (or anything using FBXLoader), the displayed animation has rotation discontinuities. However, when loading the animation onto blender, the animation is good. Similarly if we convert the FBX to GLB and load it onto the threeJS editor, there is not problem either. 

Zip containing both FBX and GLB animation:
[RotationDiscontinuities.zip](https://github.com/mrdoob/three.js/files/13167729/RotationDiscontinuities.zip)

### Reproduction steps

1. Load the fbx provided onto ThreeJS editor 
2. Play the animation

or 

1. Load the FBX with the FBX loader
2. Play the animation

### Code

N/A

### Live example

* [threeJS edior](https://threejs.org/editor/)

### Screenshots

|     | ThreeJS editor | Blender |
|-----|----------------|---------|
| FBX | RotationDiscontinuitiesFBXTHREEJS| RotationDiscontinuitiesFBXBlender |
| GLB | RotationDiscontinuitiesGLBTHREEJS |         |

### Version

r157

### Device

Desktop

### Browser

Chrome

### OS

Linux

### PR DESCRIPTION
**Pull request by solinehayes**
Fix #27056

**Description**
This PR addresses an issue in the FBXLoader where rotations with significant differences between consecutive frames were interpolated using Euler angles (each coordinate separately), which could introduce discontinuities. The proposed solution detects and corrects these discontinuities by using quaternion interpolation (taking into account possible unroll/quaternion negation), ensuring smooth rotation.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawcdn.githack.com/solinehayes/three.js/issue27056-fixRotationDiscontinuities/editor/index.html

**Comment by Mugen87** [comment]
I can confirm that your PR fixes the issue! Great! 🎉 

Still it's important to review the new code a bit more closely so let's target `r159` for this change. 

Side note: The maintenance of `FBXLoader` is currently a bit tricky since no one of the current active collaborators works at the loader. I have implemented and reviewed a few smaller changes in the recent past but I'm definitely no FBX expert 😅 . So this PR might take a little bit longer to get reviewed. 

I wish we had an additional dev with FBX knowledge who could help out reviewing FBX related PRs.

File: examples/jsm/loaders/FBXLoader.js [hunk 1]
```diff
@@ -2698,32 +2698,35 @@ class AnimationParser {
...
-			this.interpolateRotations( curves.y );
-			curves.y.values = curves.y.values.map( MathUtils.degToRad );
+	generateRotationTrack(
+		modelName,
+		curves,
+		initialValue,
+		preRotation,
+		postRotation,
+		eulerOrder
+	) {
```
Comment (Mugen87) [inline examples/jsm/loaders/FBXLoader.js:2708]: Do you mind reformatting code like in this instance?

This should make the diff smaller and the PR easier to review. In general, it's best if you stick to the existing code style whenever possible.

File: examples/jsm/loaders/FBXLoader.js [hunk 2]
```diff
@@ -2700,30 +2700,18 @@ class AnimationParser {
 
 	generateRotationTrack( modelName, curves, initialValue, preRotation, postRotation, eulerOrder ) {
 
-		if ( curves.x !== undefined ) {
+		let times;
```
Comment (Mugen87) [inline examples/jsm/loaders/FBXLoader.js:2703]: Compared to the previous version, `initialValue` is not used anymore and could be removed from `generateRotationTrack()`. 

Why is this parameter obsolete now?

Comment (solinehayes) [reply examples/jsm/loaders/FBXLoader.js:2703]: It was previously used in the `getKeyframTrackValues` function that created the final values table for the animation. It concatenated the curves values (x,y and z) and added the interpolated values by completing the non interpolated curves  by their previous known value (since the interpolation was done only on one value (x,y or z) and not the whole angle). The `initialValue` solely initialized the `prevValue` used to determine which value to add to the final values table. 
It is not useful anymore since I interpolate and create the values tables at the same time and for the whole angle (all x,y and z curves) at once. On line 2902, we see that I initialize a so called initialValue as well. the one for i=0 is equivalent to the initial value here.

**Comment by solinehayes** [comment]
> > The maintenance of FBXLoader is currently a bit tricky
> 
> Agreed.
> 
> @solinehayes Out of curiosity, is using GLB format an acceptable alternate workflow for you -- or is there a particular advantage to FBX format?

Well, I am working in a company where we're using Maya, so we majorly use FBX. We occasionally use GLB but we prefer FBX. 
Plus we're working with animation and GLB only allows multiple animations in one asset, we can not animate several character with several animations.

File: examples/jsm/loaders/FBXLoader.js (hunk 2 above)
Comment (Mugen87) [reply examples/jsm/loaders/FBXLoader.js:2703]: That makes sense. Could you then remove `initialValue` from the method and on caller level? It has obviously no purpose anymore and keeping it in the code is confusing.

Comment (Mugen87) [reply examples/jsm/loaders/FBXLoader.js:2701]: I'll merge and clean up.
