### PR TITLE
Refactored PMREM blur shader due to apparent compiler bug

### LINKED ISSUE #18936: Any example involving IBLs "crashes" my laptop
Original issue described here: https://github.com/google/model-viewer/issues/1089

OS: Windows 10
Browsers: Chrome, Firefox, Edge
GPU: Intel HD Graphics 630

This is probably just some weird shader compiler issue. I fixed it by refactoring the PMREM blur code a bit. PR: https://github.com/mrdoob/three.js/pull/18935

Creating this issue for future reference.

### PR DESCRIPTION
**Pull request by stevesan**
Without this fix, the PMREM generator would cause context loss (and my entire display to go black for a bit) on my laptop. Its GPU is the Intel HD Graphics 630. We originally thought this was a [model-viewer issue](https://github.com/google/model-viewer/issues/1089), but this was the root cause.

Fixes #18936

### CODE REVIEW

File: src/extras/PMREMGenerator.js [hunk 1]
```diff
@@ -611,29 +611,31 @@ ${_getEncodings()}
 #define ENVMAP_TYPE_CUBE_UV
 #include <cube_uv_reflection_fragment>
 
+vec3 getSample(float theta) {
+  vec3 axis = latitudinal ? poleAxis : cross(poleAxis, vOutputDirection);
+  if (all(equal(axis, vec3(0.0))))
+    axis = cross(vec3(0.0, 1.0, 0.0), vOutputDirection);
+  axis = normalize(axis);
```
Comment (elalish) [inline src/extras/PMREMGenerator.js]: Ugh, I can't believe I missed this when I wrote it first: these three lines calculating the axis can be moved out of the loop entirely as they don't depend on theta. That'll speed things up a bit.

File: src/extras/PMREMGenerator.js [hunk 2]
```diff
@@ -611,29 +611,31 @@ ${_getEncodings()}
...
-	}
-	gl_FragColor = linearToOutputTexel(gl_FragColor);
+  gl_FragColor = vec4(0.0);
+  for (int i = 0; i < n; i++) {
+    if (i >= samples)
+      break;
+    float theta = dTheta * float(i);
+    gl_FragColor.rgb += weights[i] * getSample(-1.0 * theta);
+    if(i == 0)
+      continue;
```
Comment (elalish) [inline src/extras/PMREMGenerator.js]: We can remove this conditional by getting the central sample before the loop and then running the loop starting at 1.

File: src/extras/PMREMGenerator.js [hunk 3]
```diff
@@ -611,29 +611,31 @@ ${_getEncodings()}
...
+vec3 getSample(float theta) {
+  vec3 axis = latitudinal ? poleAxis : cross(poleAxis, vOutputDirection);
+  if (all(equal(axis, vec3(0.0))))
+    axis = cross(vec3(0.0, 1.0, 0.0), vOutputDirection);
+  axis = normalize(axis);
+  float cosTheta = cos(theta);
+  // Rodrigues' axis-angle rotation
+  vec3 sampleDirection = vOutputDirection * cosTheta 
+    + cross(axis, vOutputDirection) * sin(theta) 
+    + axis * dot(axis, vOutputDirection) * (1.0 - cosTheta);
```
Comment (elalish) [inline src/extras/PMREMGenerator.js]: I can't remember if we want tabs or spaces in these files, but we should probably be consistent. This always trips me up because VSCode inevitably chooses the wrong one.

**Review by elalish — COMMENTED** [review]
Thanks for tracking down this weird glsl compiler issue @stevesan!

File: src/extras/PMREMGenerator.js (hunk 3 above)
Comment (mrdoob) [reply src/extras/PMREMGenerator.js]: Tabs 👌

File: src/extras/PMREMGenerator.js (hunk 1 above)
Comment (WestLangley) [reply src/extras/PMREMGenerator.js]: hmm...
```glsl
axis = vec3( vOutputDirection.z, 0.0, - vOutputDirection.x );
```

Comment (stevesan) [reply src/extras/PMREMGenerator.js]: > hmm...
> 
> ```glsl
> axis = vec3( vOutputDirection.z, 0.0, - vOutputDirection.x );
> ```

Will this make any difference in speed? I feel using 'cross' is more clear and readable. *shrug* don't care that much.

Comment (stevesan) [reply src/extras/PMREMGenerator.js]: Gonna resolve for now. If ya'll feel strongly about the cross fix, I'll do another PR. I did the axis-opt.

**Review by elalish — APPROVED** [review]
LGTM!

File: src/extras/PMREMGenerator.js (hunk 1 above)
Comment (RemusMar) [reply src/extras/PMREMGenerator.js]: > 
> 
> > hmm...
> > ```glsl
> > axis = vec3( vOutputDirection.z, 0.0, - vOutputDirection.x );
> > ```
> 
> Will this make any difference in speed? I feel using 'cross' is more clear and readable. _shrug_ don't care that much.

In fact that CROSS will make it look "obfuscated" and run slower.

Comment (WestLangley) [reply src/extras/PMREMGenerator.js]: I agree with @WestLangley. :-)

/ping @elalish

Comment (elalish) [reply src/extras/PMREMGenerator.js]: I also have no strong opinion. May as well change it.

Comment (stevesan) [reply src/extras/PMREMGenerator.js]: Done

**Comment by mrdoob** [comment]
Thanks!
