### PR TITLE
TAARenderPass: Fix color shift.

### LINKED ISSUE #24318: TAARenderPass: Pass over-brightens scene, shows occasional black frames
**Describe the bug**

When using TAARenderPass, certain valid settings result in incorrect behavior:

- `scene.background` — any non-black background will cause the final scene to over-brighten during TAA accumulation
- `pass.sampleLevel` — any non-zero level will cause a single-frame flash of black when the accumulation phase begins

**To Reproduce**

1. Open `webgl_postprocessing_taa` locally
2. Add a background color like `scene.background = new THREE.Color( 0xEE5555 );`
3. Increase TAASampleLevel (any level > 0)

Observe (1) the scene brightens when it stops moving and begins accumulating, and (2) the scene flashes to black for a single frame at that time. It may be easier to see the flash when the background is kept black.

**Expected behavior**

TAARenderPass should be compatible with non-black scene backgrounds, and should not show a black frame while accumulating.

**Screenshots**

If applicable, add screenshots to help explain your problem (drag and drop the image).

**Platform:**

 - Device: Desktop
 - OS: macOS 12.4
 - Browser: Chrome 103.0.5060.53
 - Three.js version: r142

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #24318.

**Description**

This PR should finally fix the color shift during the accumulation phase of `TAARenderPass`.

### CODE REVIEW

**Comment by Mugen87** [comment]
https://rawcdn.githack.com/Mugen87/three.js/dev76/examples/webgl_postprocessing_taa.html

File: examples/jsm/postprocessing/TAARenderPass.js [hunk 1]
```diff
@@ -133,7 +133,6 @@ class TAARenderPass extends SSAARenderPass {
 			this.copyUniforms[ 'opacity' ].value = 1.0 - accumulationWeight;
 			this.copyUniforms[ 'tDiffuse' ].value = this.holdRenderTarget.texture;
 			renderer.setRenderTarget( writeBuffer );
-			if ( accumulationWeight === 0 ) renderer.clear();
```
Comment (Mugen87) [inline examples/jsm/postprocessing/TAARenderPass.js:136]: The problem was this clear. When it happens it deleted the contents of the previous render which explains the flash at the beginning of the accumulation phase. The write buffer has already been cleared by the previous call of `this.fsQuad.render( renderer );` so it should be safe to delete it.
