### PR TITLE
WebGLTextures: Fix DepthTexture with WebGLMultisampleRenderTarget.

### LINKED ISSUE #18876: WebGLMultisampleRenderTarget not support DepthTexture ?
#####  code
```js
var depthTexture = new THREE.DepthTexture();

var parameters = {
    format: THREE.RGBFormat,
    stencilBuffer: false,
    depthBuffer: true,
    depthTexture: depthTexture
};

var size = renderer.getDrawingBufferSize( new THREE.Vector2() );

var renderTarget = new THREE.WebGLMultisampleRenderTarget( size.width, size.height, parameters );
```
##### output error:
    [.WebGL-0x7fcad880e800]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

    webgl2_multisampled_renderbuffers.html:1 [.WebGL-0x7fcad880e800]GL ERROR :GL_INVALID_OPERATION : glTexImage2D: <- error from previous GL command

    254[.WebGL-0x7fcad880e800]GL ERROR :GL_INVALID_OPERATION : glFramebufferTexture2D: <- error from previous GL command

##### Three.js version

- [ ] Dev
- [x] r114
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #18876.

### CODE REVIEW

File: src/renderers/webgl/WebGLTextures.js [hunk 1]
```diff
@@ -650,15 +650,29 @@ function WebGLTextures( _gl, extensions, state, properties, capabilities, utils,
...
+				} else if ( texture.type === UnsignedIntType ) {
 
-				if ( isWebGL2 === false ) throw new Error( 'Float Depth Texture only supported in WebGL2.0' );
-				glInternalFormat = _gl.DEPTH_COMPONENT32F;
+					glInternalFormat = _gl.DEPTH_COMPONENT24;
 
-			} else if ( isWebGL2 ) {
+				} else {
+
+					glInternalFormat = _gl.DEPTH_COMPONENT16; // WebGL2 requires signed internalformat for glTexImage2D
```
Comment (vanruesc) [inline src/renderers/webgl/WebGLTextures.js]: Potential typo: shouldn't it be "sized" instead of "signed"?

Comment (Mugen87) [reply src/renderers/webgl/WebGLTextures.js]: Indeed!

**Comment by mrdoob** [comment]
Thanks!
