### PR TITLE
Renderer: Fix transmission flicker.

### LINKED ISSUE #31768: WebGPU: incorrect rendering with transmission or when animated or when resizing the window
### Description

Hello, I have a model with KHR_animation_pointer physical material animations. Once the animation starts the rendered dragon looks like transmission is not displayed correctly(?). The same animation works fine in the WebGL renderer

### Reproduction steps

1. [Open WebGPU example](https://three.needle.tools/examples/?q=pointer#webgpu_loader_gltf_animation_pointer)
2. Click Toggle Animation button to start the animation

### Code

https://github.com/needle-tools/three.js/blob/a51be2d54b7dd5c45cfff2002e3d77c6ec0943a3/examples/webgpu_loader_gltf_animation_pointer.html

## Expected
Live: https://three.needle.tools/examples/?q=pointer#webgl_loader_gltf_animation_pointer

https://github.com/user-attachments/assets/1aa82057-bdeb-40f8-ab4f-510349175349

## WebGPU - Animation
Live: https://three.needle.tools/examples/?q=pointer#webgpu_loader_gltf_animation_pointer

https://github.com/user-attachments/assets/da32c996-8934-4350-93c3-7457059c418c

## WebGPU - Resizing the window

https://github.com/user-attachments/assets/0b55b900-c573-4fdb-82ee-a827419a8360

### Screenshots

_No response_

### Version

latest dev

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed https://github.com/mrdoob/three.js/issues/31768.

**Description**

Next attempt to fix #31768. 

I've realized the WebGPU backend already ends the current render pass in `copyFramebufferToTexture()`, however, the mipmaps generation started when the next main render pass was already created. That made it impossible to share the same encoder.

The PR introduces a new order that makes it possible to share the command encoder so the mipmap generation eventually happens in the correct order.

### CODE REVIEW

File: src/renderers/webgpu/WebGPUBackend.js [hunk 1]
```diff
@@ -777,8 +777,7 @@ class WebGPUBackend extends Backend {
 
 			if ( renderContext.scissor ) {
 
-				const { x, y, width, height } = renderContext.scissorValue;
-				currentPass.setScissorRect( x, y, width, height );
+				this.updateScissor( renderContext );
```
Comment (Mugen87) [inline src/renderers/webgpu/WebGPUBackend.js:780]: Similar to `updateViewport()`, I have created `updateScissor()` to improve readability.

File: src/renderers/webgpu/utils/WebGPUTexturePassUtils.js [hunk 2]
```diff
@@ -310,29 +310,27 @@ fn main( @location( 0 ) vTex : vec2<f32> ) -> @location( 0 ) vec4<f32> {
...
 	 * @param {Object} textureGPUDescriptor - The texture descriptor.
 	 * @param {number} [baseArrayLayer=0] - The index of the first array layer accessible to the texture view.
+	 * @param {?GPUCommandEncoder} [encoder=null] - An optional command encoder used to generate mipmaps.
 	 */
-	generateMipmaps( textureGPU, textureGPUDescriptor, baseArrayLayer = 0 ) {
+	generateMipmaps( textureGPU, textureGPUDescriptor, baseArrayLayer = 0, encoder = null ) {
 
 		const textureData = this.get( textureGPU );
 
-		if ( textureData.useCount === undefined ) {
```
Comment (Mugen87) [inline src/renderers/webgpu/utils/WebGPUTexturePassUtils.js:318]: The `useCount` property was actually useless and incremented indefinitely. It's actually sufficient to check for `textureData.layers`.

File: src/renderers/webgpu/utils/WebGPUTextureUtils.js [hunk 3]
```diff
@@ -344,16 +344,17 @@ class WebGPUTextureUtils {
 	 * Generates mipmaps for the given texture.
 	 *
 	 * @param {Texture} texture - The texture.
+	 * @param {?GPUCommandEncoder} [encoder=null] - An optional command encoder used to generate mipmaps.
 	 */
-	generateMipmaps( texture ) {
+	generateMipmaps( texture, encoder = null ) {
```
Comment (Mugen87) [inline src/renderers/webgpu/utils/WebGPUTextureUtils.js:349]: `generateMipmaps()` now has an optional encoder parameter which allows to share the same encoder from the main render pass resulting in correct command order.

**Comment by Mugen87** [comment]
The PR _should_ be side-effect free since the only code that triggers mipmap generation in `copyFramebufferToTexture()` is the TSL function `viewportMipTexture()`. This usage is currently broken and fixed by this PR.
