### PR TITLE
WebGLProgram: reverse shader detach.

### LINKED ISSUE #19267: r114 or newer not working on iOS 9.x
Hi,

Since r114 nothing is displayed on the screen when running on iOS 9.x (iPad 2 or iPhone 4S), but with r113 or older works fine.
Example of non-working attached, replace the Threejs version by 110 for example and it works.

Is that intended or a bug?

Thank you!

[r115.zip](https://github.com/mrdoob/three.js/files/4561736/r115.zip)

### PR DESCRIPTION
**Pull request by sciecode**
https://github.com/mrdoob/three.js/pull/18402#issuecomment-622160914

Revert `gl.detachShaders`, iOS 10 and older doesn't conform with spec.

Fixed #19267.

### CODE REVIEW

**Comment by sciecode** [comment]
Requires build update.

Might, also, want to publish fix to npm.

File: src/renderers/webgl/WebGLProgram.js [hunk 1]
```diff
@@ -797,9 +797,6 @@ function WebGLProgram( renderer, cacheKey, parameters ) {
 
 	// clean up
 
-	gl.detachShader( program, glVertexShader );
-	gl.detachShader( program, glFragmentShader );
```
Comment (WestLangley) [inline src/renderers/webgl/WebGLProgram.js:801]: Instead, maybe just comment out these lines and add a comment?

Comment (sciecode) [reply src/renderers/webgl/WebGLProgram.js:801]: Maybe there's no point in that. We might change the entire library to use WebGPU before we reach a point where people would be ok with us dropping support for iOS 10 or lower.

Comment (mrdoob) [reply src/renderers/webgl/WebGLProgram.js:801]: I think @WestLangley's idea makes sense.
That way if any other contributor tries to implement it again they'll realize we already tried.

Comment (sciecode) [reply src/renderers/webgl/WebGLProgram.js:801]: :heavy_check_mark:

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

**Comment by mrdoob** [comment]
> Might, also, want to publish fix to npm.

Yeah, the timing was unfortunate... I'll do it if we get more reports.

**Comment by mrdoob** [comment]
Changed my mind 😇
https://github.com/mrdoob/three.js/commit/79edf22a345079dc6cf5d8c6ad38ee22e9edab3c
