### PR TITLE
WebGPURenderer: Fix missing updates to geometry attributes

### LINKED ISSUE #29582: WebGPURenderer: NodeMaterialObserver can prevent BufferAttributes from being updated despite needsUpdate
### Description

Noticed a bug in the [`webgpu_animation_retargeting`](https://threejs.org/examples/#webgpu_animation_retargeting) example where under certain camera angles the `SkeletonHelper` would "freeze" and no longer update. Trying to figure out what caused it, I discovered that during a "freeze" the `BufferAttribute` of the helper would not be updated by the renderer, despite its contents having changed and `needsUpdate` being set.

A bisect revealed that this is a regression caused by #29386. Not yet familiar with these parts of Three.js, so not sure if the `SkeletonHelper` is doing something that isn't (or no longer is) supported and that now surfaces, or that the `NodeMaterialObserver` is incorrectly determining that no refresh is needed.

To summarize:

- Happens in the example with both WebGPU and the WebGL fallback backends.
- The `SkeletonHelper` _does_ update the `position` attribute's data and marks it as `needsUpdate` ([SkeletonHelper.js#L91](https://github.com/mrdoob/three.js/blob/dev/src/helpers/SkeletonHelper.js#L91))
- During rendering the `needsRefresh` check prevents the `_geometries.updateForRender` call ([Renderer.js#L1606-L1617](https://github.com/mrdoob/three.js/blob/0c7cf78a64a724c24fcca51500b8f3d1b9931af5/src/renderers/common/Renderer.js#L1606-L1617))
- From testing the fact that there are two `SkeletonHelpers` is relevant for the reproduction. My guess would be that with only a single one, the `needsRefresh` check would return true for other reasons, whereas with two (and the right camera angle) the two `SkeletonHelpers` are rendered immediately after eachother.

Nothing in the above seems specific to the `SkeletonHelper` AFAICT, so this behaviour can likely occur in other situations as well.

### Reproduction steps

1. Open https://threejs.org/examples/#webgpu_animation_retargeting
2. Enable the "helpers" using the checkbox
3. Rotate the camera around and notice the helpers "freezing" with certain camera angles (see screenshot)

### Code

Relevant code in `SkeletonHelper`: https://github.com/mrdoob/three.js/blob/dev/src/helpers/SkeletonHelper.js#L66-L91

### Live example

- [`webgpu_animation_retargeting`](https://threejs.org/examples/#webgpu_animation_retargeting)

### Screenshots

image

### Version

r169

### Device

Desktop

### Browser

Chrome, Firefox

### OS

Linux

### PR DESCRIPTION
**Pull request by RenaudRohlinger**
Fixed: #29582
Related: #29386

**Description**
This PR fixes an issue in `NodeMaterialObserver` where changes to geometry attributes or properties were not consistently reflected in the material, ensuring proper updates and synchronization between geometry and shaders.

*This contribution is funded by [Utsubo](https://utsubo.com)*

### CODE REVIEW

File: src/materials/nodes/manager/NodeMaterialObserver.js [hunk 1]
```diff
@@ -224,6 +389,21 @@ class NodeMaterialObserver {
 
 		}
 
+		// geometry
+
+		const geometryData = renderObjectData.geometry;
+		const currentGeometryData = this.getGeometryData( renderObject.geometry );
```
Comment (sunag) [inline src/materials/nodes/manager/NodeMaterialObserver.js:395]: Could we compare geometry data without get a new data every frame?

Comment (RenaudRohlinger) [reply src/materials/nodes/manager/NodeMaterialObserver.js]: Good point, done!
