### PR TITLE
MaterialXLoader: Unlit Material

### LINKED ISSUE #27494: MaterialX: Unlit materials (single-output nodegraphs) don't work
### Description

Seems that nodegraphs that don't use a surface model (aka: are unlit) are not supported right now, e.g. this one doesn't work:

```xml
<?xml version="1.0"?>
<materialx version="1.38" colorspace="lin_rec709">
  <nodegraph name="just_unlit">
    <mix name="mix_color3" type="color3">
      <input name="fg" type="color3" value="0, 0.0986187, 0.186275" />
      <input name="bg" type="color3" value="0.735294, 0.735294, 0.735294" />
      <input name="mix" type="float" value="0.6" />
    </mix>
    <output name="out" type="color3" nodename="mix_color3" />
  </nodegraph>
</materialx>
```

The above works fine in https://academysoftwarefoundation.github.io/MaterialX/.

I think the relevant spec section is [this](https://github.com/AcademySoftwareFoundation/MaterialX/blob/d4c6f60984b9ec4d7be69d8402b97b0d18e63591/documents/Specification/MaterialX.Specification.md?plain=1#L1994), saying that if there's only a single output (and no surfacematerial) then that should be used, and it doesn't matter what its name is.

@sunag I think this should become a `MeshBasicNodeMaterial`, right?
Basically checking [here if any surfacematerial was found](https://github.com/mrdoob/three.js/blob/de6dd45d7e5aa58fed0fbc1dbe53def3402b39cc/examples/jsm/loaders/MaterialXLoader.js#L722), and if not, using the first output instead for an Unlit material.

### Reproduction steps

1. Load the above MaterialX with MaterialXLoader
2. Note it returns zero materials

(Side note: after discussion on the MaterialX slack there are additional cases – not really relevant for this issue, just interesting for the future. This file is also valid and contains two materials (one implicit unlit one and another explicit surfacematerial): [two-materials.mtlx.zip](https://github.com/mrdoob/three.js/files/13824498/two-materials.mtlx.zip))

### PR DESCRIPTION
**Pull request by sunag**
Related issue: Closes https://github.com/mrdoob/three.js/issues/27494, https://github.com/mrdoob/three.js/issues/27496

**Description**

Initial support for NPR (non-photorealistic rendering) and `viewDirectionWorld`.

I was unable to reproduce different types of spaces in the official MaterialX Viewer for `viewdirection`, that's why the `viewDirectionWorld` is fixed for now.

### CODE REVIEW

File: examples/jsm/nodes/accessors/ViewDirectionNode.js [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+
+		super( 'vec3' );
+
+		this.positionNode = positionNode;
+
+	}
+
+	setup() {
+
+		return this.positionNode.sub( cameraPosition ).normalize();
```
Comment (WestLangley) [inline examples/jsm/nodes/accessors/ViewDirectionNode.js:18]: @sunag

In the shaders, we use this pattern consistently:
```glsl
vec4 mvPosition = vec4( transformed, 1.0 );

vViewPosition = - mvPosition.xyz

vec3 viewDir = normalize( vViewPosition );
```
So the view direction is a unit vector _from the vertex toward the camera_.

Just making sure you are aware. :-)

Comment (sunag) [reply examples/jsm/nodes/accessors/ViewDirectionNode.js:18]: I added this pattern through `positionViewDirection` and it is widely used in lighting models. 

https://github.com/mrdoob/three.js/blob/b8b82d96ead5a977107410336046bc082d058b07/examples/jsm/nodes/accessors/PositionNode.js#L54-L58

In some tests that I did `MaterialX` seems uses `viewdirection` in `world space` for this node as default instead of `view space`, and apparently will have `local/model space` to select.

Comment (WestLangley) [reply examples/jsm/nodes/accessors/ViewDirectionNode.js:18]: Sorry, I think you may have misunderstood my comment...

The comment is only about ensuring the _sign_ of "view direction" is correct, and consistent with historical convention, and how three.js defines it.

In the case of local vs. model space, the two definitions should be consistent with each other.

Comment (WestLangley) [reply examples/jsm/nodes/accessors/ViewDirectionNode.js:18]: Sorry, I think you may have misunderstood my comment...

The comment is only about ensuring the _sign_ of "view direction" is correct, and consistent with historical convention, and how three.js defines it.

In the case of local vs. world space, the two definitions should be consistent with each other.

Comment (sunag) [reply examples/jsm/nodes/accessors/ViewDirectionNode.js]: Thanks for the feedback, is an important point, I'll revert this part for now and check this in other PR.
