### PR TITLE
#28440 Fixed BufferGeometryUtils.mergeVertices to handle morphAttributes

### LINKED ISSUE #28440: BufferGeometryUtils.mergeVertices crashes when feeding a geometry with morphAttributes (regression)
### Description

BufferGeometryUtils.mergeVertices crashes when feeding a geometry with morphAttributes (regression)

### Reproduction steps

Use BufferGeometryUtils.mergeVertices with a geometry having morphAttributes and observe that it breaks.

### Code

Given this geometry:
```javascript
const getGeometry = () => {

	const geometry = new BufferGeometry();

	// square
	const vertices = new Float32Array( [
		- 1.0, - 1.0, 0.0, // Bottom left
		1.0, - 1.0, 0.0, // Bottom right
		1.0, 1.0, 0.0, // Top right
		- 1.0, 1.0, 0.0 // Top left
	] );

	const morphVertices = new Float32Array( [
		0.0, - 1.0, 0.0, // Bottom
		1.0, 0.0, 0.0, // Right
		0.0, 1.0, 0.0, // Top
		- 1.0, 0.0, 0.0 // Left
	] );

	geometry.setAttribute( 'position', new BufferAttribute( vertices, 3 ) );

	geometry.morphAttributes.position = [
		new BufferAttribute( morphVertices, 3 )
	];

	return geometry;

};
```
fed it into `BufferGeometryUtils.mergeVertices`.

This is a regression introduced here:
https://github.com/mrdoob/three.js/commit/f70ead9d#diff-ed91371298bdcbc8aab7034f2ea13d1def23f69aca37a77aa7cf8fee9a4cb125R596

`morphAttr` used to be a collection of `BufferGeometries` (as expected) but it was turned into a `BufferGeometry`

I have a PR prepared for this:  https://github.com/mrdoob/three.js/pull/28441.

### Live example

not needed

### Screenshots

_No response_

### Version

0.164.1

### Device

Desktop

### Browser

Edge

### OS

MacOS

### PR DESCRIPTION
**Pull request by catalin-enache**
Fixed #28440

**Description**

Reverted `morphAttr` to be a collection of BufferAttributes from being currently a BufferAttribute by itself.

### CODE REVIEW

File: examples/jsm/utils/BufferGeometryUtils.js [hunk 1]
```diff
@@ -623,20 +623,22 @@ function mergeVertices( geometry, tolerance = 1e-4 ) {
...
-		if ( morphAttr ) {
+		const morphAttrCollection = geometry.morphAttributes[ name ];
+		if ( morphAttrCollection ) {
 
-			tmpMorphAttributes[ name ] = new BufferAttribute(
-				new morphAttr.array.constructor( morphAttr.count * morphAttr.itemSize ),
-				morphAttr.itemSize,
-				morphAttr.normalized
-			);
+			if ( ! tmpMorphAttributes[ name ] ) tmpMorphAttributes[ name ] = [];
```
Comment (catalin-enache) [inline examples/jsm/utils/BufferGeometryUtils.js:635]: This is the main fix.

File: examples/jsm/utils/BufferGeometryUtils.js [hunk 2]
```diff
@@ -720,7 +722,7 @@ function mergeVertices( geometry, tolerance = 1e-4 ) {
 
 		const tmpAttribute = tmpAttributes[ name ];
 
-		result.setAttribute( name, new BufferAttribute(
+		result.setAttribute( name, new tmpAttribute.constructor(
```
Comment (catalin-enache) [inline examples/jsm/utils/BufferGeometryUtils.js:725]: Replaced everywhere in mergeVertices `new BufferAttribute` with `new <oldThing>.constructor` to preserve eventual optimization that the specialized class might have.

File: test/unit/three.source.unit.js [hunk 3]
```diff
@@ -284,3 +284,6 @@ import './src/textures/FramebufferTexture.tests.js';
 import './src/textures/Source.tests.js';
 import './src/textures/Texture.tests.js';
 import './src/textures/VideoTexture.tests.js';
+
+//addons
+import './addons/utils/BufferGeometryUtils.tests.js';
```
Comment (Mugen87) [inline test/unit/three.source.unit.js:289]: `three.source.unit.js` is only intended for `src` modules. We currently don't maintain unit tests for `examples/jsm`.

File: test/unit/addons/utils/BufferGeometryUtils.tests.js [hunk 4]
```diff
@@ -0,0 +1,60 @@
+import { BufferGeometry } from '../../../../src/core/BufferGeometry.js';
```
Comment (catalin-enache) [inline test/unit/addons/utils/BufferGeometryUtils.tests.js:1]: I understand that there is no maintenance for testing things outside src folder. However, I think adding tests for addons when possible would contribute to their stability.

File: test/unit/three.source.unit.js (hunk 3 above)
Comment (catalin-enache) [reply test/unit/three.source.unit.js:289]: Thanks for feedback. Do you want me to remove the test for acceptance ? I was thinking to do something to prevent eventual regression in the future.

File: test/unit/addons/utils/BufferGeometryUtils.tests.js (hunk 4 above)
Comment (Mugen87) [reply test/unit/addons/utils/BufferGeometryUtils.tests.js:1]: If you want to add your unit test, you have to revert some parts of #23352.

- Create an `addons/utils` folder in `unit` and place your tests there.
- Create `test/unit/three.addons.unit.js`.
- Introduce a new script `test-unit-addons` in `package.json` which should look like so:

```
"test-unit-addons": "qunit -r failonlyreporter -f !-webonly test/unit/three.addons.unit.js",
```

Comment (catalin-enache) [reply test/unit/addons/utils/BufferGeometryUtils.tests.js:1]: Thanks a lot for the hints.
I read the issue related to that commit and I understand the motivation.
On another hand, when I look at `ThreeJs` I see it as a fully-fledged framework with all "batteries included".
I'm asking myself, what would `ThreeJS` be without FBX/GLTF loaders, without OrbitControls and all that super useful stuff that lives in `addons`.
IMO it would be like a car made of the engine only (no wheels, not anything else) :)
This is not for me to decide the importance of "addons" but I thank you for allowing adding back the means to test `examples/jsm` stuff.

File: package.json [hunk 5]
```diff
@@ -58,6 +58,7 @@
     "lint": "npm run lint-core",
     "lint-fix": "npm run lint-core -- --fix && npm run lint-addons -- --fix && npm run lint-examples -- --fix && npm run lint-docs -- --fix && npm run lint-editor -- --fix && npm run lint-playground -- --fix && npm run lint-manual -- --fix && npm run lint-test -- --fix && npm run lint-utils -- --fix",
     "test-unit": "qunit -r failonlyreporter -f !-webonly test/unit/three.source.unit.js",
+    "test-unit-addons": "qunit -r failonlyreporter -f !-webonly test/unit/three.addons.unit.js",
```
Comment (Mugen87) [inline package.json:61]: @mrdoob Are you fine with reactivating unit tests for addons?

**Review by Mugen87 — APPROVED** [review]

File: examples/jsm/utils/BufferGeometryUtils.js (hunk 2 above)
Comment (Mugen87) [reply examples/jsm/utils/BufferGeometryUtils.js:725]: If someone would use `Float16BufferAttribute`, the new approach is required in any event.

File: examples/jsm/utils/BufferGeometryUtils.js (hunk 1 above)
Comment (Mugen87) [reply examples/jsm/utils/BufferGeometryUtils.js:635]: We usually don't use the word `collection` in this context. Can't you just use `morphAttributes`?

File: package.json (hunk 5 above)
Comment (donmccurdy) [reply package.json:61]: I'm personally in favor of having unit tests for addons. In several cases I've found it more more difficult to test changes (GLTFExporter and BufferGeometryUtils for example) without them, and would be easier with unit tests.

That said ... deleting the addons unit tests back in #23352 was a pretty big change! I feel like we should at least open an issue to address why we're adding them back, and what (if anything?) should be different this time. Without that I worry that new unit tests could be deleted again, and this isn't an encouraging outcome for contributors.

File: examples/jsm/utils/BufferGeometryUtils.js (hunk 1 above)
Comment (catalin-enache) [reply examples/jsm/utils/BufferGeometryUtils.js:635]: Done !

File: package.json (hunk 5 above)
Comment (catalin-enache) [reply package.json:61]: I created this one: https://github.com/mrdoob/three.js/issues/28452

Comment (mrdoob) [reply package.json:61]: At the end of the day it's all about how much value they bring versus how much maintenance and discussions they cost.

**Review by donmccurdy — APPROVED** [review]
As a note perhaps for some future PR, I think we could improve performance of this method a bit by doing a first pass over the geometry to build a mapping (stored as Uint32Array) from vertex index in the input geometry to vertex index in the output geometry, incrementing the number of unique vertices as we go. Then in the second pass we could write the destination geometry, without needing the larger intermediate tmp allocations.

But, not really related to this PR, which looks good to me — thank you for the report and the fix!
