### PR TITLE
WebGLRenderer: Allow InstancedMesh provide a unique ID for WebGLBindingStates.

### LINKED ISSUE #32552: VAO not cached when two different InstancedMesh use the same InstancedBufferGeometry
### Description

In `WebGLBindingStates` `saveCache` saved attributes not only from `geometry`, but also from `object`, when the object is `InstancedMesh`. The trouble is the cache retrieval in `getBindingState` uses only `geometry, program, material` as the cache key.

Once I use the same `InstancedBufferGeometry` with multiple `InstancedMesh` instances, their VAO is not cached and each of them calls `setupVertexAttributes`, because they all reuse the same biding state with different intancing attributes. This is common in my game, where instancing is done automatically and dynamically.

I suggest in case of `InstancedMesh` the geometryId should be extended to contain `InstancedMesh` as well, so that different combinations of `InstancedBufferGeometry` and `InstancedMesh` get their own binding state.

I think I could prepare a PR if you agree.

### Reproduction steps

Given my game uses custom JVM port of three.js, I do not have a reproduction ready yet. I have checked the current sources of three.js have the same behaviour.

### Version

r164

### PR DESCRIPTION
**Pull request by OndrejSpanel**
Fixed #32552.

**Description**

Allow meshes to provide a specific ID for `WebGLBindingState` cache, and implement this for `InstancedMesh`.

This makes sure two different `InstancedMesh` which share the same geometry get a different binding state, caching VAO for them, including their custom attributes like `instanceMatrix` or `instanceColor`.

### CODE REVIEW

File: src/renderers/webgl/WebGLBindingStates.js [hunk 1]
```diff
@@ -67,16 +67,27 @@ function WebGLBindingStates( gl, attributes ) {
...
+		let objectMap = bindingStates[ geometry.id ];
+
+		if ( objectMap === undefined ) {
+
+			objectMap = {};
+			bindingStates[ geometry.id ] = objectMap;
+
+		}
+
+		const stateId = object.getBindingStateId();
```
Comment (Mugen87) [inline src/renderers/webgl/WebGLBindingStates.js]: Can we remove this method for now and write this line like so:
```js
const stateId = ( object.isInstancedMesh === true ) ? object.id : 0;
```

Comment (OndrejSpanel) [reply src/renderers/webgl/WebGLBindingStates.js]: Sure. There is no other case which needs to be solved this way at the moment, and it can be generalized when needed.

File: src/renderers/webgl/WebGLBindingStates.js [hunk 2]
```diff
@@ -67,16 +67,28 @@ function WebGLBindingStates( gl, attributes ) {
...
+
+		if ( objectMap === undefined ) {
+
+			objectMap = {};
+			bindingStates[ geometry.id ] = objectMap;
+
+		}
+
+		// Each InstancedMesh requires unique binding states because it contains instanced attributes.
+		const stateId = ( object.isInstancedMesh === true ) ? object.id : 0;
```
Comment (Mugen87) [inline src/renderers/webgl/WebGLBindingStates.js]: Can we rename this variable to `objectId`?

**Comment by Mugen87** [comment]
For other reviewers: The effective changes of this PR are quite compact. It's easier to see by removing changes to the formatting from the diff: https://github.com/mrdoob/three.js/pull/32556/files?w=1

File: src/renderers/webgl/WebGLBindingStates.js (hunk 2 above)
Comment (OndrejSpanel) [reply src/renderers/webgl/WebGLBindingStates.js]: Your wish is my command.

**Comment by OndrejSpanel** [comment]
> It's easier to see by removing changes to the formatting from the diff

I could try removing them, if I knew how.

... oh wait, the changes are mostly caused by changed nesting level. No way to remove that, I guess.

**Comment by OndrejSpanel** [comment]
I think there is one more thing to be checked / considered. When disposing `InstancedMesh`, corresponding bingings states need to be removed as well. Marking as draft before this is clarified, as not handling this properly could cause resource leaks.

**Comment by OndrejSpanel** [comment]
As I am testing this in the game, I realized I  need a slightly different id. I have different `InstancedMesh` instances which share the same `instanceMatrix` / `instanceColor`. This is done because I create a copy of the scene for shadow map rendering and to render env. reflection map, and the copy is as shallow as possible (meshes sharing geometries and attributes with the main scene).

Instead of checking for `InstancedMesh`, I need to check for `instanceMatrix` `BufferAtrribute.id` (and perhaps even `instanceColor`, although in my case those two are always paired and checking one of them is enough).

Without this I am unable to implement the proper cleanup.

I think the nicest way how to get this working would be to go back to the original idea of using `getBindingStateId` and implementing it as `getBindingStateId = this.instanceMatrix.id`, but if you prefer, I can still use the `isInstancedMesh` test and access the property  (which I have committed now).

**Comment by OndrejSpanel** [comment]
> This is done because I create a copy of the scene for shadow map rendering and to render env. reflection map, and the copy is as shallow as possible (meshes sharing geometries and attributes with the main scene).

Turns out this is not true. Shadow and env. scenes have each their own instancer and create different instance chains. Original design should be fine, at least for my use case.

@Mugen87 However if you prefer the new version, I am fine with that as well, both should work equally well for me.

That said, I experience some resource leaks with current implementation in my game and I will not mark this as Ready for review until I solve it.

**Comment by OndrejSpanel** [comment]
> That said, I experience some resource leaks with current implementation in my game and I will not mark this as Ready for review until I solve it.

The issue was on the application side, shadow scene was missing dispose of instanced meshes.

> I have different `InstancedMesh` instances which share the same `instanceMatrix` / `instanceColor`

If anyone was tempted to do this, I would warn against it. It is hard to get it right, as on any mesh disposal its atributes are destroyed (`gl.deleteBuffer`), shared or not, making cached binding states of any other meshes sharing the same attribute invalid.

File: src/renderers/webgl/WebGLBindingStates.js [hunk 3]
```diff
@@ -67,16 +67,28 @@ function WebGLBindingStates( gl, attributes ) {
...
+
+		if ( objectMap === undefined ) {
+
+			objectMap = {};
+			bindingStates[ geometry.id ] = objectMap;
+
+		}
+
+		// Each InstancedMesh requires unique binding states because it contains instanced attributes.
+		const objectId = ( object.isInstancedMesh === true ) ? object.id : 0;
```
Comment (Mugen87) [inline src/renderers/webgl/WebGLBindingStates.js]: Can we use `-1` as the `objectId` for non-instanced objects? Strictly speaking, `0` could be a valid ID for an instanced mesh which could causes side effects.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
Tested the disposal with `webgl_instancing_dynamic` and the result looks as expected 👍 .
