### PR TITLE
TSL: Fix `dispose()` when using `reflector()`.

### LINKED ISSUE #30929: TSL: Can not dispose NodeMaterial correct
### Description

I can't dispose nodeMaterial correct , I try many times find the question , the problem is nodeMaterial , memory is rising , not stop

### Reproduction steps

1. https://jsfiddle.net/aqybh64u/1/
2.
3.

### Code

```js
    render(deltaTime: number, timestamp: number): void {

        if (this.renderer.hasInitialized()) {

            const reflection = reflector();
            scene.add(reflection.target);
            const floorMaterial = new THREE.NodeMaterial();
            floorMaterial.colorNode = reflection;

            const floor = new THREE.Mesh(new THREE.BoxGeometry(50, 0.001, 50), floorMaterial);

            scene.add(floor);

            renderer.render(scene,camera);
            floor.geometry.dispose();
            floorMaterial.dispose();
            floorMaterial.colorNode.dispose();
            reflection.dispose();
            scene.remove(floor);

            console.log(renderer.info.memory);

        }

    }
```

### Live example

https://jsfiddle.net/aqybh64u/1/

### Screenshots

Image

### Version

r175

### Device

_No response_

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #30929.

**Description**

The PR makes sure `ReflectorNode.dispose()` works as expected.

### CODE REVIEW

File: src/renderers/common/Textures.js [hunk 1]
```diff
@@ -445,10 +443,16 @@ class Textures extends DataMap {
 	 */
 	_destroyTexture( texture ) {
 
-		this.backend.destroySampler( texture );
-		this.backend.destroyTexture( texture );
+		if ( this.has( texture ) === true ) {
```
Comment (Mugen87) [inline src/renderers/common/Textures.js:446]: This is to make sure the following does not break the dispose logic:
```js
renderTarget.dispose();
renderTarget.texture.dispose();
```
Since calling `dispose()` on the render target disposes all of its textures, it's important to ensure `dispose()` called on texture does not trigger redundant operations.
