### PR TITLE
Respect the original camera view offset inside SSAARenderPass.

### LINKED ISSUE #21735: SSAARenderPass does not respect the original view object of the PerspectiveCamera.
[`SSAARenderPass` unintentionally overwrites any original, user-specified `view` of the `PerspectiveCamera` to apply jitter.](https://github.com/mrdoob/three.js/blob/d4aa9e00ea29808534a3e082f602c544e5f2419c/examples/jsm/postprocessing/SSAARenderPass.js#L107)

This could be resolved by caching the original `view`, using it to translate each jitter, and restoring it afterward.

**To Reproduce**

1. Clone the repository.

2. Edit the [postprocessing ssaa example](https://github.com/mrdoob/three.js/blob/d4aa9e00ea29808534a3e082f602c544e5f2419c/examples/webgl_postprocessing_ssaa.html) to include line `cameraP.setViewOffset( width, height, width / 2, 0, width, height );` [between lines 93 and 94](https://github.com/mrdoob/three.js/blob/d4aa9e00ea29808534a3e082f602c544e5f2419c/examples/webgl_postprocessing_ssaa.html#L93).

3. Observe the lack off horizontal offset which should have occurred.

**Platform:**

 - Device: Any
 
 - OS: Any
 
 - Browser: Any
 
 - Three.js version: r128

### PR DESCRIPTION
**Pull request by msimpson**
Respect the original camera view offset inside SSAARenderPass.

Add a viewOffsetX GUI param to the webgl_postprocessing_ssaa example.

Fixes #21735.

### CODE REVIEW

File: examples/jsm/postprocessing/SSAARenderPass.js [hunk 1]
```diff
@@ -95,7 +95,19 @@ class SSAARenderPass extends Pass {
 		const roundingRange = 1 / 32;
 		this.copyUniforms[ 'tDiffuse' ].value = this.sampleRenderTarget.texture;
 
-		const width = readBuffer.width, height = readBuffer.height;
+    const view = this.camera.view !== null && this.camera.view.enabled ? Object.assign( {}, this.camera.view ) : null;
```
Comment (Mugen87) [inline examples/jsm/postprocessing/SSAARenderPass.js:98]: Do you mind fixing the formatting?

Comment (msimpson) [reply examples/jsm/postprocessing/SSAARenderPass.js]: Sure. I'm refining things a bit, as well.

**Comment by msimpson** [comment]
@Mugen87 

Spoke too soon. Updated it one last time to always reset to the original `camera.view`, regardless.

I don't want this to be destructive in anyway, like a disabled view being lost.

**Comment by msimpson** [comment]
I've been testing this out in a project where I'm using the SSAARenderPass and this needs more work.

**Comment by msimpson** [comment]
@Mugen87 

Unless there are any objections, I'm considering this complete.

File: examples/jsm/postprocessing/SSAARenderPass.js [hunk 2]
```diff
@@ -95,7 +95,31 @@ class SSAARenderPass extends Pass {
...
+			
+			width: readBuffer.width,
+			
+			height: readBuffer.height
+		
+		};
+
+		let originalViewOffset = null;
+
+		if ( this.camera.setViewOffset ) {
```
Comment (Mugen87) [inline examples/jsm/postprocessing/SSAARenderPass.js:116]: It would be good to avoid a check for `setViewOffset()`. Wouldn't the code also work if you just remove this `if` statement and always execute the next two lines?

Comment (msimpson) [reply examples/jsm/postprocessing/SSAARenderPass.js:116]: @Mugen87 

The aim was to respect the existing `setViewOffset` and `clearViewOffset` conditionals.

Removing it would assume a `view` property always exists, and if it didn't an error would occur as `undefined` !== `null`.

Checking for the existence of `setViewOffset` proves that a `view` property exists and will behave as `null` or `Object`.

If all cameras provide a `view` property with the same behavior and methods, then all the conditionals in question can go.

Comment (msimpson) [reply examples/jsm/postprocessing/SSAARenderPass.js:116]: My aim was to remain consistent with the existing `setViewOffset` and `clearViewOffset` conditionals.

But, by virtue of JavaScript those lines wouldn't cause an issue as `Object.assign( {}, undefined )` is `{}`.

So, I'll drop the conditional.

File: examples/jsm/postprocessing/SSAARenderPass.js [hunk 3]
```diff
@@ -141,8 +165,26 @@ class SSAARenderPass extends Pass {
 			this.fsQuad.render( renderer );
 
 		}
-
-		if ( this.camera.clearViewOffset ) this.camera.clearViewOffset();
+			
+		if ( this.camera.setViewOffset && originalViewOffset !== null && originalViewOffset.enabled ) {
```
Comment (Mugen87) [inline examples/jsm/postprocessing/SSAARenderPass.js]: I guess the check for `setViewOffset()` can be removed here, too?

**Review by msimpson — COMMENTED** [review]
I streamlined things further given `Object.assign( {}, null )` behaves in the same fashion.

As `originalViewOffset` will at the least become an empty object, I can drop the `null` checks and work from `enabled` alone.

**Comment by Mugen87** [comment]
For testing: https://raw.githack.com/msimpson/three.js/preserve-perspective-camera-view-in-ssaa-render-pass/examples/webgl_postprocessing_ssaa.html

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!
