### PR TITLE
InstancedMesh: Add support for async color definitions.

### LINKED ISSUE #21786: instanceColor attribute is not defined when InstancedMesh is populated asynchronously
Just as the title says. It all boils down to this line https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLPrograms.js#L171. Setting any color for any instance just after the instanced mesh is created, solves the issue. But this is not obvious and looks like it's not documented.

**To Reproduce**

1. Prepare a scene with InstancedMesh
2. Render it
3. Populate the instanced mesh asynchronously

**Live example**

[jsfiddle](https://jsfiddle.net/odh2vzL6/2/)

**Expected behavior**

When setColorAt is called, the shader should be recompiled to include the `instanceColor`. Or there should be a valid and documented way to make sure that this attribute is always defined.

**Platform**

 - Device: Desktop
 - OS: Windows
 - Browser: Chrome
 - Three.js version: r128

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Fixed #21786

**Description**

Flags the current instanced material for update on render whenever `instanceColor` is (un)set. This tracks async effects without explicitly managing them in `InstancedMesh`.

<details>

<summary>Show Example:</summary>

<br />

The following renders a red cube whenever `instanceColor` is properly in sync with the mesh (~1s).

```js
import * as THREE from 'three';

let renderer, scene, camera;

init();
animate();

function init() {

    renderer = new THREE.WebGLRenderer();
    renderer.setSize( window.innerWidth, window.innerHeight );
    renderer.setPixelRatio( window.devicePixelRatio );
    document.body.appendChild( renderer.domElement );

    scene = new THREE.Scene();
    
    camera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight );
    camera.position.z = 5;

    const geometry = new THREE.BoxGeometry();

    const material = new THREE.ShaderMaterial({
      vertexShader: /* glsl */ `

        varying vec3 vColor;

        void main() {

          #ifdef USE_INSTANCING_COLOR

            vColor = instanceColor;

          #endif

          gl_Position = projectionMatrix * modelViewMatrix * instanceMatrix * vec4( position, 1.0 );

        }

      `,
      fragmentShader: /* glsl */ `

        varying vec3 vColor;

        void main() {

          gl_FragColor = vec4( vColor, 1.0 );

        }

      `,
    });

    const mesh = new THREE.InstancedMesh( geometry, material, 1 );
    scene.add( mesh );

    setTimeout(() => {

      mesh.setColorAt( 0, new THREE.Color( 'red' ) );
      mesh.instanceColor.needsUpdate = true;

    }, 1000 );

}

function animate() {

  requestAnimationFrame( animate );
  renderer.render( scene, camera );

}
```

</details>

### CODE REVIEW

**Comment by Mugen87** [comment]
We have to decide first if we want to support setting `instanceColor` asynchronously or if the data setup has to be done before the first render. 

The problem is that every additional check in `setProgram()` increases the per-frame overhead for _all_ scenes. So my personal preference is to not add these checks but update the docs instead. If you want to add colors to an instance mesh after the first render, call `dispose()` and create a new instanced mesh.

File: src/renderers/WebGLRenderer.js [hunk 1]
```diff
@@ -1486,6 +1486,8 @@ class WebGLRenderer {
 
 			const materialProperties = properties.get( material );
 
+			materialProperties.instancingColor = object.isInstancedMesh === true && object.instanceColor !== null;
```
Comment (Mugen87) [inline src/renderers/WebGLRenderer.js:1489]: Do you mind explaining why this line required? I was under the impression the additional checks in `setProgram()` would be sufficient.

**Comment by Mugen87** [comment]
On the other hand setting up the instanced mesh before the first render does not fix the use case described in https://github.com/mrdoob/three.js/issues/21786#issuecomment-836602055.

Um, this is indeed a tricky one. I guess I'm okay with accepting the changes to the renderer then.

File: src/renderers/WebGLRenderer.js (hunk 1 above)
Comment (CodyJasonBennett) [reply src/renderers/WebGLRenderer.js]: It was left over. I verified that the code path was reached despite the bailout via `lightsStateVersion`, so this is redundant.

**Review by Mugen87 — APPROVED** [review]
