### PR TITLE
WebGLRenderer: Add `initRenderTarget()`.

### LINKED ISSUE #28282: WebGLRenderer: Calling "copyTextureToTexture" on an unused WebGLRenderTarget does nothing
### Description

Found during #28281

If you call `copyTextureToTexture` to copy data into a RenderTarget that hasn't been rendered to, yet, then nothing occurs and an error is logged:

> ```
> GL_INVALID_VALUE: Offset overflows texture dimensions.
> ```

### Reproduction steps

1. Create a new WebGLRenderTarget
2. Create a new data texture
3. Copy data texture data into the render target
4. Render target is still empty and a warning is logged

### Code

```js
const target = new THREE.WebGLRenderTarget( 16, 16 );
const source = new THREE.DataTexture( new Uint8Array( 16 * 16 * 4 ).fill( 255 ), 16, 16 );

// uncomment these lines initialize the render target and prevent the error for logging
// renderer.setRenderTarget( target );
// renderer.render( scene, camera );
// renderer.setRenderTarget( null );

renderer.copyTextureToTexture( new THREE.Vector2( 0, 0 ), source, target.texture );

// logs warning
```

### Live example

https://jsfiddle.net/2yakmh60/3/

### Screenshots

_No response_

### Version

dev

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by gkjohnson**
Fix #28282
Based on #28281 which must be merged first

**Description**

- Updates `initTexture` to initialize a WebGLRenderTarget if it has not been already.
- Updates `copyTextureToTexture` and `copyTextureToTexture3D` to support WebGLRenderTarget and initialize it if it has not been already.

_This contribution is funded by the [Cesium GIS Ecosystem Grant](https://cesium.com/cesium-ecosystem-grants/grant-directory/)_

### CODE REVIEW

File: src/renderers/WebGLRenderer.js [hunk 1]
```diff
@@ -2488,7 +2538,15 @@ class WebGLRenderer {
 
 		this.initTexture = function ( texture ) {
 
-			if ( texture.isCubeTexture ) {
+			if ( texture.isRenderTarget ) {
```
Comment (Mugen87) [inline src/renderers/WebGLRenderer.js:2541]: The thing is `initTexture()` is not supposed to called with an instance of render target so I'm not sure about this change. You have mentioned this in https://github.com/mrdoob/three.js/issues/28282#issuecomment-2094832435 but we have a long-standing policy to _not_ use render target as textures and I don't think this is the right opportunity to change this policy. Hence, I also think `copyTextureToTexture()` should not used with render targets but with their texture property.

How about we add `initRenderTarget()` instead? Devs can then call this method in their app before using `copyTextureToTexture()` with an uninitialized render target.

Comment (gkjohnson) [reply src/renderers/WebGLRenderer.js:2541]: > How about we add WebGLRenderer.initRenderTarget() instead? 

This is fine with me - it still leads to a confusing situation where every other kind of texture can be initialized in `copyTextureToTexture` while render target textures specifically cannot. But understood that there would be larger architectural changes needed to support this correctly.

I can make the change once #28281 is merged.

**Review by Mugen87 — APPROVED** [review]
