### PR TITLE
GLTFLoader: More robust de-duping of mesh/node names, morph target fixes, etc.

### LINKED ISSUE #12368: GLTFLoader: Morph targets not animating correctly in ROME models
The [ROME glTF models](https://github.com/mrdoob/rome-gltf) are not playing correctly in the latest version of GLTFLoader. Some pieces of the models are displaced (see screenshot) and some property binding errors appear in the log:

```
THREE.PropertyBinding: Trying to update property for track: horse_colorMap.morphTargetInfluences but it wasn't found. Group
```

screen shot 2017-10-09 at 7 07 10 am

This may have been introduced by #12244.

### PR DESCRIPTION
**Pull request by donmccurdy**
Changes:
- Make uvScaleMap updates backwards-compatible
- Fix error in morph targets if normal attributes are undefined (the frog ROME model broke here)
- Flatten a THREE.Group if it only contains a single Mesh
- Try to eliminate more cases where names might be duplicated, breaking animation. Examples:
  - Parent `node` and child `mesh` share the same name in source glTF
  - Mesh is reused by multiple nodes (see: CesiumMilkTruck)

This fixes all of the ROME examples, although they still require THREE.DoubleSide.

Demo: https://gltf-viewer-experimental.donmccurdy.com/

The demo will print a tree of mesh names coming out of the loader. Examples:

| AnimatedMorphSphere | CesiumMilkTruck |
|--|--|
| screen shot 2017-10-09 at 7 02 19 pm |  screen shot 2017-10-09 at 7 07 30 pm |

- Fixes #12368. Problems with ROME models were related to (1) missing normals in one model, and (2) nodes and meshes sharing names in many models.
- Improves #11944, although there's still more we can do to flatten the output.
- Polly (#12364) still does not work completely; the head disappears at odd intervals. Looks like an animation problem, or some ambiguity in the glTF spec.

### CODE REVIEW

**Comment by mrdoob** [comment]
Thanks!

File: examples/js/loaders/GLTFLoader.js [hunk 1]
```diff
@@ -2205,6 +2240,27 @@ THREE.GLTFLoader = ( function () {
 
 		} );
 
+		// Meshes can (and should) be reused by multiple nodes in a glTF asset. To
+		// avoid having more than one THREE.Mesh with the same name, count
+		// references and rename instances below.
+		//
+		// Example: CesiumMilkTruck sample model reuses "Wheel" meshes.
+		nodes.forEach( function ( nodeDef ) {
```
Comment (mrdoob) [inline examples/js/loaders/GLTFLoader.js]: By the way... better to use `for in` in these situations I think. Using `forEach` in this manner tends to create a lot of garbage.

**Comment by Mugen87** [comment]
It looks like this PR broke some skeletal animation examples (e.g. monster, cesium man).

http://rawgit.com/mrdoob/three.js/dev/examples/index.html#webgl_loader_gltf

**Comment by takahirox** [comment]
Seems like [this line](https://github.com/donmccurdy/three.js/blob/ed042044aa3cab6bf4b22aadd25d4d725b6b22dd/examples/js/loaders/GLTFLoader.js#L2363) causes the error by attempting to set `.skinning` true for material but `Bone` doesn't have material.

**Comment by takahirox** [comment]
I haven't look into the detail code yet but seems like adding `nodeDef.mesh !== undefined` statement [here](https://github.com/donmccurdy/three.js/blob/ed042044aa3cab6bf4b22aadd25d4d725b6b22dd/examples/js/loaders/GLTFLoader.js#L2274) would fix cesium man case. (Maybe changing the order, from first `isBone` check and then `mesh` check to `mesh` check and then `isBone` check also ok.) `nodeDef` causing the error has both `isBone: true` and `mesh: 0`.

(I'm not sure if this's the root issue yet tho)

**Comment by donmccurdy** [comment]
@Mugen87 @takahirox Thanks! With #12373 and #12378 this should be fixed.
