### PR TITLE
ExtrudeGeometry: Fix toJSON() when using extrudePath.

### LINKED ISSUE #24010: CatmullRomCurve3.toJSON() works only once
When you call scene.toJSON() a second time with CatmullRomCurve3, the toJSON() method is no longer recognized for CatmullRomCurve3, CatmullRomCurve3 prototype changes to Object from Curve

We should be able to call toJSON() with CatmullRomCurve3 several times

**Screenshots**
First execution 

Second execution

**Platform:**

 - Device: [Desktop,]
 - OS: [Windows]
 - Browser: [Chrome]
 - Three.js version: [dev, r140]

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #24010.

**Description**

This PR ensures that the `data` object does have a reference to original `options` parameter object of `ExtrudeGeometry`.

### CODE REVIEW

File: src/geometries/ExtrudeGeometry.js [hunk 1]
```diff
@@ -784,6 +784,7 @@ const WorldUVGenerator = {
 function toJSON( shapes, options, data ) {
 
 	data.shapes = [];
+	data.options = Object.assign( {}, options );
```
Comment (mrdoob) [inline src/geometries/ExtrudeGeometry.js:787]: Should this be moved to line 804 for readability?

Comment (Mugen87) [reply src/geometries/ExtrudeGeometry.js:787]: Indeed!

**Comment by mrdoob** [comment]
Thanks!
