### PR TITLE
Fix color attribute initialization of InstancedMesh

### LINKED ISSUE #22170: InstancedMesh color attribute initialization is done with current count value instead of the maximum count.
**Describe the bug**

Color attribute of InstancedMesh is not initialized on the constructor but when first calling ``setColorAt()``, and it creates ``instanceColor`` BufferAtribute with the current count value, which can be lower than the initial one. This leads to issues if the count is increased after.

**To Reproduce**

1. Create an InstancedMesh with initial count of for example 1000
2. Set count to 500
3. Create color attribute array calling ``setColorAt()``
4. Set count to 1000 back again.
5. All instances from 500 to 1000 will have a black color and ``setColorAt()`` won't work on them, as the color array is out of bounds for those instances.

**Expected behavior**

``instanceColor`` BufferAttribute should be initialized with the max count used in the constructor.

### PR DESCRIPTION
**Pull request by FoolHen**
Fixes #22170 

**Description**

Color attribute of InstancedMesh is not initialized on the constructor but when first calling ``setColorAt()``, and it creates the BufferAtribute with the current count value, which can be lower than the initial one. This leads to issues if the count is increased after.
 
This PR saves the maximum count to later correctly initialize the color BufferAtribute.

### CODE REVIEW

File: src/objects/InstancedMesh.js [hunk 1]
```diff
@@ -95,7 +96,7 @@ class InstancedMesh extends Mesh {
 
 		if ( this.instanceColor === null ) {
 
-			this.instanceColor = new BufferAttribute( new Float32Array( this.count * 3 ), 3 );
+			this.instanceColor = new BufferAttribute( new Float32Array( this._maxCount * 3 ), 3 );
```
Comment (Mugen87) [inline src/objects/InstancedMesh.js:99]: I suggest you do it differently. Instead of introducing `_maxCount`, you can derive the `Float32Array` from the existent `instanceMatrix` buffer attribute.

Comment (FoolHen) [reply src/objects/InstancedMesh.js:99]: Oh nevermind, i can use ``.count``.

**Comment by mrdoob** [comment]
Thanks!
