### PR TITLE
WebGPURenderer: Use `depth32float` instead of `depth24plus` when using `reversedDepthBuffer`

### LINKED ISSUE #33166: Reversed depth buffer / Z-buffer not working in Firefox
### Description

Here is a screenshot of the "Reversed depth buffer" example in Firefox v148. What could be the issue with reversed depth buffer in Firefox? Notice how there is still z-fighting in the "reverse z-buffer" column.

https://threejs.org/examples/?q=reverse#webgpu_reversed_depth_buffer
Image

### Reproduction steps

Visit https://threejs.org/examples/?q=reverse#webgpu_reversed_depth_buffer in Firefox

### Live example

https://threejs.org/examples/?q=reverse#webgpu_reversed_depth_buffer

### PR DESCRIPTION
**Pull request by PoseidonEnergy**
Fixed #33166 

**Description**

This PR makes WebGPU use `depth32float` when `reversedDepthBuffer` is enabled.

Right now, `PassNode` creates a `DepthTexture` for its internal `RenderTarget`, but it leaves the depth texture on the default type. The WebGPU format mapping already supports `DepthFormat + FloatType -> Depth32Float`, but the default non-stencil canvas path and the pipeline format query still use `Depth24Plus`.

This fixes the Firefox `webgpu_reversed_depth_buffer` z-fighting issue: the example itself already notes that "for best results, a floating-point depth buffer should be used," and explicitly using float depth removes the remaining z-fighting seen in Firefox for the reverse-Z column.

### CODE REVIEW

**Comment by Mugen87** [comment]
I understand the PR aligns the render target setup with `webgl_reversed_depth_buffer`.

But before merging this, we should find out why Firefox+Windows is the only combination that needs a higher precision. All others don't and this change makes the implementation slower for all these devices.

**Comment by PoseidonEnergy** [comment]
> I understand the PR aligns the render target setup with `webgl_reversed_depth_buffer`.
> 
> But before merging this, we should find out why Firefox+Windows is the only combination that needs a higher precision. All others don't and this change makes the implementation slower for all these devices.

@Mugen87 I think `depth24plus` is implementation-flexible in WebGPU. It may be backed by either 24-bit depth or `depth32float` depending on the implementation, which is why in Chrome it works well but Firefox still had z-fighting.

The following is a quote from https://www.w3.org/TR/webgpu which shows it is implementation-specific:

> The depth component of the "depth24plus" and "depth24plus-stencil8" formats may be implemented as either a 24-bit depth value or a "depth32float" value.

I just reverted the changes to the reverse-Z example and instead explicitly upped the depth precision when `reversedDepthBuffer` is `true`. This appeared to have fixed the example, without having to make changes to the example.

File: src/renderers/webgpu/utils/WebGPUTextureUtils.js [hunk 1]
```diff
@@ -468,7 +468,7 @@ class WebGPUTextureUtils {
 		} else if ( depth ) {
 
 			format = DepthFormat;
-			type = UnsignedIntType;
+			type = backend.renderer.reversedDepthBuffer === true ? FloatType : UnsignedIntType;
```
Comment (Mugen87) [inline src/renderers/webgpu/utils/WebGPUTextureUtils.js:471]: Is this change and the one in `WebGPUUtils` necessary to fix the Firefox issue?

Can you please verify that even without post processing (`RenderPipeline`) reverse depth buffer is broken in Firefox+Windows as well?

File: src/nodes/display/PassNode.js [hunk 2]
```diff
@@ -757,6 +757,12 @@ class PassNode extends TempNode {
 
 		this.renderTarget.texture.type = renderer.getOutputBufferType();
 
+		if ( renderer.reversedDepthBuffer === true && this.renderTarget.depthTexture !== null && this.renderTarget.stencilBuffer !== true ) {
```
Comment (Mugen87) [inline src/nodes/display/PassNode.js]: As mentioned above: I don't think you have to test for `stencilBuffer`.

Comment (Mugen87) [reply src/nodes/display/PassNode.js]: Also a depth texture is always available so you can simply do:

```js
if ( renderer.reversedDepthBuffer === true ) {

    this.renderTarget.depthTexture.type = FloatType;

}
```

File: src/renderers/webgpu/utils/WebGPUTextureUtils.js (hunk 1 above)
Comment (Mugen87) [reply src/renderers/webgpu/utils/WebGPUTextureUtils.js:471]: It should be possible to use `FloatType` even with a stencil buffer.

You can test that here: https://threejs.org/examples/webgl_depth_texture

`DepthStencilFormat` + `FloatType` is a valid combination.

File: src/renderers/webgpu/utils/WebGPUUtils.js [hunk 3]
```diff
@@ -46,7 +46,15 @@ class WebGPUUtils {
 
 			} else {
 
-				format = GPUTextureFormat.Depth24Plus;
+				if ( this.backend.renderer.reversedDepthBuffer === true ) {
```
Comment (Mugen87) [inline src/renderers/webgpu/utils/WebGPUUtils.js:57]: See https://github.com/mrdoob/three.js/pull/33184/changes#r2939240133.

File: src/renderers/webgpu/utils/WebGPUTextureUtils.js (hunk 1 above)
Comment (PoseidonEnergy) [reply src/renderers/webgpu/utils/WebGPUTextureUtils.js:471]: > Can you please verify that even without post processing (`RenderPipeline`) reverse depth buffer is broken in Firefox+Windows as well?

Here is JSFiddle to test `reversedDepthBuffer` without post processing: https://jsfiddle.net/yzmxubt6

You will notice that in Firefox, the pink/orange colored plane does not properly intersect the blue plane when viewed at a distance.

In Chrome however, the pink/orange color plane properly intersects the blue plane.

### Firefox

image

### Chrome

image

**Comment by PoseidonEnergy** [comment]
@Mugen87 I made some changes according to your suggestions, let me know how they look.

**Review by Mugen87 — APPROVED** [review]
Looks good to me! I think we can give this a try.

@sunag Are you okay with these changes?

**Comment by sunag** [comment]
> @sunag Are you okay with these changes?

Wouldn't it be better if we had a `depthType` that could override it when assigned? 
Like `WebGPURenderer( { depthType: FloatType } )`. I think it could cover more use cases.

**Comment by Mugen87** [comment]
I think it's better when the user does not have to worry about the depth texture type. This is rather technical and most users won't get it right. Enabling reverse depth buffer should make the feature work everywhere.

https://github.com/mrdoob/three.js/pull/33184#issuecomment-4063966576 makes me consider to use `THREE.FloatType` by default for depth textures. The fact that implementations might interpret `depth24plus` differently is worrying in context of other use cases as well. Varying depth precision was already in earlier days of three.js a typical source of confusion. 

Normally a 24 bit depth buffer should be sufficient but there are use cases (like reverse depth buffer) where it obviously doesn't. Also many devices already interpret `depth24plus` as 32 bit so there should be no performance regression. Mobile is something to look after though.

For now, I would use `FloatType` just in context of reverse depth buffer and see how it goes.

**Comment by sunag** [comment]
Using 32-bit as the default and fallback to 24-bit sounds great if we can do it safely.

My concern would be, as you yourself said, that a 24-bit depth buffer might not be sufficient for all use cases. Maybe someone would want to use this without enabling reverse depth; I thought the idea would be similar to `outputBufferType` in that sense.

If you are confident, let’s move forward, we can change this later if necessary.

**Comment by Mugen87** [comment]
@PoseidonEnergy Thank you for working on this! https://github.com/mrdoob/three.js/pull/33184#issuecomment-4063966576 is an important insight!

**Comment by Makio64** [comment]
@Mugen87 @PoseidonEnergy @sunag I would really prefer to keep low precision default whenever possible. 8bit is a lot of bandwidth if not needed.

Production code as to deal with low end device all the time, also Threejs did it in past with halfFloat everywhere for mobile and it was a very nice approach.

**Comment by Mugen87** [comment]
Given that reverse depth buffer _requires_ 32 bit depth, there is no way around I'm afraid.

Devices that worked so far already used 32 bit depth. The others are now force so the feature is actually functional.
