### PR TITLE
FBXLoader: Fix polygon triangulation

### LINKED ISSUE #15211: FBXLoader: Incorrect mesh parsing
Apparently it loads correctly in Unity. Thanks @jcarpenter for the files.

[Coordinate tests.zip](https://github.com/mrdoob/three.js/files/2551293/Coordinate.tests.zip)

unnamed

/cc @looeee

### PR DESCRIPTION
**Pull request by StrandedKitty**
Fixed #15211

**Description**

I've implemented correct triangulation using Earcut for concave polygons with >3 vertices when parsing FBX models. Previously this kind of polygons was naively triangulated by looping through each vertex and sequentially creating N-2 triangles for a polygon with N vertices. This worked for convex polygons but not for concave ones. See attached screenshots for comparison (before - after).

Screenshot 2023-10-31 at 13 00 51
Screenshot 2023-10-31 at 13 00 27

Screenshot 2023-10-31 at 13 00 51
Screenshot 2023-10-31 at 13 00 27

### CODE REVIEW

**Comment by Mugen87** [comment]
For testing: https://rawcdn.githack.com/StrandedKitty/three.js/fix/fbx-triangulation/editor/index.html

File: examples/jsm/loaders/FBXLoader.js [hunk 1]
```diff
@@ -36,13 +36,15 @@ import {
...
 	Uint16BufferAttribute,
+	Vector2,
 	Vector3,
 	Vector4,
 	VectorKeyframeTrack,
 	SRGBColorSpace
 } from 'three';
 import * as fflate from '../libs/fflate.module.js';
 import { NURBSCurve } from '../curves/NURBSCurve.js';
+import { Earcut } from '../../../src/extras/Earcut.js';
```
Comment (Mugen87) [inline examples/jsm/loaders/FBXLoader.js:47]: Can you please use `ShapeUtils.triangulateShape()` instead of directly using `Earcut`? 

Sidenote: Importing the module directly from `src` can't be done because it breaks the usage with import maps.

Comment (StrandedKitty) [reply examples/jsm/loaders/FBXLoader.js]: Ok, done.

**Comment by Mugen87** [comment]
Let's give this a try!
