### PR TITLE
GLTFLoader: Fix lights list iterator.

### LINKED ISSUE #14501: GLTFLoader fails with custom inherited array.prototype properties
##### Description of the problem

Hi! I use forEach2 to iterate over arrays and I noticed it throws an error with GLTFLoader, because the "for...in" loop iterate over the inherited prototype properties too and it can't find the key named "forEach2" obviously...

I think testing with hasOwnProperty can't hurt : 

https://github.com/mrdoob/three.js/blob/5ac20d718943e23d40e5215f15452ec2240a2c58/examples/js/loaders/GLTFLoader.js#L280-L282
```
for ( var lightId in lights ) { // line 280
	if ( ! lights.hasOwnProperty( lightId ) ) continue;

// Same trick with following "for...in" loops...
```

Well adding forEach2 is the cause of this issue but maybe it can help others...

##### Three.js version
- [x] r94

##### Browser
- [x] Chrome

##### OS
- [x] Windows

### PR DESCRIPTION
**Pull request by donmccurdy**
FIxes #14501.

### CODE REVIEW

File: examples/js/loaders/GLTFLoader.js [hunk 1]
```diff
@@ -277,9 +277,9 @@ THREE.GLTFLoader = ( function () {
 		var extension = ( json.extensions && json.extensions[ EXTENSIONS.KHR_LIGHTS_PUNCTUAL ] ) || {};
 		var lights = extension.lights || {};
```
Comment (takahirox) [inline examples/js/loaders/GLTFLoader.js]: var lights = extension.lights || [];

not `{}`, but `[]` here?

File: examples/js/loaders/GLTFLoader.js [hunk 2]
```diff
@@ -277,9 +277,9 @@ THREE.GLTFLoader = ( function () {
...
 
-		for ( var lightId in lights ) {
+		for ( var lightIndex = 0; lightIndex < lights.length; ++ lightIndex ) {
```
Comment (takahirox) [inline examples/js/loaders/GLTFLoader.js]: nit: I prefer using simple loop var name `i` here for the code style consistency in this file unless this's your intentional. At least, `lightIndex ++` would be better for the consistency?

File: examples/js/loaders/GLTFLoader.js (hunk 1 above)
Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js]: Oops yes, thanks! Fixed this and did some other cleanup.

File: examples/js/loaders/GLTFLoader.js (hunk 2 above)
Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js]: Done ✅

File: examples/js/loaders/GLTFLoader.js [hunk 3]
```diff
@@ -310,31 +304,27 @@ THREE.GLTFLoader = ( function () {
...
 
-					lightNode.intensity = light.intensity;
+			lightNode.decay = 2;
 
-				}
+			if ( lightDef.intensity !== undefined ) lightNode.intensity = lightDef.intensity;
 
-				lightNode.name = light.name || ( 'light_' + lightId );
-				this.lights[ lightId ] = lightNode;
+			lightNode.name = lightDef.name || ( 'light_' + i );
```
Comment (takahirox) [inline examples/js/loaders/GLTFLoader.js]: This isn't new in this PR but I think the following would be better

    lightNode.name = lightDef.name !== undefined ? lightDef.name : ( 'light_' + i );

because `lightDef.name` can be empty strings `''`.

Comment (takahirox) [reply examples/js/loaders/GLTFLoader.js]: BTW any special reasons why you wanna name light as `light_num` if `lightDef.name` isn't defined? I think user may want the empty strings name (default in Three.js) in that case.

Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js]: See https://github.com/KhronosGroup/glTF-Validator/issues/93 — I'm increasingly thinking we should ensure that all nodes have unique names, even if it means changing user-specified names. Duplicate names are a common source of animation bugs. Because empty strings are practically guaranteed to be non-unique, I don't think we should be trying to preserve those.

**Comment by mrdoob** [comment]
Is this ready to be merged? 🤔

**Review by takahirox — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!

File: examples/js/loaders/GLTFLoader.js (hunk 3 above)
Comment (takahirox) [reply examples/js/loaders/GLTFLoader.js]: I'm one of the users who don't want loader to pollute the names as default. And currently glTF spec allows non-unique name.

But I can understand non-unique name can sometimes cause problems so wondering if I can first add a method to `SceneUtils` or somewhere which ensures non-unique name in a scene and ask users to explicit call. We can move it into the loader later if glTF spec becomes to recommend unique name.

Let's make a thread and discuss unique-name handling in Three.js there when necessary. And I want glTF spec to update or add a node about unique name first.

Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js]: The validator thread (https://github.com/KhronosGroup/glTF-Validator/issues/93) goes into some detail on this — there are many tools that expect or require uniquely named objects, even though the glTF spec does not. Currently renaming seems to be the recommended way to handle this. But I would be OK with consolidating the renaming logic into one place rather than having one-offs like this, whether that's within GLTFLoader somewhere or in a Utils class.

Technically we don't need globally unique names — just unique within the asset, so that an AnimationMixer has references to nodes that are both (a) unique and (b) portable if animations are loaded from a different file than the mesh.

Comment (takahirox) [reply examples/js/loaders/GLTFLoader.js]: > there are many tools that expect or require uniquely named objects, even though the glTF spec does not.

I think first glTF spec should add a note, it'd be a lack of consideration for asset runs anywhere.

Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js]: You may want to comment on the thread, then. The current consensus is that the spec will not require unique names.

Comment (takahirox) [reply examples/js/loaders/GLTFLoader.js]: I won't because I don't request unique-name in the spec.
