### PR TITLE
XRManager: Reset XRWebGLBinding on session end

### LINKED ISSUE #31821: XR Session restart fails with WebGPURender
### Description

I discovered programmatically ending an XR session then attempting to create a new session fails with WebGPURenderer. It claims the session has ended trying to setup a new projection layer. It only appeared updating Quest OS to v79

### Reproduction steps

1. Enter XR
2. Call to end the current session with the end method.
3. Try to enter XR again

### Code

na

### Live example

* [WebGPURenderer Session](https://electroteque.org/dev/three/examples/webgpu_session.html)

### Screenshots

Image

### Version

r181

### Device

Headset

### Browser

Quest Browser

### OS

Android

### PR DESCRIPTION
**Pull request by harryhjsh**
Related issue: #31821

**Description**

`XRWebGLBinding` can't be cached between XR sessions. Fixes #31821.

### CODE REVIEW

File: src/renderers/common/XRManager.js [hunk 1]
```diff
@@ -1381,6 +1381,7 @@ function onSessionEnd() {
 
 	this._session = null;
 	this._xrRenderTarget = null;
+	this._glBinding = null;
```
Comment (Mugen87) [inline src/renderers/common/XRManager.js:1384]: Do we need this fix in `WebXRManager` as well?

Comment (harryhjsh) [reply src/renderers/common/XRManager.js:1384]: It's already being done in `WebXRManager`, since #22260, thankfully

Comment (harryhjsh) [reply src/renderers/common/XRManager.js:1384]: I've also added some of the other cleanup steps (resetting the member base/projection layers) from that PR which exist in `WebXRManager` already, which I think is probably worth doing?

**Review by Mugen87 — APPROVED** [review]
