### PR TITLE
Loader: Add `DEFAULT_MATERIAL_NAME`.

### LINKED ISSUE #26087: Distinguish generated materials from the ones coming from the model in loaders
### Description

Most 3D model formats define the materials of the model. On the other hand there are situations where materials are not defined for some polygons. For example: "stl" doesn't define materials at all, it's possible to load an "obj" file without the "mtl" file, and so on.

In these cases most of the loaders use some kind of default material which differs from loader to loader. Sometimes it's white, sometimes it's purple, and who knows how many variations are out there.

From the end result it's impossible to tell whether a color is coming from the model or it's generated by the loader. This information can be useful if an application wants to provide recoloring when the model doesn't have material information.

### Solution

Introduce a common user data to distinguish generated materials from the ones coming from the model. Add an `isGeneratedByLoader` (or something like that) boolean field to the user data of the generated material, so later it can be decided if it's coming from the model or generated by the loader.

### Alternatives

- Introduce a function on the `Loader` interface to set the default material.
  - It would still be impossible to tell if a material comes from this or from the model.
  - It has the risk of defining a wrong material type (e.g. the loader creates phong materials, but the default one is a standard).
- Introduce a function on the `Loader` interface to set the default material color only.
  - It would still be impossible to tell if a material comes from this or from the model.
 

### Additional context

I would use this in [Online 3D Viewer](https://3dviewer.net/index.html#model=assets/models/solids.obj) where you can set the material in settings if the model has no material. When using three.js loaders I can't implement this functionality since I can't tell if a material is coming from the model or it is generated by the loader.

### PR DESCRIPTION
**Pull request by kovacsv**
Fixed #26087.

### CODE REVIEW

File: examples/jsm/loaders/LDrawLoader.js [hunk 1]
```diff
@@ -1903,11 +1903,11 @@ class LDrawLoader extends Loader {
 		this.partsLibraryPath = '';
 
 		// Material assigned to not available colors for meshes and edges
-		this.missingColorMaterial = new MeshStandardMaterial( { color: 0xFF00FF, roughness: 0.3, metalness: 0 } );
+		this.missingColorMaterial = new MeshStandardMaterial( { name: Loader.DEFAULT_MATERIAL_NAME, color: 0xFF00FF, roughness: 0.3, metalness: 0 } );
```
Comment (LeviPesin) [inline examples/jsm/loaders/LDrawLoader.js:1906]: The names are overwritten below.

Comment (kovacsv) [reply examples/jsm/loaders/LDrawLoader.js:1906]: Good catch, thanks. Fixed: d2d445b52c9b840cf52297c8077691aa43241f0b

**Review by donmccurdy — APPROVED** [review]

**Review by Mugen87 — APPROVED** [review]
