### PR TITLE
WebGLRenderer: Fix active texture setting in `copyTextureToTexture()`.

### LINKED ISSUE #25618: Rendering an object with multiple textures causes issues with later copyTextureToTexture calls
### Description

When rendering objects with multiple textures (thus using several texture slots) and the `renderer.copyTextureToTexture` function, the target texture in the `copyTextureToTexture` call actually references *the last texture bound in slot0* from a previous render call.

In other words: It ignores the input texture, and targets a previous, wrong one. 

This also causes some more errors later, as the wrong texture gets unbound after the copy.

From what I can tell, this seems to be the part where it gets a bit confused (this is in `setTexture2D`, in  `copyTextureToTexture`):
Screenshot 2023-03-03 at 6 50 54 PM

It seems like it needs to call this activeTexture/bindTexture, but skips it because it sees slot0 had this texture in currentBoundTextures? Unclear to me if it should be fixed here, or if it's the render() call that should have been cleaning up something more.

### Reproduction steps

1. Render an object with two textures, texture1 and texture2
2. Then upload some more subparts into texture1 using copyTextureToTexture: `renderer.copyTextureToTexture(uv, someMoreData, texture1)`
3. The data from someMoreData actually goes to texture2 (!)
4. Subsequent calls to renderer.copyTextureToTexture(uv, someMoreData, texture1) complains that there is no texture bound.

### Code

```js
import * as THREE from 'three';

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );
camera.position.z = 2;
scene.add(camera);

scene.add(new THREE.AmbientLight(0xffffff));

const renderer = new THREE.WebGL1Renderer();
renderer.setSize( window.innerWidth, window.innerHeight );
document.body.appendChild( renderer.domElement );

function makeColoredTexture(color, width, height) {
  const canvas = document.createElement('canvas');
  canvas.width = width;
  canvas.height = height;
  const context = canvas.getContext( '2d' );
  context.fillStyle = color;
  context.fillRect( 0, 0, width, height );
  return new THREE.CanvasTexture(canvas);
}

const redTexture = makeColoredTexture('rgba(255, 0, 0, 1.0)', 1024, 1024);
const greenTexture = makeColoredTexture('rgba(0, 255, 0, 1.0)', 1024, 1024);
const blueTexture = makeColoredTexture('rgba(0, 0, 255, 1.0)', 128, 128);

const mesh = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.ShaderMaterial({
  uniforms: {
    map1: { value: redTexture },
    map2: { value: greenTexture }, // Bug only happens with more than one texture
  },
  vertexShader: document.getElementById( 'vertexShader' ).textContent,
  fragmentShader: document.getElementById( 'fragmentShader' ).textContent
}));
mesh.material.uniformsNeedUpdate = true;
scene.add(mesh);

// After this render call, the currently active slot is slot1 and bound texture is `greenTexture`
renderer.render(scene, camera);
scene.remove(mesh);

// The first setTexture2d in this copy call sees that slot0 already has
// the required texture, so it chooses not to bind.
// But the active texture is slot 1 with `greenTexture`, so this uses the wrong texture...
renderer.copyTextureToTexture(new THREE.Vector2(0, 0), blueTexture, redTexture);

//... so `blueTexture` got written to `greenTexture`! Let's confirm:
// If the bug is present, there will be a blue square on the green texture2.
const confirmMesh = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshBasicMaterial({map: greenTexture}));
scene.add(confirmMesh);
renderer.render(scene, camera);
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/n3trqjy0/7/)
* [jsfiddle-dev](https://jsfiddle.net/79nhmjps/)

### Screenshots

_No response_

### Version

r146-r150

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by geekuillaume**
Fixed #25618.

**Description**

In some cases, calling `gl.copyTextureToTexture` can target a different texture than the one actually passed as parameter. This happens if:
- the target texture is already in slot 0
- the active slot is not slot 0

In this case, when `copyTextureToTexture` calls `textures.setTexture2D`, `state.bindTexture` is called but because this texture was already in slot 0, `state.bindTexture` is a noop. It means that the active slot is not changed and if it's not 0, then the target of `copyTextureToTexture` is invalid.

The fix in this PR solves the problem for `copyTextureToTexture` specifically but maybe we should fix `state.bindTexture` instead. The current behavior of `state.bindTexture` can create problems because it only set the active slot if the texture was not already bound to this slot. 

Here's what it currently does:
```js
if ( boundTexture.type !== webglType || boundTexture.texture !== webglTexture ) {

	if ( currentTextureSlot !== webglSlot ) {

		gl.activeTexture( webglSlot );
		currentTextureSlot = webglSlot;

	}

	gl.bindTexture( webglType, webglTexture || emptyTextures[ webglType ] );

	boundTexture.type = webglType;
	boundTexture.texture = webglTexture;

}
```

But instead we could do:

```js
if ( currentTextureSlot !== webglSlot ) {

	gl.activeTexture( webglSlot );
	currentTextureSlot = webglSlot;

}

if ( boundTexture.type !== webglType || boundTexture.texture !== webglTexture ) {

	gl.bindTexture( webglType, webglTexture || emptyTextures[ webglType ] );

	boundTexture.type = webglType;
	boundTexture.texture = webglTexture;

}

```

I'm not sure if this will cause some other side-effect. Let me know what you think!

### CODE REVIEW

**Comment by Mugen87** [comment]
Can you please reproduce the issue with a live example? 

Use https://jsfiddle.net/3mrkqyea/ as a starter template.

We must be able to reproduce the issue so we have a chance to verify if the PR actually fixes it.

**Comment by geekuillaume** [comment]
Here is the reproduction case: https://jsfiddle.net/xko5s6zf/5/

You should see a green sphere on top and a blue sphere, but actually you see a blue sphere on top of a red one. Try commenting the `renderer.copyTextureToTexture` call. It will change the color of the top sphere even if this call doesn't impact the renderTarget used to texture the sphere.

**Comment by Mugen87** [comment]
While studying the solution I think it's indeed better to fix the issue in `WebGLState` as you mentioned in https://github.com/mrdoob/three.js/pull/33153#issue-4058806331. The fix in `copyTextureToTexture()` looks more like a bandage that "hides" the real root cause. 

`WebGLState.bindTexture()` should not only update the active texture slot when a `gl.bindTexture()` happens. Even without this it must check if the texture is registered in the correct slot.

Would you please update the PR and add your proposed fix to `WebGLState` instead? Can you also update the WebGL backend of `WebGPURenderer`? It requires the same fix, see:

https://github.com/mrdoob/three.js/blob/bf65eaf73a9b7b6ebf9edd383b10616bf06e94af/src/renderers/webgl-fallback/utils/WebGLState.js#L1248-L1253

**Comment by geekuillaume** [comment]
Done! I also changed the title of the PR to reflect the actual change and not mention copyTextureToTexture directly

**Comment by Mugen87** [comment]
I did a performance review and it turns out this change introduces unnecessary `gl.activeTexture()` calls. I then let Gemini review the PR with regards on performance and it does not recommend to make this change.

I'm sorry for the back and forth but could you restore the previous version and just modify `copyTextureToTexture()`? If we stumble across this issue elsewhere, we can think of a different approach in `WebGLState`. But for now, let's fix this locally and don't risk performance regressions.

To further explain the design issue: If a texture is just used for rendering, a simple bind is sufficient. But when _mutating_ the texture (like `copyTextureToTexture()` does), `gl.activeTexture()` is required so commands like `gl.texImage2D()` and `gl.texParameteri()` target the correct texture. `state.bindTexture()` does currently do both which is not necessarily correct.

**Comment by geekuillaume** [comment]
No problem, I force pushed the first version. I'll let you edit the title of the PR however you see fit.

File: src/renderers/WebGLRenderer.js [hunk 1]
```diff
@@ -3238,6 +3238,7 @@ class WebGLRenderer {
 
 				textures.setTexture2D( dstTexture, 0 );
 				glTarget = _gl.TEXTURE_2D;
+				state.activeTexture( _gl.TEXTURE0 );
```
Comment (Mugen87) [inline src/renderers/WebGLRenderer.js]: Can we move this below the `else` block so it also works for 3d and array textures?

Comment (Mugen87) [reply src/renderers/WebGLRenderer.js]: Edit: I think `WebGPURenderer` does not need the change because the WebGL backend does not explicitly set `0` for the texture unit.

Comment (Mugen87) [reply src/renderers/WebGLRenderer.js]: Indeed, `WebGPURenderer` works fine for both backends: https://jsfiddle.net/wenck4aq/

**Comment by Mugen87** [comment]
I've made a small update and also added a comment to this PR so it's more clear why the line has been added.

**Comment by geekuillaume** [comment]
Okay, thanks for taking care of this!
