### PR TITLE
UniformsUtils: Check for XRRenderTarget in getUnlitUniformColorSpace

### LINKED ISSUE #27868: WebXR: Scene fog and background appear darker in VR
### Description

When setting either `Scene.fog` or `Scene.background` to a colour, the colour will appear darker when entering VR. It seems that this is related to colour space conversions as the issue does not happen with `THREE.ColorManagement.enabled = false`.

From what I gather the render target used for WebXR needs to be treated differently. This is done in places like `WebGLPrograms`, but not when converting the background and fog colours. Adding a check to `UniformsUtils.js#getUnlitUniformColorSpace` resolves the issue for AFAICT. 

PR implementing the above suggested fix: #27869 

### Reproduction steps

1. Create a scene and set either `Scene.fog` or `Scene.background` to a colour
2. Observe the colour before entering VR
3. Enter VR and notice the fog and/or background being noticeably darker

### Code

```js
// Setup scene
scene = new THREE.Scene();
scene.background = new THREE.Color( 0x444444 );

// Enable XR
renderer.xr.enabled = true;

// Add VR button
document.body.appendChild( VRButton.createButton( renderer ) );
```

### Live example

The `webxr_vr_handinput` example demonstrates the issue. The gray background turns almost black in VR. Can be reproduced in headset and with the [immersive web emulator](https://github.com/meta-quest/immersive-web-emulator).
* https://threejs.org/examples/#webxr_vr_handinput

### Screenshots

_No response_

### Version

r162

### Device

Headset

### Browser

Chrome

### OS

Linux

### PR DESCRIPTION
**Pull request by mrxz**
Fixed #27868

**Description**

Adds a check to `getUnlitUniformColorSpace` to return the render target's texture colour space in case of the WebXR render target. With this change both fog colour and background colour remain consistent inside and outside VR sessions. This is similar to the logic in [`WebGLProgams.js`](https://github.com/mrdoob/three.js/blob/7e74e4cc6458005ea9a4c3176f933c33bde17e72/src/renderers/webgl/WebGLPrograms.js#L199) and [`WebGLRenderer.js`](https://github.com/mrdoob/three.js/blob/7e74e4cc6458005ea9a4c3176f933c33bde17e72/src/renderers/WebGLRenderer.js#L1715C1-L1715C200).

*This contribution is funded by [Fern Solutions](https://fern.solutions)*

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

File: src/renderers/shaders/UniformsUtils.js [hunk 1]
```diff
@@ -86,13 +86,21 @@ export function cloneUniformsGroups( src ) {
...
+	const currentRenderTarget = renderer.getRenderTarget();
+
+	if ( currentRenderTarget === null ) {
 
 		// https://github.com/mrdoob/three.js/pull/23937#issuecomment-1111067398
 		return renderer.outputColorSpace;
 
 	}
 
+	if ( currentRenderTarget.isXRRenderTarget === true ) {
```
Comment (donmccurdy) [inline src/renderers/shaders/UniformsUtils.js:98]:
```suggestion
	// https://github.com/mrdoob/three.js/issues/27868
	if ( currentRenderTarget.isXRRenderTarget === true ) {
```

Let's include a link to the issue, I think it will be easy to forget why this is a special case. Thanks!

**Review by donmccurdy — APPROVED** [review]

**Comment by donmccurdy** [comment]
Note — I don't have access to a WebXR-compatible device at the moment. Could someone test that background and fog colors work as expected in a WebXR session before this is merged?

**Comment by mrxz** [comment]
@donmccurdy Here are some screenshots taken with a Meta Quest 3 on a test scene.
| | Outside WebXR | In WebXR Session |
|-|------------------------|---------------------------|
| Without this PR| image | image|
|With this PR | image | image |
