### PR TITLE
GLTFLoader: Fix for clampWhenFinished=true.

### LINKED ISSUE #14541: glTF animation doesn't stop at last frame
##### Description of the problem
I've created a scene with an animated cube and exported it(glTF). After I loaded the scene, I played the animation once. But the animation didn't stop at last frame. 
reality

Then I tried to export the scene again with "force sample animation" checked, the aniamtion worked as expected.
expected

It seems not a bug of  glTF exporter (KhronosGroup/glTF-Blender-Exporter#270). But I think it might have something to do with the GLTFCubicSplineInterpolant? Because I found something in the console (the parameter of evaluate function is the end time of the animation) :
gltfcubicsplineinterpolant

Here is the .blend file:
[test-cube.zip](https://github.com/mrdoob/three.js/files/2226317/test-cube.zip)
The web:
[animation-test.zip](https://github.com/mrdoob/three.js/files/2226366/animation-test.zip)

##### Three.js version

- [ ] Dev
- [x] r94
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome
- [x] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

### PR DESCRIPTION
**Pull request by donmccurdy**
Fixes #14541. The issue affects only cubic spline interpolation.

/cc @takahirox

### CODE REVIEW

**Comment by donmccurdy** [comment]
@takahirox any concerns on this? 😇

**Comment by takahirox** [comment]
I've been a bit busy these days. I'll review this one and others in a few days.

File: examples/js/loaders/GLTFLoader.js [hunk 1]
```diff
@@ -913,6 +913,30 @@ THREE.GLTFLoader = ( function () {
...
+		var result = this.resultBuffer,
+			values = this.sampleValues,
+			valueSize = this.valueSize,
+			offset = index * valueSize * 3 + valueSize;
+
+		for ( var i = 0; i !== valueSize; i ++ ) {
+
+			result[ i ] = values[ offset + i ];
+
+		}
```
Comment (takahirox) [inline examples/js/loaders/GLTFLoader.js]: Let me confirm my understanding. Is here copying spliteVertex_index in [ inTangent_1, splineVertex_1, outTangent_1, inTangent_2, splineVertex_2, outTangent_2, ... ] into `result`?

Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js]: That's right. 👍

If we don't override this method, it does:

```js
var result = this.resultBuffer,
  values = this.sampleValues,
  stride = this.valueSize,
  offset = index * stride;

for ( var i = 0; i !== stride; ++ i ) {

  result[ i ] = values[ offset + i ];

}

return result;
```

... which as you might imagine, does not work properly since our interpolant's valueSize and stride are not the same. 😅

Comment (takahirox) [reply examples/js/loaders/GLTFLoader.js]: OK OK

I don't understand `beforeStart_()` and `afterEnd_()` in `Interpolant` yet, so wondering if it's ok to ignore the second and third arguments `t0` and `t1`.

https://github.com/mrdoob/three.js/blob/dev/src/math/Interpolant.js#L117

Comment (donmccurdy) [reply examples/js/loaders/GLTFLoader.js]: Based on https://github.com/mrdoob/three.js/blob/dev/src/math/Interpolant.js#L248-L256, I think it is consistent with current behavior. But that is odd..

Comment (takahirox) [reply examples/js/loaders/GLTFLoader.js]: Hm, so merging this PR so far and looking into `beforeStart_()` and `afterEnd_()` later? At least, this PR seems to follow the current `Interpolant` behavior...

**Review by takahirox — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!
