### PR TITLE
WebGLRenderer: Add `ReversedCoordinateSystem`, fix shadows with `reverseDepthBuffer`.

### LINKED ISSUE #29770: Support shadow mapping with reverse Z
### Description

To repro, modify `examples/webgl_shadowmap.html` by passing `reverseDepthBuffer: true` into the `WebGLRenderer` constructor.

To get anything to render at all, you will also need to add `renderer.getContext().clearDepth(0)` (see my comment in #29579).

After these modifications, the demo looks okay except that there are no shadows.

### Solution

Ideally shadow mapping is supported without requiring clients to write any extra code, since `DepthBuffer` in `WebGLState` already flips the depth function & depth clear value at a low level.  I have not yet been able to find the missing piece.

### Alternatives

Alternatively, maybe the onus is on the applications to handle this in the onBeforeShadow hook?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by CodyJasonBennett**
Fixed #29770

**Description**

Introduces `ReversedCoordinateSystem` to produce a [0, 1] reversed projection matrix. This was previously done internally on the GPU with #29445. For backwards compatibility purposes, I have deprecated this conversion, and it now emits a warning, encouraging cameras to be configured with `ReversedCoordinateSystem` when using reverse depth. As reverse depth in WebGL relies on `EXT_clip_control`, it is best to use feature detection:

```js
const renderer = new THREE.WebGLRenderer( { reverseDepthBuffer: true } );

const camera = new THREE.PerspectiveCamera();

if ( renderer.capabilities.reverseDepthBuffer ) { // Firefox, namely

	camera.coordinateSystem = THREE.ReversedCoordinateSystem;
	camera.updateProjectionMatrix();

}
```

Shadow maps are also fixed in this PR, which previously had misconfigured shadow cameras and the wrong comparison operator (as depth is now reversed). Shaders that rely on a specific NDC range or linearize depth still need to be updated.

I have not updated cascaded shadow maps (CSM) and other add-ons like GTAO with this PR.

| Before | After |
|--------|--------|
| Before | After |

All shadow map types were tested with this PR. Below is a quality comparison after changes with/without `reverseDepthBuffer`.

Note that an ideal setup for `reverseDepthBuffer` configures a floating-point depth buffer in post-processing https://github.com/mrdoob/three.js/pull/29445#issuecomment-2362709888.

| | Default | Reverse Depth |
|--------|--------|--------|
| `BasicShadowMap` | Default | Reverse Depth |
| `PCFShadowMap` | Default | Reverse Depth |
| `PCFSoftShadowMap` | Default | Reverse Depth |
| `VSMShadowMap` | Default | Reverse Depth |

### CODE REVIEW

File: examples/jsm/shaders/UnpackDepthRGBAShader.js [hunk 1]
```diff
@@ -43,8 +43,21 @@ const UnpackDepthRGBAShader = {
...
+
+				// [0, 1] -> [-1, 1]
+				depth = depth * 2.0 - 1.0;
+
+				// Reverse to forward depth (precision is already destroyed at this point)
+				depth = 1.0 - depth;
+
+			#endif
+
+			gl_FragColor = vec4( vec3( 1.0 - depth ), opacity );
```
Comment (CodyJasonBennett) [inline examples/jsm/shaders/UnpackDepthRGBAShader.js:60]: This ensures that appearance is consistent regardless of configuration (press T on the shadow map example).

The special handling on L50 is a clearing bug, though, but I am not sure how to go about it. The same is in `shadowmap_pars_fragment`.

File: src/constants.js [hunk 2]
```diff
@@ -1564,21 +1564,31 @@ export const GLSL1 = '100';
...
 
+/**
+ * Reversed coordinate system [1, 0].
+ *
+ * Used for reverse depth buffer.
+ *
+ * @type {number}
+ * @constant
+ */
+export const ReversedCoordinateSystem = 2002;
```
Comment (gkjohnson) [inline src/constants.js:1590]: Do we not technically need "ReversedWebGPUCoordinateSystem" and "ReversedWebGLCoordinateSystem"? Or is this just for WebGPU?

Comment (Mugen87) [reply src/constants.js:1590]: At some point reverse depth buffer will also be supported in `WebGPURenderer`. If the respective computations in `Matrix4` differ in WebGL and WebGPU, then we should indeed rename to `ReversedWebGLCoordinateSystem`.

Comment (CodyJasonBennett) [reply src/constants.js:1590]: We only need one. `Matrix4` as implemented will just work in WebGPU (its derivation is based on how we make one for WebGPU normally), provided that depth comparisons and clear values are configured to be reversed. Reverse depth can only be implemented with a [0, 1] NDC range, which is what WebGPU and modern graphics APIs use and what we use in WebGL via `EXT_clip_control`, which is otherwise [−1, 1]. I explain why this range matters in floating point and the nature of it in previous comments, more recently in https://github.com/mrdoob/three.js/pull/29445#issuecomment-2362709888.

Regarding changes, apart from the reversed range, they are the same as you would make when migrating from WebGL to WebGPU. The WebGPU side would only be concerned about the reversed range. The only other constant I would consider would be for an infinite reversed matrix, which only works for perspective #11755. Explicitly handling Infinity might be a better way, provided we document it.

Importantly, as we no longer automatically convert the projection matrix for a configured camera, it is possible to construct an infinite reversed projection matrix in user-land. I'd be happy to create an example for exploration purposes and show its effect for derivations in post-processing. I found it simplifies things tremendously when dealing with depth and occlusion.

Comment (WestLangley) [reply src/constants.js:1590]: Reversed coordinate system?

The _depth range_ or _depth mapping_ is reversed, not the coordinate system.

Comment (CodyJasonBennett) [reply src/constants.js:1590]: That is not true here, and yet the use is still incorrect, although not strictly, but this is the API we established to make WebGPU possible #26140, which uses modern D3D convention. Do we really need to be pedantic about this, or can you suggest another API that would make sense?

I must say that I am incredibly unhappy to entertain sweeping, breaking changes for the sake of correctness if not strictly (in)correct, and I think that notion is disillusioned to begin with. Unless you have another suggestion, I think we need to live with words not having a strictly encompassing or even correct meaning at all times.

**Review by Mugen87 — APPROVED** [review]
