### PR TITLE
OrbitControls: fix zoom-changed detection

### LINKED ISSUE #27831: OrbitControls choppy zoom with RenderOnDemand
### Description

When using renderOnDemand instead of an animation loop, OrbitControls' zoom function becomes choppier the closer you zoom on small geometries.
This is on a MacBook's touchpad. Possibly related to the recent change in OrbitControl's zoom speed modulation?

### Reproduction steps

1. Create a scene with a small box (0.01x0.01x0.01). Make sure the camera's near clipping and OrbitControls' minDistance supports this.
2. Use OrbitControls `change` event to render new frames
3. Zoom from far away to minDistance and notice the jumps between frames
4. Optional: when zoomed all the way in, try to zoom out slightly. Note how it seems unresponsive at first.

### Code

Created a CodePen: https://codepen.io/emkajeej/pen/QWPLWOG

renderOnDemand pattern is:

```
// RENDER ON DEMAND
let renderRequested = false;

controls.addEventListener("change", (ev) => {
  requestRender();
});

const requestRender = () => {
  if (!renderRequested) {
    renderRequested = true;
    requestAnimationFrame(render);
  }
};

const render = () => {
  renderRequested = false;
  controls.update();
  renderer.render(scene, camera);
};

render();
```

### Live example

* https://codepen.io/emkajeej/pen/QWPLWOG

### Screenshots

_No response_

### Version

r0.161

### Device

Desktop

### Browser

Chrome, Firefox, Safari, Edge

### OS

MacOS

### PR DESCRIPTION
**Pull request by sciecode**
Fixes #27831

At some point our logic for detecting `zoomChanged` was modified and it is currently not functioning properly. Currently, the changes are being detected by the condition that validates camera movement and not actual zoom, however this is unreliable as seen in the linked issue. 

I made sure to properly detect changes for every variation of zoom logic (ortho/persp for zoomToCursor and regular zoom).

Also took the opportunity to only set this variable if zoom was actually modified, and not every time it is attempted. This way, if the zoom event is triggered but camera is already clamped to min/max distance, an event won't be triggered falsely.

### CODE REVIEW

File: examples/jsm/controls/OrbitControls.js [hunk 1]
```diff
@@ -269,7 +270,9 @@ class OrbitControls extends EventDispatcher {
 
 				} else {
 
+					const prevRadius = spherical.radius;
 					spherical.radius = clampDistance( spherical.radius * scale );
+					zoomChanged = prevRadius != spherical.radius;
```
Comment (Mugen87) [inline examples/jsm/controls/OrbitControls.js:275]: Nit: Can we use `!==` instead?

**Comment by sciecode** [comment]
Just validating a few edge cases to make sure everything is working properly, will merge soon.

File: examples/jsm/controls/OrbitControls.js (hunk 1 above)
Comment (sciecode) [reply examples/jsm/controls/OrbitControls.js:275]: Sure.
