### PR TITLE
WebGPUBackend: Remove redundant dispose handlers.

### LINKED ISSUE #31600: WebGPU: `CubeRenderTarget` dispose listeners increase indefinitely
### Description

In the following code, the event listeners on `renderTarget`'s `dispose` event increase indefinitely.

```ts
const renderTarget = new WebGLCubeRenderTarget(1)
const scene = new Scene()
const camera = new OrthographicCamera()

void renderer.setAnimationLoop(() => {
  renderer.setRenderTarget(renderTarget, 0)
  void renderer.render(scene, camera)
  renderer.setRenderTarget(renderTarget, 1)
  void renderer.render(scene, camera)
})
```

In [`WebGPUBackend._getRenderPassDescriptor()`](https://github.com/mrdoob/three.js/blob/r179/src/renderers/webgpu/WebGPUBackend.js#L377), `renderTargetData.activeCubeFace` and `renderContext.activeCubeFace` are always different in this case, and `renderTarget.hasEventListener()` always returns `false` because a new `onDispose` is created every time, which results in an indefinite growth of the `dispose` event listeners. `CubeCamera` and [`webgpu_cubemap_dynamic`](https://threejs.org/examples/?q=webgpu%20cube#webgpu_cubemap_dynamic) also reproduce this issue.

This might seem innocent, but after running for a couple of hours, the memory consumption becomes significant.

### Reproduction steps

1. Open the [codepen](https://codepen.io/shotamatsuda/pen/KwdqYrz) in Chrome (it should also reproduce in other browsers).
2. Open the developer console, and select the “Memory” tab.
3. Take a heap snapshot of the VM instance whose name starts with “cdpn.io", select the snapshot, navigate to `WebGLCubeRenderTarget` > `_listeners` > `dispose`, and note the number of `onDispose` listeners.
4. After running the codepen for a few minutes, take another heap snapshot and compare the number of `onDispose` listeners.

### Code

```ts
const renderer = new WebGPURenderer()
await renderer.init()
document.body.appendChild(renderer.domElement)

const renderTarget = new WebGLCubeRenderTarget(1)
const scene = new Scene()
const camera = new OrthographicCamera()

void renderer.setAnimationLoop(() => {
  renderer.setRenderTarget(renderTarget, 0)
  void renderer.render(scene, camera)
  renderer.setRenderTarget(renderTarget, 1)
  void renderer.render(scene, camera)
  ...
})
```

### Live example

* https://codepen.io/shotamatsuda/pen/KwdqYrz

### Screenshots

Initial snapshot:

Snapshot after running a few minutes:

### Version

r179

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #31600.

**Description**

The PR removes any render target dispose related code from `_getRenderPassDescriptor()`. The dispose logic is managed for all backends in [Texture.updateRenderTarget()](https://github.com/mrdoob/three.js/blob/f250f75ede2e881e3d82a09e65965784fb989cde/src/renderers/common/Textures.js#L157-L187). I assume the code in the WebGPU backend is a leftover from earlier days.

### CODE REVIEW

File: src/renderers/common/Textures.js [hunk 1]
```diff
@@ -179,6 +179,7 @@ class Textures extends DataMap {
 				}
 
 				this.delete( renderTarget );
+				this.backend.delete( renderTarget );
```
Comment (Mugen87) [inline src/renderers/common/Textures.js:182]: This delete is not necessarily required since the backend data are maintained in a weak map but it's still more correct to remove the data as soon as we can.

File: src/renderers/webgpu/WebGPUBackend.js [hunk 2]
```diff
@@ -390,7 +390,6 @@ class WebGPUBackend extends Backend {
 		if ( descriptors === undefined ||
 			renderTargetData.width !== renderTarget.width ||
 			renderTargetData.height !== renderTarget.height ||
-			renderTargetData.dimensions !== renderTarget.dimensions ||
```
Comment (Mugen87) [inline src/renderers/webgpu/WebGPUBackend.js:393]: `RenderTarget.dimensions` does not exist.
