### PR TITLE
WebGLRenderer: Stable reversed Z buffer implementation.

### LINKED ISSUE #29578: Reverse-Z state problem
### Description

Reverse Z PR not fully correctly implement reverse-Z.

Problem in state:
https://github.com/mrdoob/three.js/blob/0c7cf78a64a724c24fcca51500b8f3d1b9931af5/src/renderers/webgl/WebGLCapabilities.js#L100

This flag applied in `capabilities` that persistent after initialisation, that is wrong due to context sharing.

ThreeJS state can be flushed for some specific cases like a 1 contex for N-renderers or libs.
For ex: Three + PIXI, Three + WebXR emulator, Three+potree.

WebGLState has reset for that:
https://github.com/mrdoob/three.js/blob/0c7cf78a64a724c24fcca51500b8f3d1b9931af5/src/renderers/webgl/WebGLState.js#L1152

Because clipControl is context-related three also should reset this state and change it when needed back

@CodyJasonBennett can you apply some changes and move call of clipControl into `WebGLLState` instead of `WebGLCapabilities`?

@Mugen87 what you think about that?

### Reproduction steps

*

### Code

*

### Live example

*

### Screenshots

_No response_

### Version

r169

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by eXponenta**
Fixed #29578 
Related PR: #29445 

**Description**
Fix: reset clip state when reset is called
Fix: valid depth clear value when reversed is enabled

Feat:  non-persistent reversedZ state ( can be controlled via renderer.state.buffers.depth.setReversed(  )))

### CODE REVIEW

**Review by Mugen87 — COMMENTED** [review]
LGTM! Would be great if @CodyJasonBennett could also have a look 👍 .

File: src/renderers/webgl/WebGLCapabilities.js [hunk 1]
```diff
@@ -92,14 +92,7 @@ function WebGLCapabilities( gl, extensions, parameters, utils ) {
 	}
 
 	const logarithmicDepthBuffer = parameters.logarithmicDepthBuffer === true;
-	const reverseDepthBuffer = parameters.reverseDepthBuffer === true && extensions.has( 'EXT_clip_control' );
```
Comment (CodyJasonBennett) [inline src/renderers/webgl/WebGLCapabilities.js:95]: I would keep this line as-is to mirror user configuration.

**Comment by eXponenta** [comment]
@CodyJasonBennett can you explain how `logarithmicDepth` should work with reversedZ?
Looks like it works no fully stable ( maybe for me only ).
I got flipped depth when logarithmic is enabled. 

Looks like needs to change math for it also:
https://github.com/mrdoob/three.js/blob/36bac08e87b0a016ce920b59b3375ed682a03997/src/renderers/shaders/ShaderChunk/logdepthbuf_fragment.glsl.js#L6

**Comment by CodyJasonBennett** [comment]
You should not use those together. Reverse depth is a strict upgrade and doesn't disable early-z optimizations like logarithmic depth does. I'd expect something is not cleaning up if you see any change to logarithmic depth.

**Comment by eXponenta** [comment]
> You should not use those together. Reverse depth is a strict upgrade and doesn't disable early-z optimizations like logarithmic depth does. I'd expect something is not cleaning up if you see any change to logarithmic depth.

But by default we can create it together, because capabilities not disable logDepth if we can use reversedZ

**Comment by WestLangley** [comment]
>You should not use those together.

@Mugen87 Perhaps an API change is warranted...
 ```js
THREE.StandardDepthBuffer
THREE.ReversedZDepthBuffer
THREE.LogarithmicDepthBuffer
```
```js
const renderer = new THREE.WebGPURenderer( { depthBuffer: THREE.LogarithmicDepthBuffer } );
```

**Comment by Mugen87** [comment]
This is a great suggestion! 👍

**Comment by mrdoob** [comment]
Indeed! 👍

**Comment by CodyJasonBennett** [comment]
Also, if `EXT_clip_control` was widely available, I would suggest removing logarithmic depth entirely.

**Comment by WestLangley** [comment]
I'll  file a PR with the API change.

**Comment by CodyJasonBennett** [comment]
Is it really worth an API change which will not be future proof when exactly reverse-z is opt-in? It is a strict improvement over logarithmic depth where `EXT_clip_control` is available. I'd wager it will be GA and diffuse before WebGPU, as I implemented this after sitting in the meeting for the announcement of this extension's shipping in Safari.

**Comment by WestLangley** [comment]
Given the recent comments, I am OK with leaving the API as-is.

**Comment by prideout** [comment]
Hi @eXponenta, before this PR, reversed Z worked in my simple sandbox app without any changes other than adding the Renderer params.  However after this PR, my app does not render anything unless I add `renderer.getContext().clearDepth(0)` to my app as a workaround.

Could that be due to the removed line that called `_gl.clearDepth`?

File: src/renderers/webgl/WebGLState.js [hunk 2]
```diff
@@ -88,10 +88,36 @@ function WebGLState( gl ) {
...
+
+					} else {
+
+						ext.clipControlEXT( ext.LOWER_LEFT_EXT, ext.NEGATIVE_ONE_TO_ONE_EXT );
+
+					}
+
+					const oldDepth = currentDepthClear;
+					currentDepthClear = null;
+					this.setClear( oldDepth );
```
Comment (prideout) [inline src/renderers/webgl/WebGLState.js:107]: @eXponenta  Additionally, maybe we should also do:

```js
const oldFunc = currentDepthFunc;
currentDepthFunc = null;
this.setFunc( oldFunc );
```

Comment (eXponenta) [reply src/renderers/webgl/WebGLState.js:107]: Oops. Yep, this one. 
Because we also should upgrade depth func to inverter version.

**Comment by haxiomic** [comment]
Also finding nothing rendering when reverseDepthBuffer true

See this minimal example

https://jsfiddle.net/pgkz5vto/

Works in r169 but not r170

**Comment by haxiomic** [comment]
Ah... the implementation of WebGLState.setReversed is incorrect, 

```js
setReversed: function ( value ) {

	if ( reversed !== value ) {

		const ext = extensions.get( 'EXT_clip_control' );

		if ( reversed ) {

			ext.clipControlEXT( ext.LOWER_LEFT_EXT, ext.ZERO_TO_ONE_EXT );

		} else {

			ext.clipControlEXT( ext.LOWER_LEFT_EXT, ext.NEGATIVE_ONE_TO_ONE_EXT );

		}

		const oldDepth = currentDepthClear;
		currentDepthClear = null;
		this.setClear( oldDepth );

	}

	reversed = value;

}
```

- `if ( reversed ) ` assumes reversed has been set, it hasn't yet
- `this.setClear( oldDepth );` also assumes reversed has been set
