### PR TITLE
RenderObject: Fix material cache key regression.

### LINKED ISSUE #28927: WebGPURenderer: errors thrown rendering line segments
### Description

I get the following error if `AxesHelper` is rendered prior to `VertexNormalsHelper` (WebGPU backend only):

Screenshot 2024-07-20 at 8 05 05 PM

### Reproduction steps

See below.

### Code

In `webgpu_materials_matcap.html`, add these lines in the loader call-back:

```js
// Switch the order of these two lines and the scene renders correctly.

scene.add( new THREE.AxesHelper( 5 ) );

scene.add( new VertexNormalsHelper( mesh, 0.1, 0xff0000 ) );
```

Also include
```js
import { VertexNormalsHelper } from 'three/addons/helpers/VertexNormalsHelper.js';
```

### Live example

https://jsfiddle.net/62tzex3v/3/

### Screenshots

_No response_

### Version

r167 dev

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #28927

**Description**

This PR fixes a regression that was introduced in #28823 where the material cache key computation has been updated.

### CODE REVIEW

File: src/renderers/common/RenderObject.js [hunk 1]
```diff
@@ -214,6 +219,10 @@ export default class RenderObject {
 
 					valueKey += '}';
 
+				} else {
+
+					valueKey = String( value );
```
Comment (Mugen87) [inline src/renderers/common/RenderObject.js:224]: @sunag This additional branch is required if `value` is not `null` but also not `number` or `object` (e.g. `boolean`). Previously the value was ignored now it is honored in the cache key.
