### PR TITLE
XRManager: More fixes.

### LINKED ISSUE #31193: WebXR error in WebGPURenderer / WebGLBackend in non layer devices
### Description

I just pulled changes into a merged fork for a PR I made. And found errors in WebXR so it's stopping working altogether. I am not sure what it is. I checked against a fresh checkout.

It's suggesting this is null

```
renderTargetContextData.framebuffers
``` 
https://github.com/mrdoob/three.js/blob/c0088a72c24b4914467471ed4f0aea917842da2d/src/renderers/webgl-fallback/WebGLBackend.js#L600

Related to #31134 

### Reproduction steps

1. visit https://electroteque.org/dev/three/examples/webgpu_xr_cubes.html
2. Launch WebXR
3. Errors display in the animation frame.

### Code

```js
// code goes here
```

### Live example

* [WebGPU XR Cubes](https://electroteque.org/dev/three/examples/webgpu_xr_cubes.html)

### Screenshots

Image

### Version

176

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by cabanier**
Fixed #31193.

This fixes a couple of issues in the XR rendering:
- non-multiview rendering will now use multisampling
- webxr will render correctly in browsers that don't support layers (ie apple vision pro)
- resolve js error at end of the render pass for browsers that don't support layers

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

File: src/renderers/common/Renderer.js [hunk 1]
```diff
@@ -1260,6 +1260,7 @@ class Renderer {
 		frameBufferTarget.scissorTest = this._scissorTest;
 		frameBufferTarget.multiview = outputRenderTarget !== null ? outputRenderTarget.multiview : false;
 		frameBufferTarget.resolveDepthBuffer = outputRenderTarget !== null ? outputRenderTarget.resolveDepthBuffer : true;
+		frameBufferTarget.autoAllocateDepthBuffer = outputRenderTarget !== null ? outputRenderTarget.autoAllocateDepthBuffer : false;
```
Comment (Mugen87) [inline src/renderers/common/Renderer.js:1263]: I think we should rename `setOutputRenderTarget()` to `_setXROutputRenderTarget()`. `autoAllocateDepthBuffer` only exists for `XRRenderTarget` and `setOutputRenderTarget()` is only relevant for XR. We should not allow to use this method as a part of the public API.

Comment (mrdoob) [reply src/renderers/common/Renderer.js:1263]: Agreed 👍
