### PR TITLE
WebGLBackend: Align `copyTextureToTexture` with `WebGLRenderer`

### LINKED ISSUE #31807: WebGLBackend: `copyTextureToTexture` doesn't copy all layers of 3D render targets
### Description

In WebGL fallback, `copyTextureToTexture` doesn't copy all layers of 3D render target textures.

I noticed the implementation of `copyTextureToTexture` in [WebGLBackend](https://github.com/mrdoob/three.js/blob/r179/src/renderers/webgl-fallback/utils/WebGLTextureUtils.js#L699) deviates from the one in [WebGLRenderer](https://github.com/mrdoob/three.js/blob/r179/src/renderers/WebGLRenderer.js#L3049). I can make a PR if those can be made the same (there are a couple of differences in the conditionals which I don't fully understand).

### Reproduction steps

1. Copy a 3D render target texture to another 3D render target texture using `copyTextureToTexture` in WebGL fallback.

### Code

```ts
const rt1 = new RenderTarget3D(size, size, size)
// Draw the contents of "rt1"

const rt2 = new RenderTarget3D(size, size, size)
renderer.setRenderTarget(rt2)
void renderer.clear()
renderer.setRenderTarget(null)

renderer.copyTextureToTexture(
  rt1.texture,
  rt2.texture,
  new Box3(new Vector3(), new Vector3().setScalar(size))
)
```

### Live example

https://jsfiddle.net/shotamatsuda/xu8zs0g2/

### Screenshots

Image

### Version

r179

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by shotamatsuda**
Fixes: #31807

**Description**

This PR changes the implementation of `copyTextureToTexture` for `WebGLBackend` so that it aligns with the one in `WebGLRenderer`.

It does not handle uninitialized textures the way `WebGLRenderer` does, because it's out of my hands.

### CODE REVIEW

File: src/renderers/webgl-fallback/utils/WebGLTextureUtils.js [hunk 1]
```diff
@@ -827,8 +826,9 @@ class WebGLTextureUtils {
 		gl.pixelStorei( gl.UNPACK_SKIP_IMAGES, minZ );
 
 		// set up the src texture
+		const isSrc3D = srcTexture.isDataArrayTexture || srcTexture.isData3DTexture || dstTexture.isArrayTexture;
```
Comment (shotamatsuda) [inline src/renderers/webgl-fallback/utils/WebGLTextureUtils.js:847]: I'm not sure about the nuances of `isDataArrayTexture` and `isArrayTexture`. I've left those conditionals unchanged. If those are correct, we might need to modifiy the implementation in `WebGLRenderer`, which lacks conditionals for `isArrayTexture`.

File: src/renderers/webgl-fallback/utils/WebGLTextureUtils.js [hunk 2]
```diff
@@ -842,12 +842,76 @@ class WebGLTextureUtils {
...
+			state.bindFramebuffer( gl.READ_FRAMEBUFFER, null );
+			state.bindFramebuffer( gl.DRAW_FRAMEBUFFER, null );
+
+		} else if ( srcLevel !== 0 || srcTexture.isRenderTargetTexture || backend.has( srcTexture ) ) {
+
+			// get the appropriate frame buffers
+			const srcTextureData = backend.get( srcTexture );
+
+			if ( this._srcFramebuffer === undefined ) this._srcFramebuffer = gl.createFramebuffer();
+			if ( this._dstFramebuffer === undefined ) this._dstFramebuffer = gl.createFramebuffer();
```
Comment (shotamatsuda) [inline src/renderers/webgl-fallback/utils/WebGLTextureUtils.js]: Please let me know if there's a better location for this. Also, should those be deleted on disposal (currently `WebGLTextureUtils` doesn't have `dispose()`)?

Comment (Mugen87) [reply src/renderers/webgl-fallback/utils/WebGLTextureUtils.js]: Please define and document these properties in the constructor. Also use `null` as the initial value. The framebuffer creation can be done lazily like you have implemented.

Comment (Mugen87) [reply src/renderers/webgl-fallback/utils/WebGLTextureUtils.js]: A `dispose()` method sounds good. You can call it from `WebGBackend.dispose()`.

File: src/renderers/webgl-fallback/utils/WebGLTextureUtils.js (hunk 1 above)
Comment (Mugen87) [reply src/renderers/webgl-fallback/utils/WebGLTextureUtils.js:847]: This flag has been introduced via #30959. The features from this PR are in general not supported in `WebGLRenderer`.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
This PR also fixes the below runtime error that I originally wanted to investigate the next days^^:

> Uncaught TypeError: WeakMap key undefined must be an object

It did occur in the first frame in certain examples like [webgpu_postprocessing_traa](https://threejs.org/examples/webgpu_postprocessing_traa).

**Comment by shotamatsuda** [comment]
Oh, fancy that I've just been debugging the same error in my TAA (depth texture on my end) 😄
