### PR TITLE
EffectComposer: Add dispose().

### LINKED ISSUE #24710: Unclear how to dispose of EffectComposer
**Describe the bug**

In Three.js, how do I clean-up an EffectComposer? It does not appear to have a "dispose" method. 

However, as far as I understand it, is uses two instances of RenderTarget internally, so I am assuming these need to be disposed of just like any other RenderTarget would?

**Expected behavior**

It seems reasonable to assume that EffectComposer would have a dispose method.

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #24710.

**Description**

Adds `dispose()` to `EffectComposer`.

### CODE REVIEW

File: examples/jsm/postprocessing/Pass.js [hunk 1]
```diff
@@ -31,6 +31,8 @@ class Pass {
 
 	}
 
+	dispose() {}
```
Comment (Mugen87) [inline examples/jsm/postprocessing/Pass.js:34]: When this PR is merged, I'm planning to add more `dispose()` methods to the pass classes in `jsm/postprocessing` 👍 .
