### PR TITLE
WebGPURenderer: Fix global references in Node.js

### LINKED ISSUE #29916: Improve compatibility of three/webgpu with nextjs
### Description

As default, 1 threejs project working on nextjs, which wants to upgrade to WebGPU, needs dynamic import for three/webgpu component.
This has some limitation during development.

### Solution

We should be able to avoid all client code style as "self." in global scope.

### Alternatives

NA

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by whatisor**
Fix #29916.

**Description**
Fix compilation issue on react.

### CODE REVIEW

File: src/renderers/webgpu/WebGPUBackend.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ class WebGPUBackend extends Backend {
 				powerPreference: parameters.powerPreference
 			};
 
-			const adapter = await navigator.gpu.requestAdapter( adapterOptions );
+			const adapter = typeof navigator === 'undefined' ? false : await navigator.gpu.requestAdapter( adapterOptions );
```
Comment (Mugen87) [inline src/renderers/webgpu/WebGPUBackend.js:67]: Is the compiled application still usable if you use `false` here?

In any event, I would at least use `{}` as a fallback.

Comment (Mugen87) [reply src/renderers/webgpu/WebGPUBackend.js:67]: Besides, please write the tests like so:
```js
const adapter = ( typeof navigator !== 'undefined' ) ? await navigator.gpu.requestAdapter( adapterOptions ) : {};
```
Meaning you test for the normal case first and then handle the fallback.

File: src/renderers/webgpu/nodes/WGSLNodeBuilder.js [hunk 2]
```diff
@@ -123,7 +123,7 @@ const wgslMethods = {
 
 // WebGPU issue: does not support pow() with negative base on Windows
 
-if ( /Windows/g.test( navigator.userAgent ) ) {
+if ( typeof navigator === 'undefined' ? false : /Windows/g.test( navigator.userAgent ) ) {
```
Comment (Mugen87) [inline src/renderers/webgpu/nodes/WGSLNodeBuilder.js:126]: Same here:
```js
if ( typeof navigator !== 'undefined'  && /Windows/g.test( navigator.userAgent ) ) {
```

File: src/renderers/webgpu/nodes/WGSLNodeBuilder.js [hunk 3]
```diff
@@ -141,7 +141,7 @@ if ( /Windows/g.test( navigator.userAgent ) ) {
 
 let diagnostics = '';
 
-if ( /Firefox|Deno/g.test( navigator.userAgent ) !== true ) {
+if ( ( typeof navigator === 'undefined' ? false : /Firefox|Deno/g.test( navigator.userAgent ) ) !== true ) {
```
Comment (Mugen87) [inline src/renderers/webgpu/nodes/WGSLNodeBuilder.js:144]:
```js
if ( ( typeof navigator !== 'undefined' && /Firefox|Deno/g.test( navigator.userAgent ) ) !== true ) {
```

File: src/renderers/webgpu/utils/WebGPUUtils.js [hunk 4]
```diff
@@ -113,13 +113,13 @@ class WebGPUUtils {
 		// TODO: Remove this check when Quest 34.5 is out
 		// https://github.com/mrdoob/three.js/pull/29221/files#r1731833949
 
-		if ( navigator.userAgent.includes( 'Quest' ) ) {
+		if ( typeof navigator === 'undefined' ? false : navigator.userAgent.includes( 'Quest' ) ) {
```
Comment (Mugen87) [inline src/renderers/webgpu/utils/WebGPUUtils.js:116]:
```js
getPreferredCanvasFormat() {

	// TODO: Remove this check when Quest 34.5 is out
	// https://github.com/mrdoob/three.js/pull/29221/files#r1731833949

	if ( typeof navigator !== 'undefined' ) {

		if ( navigator.userAgent.includes( 'Quest' ) ) {

			return GPUTextureFormat.BGRA8Unorm;

		} else {

			return navigator.gpu.getPreferredCanvasFormat();

		}

	} else {


		return GPUTextureFormat.BGRA8Unorm;

	}

}
```

**Comment by donmccurdy** [comment]
Note – I've renamed the issue to "fix global references in Node.js". I think that's the issue here, not React. Next.js is a React-based framework that happens to execute code in both a browser environment and server-side in Node.js.

File: src/renderers/webgpu/WebGPUBackend.js (hunk 1 above)
Comment (whatisor) [reply src/renderers/webgpu/WebGPUBackend.js]: Thanks, fixed.

File: src/renderers/webgpu/nodes/WGSLNodeBuilder.js (hunk 2 above)
Comment (whatisor) [reply src/renderers/webgpu/nodes/WGSLNodeBuilder.js]: Thanks, fixed.

File: src/renderers/webgpu/nodes/WGSLNodeBuilder.js (hunk 3 above)
Comment (whatisor) [reply src/renderers/webgpu/nodes/WGSLNodeBuilder.js]: Thanks, fixed.

File: src/renderers/webgpu/WebGPUBackend.js [hunk 5]
```diff
@@ -64,7 +64,7 @@ class WebGPUBackend extends Backend {
 				powerPreference: parameters.powerPreference
 			};
 
-			const adapter = await navigator.gpu.requestAdapter( adapterOptions );
+			const adapter = ( typeof navigator !== 'undefined' ) ? await navigator.gpu.requestAdapter( adapterOptions ) : {};
```
Comment (Mugen87) [inline src/renderers/webgpu/WebGPUBackend.js:67]: @donmccurdy`{}` is intended as a workaround for node but I'm not sure `{}` is ideal here. Do you think this use case is handled appropriately or would you implement it differently?

Comment (whatisor) [reply src/renderers/webgpu/WebGPUBackend.js:67]: Base on that function code, it should be null, otherwise, next step is exceptional?
"adapter.features"

Comment (donmccurdy) [reply src/renderers/webgpu/WebGPUBackend.js:67]: @whatisor are you executing this code in the Node.js environment, or is this a compile-time error from TypeScript or Webpack? Not clear to me from #29916.

I'm not sure that `backend.init( renderer )` should be making efforts to avoid runtime exceptions, if running in an environment where neither WebGL nor WebGPU exists. I would support fixes that avoid build-time errors, and run-time errors in module scope. But if you are calling methods on a renderer in Node.js, a runtime exception is to be expected.

Comment (sunag) [reply src/renderers/webgpu/WebGPUBackend.js:67]: > I'm not sure that backend.init( renderer ) should be making efforts to avoid runtime exceptions, if running in an environment where neither WebGL nor WebGPU exists

I agree, I think we should be throwing an error here, it doesn't make much sense to me to proceed with an empty object as an adapter.

Comment (whatisor) [reply src/renderers/webgpu/WebGPUBackend.js:67]: @donmccurdy it is compile error.
We also need to fix three\examples\jsm\capabilities\WebGPU.js with global and await.
So, we should return null and (exception is next step as current)?

**Review by Mugen87 — APPROVED** [review]

File: src/renderers/webgpu/WebGPUBackend.js (hunk 5 above)
Comment (sunag) [reply src/renderers/webgpu/WebGPUBackend.js]: > three\examples\jsm\capabilities\WebGPU.js

Capabilities should be optional, it should be possible to use `WebGPURenderer` without global await. https://github.com/mrdoob/three.js/pull/29218

Comment (whatisor) [reply src/renderers/webgpu/WebGPUBackend.js]: can we do same thing with webgl to avoid await?
https://developer.mozilla.org/en-US/docs/Web/API/GPUCanvasContext

File: src/renderers/webgpu/utils/WebGPUUtils.js [hunk 6]
```diff
@@ -113,13 +113,21 @@ class WebGPUUtils {
 		// TODO: Remove this check when Quest 34.5 is out
 		// https://github.com/mrdoob/three.js/pull/29221/files#r1731833949
 
-		if ( navigator.userAgent.includes( 'Quest' ) ) {
+		if ( typeof navigator !== 'undefined' ) {
```
Comment (sunag) [inline src/renderers/webgpu/utils/WebGPUUtils.js:116]: Could we remove this? It is inside a function that will never be executed by the adapter return null in this case.

Comment (donmccurdy) [reply src/renderers/webgpu/utils/WebGPUUtils.js:116]: I guess the issue is that it's a compiler error, not a runtime error. I wish we knew what in the Next.js stack is doing compile-time checks on dependencies, and what its requirements are. Avoiding all references to browser globals is a pretty tall order for a large library relying heavily on Web APIs. :/

Comment (sunag) [reply src/renderers/webgpu/utils/WebGPUUtils.js:116]: The compiler throwing an error for a global variable inside a function seems strange to say the least, since a variable can be declared at the global level after the function declaration.

Comment (donmccurdy) [reply src/renderers/webgpu/utils/WebGPUUtils.js:116]: Yeah, I'm not sure why... trying to reproduce the issue:

- https://github.com/mrdoob/three.js/issues/29916#issuecomment-2487126519

Comment (whatisor) [reply src/renderers/webgpu/utils/WebGPUUtils.js:116]: I think it is this one:
https://react.dev/reference/react/StrictMode

**Comment by verekia** [comment]
I have set up a test suite of various build environments, like Vite, with and without React, Next.js, R3F, and a specific one to check this PR: https://github.com/verekia/three-gpu-ecosystem-tests

The PR does indeed fix Next.js crashing on reference errors 🙌 That being said, I am getting a `Multiple instances of Three.js being imported` warning, which I don't get when importing WebGPURenderer dynamically. Maybe @CodyJasonBennett would have insights on why that happens.

Regular import (fixed by this PR):
`next-pages-vanilla-pr-29919/pages/index.js`

Dynamic import workaround:
`next-pages-vanilla-dynamic-8ce69e0/pages/index.js`

**Comment by Mugen87** [comment]
It seems the only blocking bit is the change in `WebGPUUtils`. 

@verekia Can you please verify if build works without this change? If so, we can revert it ( see https://github.com/mrdoob/three.js/pull/29919#discussion_r1849357796).

**Comment by whatisor** [comment]
> Thanks for letting us know! I have reverted the changes in `WebGPUUtils` so it seems the PR is ready to go.
@Mugen87 We still need to update WebGPUtils and examples because people stills use it from example and it will not be able to compile, don't we?

**Comment by verekia** [comment]
@whatisor Could you provide a repro where `WebGPUUtils` causes a crash in a Next.js project?

My test is pretty basic, the only thing I import is:

```js
import * as THREE from 'three'
import { WebGPURenderer } from 'three/webgpu'
```

**Comment by CodyJasonBennett** [comment]
This PR has nothing to do with React or its strict mode etc. We need a reproduction to know what's going on here or if this is something we can actually support. Next is notorious for overzealous compilation the ecosystem itself can't mitigate.

**Comment by whatisor** [comment]
> @whatisor Could you provide a repro where `WebGPUUtils` causes a crash in a Next.js project?
> 
> My test is pretty basic, the only thing I import is:
> 
> ```js
> import * as THREE from 'three'
> import { WebGPURenderer } from 'three/webgpu'
> ```

I did not mean issue of Core. It is just simply call Webgpu.isAvailable() in your test to see compilation issue, but I will push PR to your test case

**Comment by verekia** [comment]
@whatisor You are not supposed to call any method that's meant for browsers during SSR. These should live in a `useEffect` or similar. See this classic article about [hydration](https://www.joshwcomeau.com/react/the-perils-of-rehydration/).

```jsx
WebGPU.isAvailable() // ❌ Don't do that, it runs on the server during SSR

function MyComponent(){
  WebGPU.isAvailable() // ❌ Don't do that, it runs on the server during SSR

  useEffect(() => {
    WebGPU.isAvailable() // ✅ No problem, runs only on the browser
  }, [])

  return // ...
}
```

That's why the only concern for Three.js should be that _importing_ in a Next.js doesn't cause a crash due to global browser variable access and top-level browser API calls. If you call methods during SSR that should never run on the server, then it's expected for SSR to break.

**Comment by verekia** [comment]
I added [more test cases to my repo](https://github.com/verekia/three-gpu-ecosystem-tests), including Next 14/15, React 18/19, Pages/App router, and a TSL call for all cases. Now that this PR is merged, things are looking really good for Next.js support in r171. Thank you.

> - ✅ Vite + vanilla Three.js: Works in all cases.
> - ✅ Next.js + vanilla Three.js: Works in all cases.
> - ✅ Next.js 14 + R3F: Works in both Pages and App routers.
> - ❌ Next.js 15 + R3F: Does not work, except with Pages Router + React 18.

The recent release of Next.js 15 + React 19 RC is expected to break things on the R3F side, so it's not a problem Three.js should worry about.

**Comment by whatisor** [comment]
> ```js
>   useEffect(() => {
>     WebGPU.isAvailable() // ✅ No problem, runs only in the browser
>   }, [])
> ```
I added into your 2 test cases and it is failed from BUILD step.
image

Thank @Mugen87  because of removing self but still issue with nagivator and warning with await.

**Comment by whatisor** [comment]
https://github.com/whatisor/three-gpu-ecosystem-tests/blob/main/next-14-pages-r3f-react-18/pages/index.js

**Comment by verekia** [comment]
You're right @whatisor, this [`navigator`](https://github.com/mrdoob/three.js/blob/4749f998ca6127bd49f98ccfc773b50de02274b5/examples/jsm/capabilities/WebGPU.js#L1) is at the top-level, so it will break imports. The one we reverted in `WebGPUUtils` was not top-level, as it was in a class method. Let's keep hunting down only the top-level ones :)

**Comment by Mugen87** [comment]
I guess we can simply do the following?
```js
let isAvailable = ( typeof navigator !== 'undefined'  && navigator.gpu !== undefined );
```

**Comment by Mugen87** [comment]
> and warning with await.

How does this warning look like? Is it still possible to compile your code with the below `await` usage?

https://github.com/mrdoob/three.js/blob/4749f998ca6127bd49f98ccfc773b50de02274b5/examples/jsm/capabilities/WebGPU.js#L6

**Comment by verekia** [comment]
It compiles with this warning:

```
   ▲ Next.js 15.0.3

 ✓ Linting and checking validity of types    
   Creating an optimized production build ...
 ⚠ Compiled with warnings

./node_modules/three/examples/jsm/capabilities/WebGPU.js
The generated code contains 'async/await' because this module is using "topLevelAwait".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.

Import trace for requested module:
./node_modules/three/examples/jsm/capabilities/WebGPU.js

 ✓ Compiled successfully
```
I am on Node v22.10.0, and interestingly, I was not getting the ReferenceError because `navigator` is actually defined in that version. I switched to Node 18 and it's not defined. Anyway, I think it's a good practice to do these `typeof` checks for `navigator`, `window`, and other global browser objects.

**Comment by Mugen87** [comment]
I think we can live with that warning for now.

**Comment by verekia** [comment]
After another full day of testing and Dockerizing for more reliable reproductions, I have [updated the repo with new findings](https://github.com/verekia/three-gpu-ecosystem-tests#results). I have added an import of `capabilities/WebGPU.js` and call to `isAvailable` in all cases.

The main takeaway on the Three.js side is that importing top-level await modules such as `capabilities/WebGPU.js` does break Vite's default config, and causes that warning we discussed above in Next.js, both in the browser console and at compilation.

You can test it easily:

- `cd vite-vanilla-js`
- Comment out `optimizeDeps` and `build.target` in vite.config.js
- `npm run docker` (or `npm i && npm start` if you don't have Docker)

Or Next.js:

- cd `next15-pages-vanilla-react19`
- `npm run docker` (or `npm i && npm start`)

**Comment by whatisor** [comment]
Yeah,  I still need to implement my own WebGPU async checking anyway. Because cannot risky update everything to latest.
