### PR TITLE
WebGLNodes: Ensure `onBuild()` uses the correct material reference.

### LINKED ISSUE #27095: Crash if using OutlinePass in a scene with node materials and standard materials
### Description

Three has problems to render an outline effect (using `OutlinePass`) in a scene with mixed objects, having **both** node materials and standard materials. This happens as soon as there is one object with a node material present in the scene.
As soon as the `outlinePass.selectedObjects` is set to any object, the following runtime error is thrown:

```
three.module.js:17985 Uncaught TypeError: Cannot read properties of undefined (reading 'toArray')
    at flatten (three.module.js:17985:13)
    at PureArrayUniform.setValueV3fArray [as setValue] (three.module.js:18588:15)
    at WebGLUniforms.upload (three.module.js:19017:7)
    at setProgram (three.module.js:29901:19)
    at WebGLRenderer.renderBufferDirect (three.module.js:28759:20)
    at renderObject (three.module.js:29451:11)
    at renderObjects (three.module.js:29420:6)
    at renderScene (three.module.js:29289:36)
    at WebGLRenderer.render (three.module.js:29107:5)
    at RenderPass.render (RenderPass.js:71:12)
```

When all objects **having node materials** are removed from the scene, everything is working as expected.

It is also possible to set `outlinePass.prepareMaskMaterial.lights = true` which enables using the outline effect **for any object having a node material** and makes above error go away. However, as soon as `outlinePass.selectedObjects` is then set to an object **without a node material** Three again crashes with the same error.

### Reproduction steps

1. Create a scene with two objects, one having a standard material, one having a node material
2. Add an outline pass as effect
3. Set `outlinePass.selectedObjects` to the object having the node material
4. Three crashes with said error 
5. Set `outlinePass.selectedObjects` to the object having the standard material
6. Three crashes again with the same error
7. Now remove the object with the node material from the scene
8. The object with the standard material is now rendered including outline without crash

### Code

```js
import * as THREE from 'three';
import { OutlinePass } from "three/examples/postprocessing/OutlinePass";
import { EffectComposer } from "three/examples/postprocessing/EffectComposer";
import { RenderPass } from "three/examples/postprocessing/RenderPass";
import { nodeFrame } from "three/examples/renderers/webgl-legacy/nodes/WebGLNodes";
import * as THREENodes from "three/nodes"

const scene = new THREE.Scene();
const camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );

const geometry = new THREE.BoxGeometry( 1, 1, 1 );
const material = new THREE.MeshBasicMaterial( { color: 0x00ff00 } );
const node_material = new THREENodes.MeshStandardNodeMaterial( { colorNode: THREENodes.color( 0x00ff00 ) } );

const cube = new THREE.Mesh( geometry, material );
cube.position.x = -1;
scene.add(cube);

const node_cube = new THREE.Mesh( geometry, node_material );
node_cube.position.x = 1;
scene.add(node_cube);

const light = new THREE.PointLight( 0xffffff, 30 );
light.castShadow = true
light.position.z = 5;
scene.add(light);

const renderer = new THREE.WebGLRenderer();
renderer.setSize( window.innerWidth, window.innerHeight );

const composer = new EffectComposer(renderer);
const renderPass = new RenderPass( scene, camera );
composer.addPass( renderPass );
const outlinePass = new OutlinePass(new THREE.Vector2(window.innerWidth, window.innerHeight), scene, camera);
//outlinePass.selectedObjects = [cube]; // <- !!!!!!!! Crashes if this is uncommented !!!!!!!!
//outlinePass.prepareMaskMaterial.lights = true;
composer.addPass(outlinePass);

document.body.appendChild( renderer.domElement );

camera.position.z = 5;

function animate() {
	requestAnimationFrame( animate );
  
 	nodeFrame.update();

	cube.rotation.x += 0.01;
	cube.rotation.y += 0.01;
  
	node_cube.rotation.x += 0.01;
	node_cube.rotation.y += 0.01;

	composer.render();
}

animate();
```

### Live example

[jsfiddle example](https://jsfiddle.net/TobiasNoell/6qdcb4y3/130/)
(Takes a bit to load, you should see two spinning cubes, you can then uncomment the problematic line to make the error appear)

### Screenshots

_No response_

### Version

r157

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #27095.

**Description**

This PR ensures `WebGLNodes` can process renderings with an active `overrideMaterial`.

The fix is actually simple. `Material.onBuild()` does not extract the material from the 3D object anymore but uses `this` instead.

### CODE REVIEW

File: examples/jsm/renderers/webgl-legacy/nodes/WebGLNodes.js [hunk 1]
```diff
@@ -8,21 +8,23 @@ export const nodeFrame = new NodeFrame();
 
 Material.prototype.onBuild = function ( object, parameters, renderer ) {
 
-	if ( Array.isArray( object.material ) ) {
+	const material = this;
```
Comment (Mugen87) [inline examples/jsm/renderers/webgl-legacy/nodes/WebGLNodes.js:11]: @sunag I'm not sure this fix is compatible with #26841 though. When `onBuild()` is called in `WebGLRenderer`,  the material can't be an array of materials so using `const material = this;` and then `Array.isArray( object.material )` will always evaluate to `false`.

Comment (Mugen87) [reply examples/jsm/renderers/webgl-legacy/nodes/WebGLNodes.js:11]: If we can't fix this in `WebGLNodes`, I'll revert and add this to the renderer:
```js
if ( scene.overrideMaterial === null ) material.onBuild( object, parameters, _this );
```
That means however `Scene.overrideMaterial` can't be of type node material. But at least https://github.com/mrdoob/three.js/issues/27095 will be fixed.

Comment (Mugen87) [reply examples/jsm/renderers/webgl-legacy/nodes/WebGLNodes.js:11]: I think it would be good to fix this in `WebGLNodes` somehow since the assumption materials can be derived from the `object` reference isn't right. I've realized this does not only break `overrideMaterial` but shadow rendering when an objects with node materials are rendered with depth materials.

Comment (sunag) [reply examples/jsm/renderers/webgl-legacy/nodes/WebGLNodes.js:11]: I added a remaining reference [here](https://github.com/mrdoob/three.js/pull/27097/commits/a615adee23acc507d20e43903bf0d4e8e1173f11), it looks ok to me now using `overrideMaterial`.

Comment (Mugen87) [reply examples/jsm/renderers/webgl-legacy/nodes/WebGLNodes.js:11]: I have simplified the method a bit. The fiddle from https://github.com/mrdoob/three.js/issues/26811#issue-1904059962 still works and https://github.com/mrdoob/three.js/issues/27095 is also fixed.

**Review by sunag — APPROVED** [review]
