### PR TITLE
FileLoader: Incorrect error handling.

### LINKED ISSUE #22923: FileLoader: Incorrect error handling.
**Describe the bug**

Error inside the onLoad callback of fileloader will show `TypeError: Cannot read property 'length' of undefined` instead of real error.

**To Reproduce**

1. Instantiate FileLoader
2. Throw an error insdie onLoad function intentionally
3. Check the error inside DevTools

***Code***

```js
// Simple three.js example

import * as THREE from "https://threejs.org/build/three.module.js";

const loader = new THREE.FileLoader();
const resourceURI = "https://picsum.photos/200/300";

loader.load( resourceURI, object => {
  console.log("some stuff...");
  
  // Error inside onLoad callback
  throw new Error("encounter error");
  
  console.log("other stuff...");
});
```

***Live example***

* [jsfiddle](https://jsfiddle.net/e34n5zu2/1/)

**Expected behavior**
Display the real error when there are no callbacks to call.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by leyiang**
Related issue: Fixed #22923

**Description**

Once the fetch of FileLoader is fulfilled, `url` will be deleted in `loading` object.
If there are any error being throwed inside the `onLoad` callback, `catch` function of the fetch will throw confusing error message instead of real error.

### CODE REVIEW

File: src/loaders/FileLoader.js [hunk 1]
```diff
@@ -196,6 +196,14 @@ class FileLoader extends Loader {
 				// Abort errors and other errors are handled the same
 
 				const callbacks = loading[ url ];
+
+				if ( ! callbacks ) {
+
+					// When onLoad was called and url was deleted in `loading`
+					throw err;
```
Comment (Mugen87) [inline src/loaders/FileLoader.js:203]: I guess it would make sense to call `this.manager.itemError( url );` before the `throw` statement. `itemEnd()` was already called in the previous `then()` implementation.

BTW: Please write the if clause like so:
```js
if ( callbacks === undefined )
```

Comment (leyiang) [reply src/loaders/FileLoader.js:204]: Done! So excited to finish my first pull request! :)

**Comment by Mugen87** [comment]
@gkjohnson Does this look good to you?

File: src/loaders/FileLoader.js [hunk 2]
```diff
@@ -196,6 +196,15 @@ class FileLoader extends Loader {
 				// Abort errors and other errors are handled the same
 
 				const callbacks = loading[ url ];
+
+				if ( callbacks === undefined ) {
+
+					// When onLoad was called and url was deleted in `loading`
+					this.manager.itemError( url );
```
Comment (gkjohnson) [inline src/loaders/FileLoader.js:203]: I think we need to fire `this.manager.itemEnd( url );` here as it does at the end of the "catch" block, too

Comment (Mugen87) [reply src/loaders/FileLoader.js:203]: In the mentioned case `itemEnd()` is then executed twice. At this place and in the previous `then()` block.

Comment (gkjohnson) [reply src/loaders/FileLoader.js:203]: I don't think that's the case. If an error is thrown in the promise callbacks and the catch callback is run then the above itemEnd will not be hit. And either way the catch function already calls the itemEnd function at the bottom of it so it should be called in this new branch too for consistency.

Another option would be to call itemEnd in a ".finally" callback, instead, so it always gets run

Comment (Mugen87) [reply src/loaders/FileLoader.js:203]: > Another option would be to call itemEnd in a ".finally" callback, instead, so it always gets run

That sounds like the cleanest solution to me.

Comment (leyiang) [reply src/loaders/FileLoader.js:201]: DONE

Comment (gkjohnson) [reply src/loaders/FileLoader.js:201]: Great! I think this looks right to me, now!

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!
