### PR TITLE
PMREMGenerator: Fix `fromScene()` back-side materials

### LINKED ISSUE #30048: PMREM generation produce wrong results
### Description

PMREM Generation orientation of cameras bake are probably wrong in both webGL and WebGPU version, or is it the PMREM read node that is wrong ? 

Screenshot 2024-12-06 at 16 02 54

### Live example

[Live Fiddle](https://jsfiddle.net/5L6x4mdz/40/)

### Version

171

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by sunag**
Related issue: Fixes https://github.com/mrdoob/three.js/issues/30048

**Description**

Apparently the problem was with the back of the materials, I changed the approach a bit to do the flip-y on the sampler instead of the generator and it worked. The cause of the problem is still a bit unclear for me.

### CODE REVIEW

File: src/renderers/common/extras/PMREMGenerator.js [hunk 1]
```diff
@@ -468,17 +467,17 @@ class PMREMGenerator {
...
 			if ( col === 0 ) {
 
-				cubeCamera.up.set( 0, upSign[ i ], 0 );
+				cubeCamera.up.set( 0, 1, 0 );
 				cubeCamera.lookAt( forwardSign[ i ], 0, 0 );
 
 			} else if ( col === 1 ) {
 
-				cubeCamera.up.set( 0, 0, upSign[ i ] );
+				cubeCamera.up.set( 0, - 1, 0 );
```
Comment (WestLangley) [inline src/renderers/common/extras/PMREMGenerator.js:475]: Did you mean `cubeCamera.up.set( 0, 0, - 1 );`?

Even so, this code block does not look correct to me. When looking up the y-axis, the "up-direction" is different than it is when looking down the y-axis.

Comment (sunag) [reply src/renderers/common/extras/PMREMGenerator.js:475]: `cubeCamera.up.set( 0, - 1, 0 )` It was just a trick to rotate the camera 180 degrees on the y-axis while using `lookAt()`. I believe the original version used it for the same purpose with `upSign[x]`.

Comment (WestLangley) [reply src/renderers/common/extras/PMREMGenerator.js:475]: https://github.com/mrdoob/three.js/blob/c4071d4332c9184a8a24ce70a37dd3f5c9769c55/src/renderers/common/extras/PMREMGenerator.js#L475-L476
You are setting the up-direction to be parallel to the look-direction. Doing so is invalid.

When looking parallel to the y-axis, the up-direction was set to either +/- z in the original PMREM generator.
