### PR TITLE
Examples: replace Promise.finally()

### LINKED ISSUE #19405: DRACOLoader not working on iOS11
##### Description of the problem
Current example `webgl_loader_draco` is not working under iOS11

Screenshot 2020-05-20 at 23 58 17

##### Three.js version

- [x] Dev
- [x] r116
- [ ] ...

##### Browser

- [] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [x] Safari

##### OS

- [] All of them
- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

### PR DESCRIPTION
**Pull request by sciecode**
Fixes #19405

Based on https://github.com/mrdoob/three.js/issues/19405#issuecomment-631807922

The fix is simple enough and doesn't have significant impact on performance or readability, it is just a bit redundant. I don't think enforcing a polyfill for something as simple as this is necessary.

### CODE REVIEW

**Comment by sciecode** [comment]
https://rawcdn.githack.com/sciecode/three.js/2931b0b5fea9cc7562377f899f4c606aa7a06579/examples/webgl_loader_draco.html

https://rawcdn.githack.com/sciecode/three.js/2931b0b5fea9cc7562377f899f4c606aa7a06579/examples/webgl_loader_texture_basis.html

File: examples/js/loaders/DRACOLoader.js [hunk 1]
```diff
@@ -198,7 +198,18 @@ THREE.DRACOLoader.prototype = Object.assign( Object.create( THREE.Loader.prototy
...
+				if ( worker && taskID ) {
+
+					this._releaseTask( worker, taskID );
+
+					// this.debug();
+
+				}
+
+			} )
+			.catch( () => {
```
Comment (donmccurdy) [inline examples/js/loaders/DRACOLoader.js:212]: Note that you can condense this to avoid duplicating the cleanup logic:

```
geometryPending
  .catch( () =>  true )
  .then( () => {
    // ...
  } );
```

A `.then()` block after a `.catch()` will still be called in error cases, assuming the `.catch()` block handles the error without throwing a new error itself. https://stackoverflow.com/a/42028776/1314762

Comment (donmccurdy) [reply examples/js/loaders/DRACOLoader.js:212]: ^It would also be worth including a short comment explaining *why* we're doing something confusing like that, or future readers may wonder why we didn't just use `.finally()`. 😇

Comment (sciecode) [reply examples/js/loaders/DRACOLoader.js:212]: I actually did not know that, thanks. TIL.

> It would also be worth including a short comment explaining why we're doing something confusing like that

Good point, will do.

Comment (sciecode) [reply examples/js/loaders/DRACOLoader.js]: Tested locally and `then()` block is indeed called correctly after `catch()`. This should be good, unless we have a better suggestion for the comment.

**Review by Mugen87 — APPROVED** [review]
I did not expect that the change is so compact. In this case, I'm fine with replacing `finally()`.

**Review by donmccurdy — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!
