### PR TITLE
WebGPU: Logarithmic Depth Buffer Rename/Revision + GTAONode Fixes

### LINKED ISSUE #29797: WebGPU: GTAO is incompatible with logarithmicDepthBuffer
### Description

 https://threejs.org/examples/?q=ao#webgpu_postprocessing_ao
In this example, if `logarithmicDepthBuffer` is `true,` it's broken. The error message is below:
image
```
Depth stencil state is not present when fragment stage ([ShaderModule "fragment"], [EntryPoint "main"]) is writing to frag_depth.
 - While validating fragment state.
 - While calling [Device].CreateRenderPipeline([RenderPipelineDescriptor "renderPipeline_GTAO_20"]).
```
### Reproduction steps

1.
2.
3.

### Code

```js
renderer = new THREE.WebGPURenderer({
	logarithmicDepthBuffer: true,
});
```

### Live example

* [jsfiddle-latest-release WebGLRenderer](https://jsfiddle.net/3mrkqyea/)
* [jsfiddle-dev WebGLRenderer](https://jsfiddle.net/gcqx26jv/)
* [jsfiddle-latest-release WebGPURenderer](https://jsfiddle.net/8L2jkmx7/)
* [jsfiddle-dev WebGPURenderer](https://jsfiddle.net/L3n1w4yh/)

### Screenshots

_No response_

### Version

0.170.0

### Device

Desktop

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by PoseidonEnergy**
Fixed #29797.

1. Renamed the function `perspectiveDepthToLogarithmicDepth` to `viewZToLogarithmicDepth` and modified it to expect a negative `viewZ` value in order maintain consistency with `viewZToOrthographicDepth` and `viewZToPerspectiveDepth`
2. Revised the logarithmic depth curve once more to ensure it maintains a full 0-to-1 range no matter the camera near/far values.
See new curves here on Desmos: https://www.desmos.com/calculator/uyqk0vex1u
4. Added function `logarithmicDepthToViewZ` for use in **GTAONode.js**
5. Fixed AO not working when `logarithmicDepthBuffer` is `true`

Related issue: #29797 

**Description**

The name of the function `perspectiveDepthToLogarithmicDepth` is misleading because it actually expects a `viewZ` value (i.e. `positionView.z`), and NOT a depth value (i.e. a number between 0 and 1). In addition, the `viewZ` value that it previously expected had to be a positive number, which differed from its sister functions `viewZToOrthographicDepth` and `viewZToPerspectiveDepth`, which both expect a negative `viewZ`. In this pull request, the function in question is now named `viewZToLogarithmicDepth`, and expects a negative `viewZ` like the rest in its family.

AO was not working properly in the **webgpu_postprocessing_ao** example when `logarithmicDepthBuffer` was `true`. The function `logarithmicDepthToViewZ` was added to **ViewportDepthNode.js**, so it can now be used in **GTAONode.js** to obtain the proper depth values required for AO.

Here is a JSFiddle I made to demonstrate how `viewZToLogarithmicDepth` relates to the rest of the depth functions:

https://jsfiddle.net/go6f2y4u

And here is an animation of the JSFiddle:

depthfamily

image

image

### CODE REVIEW

File: examples/jsm/tsl/display/GTAONode.js [hunk 1]
```diff
@@ -1,4 +1,4 @@
-import { DataTexture, RenderTarget, RepeatWrapping, Vector2, Vector3 } from 'three';
+import { DataTexture, RenderTarget, RepeatWrapping, Vector2, Vector3, logarithmicDepthToViewZ, viewZToPerspectiveDepth } from 'three';
 import { getNormalFromDepth, getScreenPosition, getViewPosition, QuadMesh, TempNode, nodeObject, Fn, float, NodeUpdateType, uv, uniform, Loop, vec2, vec3, vec4, int, dot, max, pow, abs, If, textureSize, sin, cos, PI, texture, passTexture, mat3, add, normalize, mul, cross, div, mix, sqrt, sub, acos, clamp, NodeMaterial, PostProcessingUtils } from 'three/tsl';
```
Comment (ligaofeng0901) [inline examples/jsm/tsl/display/GTAONode.js:2]: I think this should import from 'three/tsl'

File: src/nodes/lighting/ShadowNode.js [hunk 2]
```diff
@@ -313,10 +313,10 @@ class ShadowNode extends Node {
 			// The normally available "cameraNear" and "cameraFar" nodes cannot be used here because they do not get
 			// updated to use the shadow camera. So, we have to declare our own "local" ones here.
 			// TODO: How do we get the cameraNear/cameraFar nodes to use the shadow camera so we don't have to declare local ones here?
-			const cameraNearLocal = uniform( 'float' ).onRenderUpdate( () => shadow.camera.near );
-			const cameraFarLocal = uniform( 'float' ).onRenderUpdate( () => shadow.camera.far );
+			const cameraNearLocal = reference( 'near', 'float', shadow.camera );
+			const cameraFarLocal = reference( 'far', 'float', shadow.camera );
```
Comment (Mugen87) [inline src/nodes/lighting/ShadowNode.js:317]: @PoseidonEnergy `reference()` is a bit cleaner than defining a uniform with a `onRenderUpdate()` callback.

**Review by Mugen87 — APPROVED** [review]

**Comment by Mugen87** [comment]
@PoseidonEnergy Tested the change locally and it works as expected! Awesome PR 👍 !

**Comment by Mugen87** [comment]
@PoseidonEnergy Your fiddle for testing the TSL functions is super interesting!

The project is actually looking for a way to unit test TSL functions (see #28708). It would be great to establish a basic procedure in our current unit tests (see https://github.com/mrdoob/three.js/tree/dev/test/unit) for testing TSL modules in isolated routines.

File: examples/jsm/tsl/display/GTAONode.js [hunk 3]
```diff
@@ -107,7 +110,22 @@ class GTAONode extends TempNode {
...
-		const sampleDepth = ( uv ) => this.depthNode.uv( uv ).x;
+		const sampleDepth = ( uv ) => {
+
+			const depth = this.depthNode.uv( uv ).x;
+
+			if ( builder.renderer.logarithmicDepthBuffer === true ) {
+
+				const viewZ = logarithmicDepthToViewZ( depth, this.cameraNear, this.cameraFar );
+
+				return viewZToPerspectiveDepth( viewZ, this.cameraNear, this.cameraFar );
```
Comment (Mugen87) [inline examples/jsm/tsl/display/GTAONode.js:121]: Can we check here if the camera is orthographic and then use `viewZToOrthographicDepth()` instead?

File: src/nodes/lighting/ShadowNode.js [hunk 4]
```diff
@@ -313,10 +313,10 @@ class ShadowNode extends Node {
 			// The normally available "cameraNear" and "cameraFar" nodes cannot be used here because they do not get
 			// updated to use the shadow camera. So, we have to declare our own "local" ones here.
 			// TODO: How do we get the cameraNear/cameraFar nodes to use the shadow camera so we don't have to declare local ones here?
-			const cameraNearLocal = uniform( 'float' ).onRenderUpdate( () => shadow.camera.near );
-			const cameraFarLocal = uniform( 'float' ).onRenderUpdate( () => shadow.camera.far );
+			const cameraNearLocal = reference( 'near', 'float', shadow.camera ).setGroup( renderGroup );
```
[the remark this answers is not in the document]
Comment (Mugen87) [reply src/nodes/lighting/ShadowNode.js:316]: I did only switch to `reference()` for consistency reasons since this API is used in the rest of the file.
