### PR TITLE
WebGLTextures: Fix updateMultisampleRenderTarget FBO state

### LINKED ISSUE #18905: WebGLTextures: updateMultisampleRenderTarget() swaps active FBO
##### Description of the problem

`WebGLTextures.updateMultisampleRenderTarget()` leaves the *DRAW_FRAMEBUFFER* target as the active FBO. This causes the GL state to be different from `_currentFramebuffer` in `WebGLRenderer`, and additional calls to `WebGLRender.render` in the same frame with the same render target will have no effect (will be drawing to non-multisampled backing FBO which is overwritten by blit).

Binding `__webglMultisampledFramebuffer` as *FRAMEBUFFER* target after blitting fixes the issue.

##### Three.js version

- [x] Dev
- [x] r114

##### Browser

- [x] All of them

##### OS

- [x] All of them

### PR DESCRIPTION
**Pull request by kvholm**
Fixes #18905 by ensuring `WebGLTextures.updateMultisampleRenderTarget()` resets the active FBO back to the multisampled FBO after blitting.

### CODE REVIEW

File: src/renderers/webgl/WebGLTextures.js [hunk 1]
```diff
@@ -1133,6 +1133,8 @@ function WebGLTextures( _gl, extensions, state, properties, capabilities, utils,
 
 				_gl.blitFramebuffer( 0, 0, width, height, 0, 0, width, height, mask, _gl.NEAREST );
 
+				_gl.bindFramebuffer( _gl.FRAMEBUFFER, renderTargetProperties.__webglMultisampledFramebuffer );
```
Comment (Mugen87) [inline src/renderers/webgl/WebGLTextures.js]: Good catch! Do you mind adding the issue as a comment like so:
```js
_gl.bindFramebuffer( _gl.FRAMEBUFFER, renderTargetProperties.__webglMultisampledFramebuffer ); // see #18905
```
This makes the line more clear for devs who aren't familiar with the respective history of this change.

**Review by Mugen87 — APPROVED** [review]

**Comment by mrdoob** [comment]
Thanks!
