### PR TITLE
WebGPURenderer: Fix background

### LINKED ISSUE #26478: WebGPU, PerspectiveCamera and SkyBox (CubeMap) - Artifacts when large difference between far and near values
### Description

I have posted about this on the three.js discourse, so I don't know if this has been identified as an issue yet.

When upgrading from WebGL to WebGPU in r154, I discovered that using a large difference between far and near values (e.g. 100000 and 0.1) will create flashing black artifacts in a SkyBox (CubeMap).  This does not appear to be a problem with r153.  The size of the artifacts varies with the difference.

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* [jsfiddle-latest-release](https://jsfiddle.net/g3atw6k5/)
* [jsfiddle-dev](https://jsfiddle.net/hjqw94c5/)

### Screenshots

CubeMap

### Version

154

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by sunag**
Related issue: Fixes https://github.com/mrdoob/three.js/issues/26478

**Description**

- [x] Add [ `NodeMaterial.vertexNode` ](https://github.com/mrdoob/three.js/commit/d376b37d55d80b4cb0eb211452e7cc614813328a)
- [x] [WebGPURenderer: Fix background](https://github.com/mrdoob/three.js/commit/7df5b3f42e6eee8e3c631f3d46a0fe3438c78834)

### CODE REVIEW

File: examples/jsm/renderers/common/Background.js [hunk 1]
```diff
@@ -49,31 +49,33 @@ class Background extends DataMap {
...
 					// @TODO: Add Texture2D support using node context
-					getUVNode: () => positionWorldDirection,
+					getUVNode: () => normalWorld,
 					getSamplerLevelNode: () => backgroundBlurriness
 				} ).mul( backgroundIntensity );
 
-				const nodeMaterial = new MeshBasicNodeMaterial();
-				nodeMaterial.colorNode = this.boxMeshNode;
+				let viewProj = modelViewProjection();
+				viewProj = vec4( viewProj.x, viewProj.y, viewProj.w, viewProj.w );
```
Comment (LeviPesin) [inline examples/jsm/renderers/common/Background.js:63]: Maybe just `viewProj.z.assign( viewProj.w )`?

Comment (sunag) [reply examples/jsm/renderers/common/Background.js:63]: If I were to go with the flow I would say that this should return `z`, because the last property accessed would still be `z`, I think that to return the entire vector we should have a function directly on the vector without using `property accessors`, this can confuse the flow of reading, for example I think `viewProj.setZ( viewProj.w )` sounds better in this case.

Comment (mrdoob) [reply examples/jsm/renderers/common/Background.js:63]: `viewProj.setZ( viewProj.w )` reads much better 👌

Comment (LeviPesin) [reply examples/jsm/renderers/common/Background.js:63]: > If I were to go with the flow I would say that this should return z, because the last property accessed would still be z, I think that to return the entire vector we should have a function directly on the vector without using property accessors, 

I think we discussed this issue a few months ago and agreed that just adding `SplitNode.assign()` will allow to write `vec.x.assign( anything )`.

Comment (sunag) [reply examples/jsm/renderers/common/Background.js:63]: If we split the line, we will see that there is something very strange with `viewProj.z.assign( viewProj.w )`:

```js
const viewProjZ = viewProj.z;

// I think this should return z property not a vec3, so it cannot be inline as suggested
viewProjZ.assign( viewProj.w ) 
```

We don't have the same problem with `node.set*()` because it has no `property accessor`.

Comment (LeviPesin) [reply examples/jsm/renderers/common/Background.js:63]: `viewProjZ` internally is just `new SplitNode( viewProj, 'z' )`, no? I don't see what would be the problem for implementing `assign` for it then...

Comment (mrdoob) [reply examples/jsm/renderers/common/Background.js:63]: `nove.set*()` also follows the current JS API style.

Comment (LeviPesin) [reply examples/jsm/renderers/common/Background.js:63]: But what I'm suggesting is: 1) more powerful (you can do anything in all combinations, like `vec.xy.assign( anything )`), 2) better reflecting shader code, 3) easier to understand, 4) easier to implement. I can file a PR for it if needed.

Comment (mrdoob) [reply examples/jsm/renderers/common/Background.js:63]: So only good things?
You can't think of problems that it creates?

Comment (sunag) [reply examples/jsm/renderers/common/Background.js:63]: It is totally possible made `node.setXY()` or any combination using `Proxy`,  I always considered that when I use `node.set*()`.

Comment (LeviPesin) [reply examples/jsm/renderers/common/Background.js:63]: > You can't think of problems that it creates?

I don't really see what problems could it create. It would function similar to `VarNode.assign()`.
