### PR TITLE
FBXLoader: Guard against orphaned animation curve nodes.

### LINKED ISSUE #33326: FBXLoader: Crash on orphaned animation curve nodes
### Description

`FBXLoader.parse()` crashes with the following exception if an FBX has orphaned animation curve nodes:

```
TypeError: Cannot read properties of undefined (reading 'ID')
    at AnimationParser.parseAnimationLayers (.../three/examples/jsm/loaders/FBXLoader.js:2668:17)
```

I noticed this when working with purchased Unity Asset Store animation clips, but could reproduce it with a simple ASCII FBX file which is [attached to this report](https://github.com/user-attachments/files/26471247/fbxloader-orphan-curve-node-minimal.fbx.txt) and also used in the linked JSFiddle.

The crash happens while `parseAnimationLayers()` assumes every `AnimationCurveNode` connected to an `AnimationLayer` also has a parent connection with a defined `relationship` that resolves to a target model or deformer. The loader dereferences the first filtered parent blindly and throws before the rest of the file can load.

More specifically, in `AnimationParser.parseAnimationLayers()`, the loader does this for transform curves:

```js
const modelID = connections.get( child.ID ).parents.filter( ... )[ 0 ].ID;
```

and similarly for morph curves:

```js
const deformerID = connections.get( child.ID ).parents.filter( ... )[ 0 ].ID;
```

If the filtered result is empty, `[ 0 ]` is `undefined` and the loader throws.

`FBXLoader` should ignore orphaned animation curve nodes and continue parsing the rest of the valid scene and animation data.

### Reproduction steps

1.
2.
3.

### Code

```js
// code goes here
```

### Live example

* https://jsfiddle.net/0k2zputq/5/

### Screenshots

_No response_

### Version

0.183.2

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by digitalbreed**
Fixed #33326

**Description**

This patch guards the parent lookup and skips curve nodes that do not resolve to a valid target model/deformer so the rest of the valid scene and animation data can still load.

### CODE REVIEW

File: examples/jsm/loaders/FBXLoader.js [hunk 1]
```diff
@@ -2750,11 +2750,13 @@ class AnimationParser {
...
 
-								const modelID = connections.get( child.ID ).parents.filter( function ( parent ) {
+								const childConnection = connections.get( child.ID );
+								const modelRelationship = childConnection ? childConnection.parents.filter( function ( parent ) {
 
 									return parent.relationship !== undefined;
 
-								} )[ 0 ].ID;
+								} )[ 0 ] : undefined;
+								const modelID = modelRelationship ? modelRelationship.ID : undefined;
```
Comment (Mugen87) [inline examples/jsm/loaders/FBXLoader.js]: Looking at the code of `FBXLoader`, the check for childConnection should not be necessary. Hence, the code can be simplified to:
```js
const filteredParents = connections.get( child.ID ).parents.filter( function ( parent ) {

	return parent.relationship !== undefined;

} );

if ( filteredParents.length === 0 ) return;

const modelID = filteredParents[ 0 ].ID;
```

File: examples/jsm/loaders/FBXLoader.js [hunk 2]
```diff
@@ -2814,11 +2816,15 @@ class AnimationParser {
...
+								const childConnection = connections.get( child.ID );
+								const deformerRelationship = childConnection ? childConnection.parents.filter( function ( parent ) {
 
 									return parent.relationship !== undefined;
 
-								} )[ 0 ].ID;
+								} )[ 0 ] : undefined;
+								const deformerID = deformerRelationship ? deformerRelationship.ID : undefined;
+
+								if ( deformerID === undefined ) return;
```
Comment (Mugen87) [inline examples/jsm/loaders/FBXLoader.js]: Same as above:
```js
const filteredParents = connections.get( child.ID ).parents.filter( function ( parent ) {

	return parent.relationship !== undefined;

} );

if ( filteredParents.length === 0 ) return;

const deformerID = filteredParents[ 0 ].ID;
```

File: examples/jsm/loaders/FBXLoader.js (hunk 1 above)
Comment (digitalbreed) [reply examples/jsm/loaders/FBXLoader.js]: Fair, I have pushed a simplified version.

File: examples/jsm/loaders/FBXLoader.js (hunk 2 above)
Comment (digitalbreed) [reply examples/jsm/loaders/FBXLoader.js]: Fair, I have pushed a simplified version.
