### PR TITLE
WebGPURenderer: Make MSAA with MRT work with WebGL backend.

### LINKED ISSUE #30995: Does the WebGPU renderer not support MSAA anti aliasing when using WebGL mode?
### Description

The WebGPU renderer supports MSAA anti aliasing when using WebGL mode

### Reproduction steps

The WebGPU renderer supports MSAA anti aliasing when using WebGL mode

### Code

The WebGPU renderer supports MSAA anti aliasing when using WebGL mode

### Live example

The WebGPU renderer supports MSAA anti aliasing when using WebGL mode

### Screenshots

_No response_

### Version

174

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #30995.

**Description**

The PR tries to make the combination of MSAA and MRT work for the WebGL backend.

Unfortunately, the combination only works for the first attachment so far. I don't understand why additional attachments are not properly blit although the WebGL backend uses the same approach like in `WebGLRenderer`. The problem can be reproduced with below example (it always runs with the WebGL backend for testing).

https://rawcdn.githack.com/Mugen87/three.js/c4d55169b9dc56732cf43e5143cd31226a6d5c8e/examples/webgpu_mrt.html

The expected result looks like so: https://threejs.org/examples/webgpu_mrt

@RenaudRohlinger Since you have implemented the initial support in `WebGLRenderer`, did you ever encounter such a problem?

@cabanier I do not see any WebGL warnings in the browser console but do you see an obvious flaw in the framebuffer setup? I'm a bit out of ideas at the moment why the blit works partially but without reporting errors. A fresh pair of eyes would help^^.

The PR only implements the resolve. The setup of MSAA render buffers for each attachment has already been implemented by #27473.

https://github.com/mrdoob/three.js/blob/c7b6f81b608cbbb2b729f67b110dac50e82d96da/src/renderers/webgl-fallback/WebGLBackend.js#L2236-L2295

### CODE REVIEW

File: src/renderers/webgl-fallback/WebGLBackend.js [hunk 1]
```diff
@@ -601,6 +626,21 @@ class WebGLBackend extends Backend {
...
 				}
 
+				if ( isMRT ) {
+
+					// restore attachments
+
+					for ( let i = 0; i < textures.length; i ++ ) {
+
+						const { textureGPU } = this.get( textures[ i ] );
+
```
Comment (RenaudRohlinger) [inline src/renderers/webgl-fallback/WebGLBackend.js:636]: Not sure but I think you should bind the MSAA FBO and the FBO here @Mugen87:

```js
state.bindFramebuffer( _gl.FRAMEBUFFER, msaaFrameBuffer);

gl.framebufferRenderbuffer( gl.READ_FRAMEBUFFER, gl.COLOR_ATTACHMENT0 + i, gl.RENDERBUFFER, msaaRenderbuffers[ i ] );

state.bindFramebuffer( _gl.FRAMEBUFFER, fb);

gl.framebufferTexture2D( gl.DRAW_FRAMEBUFFER, gl.COLOR_ATTACHMENT0 + i, gl.TEXTURE_2D, textureGPU, 0 );
```

Comment (RenaudRohlinger) [reply src/renderers/webgl-fallback/WebGLBackend.js:636]: also unbind before the loop:
```js
state.bindFramebuffer( _gl.READ_FRAMEBUFFER, null );
state.bindFramebuffer( _gl.DRAW_FRAMEBUFFER, null );
```

and rebind after:
```js
state.bindFramebuffer( gl.READ_FRAMEBUFFER, msaaFrameBuffer );
```

Comment (Mugen87) [reply src/renderers/webgl-fallback/WebGLBackend.js:636]: Unfortunately, that does not do any difference. In fact, it seems some bindings in `WebGLRenderer` are redundant. A single bind of the draw and read buffer at the beginning of the blit process should be sufficinet. Removing all these bindings in `WebGLRenderer` does not break `webgl_multiple_rendertargets`.

**Comment by cabanier** [comment]
> @cabanier I do not see any WebGL warnings in the browser console but do you see an obvious flaw in the framebuffer setup? I'm a bit out of ideas at the moment why the blit works partially but without reporting errors. A fresh pair of eyes would help^^.

Could this be that you're trying to read from the renderbuffers or before they're resolved to textures?
I ran your example on Quest (which supports rendering directly to a texture) and it was rendering correctly.

**Comment by cabanier** [comment]
@Mugen87 did you figure it out? I'm debugging with renderdoc to see where things go wrong but if you already solved it, I can stop.

**Comment by Mugen87** [comment]
10 minutes ago I found out a missing call of `gl.drawBuffers()` is the issue^^.

When I understand the WebGL spec correctly, whatever you do with `gl.drawBuffers()` is part of the current bound framebuffer state. When we reoder the attachments during the resolve, it seems this state is lost so we must make sure `gl.drawBuffers()` is called again for the respective framebuffer.

**Comment by Mugen87** [comment]
In any event, thanks for support! The hint with the renderbuffers was a good starting point.

If all works, I think we can back-port part of this implementation to `WebGLRenderer` since it works with less `gl.bindFramebuffer()` commands during the resolve.
