### PR TITLE
Fix VREffect support for webvr-polyfill

### LINKED ISSUE #8712: VREffect renders nothing with webvr-polyfill
##### Description of the problem 
As of r76, stereo/cardboard mode shows a blank screen, when using webvr-polyfill. The problem seems to be [here](https://github.com/mrdoob/three.js/blob/dev/examples/js/effects/VREffect.js#L103-L105), in the `fullscreenchange` event handler:
```javascript
isPresenting = isDeprecatedAPI && vrHMD && ( document.mozFullScreenElement || document.webkitFullscreenElement ) !== undefined;
```

If WebVR is supported natively, this works fine; `vrdisplaypresentchange` fires but full screen does not. However, the polyfill uses full screen, so both events fire, and `isPresenting` gets set to `false` when it should be `true`. This was not a problem in r75 before 63fb23cef8de599074c6b007e65780467b6fc8a3.

##### Three.js version

- [x] Dev
- [x] r76
- [ ] r75

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [ ] Windows
- [ ] Linux
- [x] Android
- [ ] IOS

##### Hardware Requirements (graphics card, VR Device, ...)
Android using webvr-polyfill for Google Cardboard. Shouldn't be a problem in iOS, since it doesn't currently support full screen.

### PR DESCRIPTION
**Pull request by brianchirls**
- fixes #8712
- correctly set `isPresenting` in full screen mode
- webvr-polyfill fires fullscreenchange in VR mode
- fix needed for setting main window to full screen while presenting

### CODE REVIEW

File: examples/js/effects/VREffect.js [hunk 1]
```diff
@@ -102,16 +102,26 @@ THREE.VREffect = function ( renderer, onError ) {
 
 	document.addEventListener( fullscreenchange, function () {
 
-		isPresenting = isDeprecatedAPI && vrHMD && ( document.mozFullScreenElement || document.webkitFullscreenElement ) !== undefined;
+		isPresenting = vrHMD && ( vrHMD.isPresenting || isDeprecatedAPI && ( document.mozFullScreenElement || document.webkitFullscreenElement ) !== undefined );
```
Comment (mrdoob) [inline examples/js/effects/VREffect.js]: We should add some parenthesis to make this code more clear...

Are we doing `X && ( ( Y || Z ) && W )` or `X && ( Y || ( Z && W ) )`?

Comment (brianchirls) [inline examples/js/effects/VREffect.js]: I agree that it's difficult to read. Maybe an `if` statement or two would be clearer. Would you prefer that?

Comment (mrdoob) [inline examples/js/effects/VREffect.js]: I think adding clarifying parenthesis should be enough...

**Comment by brianchirls** [comment]
@mrdoob Updated with parentheses and some other clean-up

**Comment by brianchirls** [comment]
Fair enough. Fixed.

**Comment by mrdoob** [comment]
Thanks!
