### PR TITLE
WebGPURenderer - Disable Draw Call when object.count = 0

### LINKED ISSUE #30882: THREE.Sprite() still renders when object.count = 0
### Description

In webgpu_compute_particles_rain, if you modify the gui to let the user set rainParticles.count = 0, single sprites will still render periodically on screen. 

https://github.com/user-attachments/assets/64dd89df-db38-4bf9-b9fe-dfeffe2d5965

This is also an issue I've seen when attempting to port Simon Dev's Particles Tutorial over to TSL. Here, even with geometryAttribute set to empty arrays and a particle.count of 0, a single particle still renders. 

```
getDrawParameters() {
       
	// const instanceCount = geometry.isInstancedBufferGeometry ? geometry.instanceCount : ( object.count > 1 ? object.count : 1 );
       const instanceCount = geometry.isInstancedBufferGeometry ? geometry.instanceCount : ( object.count !== undefined  ? object.count : 1);
```

Now when the object.count value is set to 0, instanceCount will equal 0 and getDrawParameters() will return null, preventing the particles from drawing. 

https://github.com/user-attachments/assets/6e7b3534-53a6-4fdb-9dc2-8670f0965631

Will update with more visible examples in a bit. 

### Reproduction steps

1. Give the user the ability to arbitrarily set rainParticles.count to a range of 0 to maxParticles within the GUI.

### Code

```js
// code goes here
```

### Live example

// TBD

### Screenshots

_No response_

### Version

r175

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by cmhhelgeson**
Fixed #30882.

**Description**

Modifies the instanceCount behavior to acknowledge when the user sets object.count to 0.

### CODE REVIEW

File: src/renderers/common/RenderObject.js [hunk 1]
```diff
@@ -509,7 +509,7 @@ class RenderObject {
 
 		const index = this.getIndex();
 		const hasIndex = ( index !== null );
-		const instanceCount = geometry.isInstancedBufferGeometry ? geometry.instanceCount : ( object.count > 1 ? object.count : 1 );
+		const instanceCount = geometry.isInstancedBufferGeometry ? geometry.instanceCount : ( object.count !== undefined ? Math.max( 0, object.count ) : 1 );
```
Comment (Mugen87) [inline src/renderers/common/RenderObject.js:512]: Can we dissolve this statement a bit? IMO, below code easier to read and debug:
```js
let instanceCount = 1;

if ( geometry.isInstancedBufferGeometry === true ) {

    instanceCount = geometry.instanceCount;

} else if ( object.count !== undefined ) {

    instanceCount = Math.max( 0, object.count );

}
```

Comment (cmhhelgeson) [reply src/renderers/common/RenderObject.js]: sure

**Review by Mugen87 — APPROVED** [review]
