### PR TITLE
Orbitcontrol ZoomToCursor fix

### LINKED ISSUE #26548: OrbitControls when zoomToCursor is enabled `updateMouseParameters` should consider object change
### Description

in OrbitControls function `updateMouseParameters` ...dollyDirection.set(...).unproject( `object` )...

it only works with the `object` in new OrbitControls(`object`, ...) which it captured during the constructor

so, if user change the `object` to another camera/object3d (by the way checking object is a Camera is appericated) it won't work.

### Reproduction steps

1.create an orbitcontrols with zoomToCursor set to true
2.set control.object to another camera or object3d after constrcution
3.zoom in the viewport

### Code

```js
// the OrbitControls constructor
constructor(object, domElement) {
		// ...
		function updateMouseParameters( event ) {
			if ( ! scope.zoomToCursor ) {
				return;
			}
			performCursorZoom = true;

			const rect = scope.domElement.getBoundingClientRect();
			const x = event.clientX - rect.left;
			const y = event.clientY - rect.top;
			const w = rect.width;
			const h = rect.height;

			mouse.x = ( x / w ) * 2 - 1;
			mouse.y = - ( y / h ) * 2 + 1;

			// the unproject happens here
			dollyDirection.set( mouse.x, mouse.y, 1 ).unproject( object ).sub( object.position ).normalize();

		}
		// ...
}
```

the `unproject( object )` should be changed to `unproject( this.object )` or `unproject( scope.object )`
of course,  `sub( object.position )` should be change too

### Live example

see the code, i think it's clear enough

### Screenshots

_No response_

### Version

155

### Device

Desktop

### Browser

Chrome

### OS

Windows

### PR DESCRIPTION
**Pull request by xiaowangxu**
Fixed #26548 

**Description**

Fix the `updateMouseParameters` function when using `zoomToCursor` to work with changeable objects and objects other than cameras (in such cases, a warning will occur and zoomToCursor will set to false).

### CODE REVIEW

File: examples/jsm/controls/OrbitControls.js [hunk 1]
```diff
@@ -614,12 +614,21 @@ class OrbitControls extends EventDispatcher {
...
 		function updateMouseParameters( event ) {
 
-			if ( ! scope.zoomToCursor ) {
+			if ( !scope.zoomToCursor ) {
 
 				return;
 
 			}
 
+			if ( !scope.object.isPerspectiveCamera && !scope.object.isOrthographicCamera ) {
```
Comment (Mugen87) [inline examples/jsm/controls/OrbitControls.js:623]: Do you mind undoing this check? We can add it when people actually complain about it...

File: examples/jsm/controls/OrbitControls.js [hunk 2]
```diff
@@ -614,12 +614,21 @@ class OrbitControls extends EventDispatcher {
 
 		function updateMouseParameters( event ) {
 
-			if ( ! scope.zoomToCursor ) {
+			if ( !scope.zoomToCursor ) {
```
Comment (Mugen87) [inline examples/jsm/controls/OrbitControls.js:617]: Do you mind undoing this change?

Comment (xiaowangxu) [reply examples/jsm/controls/OrbitControls.js:617]: the !zoomtocursor check is the origin code in r155, so I don’t think I can remove it
but I will undo the former one tomorrow

Comment (Mugen87) [reply examples/jsm/controls/OrbitControls.js:617]: I just mean the code style^^.

**Review by Mugen87 — APPROVED** [review]
