### PR TITLE
WebGLShadowMap: Switching filters on switching shadow types fixed

### LINKED ISSUE #25835: Wrong filters applied when switching shadow map types
### Description

Related PR:
[https://github.com/mrdoob/three.js/pull/24223](https://github.com/mrdoob/three.js/pull/24223) _("Ensures VSM can not just be used when enabling it at application start but also **if someone switched from another shadow mapping type** like PCF to VSM.")_.

Problem: 
The `mapPass` bug was fixed with that PR, but the `shadow.map.texture` filters are not switched. 

### Reproduction steps

In my little demo app below, VSM shadows are correct  (even after switching forth and back) if and only if the type was already set to VSM initially. They are wrong if the initial type was something else.

[In this code line](https://github.com/mrdoob/three.js/blob/dev/src/renderers/webgl/WebGLShadowMap.js#L136) it appears that the default filter (`LinearFilter`) is meant to be applied to VSM shadow map textures, and `NearestFilter` for the other types.

But these filters are only applied initially (`if (shadow.map === null`), so switching the shadow type doesn't have an effect on the filters.

### Code

My suggestion would be to not only check for null, but also if there has been a recent switch from or to VSM (disposing the previous map before creating a new one):

```js
...

let _previousType = this.type;

this.render = function ( lights, scene, camera ) {

  ...

  const switchedToVSM = _previousType !== VSMShadowMap && this.type === VSMShadowMap;
  const switchedFromVSM = _previousType === VSMShadowMap && this.type !== VSMShadowMap;

  if ( shadow.map === null || switchedToVSM || switchedFromVSM ) {

    const pars = ( this.type !== VSMShadowMap ) ? { minFilter: NearestFilter, magFilter: NearestFilter } : {};

    shadow.map?.dispose();
    shadow.map = new WebGLRenderTarget( _shadowMapSize.x, _shadowMapSize.y, pars );
    shadow.map.texture.name = light.name + '.shadowMap';

    shadow.camera.updateProjectionMatrix();

  }

  _previousType = this.type;

  ...
```

BTW: 

Is the different treatment of the shadow types even necessary? To me, the non-VSM shadows look the same, no matter whether they have `NearestFilter`s applied or not. And since VSM shadows don't work with `NearestFilter`s, why not just omit the `NearestFilter`s at all? - But it may very well be that I overlooked something(?)

### Live example

Here is a small demo app showing the reported issue (comment/uncomment code line 21 and select VSM in the app to see the difference):

[jsfiddle demo](https://jsfiddle.net/a6vnsbym/)

### Screenshots

Here are two screenshots from the fiddle, showing a VSM shadow with a directional light.

1. Correct VSM shadow (if VSM was applied initially - even after switching forth and back between different types):

vsm-correct

2. Wrong VSM shadow (if a different shadow type was applied initially):

vsm-wrong

### Version

r151

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by digitalArt3DTobias**
Fixed [https://github.com/mrdoob/three.js/issues/25835](https://github.com/mrdoob/three.js/issues/25835).

Avoids problems when switching to VSM shadows from other shadow types dynamically.

### CODE REVIEW

**Review by Mugen87 — APPROVED** [review]

File: src/renderers/webgl/WebGLShadowMap.js [hunk 1]
```diff
@@ -131,17 +132,28 @@ function WebGLShadowMap( _renderer, _objects, _capabilities ) {
...
+				}
+
 				shadow.map = new WebGLRenderTarget( _shadowMapSize.x, _shadowMapSize.y, pars );
 				shadow.map.texture.name = light.name + '.shadowMap';
 
 				shadow.camera.updateProjectionMatrix();
 
 			}
 
+			_previousType = this.type;
```
Comment (Mugen87) [inline src/renderers/webgl/WebGLShadowMap.js:155]: When the shadow map type changes from/to VSM, all shadow maps (so all render targets) have to be recreated. Currently, this only happens for the first shadow map.

So I think this line has to be placed outside the for loop. I'll fix this on my side.
