### PR TITLE
WebGPURenderer: implement ClippingGroup object

### LINKED ISSUE #28838: WebGPURenderer: global clipping planes applied to color space and tone mapping pass.
### Description

Now tone mapping and color space conversion are applied as a separate pass, the global clipping planes are applied to the rendered Quad. 

I don't see a simple solution to this, and the problem will also apply to other post processing passes etc.

Q: Is attaching global clipping plains to the renderer the correct API. Should they be properties of the Scene, or be replaced with something like clipping groups.

@sunag  @mrdoob @Mugen87 @RenaudRohlinger 

### Reproduction steps

1. View the webgpu_clipping example.
2. Enable global clipping

The canvas is vertically clipped with no connection to scene rotation.

### Code

see example

### Live example

* [examples](https://threejs.org/examples/?q=clip#webgpu_clipping)

### Screenshots

_No response_

### Version

166

### Device

_No response_

### Browser

_No response_

### OS

_No response_

### PR DESCRIPTION
**Pull request by aardgoose**
Fixed #28838.

As suggested in original renderer https://github.com/mrdoob/three.js/blob/aedb9c75bedff3a5f8476dbb8b41dd40c4b09603/src/renderers/WebGLRenderer.js#L1777

Adds support for ClippingGroup objects. Clipping planes are additive with nested groups as demonstrated in example.

### CODE REVIEW

**Comment by Mugen87** [comment]
When I read the code correctly, this PR removes `Renderer.clippingPlanes`.

Is it also possible to remove the support for `Material.clippingPlanes`? When I understand the implementation correctly, `ClippingGroup` can handle both local and global clipping.

**Comment by aardgoose** [comment]
@Mugen87 I have already removed material clipping planes in my copy.  I'll push it here soon. It gets simplifies the Renderer somewhat.

**Comment by aardgoose** [comment]
@Mugen87 @sunag 

ClippingGroup() can now replicate the functionality of the existing API without the problems encountered with postprocessing passes etc #28838, the existing example has been updated to use this. The only clipping property now on the material object is 'alphaToCoverage' which is common to other materials.

the planes used for union testing and intersection testing are accumulated separately when inherited.


@sunag To retain the current behaviour where changing 'alphaToCoverage' results in a material rebuild, I have added boolean properties to the RenderObject.getMaterialCacheKey(), I don't know if this is the correct solution here?

**Review by Mugen87 — APPROVED** [review]

**Comment by sunag** [comment]
> To retain the current behaviour where changing 'alphaToCoverage' results in a material rebuild, I have added boolean properties to the RenderObject.getMaterialCacheKey(), I don't know if this is the correct solution here?

I'll check this weekend, sorry for the delay.

**Comment by aardgoose** [comment]
> > To retain the current behaviour where changing 'alphaToCoverage' results in a material rebuild, I have added boolean properties to the RenderObject.getMaterialCacheKey(), I don't know if this is the correct solution here?
> 
> I'll check this weekend, sorry for the delay.

The question is redundant now, fixed by a upstream PR from @Mugen87

**Comment by Mugen87** [comment]
@aardgoose Do you have the resources to rebase the PR? If not, I'm going to give it a try in the upcoming days.

We really should merge this in `r171` to eventually fix global clipping planes.

**Comment by aardgoose** [comment]
Yes, I'll take a look, then I can revisit hardware clipping which is apparently coming in WebGPU in the next chrome version.

**Comment by Mugen87** [comment]
Great! Can't wait to have access to `ClippingGroup`. It makes things so much nicer.

File: src/renderers/common/Renderer.js [hunk 1]
```diff
@@ -1584,23 +1584,23 @@ class Renderer {
...
+				this._currentRenderObjectFunction( object, scene, camera, geometry, material, group, lightsNode, clippingContext, passId );
 
 			}
 
 		}
 
 	}
 
-	renderObject( object, scene, camera, geometry, material, group, lightsNode, passId = null ) {
+	renderObject( object, scene, camera, geometry, material, group, lightsNode, clippingContext = null, passId = null ) {
```
Comment (Mugen87) [inline src/renderers/common/Renderer.js:1603]: `LensflareMesh` directly calls `renderObject()` and can't access `clippingContext` meaning it can't pass it to `renderObject()`. I've fixed the resulting runtime error by defining a default parameter.

If we add `clippingContext` to `onBeforeRender()`, we could ensure lensflares support clipping as well. Alternatively, we could also use the "current clipping context" for nested renderings if it isn't overwritten with a parameter when calling `renderObject()`.
