### PR TITLE
WebGPURenderer: GPU FlipY

### LINKED ISSUE #26813: copyExternalImageToTexture in WebGPUBackend is missing flipY
### Description

Image textures in WebGPUBackend are displaying upside down and need the flipY property added to device.queue.copyExternalImageToTexture

https://github.com/mrdoob/three.js/blob/32cf0d18778ba1ba01e1d4441c822a3661ecac7f/examples/jsm/renderers/webgpu/utils/WebGPUTextureUtils.js#L390

### Reproduction steps

na

### Code

```
    const geometry = new THREE.PlaneGeometry(10, 10);
    const imgMaterial = new MeshBasicNodeMaterial();
    const loader = new THREE.TextureLoader();
    const imgMesh = new THREE.Mesh(geometry, imgMaterial);

     imgMaterial.colorNode = texture(loader.load("./image.png"), uv());
 ```

### Live example

](https://danrossi.github.io/three-webgpu-renderer/tests/webgpu_text3.html)

### Screenshots

_No response_

### Version

153dev

### Device

Desktop

### Browser

Chrome

### OS

_No response_

### PR DESCRIPTION
**Pull request by sunag**
Related issue: Fixes https://github.com/mrdoob/three.js/issues/26813

**Description**

This PR `.flipY` texture approach using GPU-Pass. 

I also fixed CubeMap's flipY but for WebGPU.

Examples applied flipY in CubeMaps
| WebGPURenderer - `webgpu_cubemap_adjustments` | WebGLRenderer - `webgl_materials_envmaps_hdr` |
| ------------- | ------------- |
| image | image |

### CODE REVIEW

File: examples/jsm/renderers/webgpu/utils/WebGPUTextureMipmapUtils.js [hunk 1]
```diff
@@ -94,17 +115,118 @@ fn main( @location( 0 ) vTex : vec2<f32> ) -> @location( 0 ) vec4<f32> {
...
+		const dstView = tempTexture.createView( {
+			baseMipLevel: 0,
+			mipLevelCount: 1,
+			dimension: GPUTextureViewDimension.TwoD,
+			baseArrayLayer: 0
+		} );
+
+		const commandEncoder = this.device.createCommandEncoder( {} );
+
+		const pass = ( pipeline, sourceView, destinyView ) => {
```
Comment (LeviPesin) [inline examples/jsm/renderers/webgpu/utils/WebGPUTextureMipmapUtils.js:187]: It should be `destinationView`

**Comment by sunag** [comment]
This approach offers more support than the previous one, I'm just not that satisfied with the class name maybe split the class in two parts `WebGPUTextureFlipUtils.js`... Do you think we need extended support for `flipY`, except for compressed and RTT (for performance reasons), all textures would be supported

@mrdoob @Mugen87

**Comment by LeviPesin** [comment]
I like this approach! I think it's better to store both `generateMipmaps` and `flipY` utils in one file.

**Comment by mrdoob** [comment]
Could we do the flipY in the shader directly?
