### PR TITLE
TextureNode: Manage y-flip as a uniform.

### LINKED ISSUE #31750: WebGPU: UV flips Y on WebGL fallback when a texture node is reused
### Description

Using WebGPURenderer with WebGLBackend, reusing a texture node to assign a RenderTarget texture flips the Y texture coordinate. This can be reproduced with nodes in the examples such as GaussianBlurNode.

This might be caused by some internal state for texture coordinate abstraction not being updated or relying on a wrong assumption, but I'm not sure where.

### Reproduction steps

1. Render a texture using a texture node.
2. Assign a new texture to the texture node to reuse it.
3. Render the texture.

### Code

```ts
const textureNode = texture(null)
const material = new NodeMaterial()
material.fragmentNode = textureNode
const mesh = new QuadMesh(material)

// First pass:
textureNode.value = image
const rt1 = new RenderTarget(100, 100)
renderer.setRenderTarget(rt1)
mesh.render(renderer)

// Second pass:
textureNode.value = rt1.texture
// Uncommenting the line below doesn't change the result, but uncommenting it
// and commenting out the above line does change the result.
// material.fragmentNode = texture(rt1.texture)
const rt2 = new RenderTarget(100, 100)
renderer.setRenderTarget(rt2)
mesh.render(renderer)
```

See also the fiddles below.

### Live example

- Minimal reproduction: https://jsfiddle.net/shotamatsuda/j6btgk0n/
- Using GaussianBlurNode: https://jsfiddle.net/shotamatsuda/o6dbgyL4/

### Screenshots

WebGPU:
Image

WebGL fallback:
Image

### Version

r179

### Device

Desktop

### Browser

Chrome

### OS

MacOS

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #31750.

**Description**

The PR makes sure `TextureNode` manages the y-flip as a uniform which allows to reuse a texture node with textures with different flip-y requirements.

WebGPU is not affected by this change. The new uniform value is only created when the builder requests it which is only true for WebGL.

### CODE REVIEW

File: src/nodes/accessors/TextureNode.js [hunk 1]
```diff
@@ -296,17 +305,17 @@ class TextureNode extends UniformNode {
...
-		const texture = this.value;
+		if ( builder.isFlipY() ) {
 
-		if ( builder.isFlipY() && ( ( texture.image instanceof ImageBitmap && texture.flipY === true ) || texture.isRenderTargetTexture === true || texture.isFramebufferTexture === true || texture.isDepthTexture === true ) ) {
+			if ( this._flipYUniform === null ) this._flipYUniform = uniform( false );
 
 			if ( this.sampler ) {
 
-				uvNode = uvNode.flipY();
+				uvNode = this._flipYUniform.equal( true ).select( uvNode.flipY(), uvNode );
```
Comment (Mugen87) [inline src/nodes/accessors/TextureNode.js]: Some examples fail e.g. `webgpu_materials_matcap` and it seems it has to do with the new `select()` statement. For some reasons, the compiled GLSL ends up wrong. 

From SpectorJS:

```
nodeVar1 = bool( f_nodeUniform3 );
if ( ( nodeVar1 == true ) ) {
    positionViewDirection = normalize( v_positionViewDirection );
    nodeVar2 = normalize( vec3( positionViewDirection.z, 0.0, ( - positionViewDirection.x ) ) );
    normalViewGeometry = normalize( v_normalViewGeometry );
    NORMAL_normalView = normalViewGeometry;
    normalView = NORMAL_normalView;
    matcapUV = ( ( vec2( dot( nodeVar2, normalView ), dot( cross( positionViewDirection, nodeVar2 ), normalView ) ) * vec2( 0.495 ) ) + vec2( 0.5 ) );
    nodeVar3 = ( f_nodeUniform4 * vec3( matcapUV, 1.0 ) ).xy;
    nodeVar0 = vec2( nodeVar3.x, 1.0 - nodeVar3.y );
}
else {
    matcapUV = ( ( vec2( dot( nodeVar2, normalView ), dot( cross( positionViewDirection, nodeVar2 ), normalView ) ) * vec2( 0.495 ) ) + vec2( 0.5 ) );
    nodeVar0 = ( f_nodeUniform4 * vec3( matcapUV, 1.0 ) ).xy;
}
```
Um, it seems the if/else statement from the select holds way too much code.

Comment (cmhhelgeson) [reply src/nodes/accessors/TextureNode.js]: I think in the short-term this could potentially be resolved by using the uniformFlow context in your highlighted line of code, but the default behavior is certainly not correct.

Comment (cmhhelgeson) [reply src/nodes/accessors/TextureNode.js]: I did a short test and got this as output in the fragment shader. There's probably some optimizations that can be done to only evaluate the f_nodeUniform4 * matcapUV operation once...

```glsl
nodeVar17 = texture( nodeUniform2, ( nodeVar1 == true ) ? vec2( nodeVar16.x, 1.0 - nodeVar16.y ) : ( f_nodeUniform4 * vec3( matcapUV, 1.0 ) ).xy );
```

Comment (Mugen87) [reply src/nodes/accessors/TextureNode.js]: How did you update the TSL source to get this output?

Comment (cmhhelgeson) [reply src/nodes/accessors/TextureNode.js]: this._flipYUniform.equal( true ).select( uvNode.flipY(), uvNode ).uniformFlow();

Comment (Mugen87) [reply src/nodes/accessors/TextureNode.js]: Thanks! I like the fact that the if/else blocks are replaced with a ternary operation.

Unfortunately, none of the suggested versions work right now. Both the `uniformFlow()` code as well as the `uvNode.toVar()` definitions break environment maps in different ways.

E.g. add `uniformFlow()` and then test `webgpu_loader_gltf_transmission` or `webgpu_loader_gltf_sheen`. The environment maps end up way too bright.

image

Comment (sunag) [reply src/nodes/accessors/TextureNode.js]: @Mugen87 I'm checking this bug, the caching and optimization system is failing at some point in the conditionals.
