### PR TITLE
Editor: Fix black textures when loading JSON scenes.

### LINKED ISSUE #15180: Editor: Texture map doesn't render when refresh web page in Chrome, but this problem doesn't reappear in Firefox.
##### Three.js version

- [x] Dev
- [x] r97
- [ ] ...

##### Browser

- [ ] All of them
- [x] Chrome 70
- [ ] Firefox 63

##### OS

- [x] Windows

---

refresh page and mouse hover model before:
image
refresh page and mouse hover model after:
image

### PR DESCRIPTION
**Pull request by Mugen87**
Fixed #15180.

Ensures the editor only sets a scene/object if textures are actually loaded. This done by moving the related logic in the `onLoad()` callback of `ObjectLoader.parse()`. The editor already use this approach when loading `glTF` assets.

### CODE REVIEW

File: editor/js/Editor.js [hunk 1]
```diff
@@ -644,16 +644,6 @@ Editor.prototype = {
...
 		var loader = new THREE.ObjectLoader();
-
-		// backwards
-
-		if ( json.scene === undefined ) {
-
-			this.setScene( loader.parse( json ) );
-			return;
-
-		}
```
Comment (Mugen87) [inline editor/js/Editor.js]: This block was introduced here 7431f1a3e07f0090804cbfd60a5b1fd8c2943ceb, five years ago. I think we can safely remove this now.
